Xuggle: com::xuggle::xuggler::MetaData Class Reference
com::xuggle::xuggler::MetaData Class Reference
#include <MetaData.h>
Detailed Description
Definition at line 34 of file MetaData.h.
Public Member Functions
virtual int32_t getNumKeys ()
Get the total number of keys currently in this IMetaData object.
virtual const char * getKey (int32_t position)
Get the key at the given position, or null if no such key at that position.
virtual const char * getValue (const char *key, Flags flag)
Get the value for the given key.
virtual int32_t setValue (const char *key, const char *value)
Sets the value for the given key to value.
int32_t copy (IMetaData *copy)
Destroys the current data, and copies all data from copy.
Static Public Member Functions
static MetaData * make (AVMetadata **metaDataToReference)
Create a MetaData object using metaDataToReference.
static MetaData * make (AVMetadata *metaDataToCopy)
Copies all meta data currently in metaDataToCopy and returns a new object.
Protected Member Functions
MetaData ()
virtual ~MetaData ()
Constructor & Destructor Documentation
com::xuggle::xuggler::MetaData::MetaData () [protected]
Definition at line 37 of file MetaData.cpp.
{
  mLocalMeta = 0;
  mMetaData = &mLocalMeta;
}
com::xuggle::xuggler::MetaData::~MetaData () [protected, virtual]
Definition at line 43 of file MetaData.cpp.
{
  if (mMetaData && *mMetaData)
    av_metadata_free(mMetaData);
}
Member Function Documentation
int32_t com::xuggle::xuggler::MetaData::getNumKeys () [virtual]
Get the total number of keys currently in this IMetaData object.
Returns:
the number of keys.
Implements com::xuggle::xuggler::IMetaData.
Definition at line 50 of file MetaData.cpp.
{
  if (!mMetaData || !*mMetaData)
    return 0;
  AVMetadataTag* tag=0;
  int32_t retval=0;
  do
  {
    tag = av_metadata_get(*mMetaData, "", tag, AV_METADATA_IGNORE_SUFFIX);
    if (tag)
      retval++;
  } while(tag);
  return retval;
}
const char * com::xuggle::xuggler::MetaData::getKey (int32_t position) [virtual]
Get the key at the given position, or null if no such key at that position.
Note: positions of keys may change between calls to setValue(String, String) and should be requiried.
Parameters:
position The position. Must be >=0 and < getNumKeys().
Returns:
the key, or null if not found.
Implements com::xuggle::xuggler::IMetaData.
Definition at line 67 of file MetaData.cpp.
{
  if (!mMetaData || !*mMetaData || index < 0)
    return 0;
  AVMetadataTag* tag=0;
  int32_t position=-1;
  do
  {
    tag = av_metadata_get(*mMetaData, "", tag, AV_METADATA_IGNORE_SUFFIX);
    if (tag) {
      position++;
      if (position == index)
        return tag->key;
    }
  } while(tag);
  return 0;
}
const char * com::xuggle::xuggler::MetaData::getValue (const char * key, Flags flag) [virtual]
Get the value for the given key.
Parameters:
key The key
flag A flag for how to search
Returns:
The value, or null if none.
Implements com::xuggle::xuggler::IMetaData.
Definition at line 86 of file MetaData.cpp.
{
   if (!mMetaData || !*mMetaData || !key || !*key)
     return 0;
   AVMetadataTag* tag = av_metadata_get(*mMetaData, key, 0, (int)flag);
   if (tag)
     return tag->value;
   else
     return 0;
}
int32_t com::xuggle::xuggler::MetaData::setValue (const char * key, const char * value) [virtual]
Sets the value for the given key to value.
This overrides any prior setting for key, or adds key to the meta-data if appropriate.
Parameters:
key The key to set.
value The value to set.
Implements com::xuggle::xuggler::IMetaData.
Definition at line 98 of file MetaData.cpp.
{
  if (!key || !*key || !mMetaData)
    return -1;
  return (int32_t)av_metadata_set2(mMetaData, key, value,0);
}
MetaData * com::xuggle::xuggler::MetaData::make (AVMetadata ** metaDataToReference) [static]
Create a MetaData object using metaDataToReference.
Once this is done, this MetaData object is responsible for calling av_metadata_free(*metaDataToReference), so take care.
Definition at line 106 of file MetaData.cpp.
References com::xuggle::xuggler::IMetaData::make(), and mMetaData.
{
  if (!metaToUse)
    return 0;
  MetaData* retval = make();
  if (retval)
    retval->mMetaData = metaToUse;
  return retval;
}
MetaData * com::xuggle::xuggler::MetaData::make (AVMetadata * metaDataToCopy) [static]
Copies all meta data currently in metaDataToCopy and returns a new object.
Definition at line 120 of file MetaData.cpp.
References com::xuggle::xuggler::IMetaData::make(), mMetaData, and VS_REF_RELEASE.
{
  MetaData* retval = make();
  if (retval && metaDataToCopy)
  {
    AVMetadataTag* tag = 0;
    do {
      tag = av_metadata_get(metaDataToCopy, "", tag,
          AV_METADATA_IGNORE_SUFFIX);
      if (tag)
        if (av_metadata_set2(retval->mMetaData, tag->key, tag->value,0) < 0)
        {
          VS_REF_RELEASE(retval);
          break;
        }
    } while(tag);
  }
  return retval;
}
int32_t com::xuggle::xuggler::MetaData::copy (IMetaData * copy)
Destroys the current data, and copies all data from copy.
Definition at line 141 of file MetaData.cpp.
References mMetaData.
Referenced by com::xuggle::xuggler::Stream::setMetaData(), and com::xuggle::xuggler::Container::setMetaData().
{
  MetaData* data = dynamic_cast<MetaData*>(dataToCopy);
  if (!data)
    return -1;
  if (data == this)
    return 0;
  if (mMetaData && *mMetaData) {
    av_metadata_free(mMetaData);
    *mMetaData = 0;
  }
  AVMetadataTag* tag = 0;
  do {
    tag = av_metadata_get(*data->mMetaData, "", tag,
        AV_METADATA_IGNORE_SUFFIX);
    if (tag) {
      int32_t retval = av_metadata_set2(mMetaData,
          tag->key, tag->value, 0);
      if (retval < 0)
      {
        return retval;
      }
    }
  } while(tag);
  return 0;
}
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/MetaData.h
csrc/com/xuggle/xuggler/MetaData.cpp