Xuggle: com::xuggle::xuggler::Codec Class Reference
com::xuggle::xuggler::Codec Class Reference
#include <Codec.h>
Detailed Description
Definition at line 30 of file Codec.h.
Public Member Functions
virtual const char * getName ()
Get the name of the codec.
virtual int getIDAsInt ()
Get the ID of this codec, as an integer.
virtual Type getType ()
Get the type of this codec.
virtual ID getID ()
Get the ID of this codec as an enumeration.
AVCodec * getAVCodec ()
virtual bool canDecode ()
Can this codec be used for decoding?
virtual bool canEncode ()
Can this codec be used for encoding?
virtual const char * getLongName ()
Added for 1.17.
virtual int32_t getCapabilities ()
Get the capabilites flag from the codec.
virtual bool hasCapability (Capabilities flag)
Convenience method to check individual capability flags.
virtual int32_t getNumSupportedVideoFrameRates ()
Get the number of frame rates this codec supports for encoding.
virtual IRational * getSupportedVideoFrameRate (int32_t index)
Return the supported frame rate at the given index.
virtual int32_t getNumSupportedVideoPixelFormats ()
Get the number of supported video pixel formats this codec supports for encoding.
virtual IPixelFormat::Type getSupportedVideoPixelFormat (int32_t index)
Return the supported video pixel format at the given index.
virtual int32_t getNumSupportedAudioSampleRates ()
Get the number of different audio sample rates this codec supports for encoding.
virtual int32_t getSupportedAudioSampleRate (int32_t index)
Return the support audio sample rate at the given index.
virtual int32_t getNumSupportedAudioSampleFormats ()
Get the number of different audio sample formats this codec supports for encoding.
virtual IAudioSamples::Format getSupportedAudioSampleFormat (int32_t index)
Get the supported sample format at this index.
virtual int32_t getNumSupportedAudioChannelLayouts ()
Get the number of different audio channel layouts this codec supports for encoding.
virtual int64_t getSupportedAudioChannelLayout (int32_t index)
Get the supported audio channel layout at this index.
virtual int32_t acquire ()
Internal Only.
virtual int32_t release ()
Internal Only.
Codec ()
virtual ~Codec ()
Static Public Member Functions
static Codec * make (AVCodec *)
static Codec * findEncodingCodec (const ICodec::ID)
Find a codec that can be used for encoding.
static Codec * findEncodingCodecByIntID (const int)
Find a codec that can be used for encoding.
static Codec * findEncodingCodecByName (const char *)
Find a codec that can be used for encoding.
static Codec * findDecodingCodec (const ICodec::ID)
Find a codec that can be used for decoding.
static Codec * findDecodingCodecByIntID (const int)
Find a codec that can be used for decoding.
static Codec * findDecodingCodecByName (const char *)
Find a codec that can be used for decoding.
static Codec * guessEncodingCodec (IContainerFormat *fmt, const char *shortName, const char *url, const char *mime_type, ICodec::Type type)
Ask us to guess an encoding codec based on the inputs passed in.
Public Attributes
AVCodec * mCodec
Constructor & Destructor Documentation
com::xuggle::xuggler::Codec::Codec ()
Definition at line 32 of file Codec.cpp.
References mCodec, and VS_LOG_TRACE.
  {
    VS_LOG_TRACE("Starting");
    mCodec = 0;
  }
com::xuggle::xuggler::Codec::~Codec () [virtual]
Definition at line 38 of file Codec.cpp.
References mCodec.
  {
    // no memory freeing required.
    mCodec = 0;
  }
Member Function Documentation
Codec * com::xuggle::xuggler::Codec::make (AVCodec * aCodec) [static]
Definition at line 71 of file Codec.cpp.
References mCodec.
Referenced by findDecodingCodecByIntID(), findDecodingCodecByName(), findEncodingCodecByIntID(), findEncodingCodecByName(), and com::xuggle::xuggler::ICodec::getInstalledCodec().
  {
    Codec *retval = 0;
    if (aCodec)
    {
      retval = Codec::make();
      if (retval)
        retval->mCodec = aCodec;
    }
    return retval;
  }
const char * com::xuggle::xuggler::Codec::getName () [virtual]
Get the name of the codec.
Returns:
The name of this Codec.
Implements com::xuggle::xuggler::ICodec.
Definition at line 45 of file Codec.cpp.
References mCodec.
                   {
    const char * retval = 0;
    if (mCodec)
      retval = mCodec->name;
    return retval;
  }
int com::xuggle::xuggler::Codec::getIDAsInt () [virtual]
Get the ID of this codec, as an integer.
Returns:
the ID of this codec, as an integer.
Implements com::xuggle::xuggler::ICodec.
Definition at line 53 of file Codec.cpp.
References com::xuggle::xuggler::ICodec::CODEC_ID_NONE, and mCodec.
Referenced by getID().
  {
    int retval = CODEC_ID_NONE;
    if (mCodec)
      retval = mCodec->id;
    return retval;
  }
ICodec::Type com::xuggle::xuggler::Codec::getType () [virtual]
Get the type of this codec.
Returns:
The type of this Codec, as a enum Type
Implements com::xuggle::xuggler::ICodec.
Definition at line 62 of file Codec.cpp.
References mCodec.
  {
    Type retval = (Type) AVMEDIA_TYPE_UNKNOWN;
    if (mCodec)
      retval = (Type) mCodec->type;
    return retval;
  }
virtual ID com::xuggle::xuggler::Codec::getID () [inline, virtual]
Get the ID of this codec as an enumeration.
Returns:
the ID of this codec, an enum ID
Implements com::xuggle::xuggler::ICodec.
Definition at line 38 of file Codec.h.
References com::xuggle::xuggler::ICodec::CODEC_ID_NONE, and getIDAsInt().
    {
      // Warning; this might not be protable
      ID retval = CODEC_ID_NONE;
      int id = getIDAsInt();
      // This cast is not defined in C++ when id is
      // not in ID.  That means if we're using a
      // newer version of LIBAVCODEC this might
      // give a bogus value for a Codec we don't
      // know about.
      retval = (ID)id;
      if (id != (int) retval)
      {
        // we assume some back and forth conversion failed...
        retval = CODEC_ID_NONE;
      }
      return retval;
    }
AVCodec* com::xuggle::xuggler::Codec::getAVCodec () [inline]
Definition at line 59 of file Codec.h.
References mCodec.
{ return mCodec; }
Codec * com::xuggle::xuggler::Codec::findEncodingCodec (const ICodec::ID id) [static]
Find a codec that can be used for encoding.
Parameters:
id The id of the codec
Returns:
the codec, or null if we can't find it.
Reimplemented from com::xuggle::xuggler::ICodec.
Definition at line 84 of file Codec.cpp.
References findEncodingCodecByIntID().
Referenced by com::xuggle::xuggler::ICodec::findEncodingCodec().
  {
    return Codec::findEncodingCodecByIntID((const int)id);
  }
Codec * com::xuggle::xuggler::Codec::findEncodingCodecByIntID (const id) [static]
Find a codec that can be used for encoding.
Parameters:
id The id of the codec, as an integer.
Returns:
the codec, or null if we can't find it.
Reimplemented from com::xuggle::xuggler::ICodec.
Definition at line 89 of file Codec.cpp.
References com::xuggle::xuggler::Global::lock(), make(), and com::xuggle::xuggler::Global::unlock().
Referenced by findEncodingCodec(), com::xuggle::xuggler::ICodec::findEncodingCodecByIntID(), guessEncodingCodec(), and com::xuggle::xuggler::StreamCoder::setCodec().
  {
    Codec *retval = 0;
    AVCodec *codec = 0;
    enum CodecID ffmpeg_id = (enum CodecID) id;
    Global::lock();
    codec = avcodec_find_encoder(ffmpeg_id);
    Global::unlock();
    if (codec)
      retval = Codec::make(codec);
    return retval;
  }
Codec * com::xuggle::xuggler::Codec::findEncodingCodecByName (const char * id) [static]
Find a codec that can be used for encoding.
Parameters:
id The id of the codec, as a FFMPEG short-name string (for example, "mpeg4").
Returns:
the codec, or null if we can't find it.
Reimplemented from com::xuggle::xuggler::ICodec.
Definition at line 104 of file Codec.cpp.
References com::xuggle::xuggler::Global::lock(), make(), and com::xuggle::xuggler::Global::unlock().
Referenced by com::xuggle::xuggler::ICodec::findEncodingCodecByName().
  {
    Codec *retval = 0;
    AVCodec *codec = 0;
    if (name && *name)
    {
      Global::lock();
      codec = avcodec_find_encoder_by_name(name);
      Global::unlock();
      if (codec)
        retval = Codec::make(codec);
    }
    return retval;
  }
Codec * com::xuggle::xuggler::Codec::findDecodingCodec (const ICodec::ID id) [static]
Find a codec that can be used for decoding.
Parameters:
id The id of the codec
Returns:
the codec, or null if we can't find it.
Reimplemented from com::xuggle::xuggler::ICodec.
Definition at line 120 of file Codec.cpp.
References findDecodingCodecByIntID().
Referenced by com::xuggle::xuggler::ICodec::findDecodingCodec().
  {
    return Codec::findDecodingCodecByIntID((const int)id);
  }
Codec * com::xuggle::xuggler::Codec::findDecodingCodecByIntID (const id) [static]
Find a codec that can be used for decoding.
Parameters:
id The id of the codec, as an integer
Returns:
the codec, or null if we can't find it.
Reimplemented from com::xuggle::xuggler::ICodec.
Definition at line 126 of file Codec.cpp.
References com::xuggle::xuggler::Global::lock(), make(), and com::xuggle::xuggler::Global::unlock().
Referenced by findDecodingCodec(), com::xuggle::xuggler::ICodec::findDecodingCodecByIntID(), and com::xuggle::xuggler::StreamCoder::setCodec().
  {
    Codec *retval = 0;
    AVCodec *codec = 0;
    Global::lock();
    codec = avcodec_find_decoder((enum CodecID) id);
    Global::unlock();
    if (codec)
      retval = Codec::make(codec);
    return retval;
  }
Codec * com::xuggle::xuggler::Codec::findDecodingCodecByName (const char * id) [static]
Find a codec that can be used for decoding.
Parameters:
id The id of the codec, as a FFMPEG short-name string (for example, "mpeg4")
Returns:
the codec, or null if we can't find it.
Reimplemented from com::xuggle::xuggler::ICodec.
Definition at line 141 of file Codec.cpp.
References com::xuggle::xuggler::Global::lock(), make(), and com::xuggle::xuggler::Global::unlock().
Referenced by com::xuggle::xuggler::ICodec::findDecodingCodecByName().
  {
    Codec *retval = 0;
    AVCodec *codec = 0;
    if (name && *name)
    {
      Global::lock();
      codec = avcodec_find_decoder_by_name(name);
      Global::unlock();
      if (codec)
        retval = Codec::make(codec);
    }
    return retval;
  }
Codec * com::xuggle::xuggler::Codec::guessEncodingCodec (IContainerFormat * fmt, const char * shortName, const char * url, const char * mimeType, ICodec::Type type) [static]
Ask us to guess an encoding codec based on the inputs passed in.
You must pass in at least one non null fmt, shortName, url or mime_type.
Parameters:
fmt An IContainerFormat for the container you'll want to encode into.
shortName The FFMPEG short name of the codec (e.g. "mpeg4").
url The URL you'll be writing packets to.
mimeType The mime type of the container.
type The codec type.
Returns:
the codec, or null if we can't find it.
Reimplemented from com::xuggle::xuggler::ICodec.
Definition at line 168 of file Codec.cpp.
References findEncodingCodecByIntID(), com::xuggle::xuggler::IContainerFormat::make(), and com::xuggle::ferry::RefPointer< T >::reset().
Referenced by com::xuggle::xuggler::ICodec::guessEncodingCodec().
  {
    Codec* retval = 0;
    RefPointer<ContainerFormat> fmt = 0;
    AVOutputFormat * oFmt = 0;
    // We acquire here because the RefPointer always
    // releases.
    fmt.reset(dynamic_cast<ContainerFormat*>(pFmt), true);
    if (!fmt)
    {
      fmt = ContainerFormat::make();
      if (fmt)
        fmt->setOutputFormat(shortName, url, mimeType);
    }
    if (fmt)
      oFmt = fmt->getOutputFormat();
    // Make sure at least one in put is specified.
    // The av_guess_codec function REQUIRES a
    // non null AVOutputFormat
    // It also examines url with a strcmp(), so let's
    // give it a zero-length string.
    // In reality, it ignores the other params.
    if (!url)
      url = "";
    if (oFmt)
    {
      enum CodecID id = av_guess_codec(oFmt, shortName, url,
          mimeType, (enum AVMediaType) type);
      retval = Codec::findEncodingCodecByIntID((int)id);
    }
    return retval;
  }
bool com::xuggle::xuggler::Codec::canDecode () [virtual]
Can this codec be used for decoding?
Returns:
Can this Codec decode?
Implements com::xuggle::xuggler::ICodec.
Definition at line 156 of file Codec.cpp.
References mCodec.
  {
    return mCodec ? mCodec->decode : false;
  }
bool com::xuggle::xuggler::Codec::canEncode () [virtual]
Can this codec be used for encoding?
Returns:
Can this Codec encode?
Implements com::xuggle::xuggler::ICodec.
Definition at line 162 of file Codec.cpp.
References mCodec.
  {
    return mCodec ? mCodec->encode : false;
  }
const char * com::xuggle::xuggler::Codec::getLongName () [virtual]
Added for 1.17.
Get the long name for this codec.
Returns:
the long name.
Implements com::xuggle::xuggler::ICodec.
Definition at line 226 of file Codec.cpp.
References mCodec.
  {
    return mCodec ? mCodec->long_name : 0;
  }
int32_t com::xuggle::xuggler::Codec::getCapabilities () [virtual]
Get the capabilites flag from the codec.
Returns:
the capabilities flag
Implements com::xuggle::xuggler::ICodec.
Definition at line 232 of file Codec.cpp.
References mCodec.
  {
    if (!mCodec)
      return 0;
    return mCodec->capabilities;
  }
bool com::xuggle::xuggler::Codec::hasCapability (Capabilities capability) [virtual]
Convenience method to check individual capability flags.
Parameters:
capability the capability
Returns:
true if flag is set; false otherwise.
Implements com::xuggle::xuggler::ICodec.
Definition at line 239 of file Codec.cpp.
References mCodec.
  {
    if (!mCodec)
      return false;
    return mCodec->capabilities&flag;
  }
int32_t com::xuggle::xuggler::Codec::getNumSupportedVideoFrameRates () [virtual]
Get the number of frame rates this codec supports for encoding.
Not all codecs will report this number.
Returns:
the number or 0 if we don't know.
Implements com::xuggle::xuggler::ICodec.
Definition at line 247 of file Codec.cpp.
References mCodec.
  {
    if (!mCodec)
      return 0;
    int count = 0;
    for(
        const AVRational* p=mCodec->supported_framerates;
        p && !(!p->den && !p->num);
        p++
    )
      ++count;
    return count;
  }
IRational * com::xuggle::xuggler::Codec::getSupportedVideoFrameRate (int32_t index) [virtual]
Return the supported frame rate at the given index.
Parameters:
index the index in our list.
Returns:
the frame rate, or null if unknown, if index <0 or if index >= getNumSupportedVideoFrameRates()
Implements com::xuggle::xuggler::ICodec.
Definition at line 261 of file Codec.cpp.
References com::xuggle::xuggler::IRational::make(), and mCodec.
  {
    if (!mCodec)
      return 0;
    int i = 0;
    for(
        const AVRational* p=mCodec->supported_framerates;
        p && !(!p->den && !p->num);
        p++, i++
    )
      if (index == i)
        return IRational::make(p->num,p->den);
    return 0;
  }
int32_t com::xuggle::xuggler::Codec::getNumSupportedVideoPixelFormats () [virtual]
Get the number of supported video pixel formats this codec supports for encoding.
Not all codecs will report this.
Returns:
the number or 0 if we don't know.
Implements com::xuggle::xuggler::ICodec.
Definition at line 277 of file Codec.cpp.
References mCodec.
  {
    if (!mCodec)
      return 0;
    int count = 0;
    for(const enum PixelFormat* p = mCodec->pix_fmts;
    p && (*p!=-1);
    p++)
      ++count;
    return count;
  }
IPixelFormat::Type com::xuggle::xuggler::Codec::getSupportedVideoPixelFormat (int32_t index) [virtual]
Return the supported video pixel format at the given index.
Parameters:
index the index in our list.
Returns:
the pixel format, or IPixelFormat.Type#NONE if unknown, if index <0 or if index >= getNumSupportedVideoPixelFormats()
Implements com::xuggle::xuggler::ICodec.
Definition at line 291 of file Codec.cpp.
References mCodec, and com::xuggle::xuggler::IPixelFormat::NONE.
  {
    if (!mCodec)
      return IPixelFormat::NONE;
    int i = 0;
    for(const enum PixelFormat* p = mCodec->pix_fmts;
    p && (*p!=-1);
    p++,i++)
      if (index == i)
        return (IPixelFormat::Type)*p;
    return IPixelFormat::NONE;
  }
int32_t com::xuggle::xuggler::Codec::getNumSupportedAudioSampleRates () [virtual]
Get the number of different audio sample rates this codec supports for encoding.
Not all codecs will report this.
Returns:
the number or 0 if we don't know.
Implements com::xuggle::xuggler::ICodec.
Definition at line 305 of file Codec.cpp.
References mCodec.
  {
    if (!mCodec)
      return 0;
    int i = 0;
    for(const int *p = mCodec->supported_samplerates;
    p && *p;
    ++p, ++i)
      ;
    return i;
  }
int32_t com::xuggle::xuggler::Codec::getSupportedAudioSampleRate (int32_t index) [virtual]
Return the support audio sample rate at the given index.
Parameters:
index the index in our list.
Returns:
the sample rate, or 0 if unknown, index < 0 or index >= getNumSupportedAudioSampleRates()
Implements com::xuggle::xuggler::ICodec.
Definition at line 317 of file Codec.cpp.
References mCodec.
  {
    if (!mCodec)
      return 0;
    int i = 0;
    for(const int *p = mCodec->supported_samplerates;
    p && *p;
    p++, i++)
      if (i == index)
        return *p;
    return 0;
  }
int32_t com::xuggle::xuggler::Codec::getNumSupportedAudioSampleFormats () [virtual]
Get the number of different audio sample formats this codec supports for encoding.
Not all codecs will report this.
Returns:
the number or 0 if we don't know.
Implements com::xuggle::xuggler::ICodec.
Definition at line 331 of file Codec.cpp.
References mCodec.
  {
    if (!mCodec)
      return 0;
    int i = 0;
    for(const enum SampleFormat* p=mCodec->sample_fmts;
      p && (*p != -1);
      p++,i++)
      ;
    return i;
  }
IAudioSamples::Format com::xuggle::xuggler::Codec::getSupportedAudioSampleFormat (int32_t index) [virtual]
Get the supported sample format at this index.
Parameters:
index the index in our list.
Returns:
the format, or IAudioSamples.Format.FMT_NONE if unknown, index < 0 or index >= getNumSupportedAudioSampleFormats().
Implements com::xuggle::xuggler::ICodec.
Definition at line 344 of file Codec.cpp.
References com::xuggle::xuggler::IAudioSamples::FMT_NONE, and mCodec.
  {
    if (!mCodec)
      return IAudioSamples::FMT_NONE;
    int i = 0;
    for(const enum SampleFormat* p=mCodec->sample_fmts;
      p && (*p != -1);
      p++,i++)
      if (index == i)
        return (IAudioSamples::Format)*p;
    return IAudioSamples::FMT_NONE;
  }
int32_t com::xuggle::xuggler::Codec::getNumSupportedAudioChannelLayouts () [virtual]
Get the number of different audio channel layouts this codec supports for encoding.
Not all codecs will report this.
Returns:
the number or 0 if we don't know.
Implements com::xuggle::xuggler::ICodec.
Definition at line 359 of file Codec.cpp.
References mCodec.
  {
    if (!mCodec)
      return 0;
    int i = 0;
    for(const int64_t* p=mCodec->channel_layouts;
      p && *p;
      p++,i++)
      ;
    return i;
  }
int64_t com::xuggle::xuggler::Codec::getSupportedAudioChannelLayout (int32_t index) [virtual]
Get the supported audio channel layout at this index.
The value returned is a bit flag representing the different types of audio layout this codec can support. Test the values by bit-comparing them to the IAudioSamples.ChannelLayout enum types.
Parameters:
index the index
Returns:
the channel layout, or 0 if unknown, index < 0 or index >= getNumSupportedAudioChannelLayouts.
Implements com::xuggle::xuggler::ICodec.
Definition at line 371 of file Codec.cpp.
References mCodec.
  {
    if (!mCodec)
      return 0;
    int i = 0;
    for(const int64_t* p=mCodec->channel_layouts;
      p && *p;
      p++,i++)
      if (index == i)
        return *p;
    return 0;
  }
int32_t com::xuggle::xuggler::Codec::acquire () [virtual]
Internal Only.
DO NOT USE FROM JAVA.
Acquire a reference to this object. This increments the native internal ref count in native code by +1.
This method is called internally by Ferry in Java, and you should not call it without knowing what you are doing. But if you do call it, make sure you call release() once for each call you make to this method.
Returns:
The refcount after the acquire. Note due to multi-threaded issues, you should not rely on this value, as it may change before the method returns to you.
Reimplemented from com::xuggle::ferry::RefCounted.
Definition at line 210 of file Codec.cpp.
References com::xuggle::ferry::RefCounted::acquire(), and VS_LOG_TRACE.
  {
    int retval = 0;
    retval = RefCounted::acquire();
    VS_LOG_TRACE("Acquired %p: %d", this, retval);
    return retval;
  }
int32_t com::xuggle::xuggler::Codec::release () [virtual]
Internal Only.
DO NOT USE FROM JAVA.
This decrements the native internal ref count by -1; the object is destroyed if its ref count reaches zero.
This method is called internally by Ferry in Java, and you should not call it without knowing what you are doing. But if you do call it, make sure you had previously called acquire() once for each call to release() you make.
Returns:
The ref count after the release. Note due to multi-threaded issues, you should not rely on this value, as it may change before the method returns to you.
Reimplemented from com::xuggle::ferry::RefCounted.
Definition at line 218 of file Codec.cpp.
References com::xuggle::ferry::RefCounted::release(), and VS_LOG_TRACE.
  {
    int retval = 0;
    retval = RefCounted::release();
    VS_LOG_TRACE("Released %p: %d", this, retval);
    return retval;
  }
Member Data Documentation
AVCodec* com::xuggle::xuggler::Codec::mCodec
Definition at line 103 of file Codec.h.
Referenced by canDecode(), canEncode(), Codec(), getAVCodec(), getCapabilities(), getIDAsInt(), getLongName(), getName(), getNumSupportedAudioChannelLayouts(), getNumSupportedAudioSampleFormats(), getNumSupportedAudioSampleRates(), getNumSupportedVideoFrameRates(), getNumSupportedVideoPixelFormats(), getSupportedAudioChannelLayout(), getSupportedAudioSampleFormat(), getSupportedAudioSampleRate(), getSupportedVideoFrameRate(), getSupportedVideoPixelFormat(), getType(), hasCapability(), make(), and ~Codec().
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/Codec.h
csrc/com/xuggle/xuggler/Codec.cpp