Xuggle: com::xuggle::ferry::LoggerStack Class Reference
com::xuggle::ferry::LoggerStack Class Reference
#include <LoggerStack.h>
Detailed Description
This class records the Global logging levels when it is created, and, if it changes the Global logging level, restores it to the original values when it is destroyed.
It is handy to use in tests where you know a log (and hence error message) will be generated, but you want to temporarily turn off logging when the test runs.
Definition at line 37 of file LoggerStack.h.
Public Member Functions
LoggerStack ()
virtual ~LoggerStack ()
void setGlobalLevel (Logger::Level level, bool value)
If false, sets level and all lower levels to false.
Constructor & Destructor Documentation
com::xuggle::ferry::LoggerStack::LoggerStack ()
Definition at line 28 of file LoggerStack.cpp.
References com::xuggle::ferry::Logger::isGlobalLogging(), and VS_LOG_TRACE.
  {
    VS_LOG_TRACE("Creating LoggerStack");
    for(int i = 0; i < 5; i++)
    {
      mOrigLevel[i] = Logger::isGlobalLogging((Logger::Level)i);
      mHasChangedLevel[i] = false;
    }
  }
com::xuggle::ferry::LoggerStack::~LoggerStack () [virtual]
Definition at line 38 of file LoggerStack.cpp.
References com::xuggle::ferry::Logger::setGlobalIsLogging(), and VS_LOG_TRACE.
  {
    for(int i = 0; i<5; i++)
    {
      if (mHasChangedLevel[i])
        Logger::setGlobalIsLogging((Logger::Level)i, mOrigLevel[i]);
    }
    VS_LOG_TRACE("Destroying LoggerStack");
  }
Member Function Documentation
void com::xuggle::ferry::LoggerStack::setGlobalLevel (Logger::Level level, bool value)
If false, sets level and all lower levels to false.
If true, sets current level to true, and all lower levels to original value.
Parameters:
level The level to set.
value Whether to log (true) or not (false).
Definition at line 50 of file LoggerStack.cpp.
References com::xuggle::ferry::Logger::setGlobalIsLogging().
  {
    // Set all levels up to an include this level to value.
    mHasChangedLevel[level] = true;
    Logger::setGlobalIsLogging(level, value);
    for(int i = level; i < 5; i++)
    {
      mHasChangedLevel[i] = true;
      if (value)
      {
        Logger::setGlobalIsLogging((Logger::Level)i, mOrigLevel[i]);
      } else {
        Logger::setGlobalIsLogging((Logger::Level)i, value);
      }
    }
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/ferry/LoggerStack.h
csrc/com/xuggle/ferry/LoggerStack.cpp