Xuggle: com::xuggle::xuggler::Property Class Reference
com::xuggle::xuggler::Property Class Reference
#include <Property.h>
Detailed Description
A wrapper for an FFMPEG AVOption value.
Definition at line 35 of file Property.h.
Public Member Functions
virtual const char * getName ()
IProperty implementation.
virtual const char * getHelp ()
Get the (English) help string for this property.
virtual const char * getUnit ()
Get any sub-unit this option or constant belongs to.
virtual Type getType ()
Get the underlying native type of this property.
virtual int64_t getDefault ()
Get the default setting this flag would have it not set.
virtual double getDefaultAsDouble ()
Get the default setting this flag would have it not set.
virtual int32_t getFlags ()
Get any set flags (a bitmask) for this option.
virtual int32_t getNumFlagSettings ()
If this IProperty is of the type Type#PROPERTY_FLAGS, this method will tell you how many different flag settings it takes.
virtual IProperty * getFlagConstant (int32_t position)
If this IProperty is of the type Type#PROPERTY_FLAGS, this method will give you another IProperty representing a constant setting for that flag.
virtual IProperty * getFlagConstant (const char *name)
If this IProperty is of the type Type#PROPERTY_FLAGS, this method will give you another IProperty representing a constant setting for that flag.
Static Public Member Functions
static Property * make (const AVOption *start, const AVOption *option)
static int32_t getNumProperties (void *context)
For internal use.
static IProperty * getPropertyMetaData (void *context, int32_t propertyNo)
Returns the metadata for the numbered property.
static IProperty * getPropertyMetaData (void *context, const char *name)
Returns the metadata for the named property.
static int32_t setProperty (void *context, const char *name, const char *value)
Looks up the property 'name' in 'context' and sets the value of the property to 'value'.
static int32_t setProperty (void *context, const char *name, double value)
Looks up the property 'name' in 'context' and sets the value of the property to 'value'.
static int32_t setProperty (void *context, const char *name, int64_t value)
Looks up the property 'name' in 'context' and sets the value of the property to 'value'.
static int32_t setProperty (void *context, const char *name, bool value)
Looks up the property 'name' in 'context' and sets the value of the property to 'value'.
static int32_t setProperty (void *context, const char *name, IRational *value)
Looks up the property 'name' in 'context' and sets the value of the property to 'value'.
static char * getPropertyAsString (void *context, const char *name)
Gets the value of this property, and returns as a new[]ed string.
static double getPropertyAsDouble (void *context, const char *name)
Gets the value of this property, and returns as a double;.
static int64_t getPropertyAsLong (void *context, const char *name)
Gets the value of this property, and returns as an long;.
static IRational * getPropertyAsRational (void *context, const char *name)
Gets the value of this property, and returns as an IRational;.
static bool getPropertyAsBoolean (void *context, const char *name)
Gets the value of this property, and returns as a boolean.
Protected Member Functions
Property ()
virtual ~Property ()
Constructor & Destructor Documentation
com::xuggle::xuggler::Property::Property () [protected]
Definition at line 34 of file Property.cpp.
  {
    mOption=0;
    mOptionStart=0;
  }
com::xuggle::xuggler::Property::~Property () [protected, virtual]
Definition at line 40 of file Property.cpp.
  {
  }
Member Function Documentation
Property * com::xuggle::xuggler::Property::make (const AVOption * start, const AVOption * option) [static]
Definition at line 45 of file Property.cpp.
References mOption, mOptionStart, and VS_REF_RELEASE.
Referenced by getFlagConstant(), and getPropertyMetaData().
  {
    Property *retval = 0;
    try
    {
      if (!start)
        throw std::bad_alloc();
      if (!option)
        throw std::bad_alloc();
      retval = Property::make();
      if (retval)
      {
        retval ->mOptionStart = start;
        retval->mOption = option;
      }
    }
    catch (std::bad_alloc & e)
    {
      VS_REF_RELEASE(retval);
      throw e;
    }
    return retval;
  }
const char * com::xuggle::xuggler::Property::getName () [virtual]
IProperty implementation.
Implements com::xuggle::xuggler::IProperty.
Definition at line 70 of file Property.cpp.
  {
    return mOption ? mOption->name : 0;
  }
const char * com::xuggle::xuggler::Property::getHelp () [virtual]
Get the (English) help string for this property.
Returns:
the help string
Implements com::xuggle::xuggler::IProperty.
Definition at line 76 of file Property.cpp.
  {
    return mOption ? mOption->help : 0;
  }
const char * com::xuggle::xuggler::Property::getUnit () [virtual]
Get any sub-unit this option or constant belongs to.
Returns:
the unit, or null if none.
Implements com::xuggle::xuggler::IProperty.
Definition at line 82 of file Property.cpp.
Referenced by getFlagConstant(), and getNumFlagSettings().
  {
    return mOption ? mOption->unit : 0;
  }
IProperty::Type com::xuggle::xuggler::Property::getType () [virtual]
Get the underlying native type of this property.
Returns:
the type
Implements com::xuggle::xuggler::IProperty.
Definition at line 88 of file Property.cpp.
References com::xuggle::xuggler::IProperty::PROPERTY_UNKNOWN.
Referenced by getFlagConstant(), and getNumFlagSettings().
  {
    return mOption ? (IProperty::Type) mOption->type : IProperty::PROPERTY_UNKNOWN;
  }
int64_t com::xuggle::xuggler::Property::getDefault () [virtual]
Get the default setting this flag would have it not set.
Returns:
the default
Implements com::xuggle::xuggler::IProperty.
Definition at line 94 of file Property.cpp.
References getDefaultAsDouble().
  {
    return (int64_t)getDefaultAsDouble();
  }
double com::xuggle::xuggler::Property::getDefaultAsDouble () [virtual]
Get the default setting this flag would have it not set.
Returns:
the default
Implements com::xuggle::xuggler::IProperty.
Definition at line 100 of file Property.cpp.
Referenced by getDefault().
  {
    return mOption ? mOption->default_val.dbl: 0.0;
  }
int32_t com::xuggle::xuggler::Property::getFlags () [virtual]
Get any set flags (a bitmask) for this option.
Returns:
the flags
Implements com::xuggle::xuggler::IProperty.
Definition at line 106 of file Property.cpp.
  {
    return mOption ? mOption->flags : 0;
  }
int32_t com::xuggle::xuggler::Property::getNumFlagSettings () [virtual]
If this IProperty is of the type Type#PROPERTY_FLAGS, this method will tell you how many different flag settings it takes.
Returns:
Number of flag settings, or <0 if not a FLAGS value
Implements com::xuggle::xuggler::IProperty.
Definition at line 277 of file Property.cpp.
References getType(), getUnit(), com::xuggle::xuggler::IProperty::PROPERTY_FLAGS, and VS_LOG_DEBUG.
  {
    int32_t retval = 0;
    try {
      if (getType() != IProperty::PROPERTY_FLAGS)
        throw std::runtime_error("flag is not of type PROPERTY_FLAGS");
      // now, iterate through all options, counting all CONSTS that belong
      // to the same unit as this option
      const char* unit = getUnit();
      if (!unit || !*unit)
        throw std::runtime_error("flag doesn't have a unit setting, so can't tell what constants");
      // Create a fake class
      AVClass fakeClass;
      fakeClass.class_name="XuggleFakeClass";
      fakeClass.item_name = fakeContextToName;
      fakeClass.option = mOptionStart;
      AVClass *fakeClassPtr = &fakeClass;
      const AVOption* last = 0;
      do
      {
        last = av_next_option(&fakeClassPtr, last);
        if (last &&
            last->unit &&
            last->type == FF_OPT_TYPE_CONST &&
            strcmp(unit, last->unit)==0)
          ++retval;
      } while(last);
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      retval = -1;
    }
    return retval;
  }
IProperty * com::xuggle::xuggler::Property::getFlagConstant (int32_t position) [virtual]
If this IProperty is of the type Type#PROPERTY_FLAGS, this method will give you another IProperty representing a constant setting for that flag.
Parameters:
position The position number for the flag; Must be in range 0 <= position <= getNumFlagSettings().
Returns:
An IProperty object for the flag setting, or null if not available.
Implements com::xuggle::xuggler::IProperty.
Definition at line 317 of file Property.cpp.
References getType(), getUnit(), make(), com::xuggle::xuggler::IProperty::PROPERTY_FLAGS, VS_LOG_DEBUG, and VS_REF_RELEASE.
  {
    IProperty *retval = 0;
    try
    {
      if (getType() != IProperty::PROPERTY_FLAGS)
        throw std::runtime_error("flag is not of type PROPERTY_FLAGS");
      // now, iterate through all options, counting all CONSTS that belong
      // to the same unit as this option
      const char* unit = getUnit();
      if (!unit || !*unit)
        throw std::runtime_error("flag doesn't have a unit setting, so can't tell what constants");
      // Create a fake class
      AVClass fakeClass;
      fakeClass.class_name="XuggleFakeClass";
      fakeClass.item_name = fakeContextToName;
      fakeClass.option = mOptionStart;
      AVClass *fakeClassPtr = &fakeClass;
      const AVOption* last = 0;
      int32_t constNo = -1;
      do
      {
        last = av_next_option(&fakeClassPtr, last);
        if (last &&
            last->unit &&
            last->type == FF_OPT_TYPE_CONST &&
            strcmp(unit, last->unit)==0)
        {
          // count in the same was as getNumFlagSettings,
          // and then return if the position is equal
          ++constNo;
          if (constNo == position)
          {
            retval = Property::make(av_next_option(&fakeClassPtr, 0), last);
          }
        }
      } while(last);
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
IProperty * com::xuggle::xuggler::Property::getFlagConstant (const char * name) [virtual]
If this IProperty is of the type Type#PROPERTY_FLAGS, this method will give you another IProperty representing a constant setting for that flag.
Parameters:
name The name of the constant.
Returns:
An IProperty object for the flag setting, or null if not available.
Implements com::xuggle::xuggler::IProperty.
Definition at line 368 of file Property.cpp.
References getType(), getUnit(), make(), com::xuggle::xuggler::IProperty::PROPERTY_FLAGS, VS_LOG_DEBUG, and VS_REF_RELEASE.
  {
    IProperty *retval = 0;
    try
    {
      if (getType() != IProperty::PROPERTY_FLAGS)
        throw std::runtime_error("flag is not of type PROPERTY_FLAGS");
      // now, iterate through all options, counting all CONSTS that belong
      // to the same unit as this option
      const char* unit = getUnit();
      if (!unit || !*unit)
        throw std::runtime_error("flag doesn't have a unit setting, so can't tell what constants");
      AVClass fakeClass;
      fakeClass.class_name="XuggleFakeClass";
      fakeClass.item_name = fakeContextToName;
      fakeClass.option = mOptionStart;
      const AVOption* last = 0;
      last = av_find_opt(&fakeClass, aName, unit, 0, 0);
      if (last)
      {
        if (last->type == FF_OPT_TYPE_CONST)
        {
          retval = Property::make(av_next_option(&fakeClass, 0), last);
        }
      }
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
int32_t com::xuggle::xuggler::Property::getNumProperties (void * context) [static]
For internal use.
Returns the total number of settable properties on this object
Parameters:
context AVClass to search for options in
Returns:
total number of options (not including constant definitions)
Definition at line 112 of file Property.cpp.
Referenced by com::xuggle::xuggler::VideoResampler::getNumProperties(), com::xuggle::xuggler::StreamCoder::getNumProperties(), and com::xuggle::xuggler::Container::getNumProperties().
  {
    int32_t retval=0;
    const AVOption* last = 0;
    if (aContext)
    {
      do {
        last = av_next_option(aContext, last);
        if (last)
        {
          if (last->type != FF_OPT_TYPE_CONST)
            ++retval;
        }
      } while (last);
    }
    return retval;
  }
IProperty * com::xuggle::xuggler::Property::getPropertyMetaData (void * context, int32_t propertyNo) [static]
Returns the metadata for the numbered property.
Note that a property number is guaranteed to stay constant during this run of Xuggler, but the property number may change if the process restarts.
Parameters:
context AVClass to search for options in
propertyNo The property number in the options list.
Returns:
the meta data for this property, or null if not found
Definition at line 131 of file Property.cpp.
References make(), VS_LOG_DEBUG, and VS_REF_RELEASE.
Referenced by com::xuggle::xuggler::VideoResampler::getPropertyMetaData(), com::xuggle::xuggler::StreamCoder::getPropertyMetaData(), and com::xuggle::xuggler::Container::getPropertyMetaData().
  {
    IProperty *retval = 0;
    const AVOption* last = 0;
    try
    {
      if (!aContext)
        throw std::runtime_error("no context passed in");
      int32_t optionNo=-1;
      do {
        last = av_next_option(aContext, last);
        if (last)
        {
          if (last->type != FF_OPT_TYPE_CONST)
          {
            ++optionNo;
            // now see if this option position matches the property asked for
            if (optionNo == aPropertyNo)
            {
              retval = Property::make(av_next_option(aContext, 0), last);
              break;
            }
          }
        }
      } while (last);
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
IProperty * com::xuggle::xuggler::Property::getPropertyMetaData (void * context, const char * name) [static]
Returns the metadata for the named property.
Parameters:
context AVClass to search for options in
name The property number in the options list.
Returns:
the meta data for this property, or null if not found
Definition at line 168 of file Property.cpp.
References make(), VS_LOG_DEBUG, and VS_REF_RELEASE.
  {
    IProperty *retval = 0;
    const AVOption* last = 0;
    try
    {
      if (!aContext)
        throw std::runtime_error("no context passed in");
      if (!aName || !*aName)
        throw std::runtime_error("no property name passed in");
      last = av_find_opt(aContext, aName, 0, 0, 0);
      if (last)
      {
        if (last->type != FF_OPT_TYPE_CONST)
        {
          retval = Property::make(av_next_option(aContext, 0), last);
        }
      }
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
int32_t com::xuggle::xuggler::Property::setProperty (void * context, const char * name, const char * value) [static]
Looks up the property 'name' in 'context' and sets the value of the property to 'value'.
Parameters:
context AVClass to search for option in.
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Definition at line 199 of file Property.cpp.
References VS_LOG_DEBUG.
Referenced by com::xuggle::xuggler::VideoResampler::setProperty(), com::xuggle::xuggler::StreamCoder::setProperty(), setProperty(), and com::xuggle::xuggler::Container::setProperty().
  {
    int32_t retval = -1;
    try
    {
      if (!aContext)
        throw std::runtime_error("no context passed in");
      if (!aName  || !*aName)
        throw std::runtime_error("empty property name passed to setProperty");
      retval = av_set_string3(aContext, aName, aValue, 1, 0);
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      retval = -1;
    }
    return retval;
  }
int32_t com::xuggle::xuggler::Property::setProperty (void * context, const char * name, double value) [static]
Looks up the property 'name' in 'context' and sets the value of the property to 'value'.
Parameters:
context AVClass to search for option in.
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Definition at line 483 of file Property.cpp.
References VS_LOG_DEBUG.
  {
    int32_t retval = 0;
    try
    {
      if (!aContext)
        throw std::runtime_error("no context passed in");
      if (!aName  || !*aName)
        throw std::runtime_error("empty property name passed to setProperty");
      retval = av_set_double(aContext, aName, value) ? 0 : -1;
    }
    catch (std::exception &e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      retval = -1;
    }
    return retval;
  }
int32_t com::xuggle::xuggler::Property::setProperty (void * context, const char * name, int64_t value) [static]
Looks up the property 'name' in 'context' and sets the value of the property to 'value'.
Parameters:
context AVClass to search for option in.
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Definition at line 505 of file Property.cpp.
References VS_LOG_DEBUG.
  {
    int32_t retval = 0;
    try
    {
      if (!aContext)
        throw std::runtime_error("no context passed in");
      if (!aName  || !*aName)
        throw std::runtime_error("empty property name passed to setProperty");
      retval = av_set_int(aContext, aName, value) ? 0 : -1;
    }
    catch (std::exception &e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      retval = -1;
    }
    return retval;
  }
int32_t com::xuggle::xuggler::Property::setProperty (void * context, const char * name, bool value) [static]
Looks up the property 'name' in 'context' and sets the value of the property to 'value'.
Parameters:
context AVClass to search for option in.
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Definition at line 527 of file Property.cpp.
References setProperty().
  {
    return setProperty(aContext, aName, (int64_t)value);
  }
int32_t com::xuggle::xuggler::Property::setProperty (void * context, const char * name, IRational * value) [static]
Looks up the property 'name' in 'context' and sets the value of the property to 'value'.
Parameters:
context AVClass to search for option in.
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Definition at line 533 of file Property.cpp.
References com::xuggle::xuggler::IRational::getDenominator(), com::xuggle::xuggler::IRational::getNumerator(), and VS_LOG_DEBUG.
  {
    int32_t retval = 0;
    try
    {
      if (!aContext)
        throw std::runtime_error("no context passed in");
      if (!aName  || !*aName)
        throw std::runtime_error("empty property name passed to setProperty");
      if (!value)
        throw std::runtime_error("no rational value passed in");
      AVRational rational;
      rational.num = value->getNumerator();
      rational.den = value->getDenominator();
      retval = av_set_q(aContext, aName, rational) ? 0 : -1;
    }
    catch (std::exception &e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      retval = -1;
    }
    return retval;
  }
char * com::xuggle::xuggler::Property::getPropertyAsString (void * context, const char * name) [static]
Gets the value of this property, and returns as a new[]ed string.
Caller must call delete[] on string.
Parameters:
context AVClass context to search for option in.
name name of option
Returns:
string version of option value (caller must call delete[]) or null on error.
Definition at line 224 of file Property.cpp.
References VS_LOG_DEBUG.
Referenced by com::xuggle::xuggler::VideoResampler::getPropertyAsString(), com::xuggle::xuggler::StreamCoder::getPropertyAsString(), and com::xuggle::xuggler::Container::getPropertyAsString().
  {
    char* retval = 0;
    try
    {
      if (!aContext)
        throw std::runtime_error("no context passed in");
      if (!aName  || !*aName)
        throw std::runtime_error("empty property name passed to setProperty");
      // we don't allow a string value longer than this.  This is
      // actually safe because this buffer is only used for non-string options
      char tmpBuffer[512];
      int32_t bufLen = sizeof(tmpBuffer)/sizeof(char);
      const char* value = av_get_string(aContext, aName,0,tmpBuffer,bufLen);
      if (value)
      {
        // let's make a copy of the data
        int32_t valLen = strlen(value);
        if (valLen > 0)
        {
          retval = new char[valLen+1];
          if (!retval)
            throw std::bad_alloc();
          // copy the data
          strncpy(retval, value, valLen+1);
        }
      }
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      if (retval)
        delete [] retval;
      retval = 0;
    }
    // NOTE: Caller must call delete[] on returned value; we mean it!
    return retval;
  }
double com::xuggle::xuggler::Property::getPropertyAsDouble (void * context, const char * name) [static]
Gets the value of this property, and returns as a double;.
Parameters:
context AVClass context to search for option in.
name name of option
Returns:
double value of property, or 0 on error.
Definition at line 407 of file Property.cpp.
References VS_LOG_DEBUG.
Referenced by com::xuggle::xuggler::VideoResampler::getPropertyAsDouble(), com::xuggle::xuggler::StreamCoder::getPropertyAsDouble(), and com::xuggle::xuggler::Container::getPropertyAsDouble().
  {
    double retval = 0;
    try
    {
      if (!aContext)
        throw std::runtime_error("no context passed in");
      if (!aName  || !*aName)
        throw std::runtime_error("empty property name passed to setProperty");
      retval = av_get_double(aContext, aName, 0);
    }
    catch (std::exception &e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      retval = 0;
    }
    return retval;
  }
int64_t com::xuggle::xuggler::Property::getPropertyAsLong (void * context, const char * name) [static]
Gets the value of this property, and returns as an long;.
Parameters:
context AVClass context to search for option in.
name name of option
Returns:
long value of property, or 0 on error.
Definition at line 430 of file Property.cpp.
References VS_LOG_DEBUG.
Referenced by getPropertyAsBoolean(), com::xuggle::xuggler::VideoResampler::getPropertyAsLong(), com::xuggle::xuggler::StreamCoder::getPropertyAsLong(), and com::xuggle::xuggler::Container::getPropertyAsLong().
  {
    int64_t retval = 0;
    try
    {
      if (!aContext)
        throw std::runtime_error("no context passed in");
      if (!aName  || !*aName)
        throw std::runtime_error("empty property name passed to setProperty");
      retval = av_get_int(aContext, aName, 0);
    }
    catch (std::exception &e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      retval = 0;
    }
    return retval;
  }
IRational * com::xuggle::xuggler::Property::getPropertyAsRational (void * context, const char * name) [static]
Gets the value of this property, and returns as an IRational;.
Parameters:
context AVClass context to search for option in.
name name of option
Returns:
long value of property, or 0 on error.
Definition at line 453 of file Property.cpp.
References com::xuggle::xuggler::IRational::make(), VS_LOG_DEBUG, and VS_REF_RELEASE.
Referenced by com::xuggle::xuggler::VideoResampler::getPropertyAsRational(), com::xuggle::xuggler::StreamCoder::getPropertyAsRational(), and com::xuggle::xuggler::Container::getPropertyAsRational().
  {
    IRational *retval = 0;
    try
    {
      if (!aContext)
        throw std::runtime_error("no context passed in");
      if (!aName  || !*aName)
        throw std::runtime_error("empty property name passed to setProperty");
      AVRational value = av_get_q(aContext, aName, 0);
      retval = IRational::make(value.num, value.den);
    }
    catch (std::exception &e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
bool com::xuggle::xuggler::Property::getPropertyAsBoolean (void * context, const char * name) [static]
Gets the value of this property, and returns as a boolean.
Parameters:
context AVClass context to search for option in.
name name of option
Returns:
boolean value of property, or false on error.
Definition at line 477 of file Property.cpp.
References getPropertyAsLong().
Referenced by com::xuggle::xuggler::VideoResampler::getPropertyAsBoolean(), com::xuggle::xuggler::StreamCoder::getPropertyAsBoolean(), and com::xuggle::xuggler::Container::getPropertyAsBoolean().
  {
    return (bool) getPropertyAsLong(aContext, aName);
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/Property.h
csrc/com/xuggle/xuggler/Property.cpp