Xuggle: com::xuggle::xuggler::StreamCoder Class Reference
com::xuggle::xuggler::StreamCoder Class Reference
#include <StreamCoder.h>
Detailed Description
Definition at line 35 of file StreamCoder.h.
Public Member Functions
virtual Direction getDirection ()
Get the direction.
virtual IStream * getStream ()
The associated Stream we're working on.
virtual ICodec * getCodec ()
The Codec this StreamCoder will use.
virtual ICodec::Type getCodecType ()
A short hand for getCodec().getType().
virtual ICodec::ID getCodecID ()
A short hand for getCodec().getID().
virtual void setCodec (ICodec *)
Set the Codec to the passed in Codec, discarding the old Codec if set.
virtual void setCodec (ICodec::ID)
Look up a Codec based on the passed in ID, and then set it.
virtual void setCodecID (ICodec::ID id)
Look up a Codec based on the passed in ID, and then set it.
virtual int32_t getBitRate ()
The bit rate.
virtual void setBitRate (int32_t rate)
When ENCODING, sets the bit rate to use.
virtual int32_t getBitRateTolerance ()
The bit rate tolerance.
virtual void setBitRateTolerance (int32_t tolerance)
When ENCODING set the bit rate tolerance.
virtual int32_t getHeight ()
The height, in pixels.
virtual void setHeight (int32_t)
Set the height, in pixels.
virtual int32_t getWidth ()
The width, in pixels.
virtual void setWidth (int32_t)
Set the width, in pixels.
virtual IRational * getTimeBase ()
Get the time base this stream will ENCODE in, or the time base we detect while DECODING.
virtual void setTimeBase (IRational *newTimeBase)
Set the time base we'll use to ENCODE with.
virtual IRational * getFrameRate ()
Get the frame-rate the attached stream claims to be using when DECODING, or the frame-rate we'll claim we're using when ENCODING.
virtual void setFrameRate (IRational *newFrameRate)
Set the frame rate we'll set in the headers of this stream while ENCODING.
virtual int32_t getNumPicturesInGroupOfPictures ()
The the number of pictures in this Group of Pictures (GOP).
virtual void setNumPicturesInGroupOfPictures (int32_t gops)
Set the GOPS on this stream.
virtual IPixelFormat::Type getPixelType ()
For Video streams, get the Pixel Format in use by the stream.
virtual void setPixelType (IPixelFormat::Type pixelFmt)
Set the pixel format to ENCODE with.
virtual int32_t getSampleRate ()
Get the sample rate we use for this stream.
virtual void setSampleRate (int32_t sampleRate)
Set the sample rate to use when ENCODING.
virtual int32_t getChannels ()
Get the number of channels in this audio stream.
virtual void setChannels (int32_t channels)
Set the number of channels to use when ENCODING.
virtual IAudioSamples::Format getSampleFormat ()
Get the audio sample format.
virtual void setSampleFormat (IAudioSamples::Format aFormat)
Set the sample format when ENCODING.
virtual int32_t getGlobalQuality ()
Get the Global Quality setting this codec uses for video if a VideoPicture doesn't have a quality set.
virtual void setGlobalQuality (int32_t newQuality)
Set the Global Quality to a new value.
virtual int32_t getFlags ()
Get the flags associated with this codec.
virtual void setFlags (int32_t newFlags)
Set the FFMPEG flags to use with this codec.
virtual bool getFlag (Flags flag)
Get the setting for the specified flag.
virtual void setFlag (Flags flag, bool value)
Set the flag.
virtual int32_t getAudioFrameSize ()
For this stream, get the number of audio samples that are represented in a packet of information.
virtual int32_t open ()
Open the Codec associated with this StreamCoder.
virtual int32_t close ()
Close a Codec that was opened on this StreamCoder.
virtual int32_t decodeAudio (IAudioSamples *pOutSamples, IPacket *packet, int32_t byteOffset)
Decode this packet into pOutSamples.
virtual int32_t decodeVideo (IVideoPicture *pOutFrame, IPacket *packet, int32_t byteOffset)
Decode this packet into pOutFrame.
virtual int32_t encodeVideo (IPacket *pOutPacket, IVideoPicture *pFrame, int32_t suggestedBufferSize)
Encode the given frame using this StreamCoder.
virtual int32_t encodeAudio (IPacket *pOutPacket, IAudioSamples *pSamples, uint32_t sampleToStartFrom)
Encode the given samples using this StreamCoder.
virtual int64_t getNextPredictedPts ()
For this stream, get the next Pts that we expect to decode.
virtual int32_t getCodecTag ()
Returns the 4-byte FOURCC tag (Least Significant Byte first).
virtual void setCodecTag (int32_t)
Set the 4-byte FOURCC tag for this coder.
virtual int32_t getNumProperties ()
Returns the total number of settable properties on this object.
virtual IProperty * getPropertyMetaData (int32_t propertyNo)
Returns the name of the numbered property.
virtual IProperty * getPropertyMetaData (const char *name)
Returns the name of the numbered property.
virtual int32_t setProperty (const char *name, const char *value)
Sets a property on this Object.
virtual int32_t setProperty (const char *name, double value)
Looks up the property 'name' and sets the value of the property to 'value'.
virtual int32_t setProperty (const char *name, int64_t value)
Looks up the property 'name' and sets the value of the property to 'value'.
virtual int32_t setProperty (const char *name, bool value)
Looks up the property 'name' and sets the value of the property to 'value'.
virtual int32_t setProperty (const char *name, IRational *value)
Looks up the property 'name' and sets the value of the property to 'value'.
virtual char * getPropertyAsString (const char *name)
Gets a property on this Object.
virtual double getPropertyAsDouble (const char *name)
Gets the value of this property, and returns as a double;.
virtual int64_t getPropertyAsLong (const char *name)
Gets the value of this property, and returns as an long;.
virtual IRational * getPropertyAsRational (const char *name)
Gets the value of this property, and returns as an IRational;.
virtual bool getPropertyAsBoolean (const char *name)
Gets the value of this property, and returns as a boolean.
virtual bool isOpen ()
Returns true if this IStreamCoder is currently open.
virtual int32_t getDefaultAudioFrameSize ()
Get the default audio frame size (in samples).
virtual void setDefaultAudioFrameSize (int32_t)
Set the default audio frame size.
void setCodec (int32_t)
int32_t setStream (Stream *, bool assumeOnlyStream)
int32_t streamClosed (Stream *)
virtual int64_t getNumDroppedFrames ()
Get the number of frames this StreamCoder had to drop to encode at the specified getTimeBase().
virtual void setAutomaticallyStampPacketsForStream (bool value)
Should the IStreamCoder automatically adjust time stamps on output packets for the IStream it is ultimately destined for.
virtual bool getAutomaticallyStampPacketsForStream ()
Does this IStreamCoder automatically adjust time stamps on output packets for the IStream it is ultimately destined for.
virtual int32_t acquire ()
Internal Only.
virtual int32_t release ()
Internal Only.
virtual int32_t setExtraData (com::xuggle::ferry::IBuffer *src, int32_t offset, int32_t length, bool allocNew)
Copies data from the given buffer into the extra-data area maintained by encoders.
virtual int32_t getExtraData (com::xuggle::ferry::IBuffer *dest, int32_t offset, int32_t maxBytesToCopy)
Copies the current content of the extra-data buffer maintained by this codec (e.g.
virtual int32_t getExtraDataSize ()
Gets the current number of bytes of data maintained in the coder extra-data area.
Static Public Member Functions
static StreamCoder * make (Direction direction)
This method creates a StreamCoder that is not tied to any container or stream.
static StreamCoder * make (Direction direction, AVCodecContext *context, Stream *stream)
This method creates a StreamCoder that is tied to a specific stream in a container.
static StreamCoder * make (Direction direction, IStreamCoder *copyCoder)
Protected Member Functions
StreamCoder ()
virtual ~StreamCoder ()
Constructor & Destructor Documentation
com::xuggle::xuggler::StreamCoder::StreamCoder () [protected]
Definition at line 45 of file StreamCoder.cpp.
References com::xuggle::xuggler::IStreamCoder::DECODING, com::xuggle::xuggler::IRational::make(), and com::xuggle::xuggler::Global::NO_PTS.
                         :
  mCodec(0)
{
  mCodecContext = 0;
  // default to DECODING.
  mDirection = DECODING;
  mOpened = false;
  mStream = 0;
  mAudioFrameBuffer = 0;
  mBytesInFrameBuffer = 0;
  mFakePtsTimeBase = IRational::make(1, AV_TIME_BASE);
  mFakeNextPts = Global::NO_PTS;
  mFakeCurrPts = Global::NO_PTS;
  mLastPtsEncoded = Global::NO_PTS;
  mSamplesCoded = 0;
  mLastExternallySetTimeStamp = Global::NO_PTS;
  mDefaultAudioFrameSize = 576;
  mNumDroppedFrames = 0;
  mAutomaticallyStampPacketsForStream = true;
  for(uint32_t i = 0; i < sizeof(mPtsBuffer)/sizeof(mPtsBuffer[0]); i++)
  {
    mPtsBuffer[i] = Global::NO_PTS;
  }
}
com::xuggle::xuggler::StreamCoder::~StreamCoder () [protected, virtual]
Definition at line 70 of file StreamCoder.cpp.
{
  reset();
}
Member Function Documentation
virtual Direction com::xuggle::xuggler::StreamCoder::getDirection () [inline, virtual]
Get the direction.
Returns:
The direction this StreamCoder works in.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 44 of file StreamCoder.h.
{ return mDirection; }
IStream * com::xuggle::xuggler::StreamCoder::getStream () [virtual]
The associated Stream we're working on.
Returns:
The stream associated with this object.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 224 of file StreamCoder.cpp.
References VS_REF_ACQUIRE.
Referenced by make().
{
  // Acquire for the caller.
  VS_REF_ACQUIRE(mStream);
  return mStream;
}
ICodec * com::xuggle::xuggler::StreamCoder::getCodec () [virtual]
The Codec this StreamCoder will use.
Returns:
The Codec used by this StreamCoder, or 0 (null) if none.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 232 of file StreamCoder.cpp.
References setCodec().
Referenced by open().
{
  ICodec *retval = 0;
  if (!mCodec && mCodecContext)
  {
    // Try getting it from the context
    setCodec(mCodecContext->codec_id);
  }
  if (mCodec)
    retval = mCodec.get();
  return retval;
}
ICodec::Type com::xuggle::xuggler::StreamCoder::getCodecType () [virtual]
A short hand for getCodec().getType().
Note for Native (C++) users: If you actually write code like the above from Native code, you'd leak a Codec() since you didn't call release() on it. This method is a short hand way to avoid you having to worry about releasing in between.
Returns:
The Type of the Codec we'll use.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 247 of file StreamCoder.cpp.
References com::xuggle::xuggler::ICodec::CODEC_TYPE_UNKNOWN, and VS_LOG_WARN.
Referenced by decodeAudio(), decodeVideo(), encodeAudio(), encodeVideo(), and open().
{
  ICodec::Type retval = ICodec::CODEC_TYPE_UNKNOWN;
  if (mCodecContext)
  {
    retval = (ICodec::Type) mCodecContext->codec_type;
  }
  else
  {
    VS_LOG_WARN("Attempt to get CodecType from uninitialized StreamCoder");
  }
  return retval;
}
ICodec::ID com::xuggle::xuggler::StreamCoder::getCodecID () [virtual]
A short hand for getCodec().getID().
Note for Native (C++) users: If you actually write code like the above from Native code, you'd leak a Codec() since you didn't call release() on it. This method is a short hand way to avoid you having to worry about releasing in between.
Returns:
The ID of the Codec we'll use.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 262 of file StreamCoder.cpp.
References com::xuggle::xuggler::ICodec::CODEC_ID_NONE, and VS_LOG_WARN.
{
  ICodec::ID retval = ICodec::CODEC_ID_NONE;
  if (mCodecContext)
  {
    retval = (ICodec::ID) mCodecContext->codec_id;
  }
  else
  {
    VS_LOG_WARN("Attempt to get CodecID from uninitialized StreamCoder");
  }
  return retval;
}
void com::xuggle::xuggler::StreamCoder::setCodec (ICodec * codec) [virtual]
Set the Codec to the passed in Codec, discarding the old Codec if set.
Once you call setCodec, all settings on the IStreamCoder are reset to default values. So you probably want to call this first.
Parameters:
codec Codec to set.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 277 of file StreamCoder.cpp.
References VS_LOG_INFO.
Referenced by getCodec(), make(), setCodec(), and setCodecID().
{
  // reset our code and acquire the one passed in
  if (mCodec.value() != newCodec)
  {
    mCodec.reset(dynamic_cast<Codec*> (newCodec), true);
    // Check that the new codec can do the right
    // thing
    if (mCodec && mCodecContext && !mOpened)
    {
      mCodecContext->codec_type = (enum AVMediaType) mCodec->getType();
      //      if (mDirection == ENCODING)
      //      {
      //        avcodec_get_context_defaults2(mCodecContext, mCodecContext->codec_type);
      //      }
      mCodecContext->codec_id = (enum CodecID) mCodec->getIDAsInt();
    }
    else
    {
      VS_LOG_INFO("Cannot set Codec because StreamCoder is either not initialized or already open");
      mCodec = 0;
    }
  }
}
void com::xuggle::xuggler::StreamCoder::setCodec (ICodec::ID id) [virtual]
Look up a Codec based on the passed in ID, and then set it.
To see if you actually set the correct ID, call getCodec() and check for 0 (null).
Once you call setCodec, all settings on the IStreamCoder are reset to default values. So you probably want to call this first.
Parameters:
id ID of codec to set.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 303 of file StreamCoder.cpp.
References setCodec().
{
  setCodec((int32_t) id);
}
virtual void com::xuggle::xuggler::StreamCoder::setCodecID (ICodec::ID id) [inline, virtual]
Look up a Codec based on the passed in ID, and then set it.
Forwards to setCodecID(com.xuggle.xuggler.ICodec.ID)
To see if you actually set the correct ID, call getCodec() and check for 0 (null).
Once you call setCodec, all settings on the IStreamCoder are reset to default values. So you probably want to call this first.
Parameters:
id ID of codec to set.
Since:
3.2
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 54 of file StreamCoder.h.
References setCodec().
{ setCodec(id); }
int32_t com::xuggle::xuggler::StreamCoder::getBitRate () [virtual]
The bit rate.
Returns:
The bit-rate the stream is, or will be, encoded in.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 331 of file StreamCoder.cpp.
{
  return (mCodecContext ? mCodecContext->bit_rate : -1);
}
void com::xuggle::xuggler::StreamCoder::setBitRate (int32_t rate) [virtual]
When ENCODING, sets the bit rate to use.
No-op when DECODING.
See also:
getBitRate()
Parameters:
rate The bit rate to use.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 336 of file StreamCoder.cpp.
{
  if (mCodecContext && !mOpened)
    mCodecContext->bit_rate = val;
}
int32_t com::xuggle::xuggler::StreamCoder::getBitRateTolerance () [virtual]
The bit rate tolerance.
Returns:
The bit-rate tolerance
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 342 of file StreamCoder.cpp.
{
  return (mCodecContext ? mCodecContext->bit_rate_tolerance : -1);
}
void com::xuggle::xuggler::StreamCoder::setBitRateTolerance (int32_t tolerance) [virtual]
When ENCODING set the bit rate tolerance.
No-op when DECODING.
Parameters:
tolerance The bit rate tolerance
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 347 of file StreamCoder.cpp.
{
  if (mCodecContext && !mOpened)
    mCodecContext->bit_rate_tolerance = val;
}
int32_t com::xuggle::xuggler::StreamCoder::getHeight () [virtual]
The height, in pixels.
Returns:
The height of the video frames in the attached stream or -1 if an audio stream, or we cannot determine the height.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 353 of file StreamCoder.cpp.
Referenced by decodeVideo(), and encodeVideo().
{
  return (mCodecContext ? mCodecContext->height : -1);
}
void com::xuggle::xuggler::StreamCoder::setHeight (int32_t height) [virtual]
Set the height, in pixels.
See also:
getHeight()
Parameters:
height Sets the height of video frames we'll encode. No-op when DECODING.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 359 of file StreamCoder.cpp.
{
  if (mCodecContext && !mOpened)
    mCodecContext->height = val;
}
int32_t com::xuggle::xuggler::StreamCoder::getWidth () [virtual]
The width, in pixels.
Returns:
The width of the video frames in the attached stream or -1 if an audio stream, or we cannot determine the width.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 366 of file StreamCoder.cpp.
Referenced by decodeVideo(), and encodeVideo().
{
  return (mCodecContext ? mCodecContext->width : -1);
}
void com::xuggle::xuggler::StreamCoder::setWidth (int32_t width) [virtual]
Set the width, in pixels.
See also:
getWidth()
Parameters:
width Sets the width of video frames we'll encode. No-op when DECODING.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 372 of file StreamCoder.cpp.
{
  if (mCodecContext && !mOpened)
    mCodecContext->width = val;
}
IRational * com::xuggle::xuggler::StreamCoder::getTimeBase () [virtual]
Get the time base this stream will ENCODE in, or the time base we detect while DECODING.
Caller must call release() on the returned value.
Returns:
The time base this StreamCoder is using.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 379 of file StreamCoder.cpp.
References com::xuggle::xuggler::Stream::getTimeBase(), and com::xuggle::xuggler::IRational::make().
Referenced by decodeAudio(), decodeVideo(), encodeAudio(), encodeVideo(), and make().
{
  // we make a new value and return it; caller must
  // release.
  IRational *retval = 0;
  // annoyingly, some codec contexts will NOT have
  // a timebase... so we take it from stream then.
  if (mCodecContext && mCodecContext->time_base.den
      && mCodecContext->time_base.num)
  {
    retval = Rational::make(&mCodecContext->time_base);
  }
  else if (mAutomaticallyStampPacketsForStream)
  {
    retval = mStream ? mStream->getTimeBase() : 0;
  }
  return retval;
}
void com::xuggle::xuggler::StreamCoder::setTimeBase (IRational * newTimeBase) [virtual]
Set the time base we'll use to ENCODE with.
A no-op when DECODING.
As a convenience, we forward this call to the Stream::setTimeBase() method.
See also:
getTimeBase()
Parameters:
newTimeBase The new time base to use.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 401 of file StreamCoder.cpp.
References com::xuggle::xuggler::IRational::getDenominator(), com::xuggle::xuggler::IRational::getNumerator(), and VS_LOG_INFO.
{
  if (mCodecContext && src && !mOpened)
  {
    mCodecContext->time_base.num = src->getNumerator();
    mCodecContext->time_base.den = src->getDenominator();
  }
  else
  {
    VS_LOG_INFO("Failed to setTimeBase on StreamCoder");
  }
}
IRational * com::xuggle::xuggler::StreamCoder::getFrameRate () [virtual]
Get the frame-rate the attached stream claims to be using when DECODING, or the frame-rate we'll claim we're using when ENCODING.
Returns:
The frame rate.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 421 of file StreamCoder.cpp.
References com::xuggle::xuggler::Stream::getFrameRate().
{
  return (mStream ? mStream->getFrameRate() : 0);
}
void com::xuggle::xuggler::StreamCoder::setFrameRate (IRational * newFrameRate) [virtual]
Set the frame rate we'll set in the headers of this stream while ENCODING.
Note that you can set whatever frame-rate you'd like, but the TimeBase and the PTS you set on the encoded audio and video frames can override this.
As a convenience, we forward this call to the Stream::setFrameRate() method.
See also:
getFrameRate()
Parameters:
newFrameRate The new frame rate to use.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 427 of file StreamCoder.cpp.
References com::xuggle::xuggler::Stream::setFrameRate().
{
  if (mStream && !mOpened)
    mStream->setFrameRate(src);
}
int32_t com::xuggle::xuggler::StreamCoder::getNumPicturesInGroupOfPictures () [virtual]
The the number of pictures in this Group of Pictures (GOP).
See the MPEG specs for what a GOP is officially, but this is the minimum number of frames between key-frames (or Intra-Frames in MPEG speak).
Returns:
the GOPS for this stream.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 434 of file StreamCoder.cpp.
{
  return (mCodecContext ? mCodecContext->gop_size : -1);
}
void com::xuggle::xuggler::StreamCoder::setNumPicturesInGroupOfPictures (int32_t gops) [virtual]
Set the GOPS on this stream.
Ignored if DECODING.
See also:
getNumPicturesInGroupOfPictures()
Parameters:
gops The new GOPS for the stream we're encoding.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 440 of file StreamCoder.cpp.
{
  if (mCodecContext && !mOpened)
    mCodecContext->gop_size = val;
}
IPixelFormat::Type com::xuggle::xuggler::StreamCoder::getPixelType () [virtual]
For Video streams, get the Pixel Format in use by the stream.
Returns:
the Pixel format, or IPixelFormat::NONE if audio.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 447 of file StreamCoder.cpp.
References com::xuggle::xuggler::IPixelFormat::NONE, and VS_LOG_ERROR.
Referenced by decodeVideo(), and encodeVideo().
{
  IPixelFormat::Type retval = IPixelFormat::NONE;
  int32_t type = 0;
  if (mCodecContext)
  {
    retval = (IPixelFormat::Type) mCodecContext->pix_fmt;
    // little check here to see if we have an undefined int32_t.
    type = (int32_t) retval;
    if (type != mCodecContext->pix_fmt) {
      VS_LOG_ERROR("Undefined pixel format type: %d", mCodecContext->pix_fmt);
      retval = IPixelFormat::NONE;
    }
  }
  return retval;
}
void com::xuggle::xuggler::StreamCoder::setPixelType (IPixelFormat::Type pixelFmt) [virtual]
Set the pixel format to ENCODE with.
Ignored if audio or DECODING.
Parameters:
pixelFmt Pixel format to use.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 466 of file StreamCoder.cpp.
{
  if (mCodecContext && !mOpened)
  {
    mCodecContext->pix_fmt = (enum PixelFormat) type;
  }
}
int32_t com::xuggle::xuggler::StreamCoder::getSampleRate () [virtual]
Get the sample rate we use for this stream.
Returns:
The sample rate (in Hz) we use for this stream, or -1 if unknown or video.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 475 of file StreamCoder.cpp.
Referenced by decodeAudio(), and encodeAudio().
{
  return (mCodecContext ? mCodecContext->sample_rate : -1);
}
void com::xuggle::xuggler::StreamCoder::setSampleRate (int32_t sampleRate) [virtual]
Set the sample rate to use when ENCODING.
Ignored if DECODING or a non-audio stream.
Parameters:
sampleRate New sample rate (in Hz) to use.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 481 of file StreamCoder.cpp.
{
  if (mCodecContext && !mOpened && val > 0)
    mCodecContext->sample_rate = val;
}
int32_t com::xuggle::xuggler::StreamCoder::getChannels () [virtual]
Get the number of channels in this audio stream.
Returns:
The sample rate (in Hz) we use for this stream, or 0 if unknown.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 502 of file StreamCoder.cpp.
Referenced by decodeAudio(), encodeAudio(), and open().
{
  return (mCodecContext ? mCodecContext->channels : -1);
}
void com::xuggle::xuggler::StreamCoder::setChannels (int32_t channels) [virtual]
Set the number of channels to use when ENCODING.
Ignored if a non audio stream, or if DECODING.
Parameters:
channels The number of channels we'll encode with.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 508 of file StreamCoder.cpp.
{
  if (mCodecContext && !mOpened && val > 0)
    mCodecContext->channels = val;
}
IAudioSamples::Format com::xuggle::xuggler::StreamCoder::getSampleFormat () [virtual]
Get the audio sample format.
Returns:
The sample format of samples for encoding/decoding.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 488 of file StreamCoder.cpp.
{
  return (IAudioSamples::Format) (mCodecContext ? mCodecContext->sample_fmt
      : -1);
}
void com::xuggle::xuggler::StreamCoder::setSampleFormat (IAudioSamples::Format aFormat) [virtual]
Set the sample format when ENCODING.
Ignored if DECODING or if the coder is already open.
Parameters:
aFormat The sample format.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 495 of file StreamCoder.cpp.
{
  if (mCodecContext && !mOpened && val > 0)
    mCodecContext->sample_fmt = (SampleFormat) val;
}
int32_t com::xuggle::xuggler::StreamCoder::getGlobalQuality () [virtual]
Get the Global Quality setting this codec uses for video if a VideoPicture doesn't have a quality set.
Returns:
The global quality.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 515 of file StreamCoder.cpp.
{
  return (mCodecContext ? mCodecContext->global_quality : FF_LAMBDA_MAX);
}
void com::xuggle::xuggler::StreamCoder::setGlobalQuality (int32_t newQuality) [virtual]
Set the Global Quality to a new value.
Parameters:
newQuality The new global quality.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 521 of file StreamCoder.cpp.
{
  if (newQuality < 0 || newQuality > FF_LAMBDA_MAX)
    newQuality = FF_LAMBDA_MAX;
  if (mCodecContext)
    mCodecContext->global_quality = newQuality;
}
int32_t com::xuggle::xuggler::StreamCoder::getFlags () [virtual]
Get the flags associated with this codec.
Returns:
The (compacted) value of all flags set.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 530 of file StreamCoder.cpp.
{
  return (mCodecContext ? mCodecContext->flags : 0);
}
void com::xuggle::xuggler::StreamCoder::setFlags (int32_t newFlags) [virtual]
Set the FFMPEG flags to use with this codec.
All values must be ORed (|) together.
See also:
Flags
Parameters:
newFlags The new set flags for this codec.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 536 of file StreamCoder.cpp.
{
  if (mCodecContext)
    mCodecContext->flags = newFlags;
}
bool com::xuggle::xuggler::StreamCoder::getFlag (Flags flag) [virtual]
Get the setting for the specified flag.
Parameters:
flag The flag you want to find the setting for
Returns:
0 for false; non-zero for true
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 543 of file StreamCoder.cpp.
{
  bool result = false;
  if (mCodecContext)
    result = mCodecContext->flags & flag;
  return result;
}
void com::xuggle::xuggler::StreamCoder::setFlag (Flags flag, bool value) [virtual]
Set the flag.
Parameters:
flag The flag to set
value The value to set it to (true or false)
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 552 of file StreamCoder.cpp.
Referenced by open().
{
  if (mCodecContext)
  {
    if (value)
    {
      mCodecContext->flags |= flag;
    }
    else
    {
      mCodecContext->flags &= (~flag);
    }
  }
}
int32_t com::xuggle::xuggler::StreamCoder::getAudioFrameSize () [virtual]
For this stream, get the number of audio samples that are represented in a packet of information.
Returns:
Number of samples per 'frame' of encoded audio
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1616 of file StreamCoder.cpp.
References com::xuggle::xuggler::ICodec::CODEC_TYPE_AUDIO, and getDefaultAudioFrameSize().
Referenced by encodeAudio(), and open().
{
  int32_t retval = 0;
  if (mCodec && mCodec->getType() == ICodec::CODEC_TYPE_AUDIO)
  {
    if (mCodecContext->frame_size <= 1)
    {
      // Rats; some PCM encoders give a frame size of 1, which is too
      //small.  We pick a more sensible value.
      retval = getDefaultAudioFrameSize();
    }
    else
    {
      retval = mCodecContext->frame_size;
    }
  }
  return retval;
}
int32_t com::xuggle::xuggler::StreamCoder::open () [virtual]
Open the Codec associated with this StreamCoder.
You can get the codec through getCodec(...) and set it with setCodec(...). You cannot call any set* methods after you've called open() on this StreamCoder until you close() it.
You must call close() when you're done, but if you don't, the container will clean up after you (but yell at you) when it is closed.
Returns:
>= 0 on success; < 0 on error.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 569 of file StreamCoder.cpp.
References com::xuggle::xuggler::ICodec::CODEC_TYPE_AUDIO, com::xuggle::xuggler::IStreamCoder::ENCODING, com::xuggle::xuggler::IAudioSamples::findSampleBitDepth(), com::xuggle::xuggler::IStreamCoder::FLAG_GLOBAL_HEADER, com::xuggle::xuggler::IContainerFormat::FLAG_GLOBALHEADER, getAudioFrameSize(), getChannels(), getCodec(), getCodecType(), com::xuggle::xuggler::Stream::getContainer(), com::xuggle::ferry::IBuffer::make(), com::xuggle::xuggler::Global::NO_PTS, setFlag(), and VS_LOG_WARN.
{
  int32_t retval = -1;
  try
  {
    if (!mCodecContext)
      throw std::runtime_error("no codec context");
    if (!mCodec)
    {
      RefPointer<ICodec> codec = this->getCodec();
      // This should set mCodec and then release
      // the local reference.
    }
    if (!mCodec)
      throw std::runtime_error("no codec set for coder");
    // don't allow us to open a coder without a time base
    if (mDirection == ENCODING && mCodecContext->time_base.num == 0)
    {
      if (this->getCodecType() == ICodec::CODEC_TYPE_AUDIO)
      {
        if (mCodecContext->sample_rate > 0)
        {
          mCodecContext->time_base.num = 1;
          mCodecContext->time_base.den = mCodecContext->sample_rate;
        }
        else
        {
          throw std::runtime_error("no sample rate set on coder");
        }
      }
      else
        throw std::runtime_error("no timebase set on coder");
    }
    // Fix for issue #14: http://code.google.com/p/xuggle/issues/detail?id=14
    if (mStream)
    {
      RefPointer<IContainer> container = mStream->getContainer();
      if (container)
      {
        RefPointer<IContainerFormat> format = container->getContainerFormat();
        if (format && mDirection == ENCODING && format->getOutputFlag(
            IContainerFormat::FLAG_GLOBALHEADER))
        {
          this->setFlag(FLAG_GLOBAL_HEADER, true);
        }
      }
    }
    retval = avcodec_open(mCodecContext, mCodec->getAVCodec());
    if (retval < 0)
      throw std::runtime_error("could not open codec");
    mOpened = true;
    mNumDroppedFrames = 0;
    mSamplesCoded = mSamplesForEncoding = mLastExternallySetTimeStamp = 0;
    mFakeCurrPts = mFakeNextPts = mLastPtsEncoded = Global::NO_PTS;
    for(uint32_t i = 0; i < sizeof(mPtsBuffer)/sizeof(mPtsBuffer[0]); i++)
    {
      mPtsBuffer[i] = Global::NO_PTS;
    }
    // Do any post open initialization here.
    if (this->getCodecType() == ICodec::CODEC_TYPE_AUDIO)
    {
      int32_t frame_bytes = getAudioFrameSize() * getChannels()
          * IAudioSamples::findSampleBitDepth(
              (IAudioSamples::Format) mCodecContext->sample_fmt) / 8;
      if (frame_bytes <= 0)
        frame_bytes = AVCODEC_MAX_AUDIO_FRAME_SIZE;
      if (!mAudioFrameBuffer || mAudioFrameBuffer->getBufferSize()
          < frame_bytes)
        // Re-create it.
        mAudioFrameBuffer = IBuffer::make(this, frame_bytes);
      mBytesInFrameBuffer = 0;
    }
  }
  catch (std::bad_alloc & e)
  {
    throw e;
  }
  catch (std::exception & e)
  {
    VS_LOG_WARN("Error: %s", e.what());
    retval = -1;
  }
  return retval;
}
int32_t com::xuggle::xuggler::StreamCoder::close () [virtual]
Close a Codec that was opened on this StreamCoder.
Returns:
>= 0 on success; < 0 on error.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 664 of file StreamCoder.cpp.
{
  int32_t retval = -1;
  if (mCodecContext && mOpened)
  {
    retval = avcodec_close(mCodecContext);
    mOpened = false;
  }
  mBytesInFrameBuffer = 0;
  return retval;
}
int32_t com::xuggle::xuggler::StreamCoder::decodeAudio (IAudioSamples * pOutSamples, IPacket * packet, int32_t byteOffset) [virtual]
Decode this packet into pOutSamples.
It will try to fill up the audio samples object, starting from the byteOffset inside this packet.
The caller is responsible for allocating the IAudioSamples object. This function will overwrite any data in the samples object.
Note that the IAudioSamples object passed in must have a IAudioSamples#getMaxBufferSize() of at least 192kbytes. Sorry, but this requirement is imposed on us via FFmpeg. If the buffer is not large enough, this method will reallocate the underlying buffers to make them at least 192kbytes.
Parameters:
pOutSamples The AudioSamples we decode to
packet The packet we're attempting to decode from.
byteOffset Where in the packet payload to start decoding
Returns:
number of bytes actually processed from the packet, or negative for error
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 677 of file StreamCoder.cpp.
References com::xuggle::xuggler::ICodec::CODEC_TYPE_AUDIO, com::xuggle::xuggler::IStreamCoder::DECODING, com::xuggle::xuggler::AudioSamples::ensureCapacity(), com::xuggle::xuggler::IAudioSamples::findSampleBitDepth(), com::xuggle::xuggler::Packet::getAVPacket(), getChannels(), getCodecType(), com::xuggle::xuggler::Packet::getData(), com::xuggle::xuggler::Packet::getDts(), com::xuggle::xuggler::AudioSamples::getMaxBufferSize(), com::xuggle::xuggler::Packet::getPts(), com::xuggle::xuggler::AudioSamples::getRawSamples(), getSampleRate(), com::xuggle::xuggler::Packet::getSize(), getTimeBase(), com::xuggle::xuggler::Stream::getTimeBase(), com::xuggle::xuggler::Global::NO_PTS, com::xuggle::xuggler::IAudioSamples::samplesToDefaultPts(), com::xuggle::xuggler::AudioSamples::setComplete(), com::xuggle::ferry::RefPointer< T >::value(), VS_ASSERT, VS_LOG_TRACE, and VS_LOG_WARN.
{
  int32_t retval = -1;
  AudioSamples *samples = dynamic_cast<AudioSamples*> (pOutSamples);
  Packet* packet = dynamic_cast<Packet*> (pPacket);
  if (samples)
    // reset the samples
    samples->setComplete(false, 0, getSampleRate(), getChannels(),
        (IAudioSamples::Format) mCodecContext->sample_fmt, Global::NO_PTS);
  if (!samples) {
    VS_LOG_WARN("Attempting to decode when not ready; no samples");
    return retval;
  }
  if (!packet) {
    VS_LOG_WARN("Attempting to decode when not ready; no packet");
    return retval;
  }
  if (!mOpened) {
    VS_LOG_WARN("Attempting to decode when not ready; codec not opened");
    return retval;
  }
  if (!mCodecContext) {
    VS_LOG_WARN("Attempting to decode when not ready; internal context not allocated");
    return retval;
  }
  if (mDirection != DECODING) {
    VS_LOG_WARN("Attempting to decode when not ready; StreamCoder is set to encode, not decode");
    return retval;
  }
  if (!mCodec || !mCodec->canDecode()) {
    VS_LOG_WARN("Attempting to decode when not ready; codec set cannot decode");
    return retval;
  }
  if (getCodecType() != ICodec::CODEC_TYPE_AUDIO) {
    VS_LOG_WARN("Attempting to decode when not ready; codec set is not an audio codec");
    return retval;
  }
  int outBufSize = 0;
  int32_t inBufSize = 0;
  // When decoding with FFMPEG, ffmpeg needs the sample buffer
  // to be at least this long.
  samples->ensureCapacity(AVCODEC_MAX_AUDIO_FRAME_SIZE);
  outBufSize = samples->getMaxBufferSize();
  inBufSize = packet->getSize() - startingByte;
  if (inBufSize > 0 && outBufSize > 0)
  {
    RefPointer<IBuffer> buffer = packet->getData();
    uint8_t * inBuf = 0;
    int16_t * outBuf = 0;
    VS_ASSERT(buffer, "no buffer in packet!");
    if (buffer)
      inBuf = (uint8_t*) buffer->getBytes(startingByte, inBufSize);
    outBuf = samples->getRawSamples(0);
    VS_ASSERT(inBuf, "no in buffer");
    VS_ASSERT(outBuf, "no out buffer");
    if (outBuf && inBuf)
    {
      VS_LOG_TRACE("Attempting decodeAudio(%p, %p, %d, %p, %d);",
          mCodecContext,
          outBuf,
          outBufSize,
          inBuf,
          inBufSize);
      AVPacket pkt;
      av_init_packet(&pkt);
      if (packet && packet->getAVPacket())
        pkt = *packet->getAVPacket();
      // copy in our buffer
      pkt.data = inBuf;
      pkt.size = inBufSize;
      mCodecContext->reordered_opaque = packet->getPts();
      retval
      = avcodec_decode_audio3(mCodecContext, outBuf, &outBufSize, &pkt);
      VS_LOG_TRACE("Finished %d decodeAudio(%p, %p, %d, %p, %d);",
          retval,
          mCodecContext,
          outBuf,
          outBufSize,
          inBuf,
          inBufSize);
    }
    if (retval >= 0)
    {
      // outBufSize is an In-Out parameter
      if (outBufSize < 0)
        // this can happen for some MPEG decoders
        outBufSize = 0;
      IAudioSamples::Format format =
          (IAudioSamples::Format) mCodecContext->sample_fmt;
      int32_t bytesPerSample = (IAudioSamples::findSampleBitDepth(format) / 8
          * getChannels());
      int32_t numSamples = outBufSize / bytesPerSample;
      // The audio decoder doesn't set a PTS, so we need to manufacture one.
      RefPointer<IRational> timeBase =
          this->mStream ? this->mStream->getTimeBase() : 0;
      if (!timeBase)
        timeBase = this->getTimeBase();
      int64_t packetTs = packet->getPts();
      if (packetTs == Global::NO_PTS)
        packetTs = packet->getDts();
      if (packetTs == Global::NO_PTS && mFakeNextPts == Global::NO_PTS)
      {
        // the container doesn't have time stamps; assume we start
        // at zero
        VS_LOG_TRACE("Setting fake pts to 0");
        mFakeNextPts = 0;
      }
      if (packetTs != Global::NO_PTS)
      {
        // The packet had a valid stream, and a valid time base
        if (timeBase->getNumerator() != 0 && timeBase->getDenominator() != 0)
        {
          int64_t tsDelta = Global::NO_PTS;
          if (mFakeNextPts != Global::NO_PTS)
          {
            int64_t fakeTsInStreamTimeBase = Global::NO_PTS;
            // rescale our fake into the time base of stream
            fakeTsInStreamTimeBase = timeBase->rescale(mFakeNextPts,
                mFakePtsTimeBase.value());
            tsDelta = fakeTsInStreamTimeBase - packetTs;
          }
          // now, compare it to our internal value;  if our internally calculated value
          // is within 1 tick of the packet's time stamp (in the packet's time base),
          // then we're probably right;
          // otherwise, we should reset the stream's fake time stamp based on this
          // packet
          if (mFakeNextPts != Global::NO_PTS && (tsDelta >= -1 && tsDelta
              <= 1))
          {
            // we're the right value; keep our fake next pts
            VS_LOG_TRACE("Keeping mFakeNextPts: %lld", mFakeNextPts);
          }
          else
          {
            // rescale to our internal timebase
            int64_t packetTsInMicroseconds = mFakePtsTimeBase->rescale(
                packetTs, timeBase.value());
            VS_LOG_TRACE("%p Gap in audio (%lld); Resetting calculated ts from %lld to %lld",
                this,
                tsDelta,
                mFakeNextPts,
                packetTsInMicroseconds);
            mLastExternallySetTimeStamp = packetTsInMicroseconds;
            mSamplesCoded = 0;
            mFakeNextPts = mLastExternallySetTimeStamp;
          }
        }
      }
      // Use the last value of the next pts
      mFakeCurrPts = mFakeNextPts;
      // adjust our next Pts pointer
      if (numSamples > 0)
      {
        mSamplesCoded += numSamples;
        mFakeNextPts = mLastExternallySetTimeStamp
            + IAudioSamples::samplesToDefaultPts(mSamplesCoded,
                getSampleRate());
      }
      // copy the packet PTS
      samples->setComplete(numSamples > 0, numSamples, getSampleRate(),
          getChannels(), format, mFakeCurrPts);
    }
  }
  return retval;
}
int32_t com::xuggle::xuggler::StreamCoder::decodeVideo (IVideoPicture * pOutFrame, IPacket * packet, int32_t byteOffset) [virtual]
Decode this packet into pOutFrame.
The caller is responsible for allocating the IVideoPicture object. This function will potentially overwrite any data in the frame object, but you should pass the same IVideoPicture into this function repeatedly until IVideoPicture::isComplete() is true.
Parameters:
pOutFrame The AudioSamples we decode.
packet The packet we're attempting to decode from.
byteOffset Where in the packet payload to start decoding
Returns:
number of bytes actually processed from the packet, or negative for error
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 861 of file StreamCoder.cpp.
References com::xuggle::xuggler::ICodec::CODEC_TYPE_VIDEO, com::xuggle::xuggler::VideoPicture::copyAVFrame(), com::xuggle::xuggler::IStreamCoder::DECODING, com::xuggle::xuggler::Packet::getAVPacket(), getCodecType(), com::xuggle::xuggler::Packet::getData(), com::xuggle::xuggler::Packet::getDts(), getHeight(), getPixelType(), com::xuggle::xuggler::Packet::getPts(), com::xuggle::xuggler::Packet::getSize(), getTimeBase(), com::xuggle::xuggler::Stream::getTimeBase(), getWidth(), com::xuggle::xuggler::Global::NO_PTS, com::xuggle::xuggler::IPixelFormat::NONE, com::xuggle::xuggler::VideoPicture::setComplete(), com::xuggle::ferry::RefPointer< T >::value(), VS_ASSERT, VS_LOG_TRACE, and VS_LOG_WARN.
{
  int32_t retval = -1;
  VideoPicture* frame = dynamic_cast<VideoPicture*> (pOutFrame);
  Packet* packet = dynamic_cast<Packet*> (pPacket);
  if (frame)
    // reset the frame
    frame->setComplete(false, IPixelFormat::NONE, -1, -1, mFakeCurrPts);
  if (!frame) {
    VS_LOG_WARN("Attempting to decode when not ready; no frame");
    return retval;
  }
  if (!packet) {
    VS_LOG_WARN("Attempting to decode when not ready; no packet");
    return retval;
  }
  if (!mOpened) {
    VS_LOG_WARN("Attempting to decode when not ready; codec not opened");
    return retval;
  }
  if (!mCodecContext) {
    VS_LOG_WARN("Attempting to decode when not ready; internal context not allocated");
    return retval;
  }
  if (mDirection != DECODING) {
    VS_LOG_WARN("Attempting to decode when not ready; StreamCoder is set to encode, not decode");
    return retval;
  }
  if (!mCodec || !mCodec->canDecode()) {
    VS_LOG_WARN("Attempting to decode when not ready; codec set cannot decode");
    return retval;
  }
  if (getCodecType() != ICodec::CODEC_TYPE_VIDEO) {
    VS_LOG_WARN("Attempting to decode when not ready; codec set is not a video codec");
    return retval;
  }
  AVFrame *avFrame = avcodec_alloc_frame();
  if (avFrame)
  {
    RefPointer<IBuffer> buffer = packet->getData();
    int frameFinished = 0;
    int32_t inBufSize = 0;
    uint8_t * inBuf = 0;
    inBufSize = packet->getSize() - byteOffset;
    VS_ASSERT(buffer, "no buffer in packet?");
    if (buffer)
      inBuf = (uint8_t*) buffer->getBytes(byteOffset, inBufSize);
    VS_ASSERT(inBuf, "incorrect size or no data in packet");
    if (inBufSize > 0 && inBuf)
    {
      VS_LOG_TRACE("Attempting decodeVideo(%p, %p, %d, %p, %d);",
          mCodecContext,
          avFrame,
          frameFinished,
          inBuf,
          inBufSize);
      AVPacket pkt;
      av_init_packet(&pkt);
      if (packet && packet->getAVPacket())
        pkt = *packet->getAVPacket();
      // copy in our buffer
      pkt.data = inBuf;
      pkt.size = inBufSize;
      mCodecContext->reordered_opaque = packet->getPts();
      retval = avcodec_decode_video2(mCodecContext, avFrame, &frameFinished,
          &pkt);
      VS_LOG_TRACE("Finished %d decodeVideo(%p, %p, %d, %p, %d);",
          retval,
          mCodecContext,
          avFrame,
          frameFinished,
          inBuf,
          inBufSize);
      if (frameFinished)
      {
        // copy FFMPEG's buffer into our buffer; don't try to get efficient
        // and reuse the buffer FFMPEG is using; in order to allow our
        // buffers to be thread safe, we must do a copy here.
        frame->copyAVFrame(avFrame, getPixelType(), getWidth(), getHeight());
        RefPointer<IRational> timeBase = 0;
        timeBase = this->mStream ? this->mStream->getTimeBase() : 0;
        if (!timeBase)
          timeBase = this->getTimeBase();
        int64_t packetTs = avFrame->reordered_opaque;
        // if none, assume this packet's decode time, since
        // it's presentation time should have been in reordered_opaque
        if (packetTs == Global::NO_PTS)
          packetTs = packet->getDts();
        if (packetTs != Global::NO_PTS)
        {
          if (timeBase->getNumerator() != 0)
          {
            // The decoder set a PTS, so we let it override us
            int64_t nextPts = mFakePtsTimeBase->rescale(packetTs,
                timeBase.value());
            // some youtube videos incorrectly return a packet
            // with the wrong re-ordered opaque setting.  this
            // detects that and uses the PTS from the packet instead.
            // See: http://code.google.com/p/xuggle/issues/detail?id=165
            // in this way we enforce that timestamps are always
            // increasing
            if (nextPts < mFakeNextPts && packet->getPts() != Global::NO_PTS)
              nextPts = mFakePtsTimeBase->rescale(packet->getPts(),
                  timeBase.value());
            mFakeNextPts = nextPts;
          }
        }
        // Use the last value of the next pts
        mFakeCurrPts = mFakeNextPts;
        double frameDelay = av_rescale(timeBase->getNumerator(),
            AV_TIME_BASE, timeBase->getDenominator());
        frameDelay += avFrame->repeat_pict * (frameDelay * 0.5);
        // adjust our next Pts pointer
        mFakeNextPts += (int64_t) frameDelay;
        //          VS_LOG_DEBUG("frame complete: %s; pts: %lld; packet ts: %lld; opaque ts: %lld; tb: %ld/%ld",
        //              (frameFinished ? "yes" : "no"),
        //              mFakeCurrPts,
        //              (packet ? packet->getDts() : 0),
        //              packetTs,
        //              timeBase->getNumerator(),
        //              timeBase->getDenominator()
        //          );
      }
      frame->setComplete(frameFinished, this->getPixelType(),
          this->getWidth(), this->getHeight(), mFakeCurrPts);
    }
    av_free(avFrame);
  }
  return retval;
}
int32_t com::xuggle::xuggler::StreamCoder::encodeVideo (IPacket * pOutPacket, IVideoPicture * pFrame, int32_t suggestedBufferSize) [virtual]
Encode the given frame using this StreamCoder.
The VideoPicture will allocate a buffer to use internally for this, and will free it when the frame destroys itself.
Also, when done in order to flush the encoder, caller should call this method passing in 0 (null) for pFrame to tell the encoder to flush any data it was keeping a hold of.
Parameters:
pOutPacket [out] The packet to encode into. It will point to a buffer allocated in the frame. Caller should check IPacket::isComplete() after call to find out if we had enough information to encode a full packet.
pFrame [in/out] The frame to encode
suggestedBufferSize The suggested buffer size to allocate or -1 for choose ourselves. If -1 we'll allocate a buffer exactly the same size (+1) as the decoded frame with the guess that you're encoding a frame because you want to use LESS space than that.
@ return >= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1007 of file StreamCoder.cpp.
References com::xuggle::xuggler::Packet::allocateNewPayload(), com::xuggle::xuggler::ICodec::CODEC_TYPE_VIDEO, com::xuggle::xuggler::IStreamCoder::ENCODING, com::xuggle::xuggler::VideoPicture::fillAVFrame(), getCodecType(), com::xuggle::xuggler::Packet::getData(), getHeight(), com::xuggle::xuggler::VideoPicture::getHeight(), getPixelType(), com::xuggle::xuggler::VideoPicture::getPixelType(), com::xuggle::xuggler::VideoPicture::getPts(), com::xuggle::xuggler::VideoPicture::getSize(), getTimeBase(), getWidth(), com::xuggle::xuggler::VideoPicture::getWidth(), com::xuggle::xuggler::Global::NO_PTS, com::xuggle::xuggler::Packet::reset(), com::xuggle::xuggler::IRational::ROUND_DOWN, com::xuggle::ferry::RefPointer< T >::value(), VS_ASSERT, VS_LOG_TRACE, and VS_LOG_WARN.
{
  int32_t retval = -1;
  VideoPicture *frame = dynamic_cast<VideoPicture*> (pFrame);
  Packet *packet = dynamic_cast<Packet*> (pOutPacket);
  RefPointer<IBuffer> encodingBuffer;
  try
  {
    if (packet)
      packet->reset();
    if (getCodecType() != ICodec::CODEC_TYPE_VIDEO)
      throw std::runtime_error(
          "Attempting to encode video with non video coder");
    if (frame && frame->getPixelType() != this->getPixelType())
      throw std::runtime_error(
          "picture is not of the same PixelType as this Coder expected");
    if (frame && frame->getWidth() != this->getWidth())
      throw std::runtime_error("picture is not of the same width as this Coder");
    if (frame && frame->getHeight() != this->getHeight())
      throw std::runtime_error(
          "picture is not of the same height as this Coder");
    if (mDirection != ENCODING)
      throw std::runtime_error("Decoding StreamCoder not valid for encoding");
    if (!mCodec)
      throw std::runtime_error("Codec not set");
    if (!mCodec->canEncode())
      throw std::runtime_error("Codec cannot be used to encode");
    if (mCodecContext && mOpened && mDirection == ENCODING && packet)
    {
      uint8_t* buf = 0;
      uint32_t bufLen = 0;
      // First, get the right buffer size.
      if (suggestedBufferSize <= 0)
      {
        if (frame)
        {
          suggestedBufferSize = frame->getSize();
        }
        else
        {
          suggestedBufferSize = avpicture_get_size(
              (PixelFormat) getPixelType(), getWidth(), getHeight());
        }
      }
      VS_ASSERT(suggestedBufferSize> 0, "no buffer size in input frame");
      suggestedBufferSize = FFMAX(suggestedBufferSize, FF_MIN_BUFFER_SIZE);
      retval = packet->allocateNewPayload(suggestedBufferSize);
      if (retval >= 0)
      {
        encodingBuffer = packet->getData();
      }
      if (encodingBuffer)
      {
        buf = (uint8_t*) encodingBuffer->getBytes(0, suggestedBufferSize);
        bufLen = encodingBuffer->getBufferSize();
      }
      if (buf && bufLen)
      {
        // Change the PTS in our frame to the timebase of the encoded stream
        RefPointer<IRational> thisTimeBase = getTimeBase();
        /*
         * We make a copy of the AVFrame object and explicitly copy
         * over the values that we know encoding cares about.
         *
         * This is because often some programs decode into an VideoPicture
         * and just want to pass that to encodeVideo.  If we just
         * leave the values that Ffmpeg had in the AVFrame during
         * decoding, strange errors can result.
         *
         * Plus, this forces us to KNOW what we're passing into the encoder.
         */
        AVFrame* avFrame = 0;
        bool dropFrame = false;
        if (frame)
        {
          avFrame = avcodec_alloc_frame();
          if (!avFrame)
            throw std::bad_alloc();
          frame->fillAVFrame(avFrame);
          // convert into the time base that this coder wants
          // to output in
          int64_t codecTimeBasePts = thisTimeBase->rescale(frame->getPts(),
              mFakePtsTimeBase.value(), IRational::ROUND_DOWN);
          if (mLastPtsEncoded != Global::NO_PTS)
          {
            // adjust for rounding;
            // fixes http://code.google.com/p/xuggle/issues/detail?id=180
            if (codecTimeBasePts < mLastPtsEncoded)
            {
              VS_LOG_TRACE(
                  "Dropping frame with timestamp %lld (if coder supports higher time-base use that instead)",
                  frame->getPts());
              dropFrame = true;
            }
            else if (codecTimeBasePts == mLastPtsEncoded)
            {
              // else we're close enough; increment by 1
              ++codecTimeBasePts;
            }
          }
          VS_LOG_TRACE("Rescaling ts: %lld to %lld (last: %lld) (from base %d/%d to %d/%d)",
              frame->getPts(),
              codecTimeBasePts,
              mLastPtsEncoded,
              mFakePtsTimeBase->getNumerator(),
              mFakePtsTimeBase->getDenominator(),
              thisTimeBase->getNumerator(),
              thisTimeBase->getDenominator());
          avFrame->pts = codecTimeBasePts;
          if (!dropFrame)
            mLastPtsEncoded = avFrame->pts;
        }
        if (!dropFrame)
        {
          VS_LOG_TRACE("Attempting encodeVideo(%p, %p, %d, %p)",
              mCodecContext,
              buf,
              bufLen,
              avFrame);
          retval = avcodec_encode_video(mCodecContext, buf, bufLen, avFrame);
          VS_LOG_TRACE("Finished %d encodeVideo(%p, %p, %d, %p)",
              retval,
              mCodecContext,
              buf,
              bufLen,
              avFrame);
        }
        else
        {
          ++mNumDroppedFrames;
          retval = 0;
        }
        if (retval >= 0)
        {
          int64_t dts = (avFrame ? mLastPtsEncoded : mLastPtsEncoded + 1);
          int64_t duration = 1;
          if (retval > 0) {
            int32_t num = thisTimeBase->getNumerator();
            int32_t den = thisTimeBase->getDenominator();
            if (num*1000LL > den)
            {
              if (mCodecContext->coded_frame
                  && mCodecContext->coded_frame->repeat_pict)
              {
                num = num * (1+mCodecContext->coded_frame->repeat_pict);
              }
            }
            duration = av_rescale(1,
                num * (int64_t)den * mCodecContext->ticks_per_frame,
                den * (int64_t) thisTimeBase->getNumerator());
            // This will be zero if the Codec does not use b-frames;
            // although we provide space for delaying up to the
            // max H264 delay, in reality we only need delay by 1 tick.
            int32_t delay = FFMAX(mCodecContext->has_b_frames,
                !!mCodecContext->max_b_frames);
            if (mCodecContext->coded_frame
                && mCodecContext->coded_frame->pts != Global::NO_PTS)
            {
              int64_t pts = mCodecContext->coded_frame->pts;
              mPtsBuffer[0] = pts;
              int32_t i;
              // If first time through set others to some 'sensible' defaults.
              // If the first PTS is zero, this leads to starting negative
              // dts values, but FFmpeg allows that so we do too.
              for(i = 1; i < delay + 1 && mPtsBuffer[i] == Global::NO_PTS; i++)
                mPtsBuffer[i] = pts + (i-delay-1)*duration;
              // Order the PTS values in increasing order and the lowest
              // one will magically be the DTS we should use for this packet.
              for(i = 0; i < delay && mPtsBuffer[i] > mPtsBuffer[i+1]; i++)
                FFSWAP(int64_t, mPtsBuffer[i], mPtsBuffer[i+1]);
              dts = mPtsBuffer[0];
//              VS_LOG_ERROR("type: %d; output: dts: %lld; pts: %lld",
//                  mCodecContext->coded_frame->pict_type,
//                  dts,
//                  pts);
            }
          }
          setPacketParameters(
              packet,
              retval,
              // if the last packet, increment the pts encoded
              // by one
              dts,
              thisTimeBase.value(),
              (mCodecContext->coded_frame ? mCodecContext->coded_frame->key_frame
                  : 0), duration);
        }
        if (avFrame)
          av_free(avFrame);
      }
    }
    else
    {
      VS_LOG_WARN("Attempting to encode when not ready");
    }
  }
  catch (std::bad_alloc & e)
  {
    retval = -1;
    throw e;
  }
  catch (std::exception & e)
  {
    VS_LOG_WARN("Got error: %s", e.what());
    retval = -1;
  }
  return retval;
}
int32_t com::xuggle::xuggler::StreamCoder::encodeAudio (IPacket * pOutPacket, IAudioSamples * pSamples, uint32_t sampleToStartFrom) [virtual]
Encode the given samples using this StreamCoder.
The VideoPicture will allocate a buffer to use internally for this, and will free it when the frame destroys itself.
Callers should call this repeatedly on a set of samples until we consume all the samples.
Also, when done in order to flush the encoder, caller should call this method passing in 0 (null) for pSamples to tell the encoder to flush any data it was keeping a hold of.
Parameters:
pOutPacket [out] The packet to encode into. It will point to a buffer allocated in the frame. Caller should check IPacket::isComplete() after call to find out if we had enough information to encode a full packet.
pSamples [in] The samples to consume
sampleToStartFrom [in] Which sample you want to start with This is usually zero, but if you're using a codec that packetizes output with small number of samples, you may need to call encodeAudio repeatedly with different starting samples to consume all of your samples.
Returns:
number of samples we consumed when encoding, or negative for errors.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1230 of file StreamCoder.cpp.
References com::xuggle::xuggler::Packet::allocateNewPayload(), com::xuggle::xuggler::ICodec::CODEC_TYPE_AUDIO, com::xuggle::xuggler::IStreamCoder::ENCODING, com::xuggle::xuggler::IAudioSamples::findSampleBitDepth(), getAudioFrameSize(), getChannels(), com::xuggle::xuggler::AudioSamples::getChannels(), getCodecType(), com::xuggle::xuggler::Packet::getData(), com::xuggle::xuggler::AudioSamples::getNumSamples(), com::xuggle::xuggler::AudioSamples::getRawSamples(), getSampleRate(), com::xuggle::xuggler::AudioSamples::getSampleRate(), com::xuggle::xuggler::AudioSamples::getSampleSize(), getTimeBase(), com::xuggle::xuggler::AudioSamples::getTimeStamp(), com::xuggle::xuggler::AudioSamples::isComplete(), com::xuggle::xuggler::Global::NO_PTS, com::xuggle::ferry::RefPointer< T >::reset(), com::xuggle::xuggler::Packet::reset(), com::xuggle::xuggler::IAudioSamples::samplesToDefaultPts(), com::xuggle::ferry::RefPointer< T >::value(), VS_ASSERT, VS_LOG_TRACE, and VS_LOG_WARN.
{
  int32_t retval = -1;
  AudioSamples *samples = dynamic_cast<AudioSamples*> (pSamples);
  Packet *packet = dynamic_cast<Packet*> (pOutPacket);
  RefPointer<IBuffer> encodingBuffer;
  bool usingInternalFrameBuffer = false;
  try
  {
    if (mDirection != ENCODING)
      throw std::runtime_error("Decoding StreamCoder not valid for encoding");
    if (!mCodec)
      throw std::runtime_error("Codec not set");
    if (!mCodec->canEncode())
      throw std::runtime_error("Codec cannot be used to encode");
    if (!packet)
      throw std::invalid_argument("Invalid packet to encode to");
    // Zero out our packet
    packet->reset();
    if (!mCodecContext)
      throw std::runtime_error("StreamCoder not initialized properly");
    if (!mOpened)
      throw std::runtime_error("StreamCoder not open");
    if (getCodecType() != ICodec::CODEC_TYPE_AUDIO)
      throw std::runtime_error(
          "Attempting to encode audio with non audio coder");
    if (!mAudioFrameBuffer)
      throw std::runtime_error("Audio Frame Buffer not initialized");
    // First, how many bytes do we need to encode a packet?
    int32_t frameSize = 0;
    int32_t frameBytes = 0;
    int32_t availableSamples = (samples ? samples->getNumSamples()
        - startingSample : 0);
    int32_t samplesConsumed = 0;
    int16_t *avSamples = (samples ? samples->getRawSamples(startingSample) : 0);
    if (samples)
    {
      if (samples->getChannels() != getChannels())
        throw std::invalid_argument(
            "channels in sample do not match StreamCoder");
      if (samples->getSampleRate() != getSampleRate())
        throw std::invalid_argument(
            "sample rate in sample does not match StreamCoder");
      if (!samples->isComplete())
        throw std::invalid_argument("input samples are not complete");
      if (mFakeNextPts == Global::NO_PTS && samples->getTimeStamp()
          != Global::NO_PTS)
        mFakeNextPts = samples->getTimeStamp()
            + IAudioSamples::samplesToDefaultPts(startingSample,
                getSampleRate());
    }
    if (mFakeNextPts == Global::NO_PTS)
      mFakeNextPts = 0;
    if (availableSamples < 0 || (avSamples && availableSamples == 0))
      throw std::invalid_argument(
          "no bytes in buffer at specified starting sample");
    int32_t bytesPerSample = (samples ? samples->getSampleSize()
        : IAudioSamples::findSampleBitDepth(
            (IAudioSamples::Format) mCodecContext->sample_fmt) / 8
            * getChannels());
    /*
     * This gets tricky; There may be more audio samples passed to
     * us than can fit in an audio frame, or there may be less.
     *
     * If less, we need to cache for a future call.
     *
     * If more, we need to just use what's needed, and let the caller
     * know the number of samples we used.
     *
     * What happens when we exhaust all audio, but we still don't
     * have enough to decode a frame?  answer: the caller passes us
     * NULL as the pInSamples, and we just silently drop the incomplete
     * frame.
     *
     * To simplify coding here (and hence open for optimization if
     * this ends up being a bottleneck), I always copy audio samples
     * into a frame buffer, and then only encode from the frame buffer
     * in this class.
     */
    frameSize = getAudioFrameSize();
    frameBytes = frameSize * bytesPerSample;
    // More error checking
    VS_ASSERT(frameBytes <= mAudioFrameBuffer->getBufferSize(),
        "did frameSize change from open?");
    if (frameBytes > mAudioFrameBuffer->getBufferSize())
      throw std::runtime_error("not enough memory in internal frame buffer");
    VS_ASSERT(mBytesInFrameBuffer <= frameBytes,
        "did frameSize change from open?");
    if (frameBytes < mBytesInFrameBuffer)
      throw std::runtime_error(
          "too many bytes left over in internal frame buffer");
    unsigned char * frameBuffer = (unsigned char*) mAudioFrameBuffer->getBytes(
        0, frameBytes);
    if (!frameBuffer)
      throw std::runtime_error("could not get internal frame buffer");
    int32_t bytesToCopyToFrameBuffer = frameBytes - mBytesInFrameBuffer;
    bytesToCopyToFrameBuffer = FFMIN(bytesToCopyToFrameBuffer,
        availableSamples*bytesPerSample);
    if (avSamples)
    {
      if (availableSamples >= frameSize && mBytesInFrameBuffer == 0)
      {
        VS_LOG_TRACE("audioEncode: Using passed in buffer: %d, %d, %d",
            availableSamples, frameSize, mBytesInFrameBuffer);
        frameBuffer = (unsigned char*) avSamples;
        samplesConsumed = frameSize;
        usingInternalFrameBuffer = false;
      }
      else
      {
        VS_LOG_TRACE("audioEncode: Using internal buffer: %d, %d, %d",
            availableSamples, frameSize, mBytesInFrameBuffer);
        memcpy(frameBuffer + mBytesInFrameBuffer, avSamples,
            bytesToCopyToFrameBuffer);
        mBytesInFrameBuffer += bytesToCopyToFrameBuffer;
        samplesConsumed = bytesToCopyToFrameBuffer / bytesPerSample;
        retval = samplesConsumed;
        usingInternalFrameBuffer = true;
      }
    }
    else
    {
      // drop everything in the frame buffer, and instead
      // just pass a null buffer to the encoder.
      // this should happen when the caller passes NULL for the
      // input samples
      frameBuffer = 0;
    }
    mSamplesForEncoding += samplesConsumed;
    VS_LOG_TRACE("Consumed %ld for total of %lld",
        samplesConsumed, mSamplesForEncoding);
    if (!frameBuffer || !usingInternalFrameBuffer || mBytesInFrameBuffer
        >= frameBytes)
    {
      // First, get the right buffer size.
      int32_t bufferSize = frameBytes;
      if (mCodecContext->codec->id == CODEC_ID_FLAC
              || mCodecContext->codec->id == CODEC_ID_VORBIS)
      {
        // FLAC & VORBIS audio for some reason gives an error if your output buffer isn't
        // over double the frame size, so we fake it here.  This could be further optimized
        // to only require an exact number, but this math is simpler and will always
        // be large enough.
        bufferSize = (64 + getAudioFrameSize() * (bytesPerSample + 1)) * 2;
      }
      VS_ASSERT(bufferSize> 0, "no buffer size in samples");
      retval = packet->allocateNewPayload(bufferSize);
      if (retval >= 0)
      {
        encodingBuffer = packet->getData();
      }
      uint8_t* buf = 0;
      if (encodingBuffer)
      {
        buf = (uint8_t*) encodingBuffer->getBytes(0, bufferSize);
      }
      if (buf && bufferSize)
      {
        VS_LOG_TRACE("Attempting encodeAudio(%p, %p, %d, %p)",
            mCodecContext,
            buf,
            bufferSize,
            frameBuffer);
        // This hack works around the fact that PCM's codecs
        // calculate samples from buffer length, and sets
        // the wrong frame size, but in
        // reality we're always passing in 2 byte samples.
        double pcmCorrection = 1.0;
        switch (mCodecContext->codec->id)
        {
        case CODEC_ID_PCM_S32LE:
        case CODEC_ID_PCM_S32BE:
        case CODEC_ID_PCM_U32LE:
        case CODEC_ID_PCM_U32BE:
          pcmCorrection = 2.0;
          break;
        case CODEC_ID_PCM_S24LE:
        case CODEC_ID_PCM_S24BE:
        case CODEC_ID_PCM_U24LE:
        case CODEC_ID_PCM_U24BE:
        case CODEC_ID_PCM_S24DAUD:
          pcmCorrection = 1.5;
          break;
        case CODEC_ID_PCM_S16LE:
        case CODEC_ID_PCM_S16BE:
        case CODEC_ID_PCM_U16LE:
        case CODEC_ID_PCM_U16BE:
          pcmCorrection = 1.0;
          break;
        case CODEC_ID_PCM_ALAW:
        case CODEC_ID_PCM_MULAW:
        case CODEC_ID_PCM_S8:
        case CODEC_ID_PCM_U8:
        case CODEC_ID_PCM_ZORK:
          pcmCorrection = 0.5;
          break;
        default:
          pcmCorrection = 1.0;
        }
        retval = avcodec_encode_audio(mCodecContext, buf, (int32_t) (bufferSize
            * pcmCorrection), (int16_t*) frameBuffer);
        VS_LOG_TRACE("Finished %d encodeAudio(%p, %p, %d, %p)",
            retval,
            mCodecContext,
            buf,
            bufferSize,
            frameBuffer);
        // regardless of what happened, nuke any data in our frame
        // buffer.
        mBytesInFrameBuffer = 0;
        if (retval >= 0)
        {
          // and only do this if a packet is returned
          if (retval > 0)
          {
            mSamplesCoded += frameSize;
            // let's check to see if the time stamp of passed in
            // samples (if any) are within tolerance of our expected
            // time stamp.  if not, this is most likely happening
            // because the IStreamCoder's data source lost a packet.
            // We will adjust our starting time stamps then for this new
            // packet
            mFakeCurrPts = mFakeNextPts;
            if (samples && samples->getTimeStamp() != Global::NO_PTS)
            {
              int64_t samplesTs = samples->getTimeStamp()
                  + IAudioSamples::samplesToDefaultPts(startingSample
                      + samplesConsumed, getSampleRate());
              int64_t samplesCached = mSamplesForEncoding - mSamplesCoded;
              int64_t tsDelta = IAudioSamples::samplesToDefaultPts(
                  samplesCached, getSampleRate());
              int64_t gap = samplesTs - (mFakeNextPts + tsDelta);
              // ignore negative gaps; some containers like WMV
              // don't actually set the right time stamps, and we
              // can assume a negative gap can't happen
              if ((gap > 1))
              {
                VS_LOG_TRACE("reset;"
                    "samplesTs:%lld;"
                    "samplesConsumed:%ld;"
                    "startingSample:%lu;"
                    "samplesForEncoding:%lld;"
                    "samplesCoded:%lld;"
                    "samplesCached:%lld;"
                    "tsDelta:%lld;"
                    "fakeNextPts:%lld;"
                    "gap:%lld;"
                    "lastExternallySetTs:%lld;"
                    "new fakeNextPts:%lld;",
                    samplesTs,
                    samplesConsumed,
                    startingSample,
                    mSamplesForEncoding,
                    mSamplesCoded,
                    samplesCached,
                    tsDelta,
                    mFakeNextPts,
                    gap,
                    mLastExternallySetTimeStamp,
                    samplesTs - tsDelta);
                mLastExternallySetTimeStamp = samplesTs - tsDelta;
                mSamplesCoded = 0;
                mSamplesForEncoding = samplesCached;
              }
            }
            mFakeNextPts = mLastExternallySetTimeStamp
                + IAudioSamples::samplesToDefaultPts(mSamplesCoded,
                    getSampleRate());
          }
          RefPointer<IRational> thisTimeBase = getTimeBase();
          int64_t ts;
          int64_t duration = IAudioSamples::samplesToDefaultPts(frameSize,
              getSampleRate());
          if (!thisTimeBase)
          {
            thisTimeBase.reset(mFakePtsTimeBase.value(), true);
            ts = mFakeCurrPts;
          }
          else
          {
            ts = thisTimeBase->rescale(mFakeCurrPts, mFakePtsTimeBase.value());
            duration
                = thisTimeBase->rescale(duration, mFakePtsTimeBase.value());
          }
          setPacketParameters(packet, retval, ts, thisTimeBase.value(), true,
              duration);
          retval = samplesConsumed;
        }
        else
        {
          throw std::runtime_error("avcodec_encode_audio failed");
        }
      }
    }
  }
  catch (std::bad_alloc & e)
  {
    throw e;
  }
  catch (std::exception& e)
  {
    VS_LOG_WARN("error: %s", e.what());
    retval = -1;
  }
  return retval;
}
int64_t com::xuggle::xuggler::StreamCoder::getNextPredictedPts () [virtual]
For this stream, get the next Pts that we expect to decode.
Note that this may not actually be the next Pts (for example due to transmission packet drops in the input source). Still it can be a useful tool.
Returns:
The next presentation time stamp we expect to decode on this stream. This is always in units of 1/1,000,000 seconds
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 415 of file StreamCoder.cpp.
{
  return mFakeNextPts;
}
int32_t com::xuggle::xuggler::StreamCoder::getCodecTag () [virtual]
Returns the 4-byte FOURCC tag (Least Significant Byte first).
This is really a packed 4-byte array so it's only useful if you use bit-wise operations on it. Some language wrappings may provide more obvious ways of manipulating, but this is the safest way to do this that will work with all wrappers.
Returns:
the FOURCC tag.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1666 of file StreamCoder.cpp.
{
  return (mCodecContext ? mCodecContext->codec_tag : 0);
}
void com::xuggle::xuggler::StreamCoder::setCodecTag (int32_t fourcc) [virtual]
Set the 4-byte FOURCC tag for this coder.
Parameters:
fourcc The FOURCC to set, with Least Significant Byte first.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1672 of file StreamCoder.cpp.
{
  if (mCodecContext)
    mCodecContext->codec_tag = tag;
}
int32_t com::xuggle::xuggler::StreamCoder::getNumProperties () [virtual]
Returns the total number of settable properties on this object.
Returns:
total number of options (not including constant definitions)
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1679 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::getNumProperties().
{
  return Property::getNumProperties(mCodecContext);
}
IProperty * com::xuggle::xuggler::StreamCoder::getPropertyMetaData (int32_t propertyNo) [virtual]
Returns the name of the numbered property.
Parameters:
propertyNo The property number in the options list.
Returns:
an IProperty value for this properties meta-data
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1685 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::getPropertyMetaData().
{
  return Property::getPropertyMetaData(mCodecContext, propertyNo);
}
IProperty * com::xuggle::xuggler::StreamCoder::getPropertyMetaData (const char * name) [virtual]
Returns the name of the numbered property.
Parameters:
name The property name.
Returns:
an IProperty value for this properties meta-data
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1691 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::getPropertyMetaData().
{
  return Property::getPropertyMetaData(mCodecContext, name);
}
int32_t com::xuggle::xuggler::StreamCoder::setProperty (const char * name, const char * value) [virtual]
Sets a property on this Object.
All AVOptions supported by the underlying AVClass are supported.
Parameters:
name The property name. For example "b" for bit-rate.
value The value of the property.
Returns:
>= 0 if the property was successfully set; <0 on error
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1697 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::setProperty().
{
  return Property::setProperty(mCodecContext, aName, aValue);
}
int32_t com::xuggle::xuggler::StreamCoder::setProperty (const char * name, double value) [virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1703 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::setProperty().
{
  return Property::setProperty(mCodecContext, aName, aValue);
}
int32_t com::xuggle::xuggler::StreamCoder::setProperty (const char * name, int64_t value) [virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1709 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::setProperty().
{
  return Property::setProperty(mCodecContext, aName, aValue);
}
int32_t com::xuggle::xuggler::StreamCoder::setProperty (const char * name, bool value) [virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1715 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::setProperty().
{
  return Property::setProperty(mCodecContext, aName, aValue);
}
int32_t com::xuggle::xuggler::StreamCoder::setProperty (const char * name, IRational * value) [virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1721 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::setProperty().
{
  return Property::setProperty(mCodecContext, aName, aValue);
}
char * com::xuggle::xuggler::StreamCoder::getPropertyAsString (const char * name) [virtual]
Gets a property on this Object.
Note for C++ callers; you must free the returned array with delete[] in order to avoid a memory leak. Other language folks need not worry.
Parameters:
name property name
Returns:
an string copy of the option value, or null if the option doesn't exist.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1727 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::getPropertyAsString().
{
  return Property::getPropertyAsString(mCodecContext, aName);
}
double com::xuggle::xuggler::StreamCoder::getPropertyAsDouble (const char * name) [virtual]
Gets the value of this property, and returns as a double;.
Parameters:
name name of option
Returns:
double value of property, or 0 on error.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1733 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::getPropertyAsDouble().
{
  return Property::getPropertyAsDouble(mCodecContext, aName);
}
int64_t com::xuggle::xuggler::StreamCoder::getPropertyAsLong (const char * name) [virtual]
Gets the value of this property, and returns as an long;.
Parameters:
name name of option
Returns:
long value of property, or 0 on error.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1739 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::getPropertyAsLong().
{
  return Property::getPropertyAsLong(mCodecContext, aName);
}
IRational * com::xuggle::xuggler::StreamCoder::getPropertyAsRational (const char * name) [virtual]
Gets the value of this property, and returns as an IRational;.
Parameters:
name name of option
Returns:
long value of property, or 0 on error.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1745 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::getPropertyAsRational().
{
  return Property::getPropertyAsRational(mCodecContext, aName);
}
bool com::xuggle::xuggler::StreamCoder::getPropertyAsBoolean (const char * name) [virtual]
Gets the value of this property, and returns as a boolean.
Parameters:
name name of option
Returns:
boolean value of property, or false on error.
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1751 of file StreamCoder.cpp.
References com::xuggle::xuggler::Property::getPropertyAsBoolean().
{
  return Property::getPropertyAsBoolean(mCodecContext, aName);
}
bool com::xuggle::xuggler::StreamCoder::isOpen () [virtual]
Returns true if this IStreamCoder is currently open.
Returns:
true if open; false if not
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1757 of file StreamCoder.cpp.
Referenced by com::xuggle::xuggler::Stream::setStreamCoder().
{
  return mOpened;
}
int32_t com::xuggle::xuggler::StreamCoder::getDefaultAudioFrameSize () [virtual]
Get the default audio frame size (in samples).
Some codecs, especially raw codecs, like PCM, don't have a standard frame size. In those cases, we use the value of this setting to determine how many samples to encode into a single packet.
Returns:
the number of samples in an audio frame size if the codec doesn't specify the size.
Since:
1.21
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1763 of file StreamCoder.cpp.
Referenced by getAudioFrameSize().
{
  return mDefaultAudioFrameSize;
}
void com::xuggle::xuggler::StreamCoder::setDefaultAudioFrameSize (int32_t aNewSize) [virtual]
Set the default audio frame size.
Parameters:
aNewSize The new number of samples to use to encode samples into a packet. This setting is ignored if <= 0 or if the codec requires it's own frame size (e.g. Nellymoser).
See also:
getDefaultAudioFrameSize()
Since:
1.21
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1769 of file StreamCoder.cpp.
{
  if (aNewSize > 0)
    mDefaultAudioFrameSize = aNewSize;
}
void com::xuggle::xuggler::StreamCoder::setCodec (int32_t id)
Definition at line 309 of file StreamCoder.cpp.
References com::xuggle::xuggler::IStreamCoder::ENCODING, com::xuggle::xuggler::Codec::findDecodingCodecByIntID(), com::xuggle::xuggler::Codec::findEncodingCodecByIntID(), com::xuggle::ferry::RefCounted::release(), and setCodec().
{
  ICodec *codec = 0;
  if (ENCODING == mDirection)
  {
    codec = Codec::findEncodingCodecByIntID(id);
  }
  else
  {
    codec = Codec::findDecodingCodecByIntID(id);
  }
  if (codec)
  {
    setCodec(codec);
    // release it because the set above should get
    // the permanent reference.
    codec->release();
    codec = 0;
  }
}
static StreamCoder* com::xuggle::xuggler::StreamCoder::make (Direction direction) [static]
This method creates a StreamCoder that is not tied to any container or stream.
Referenced by make(), com::xuggle::xuggler::Stream::make(), and com::xuggle::xuggler::IStreamCoder::make().
StreamCoder * com::xuggle::xuggler::StreamCoder::make (Direction direction, AVCodecContext * context, Stream * stream) [static]
This method creates a StreamCoder that is tied to a specific stream in a container.
Definition at line 192 of file StreamCoder.cpp.
References make(), mCodecContext, mDirection, mStream, and VS_REF_RELEASE.
{
  StreamCoder *retval = 0;
  if (codecCtx)
  {
    try
    {
      retval = StreamCoder::make();
      // In FFmpeg r20623 they started defaulting the sample
      // format to NONE, but Xuggler uses assume S16, so we
      // override that.
      if (codecCtx->sample_fmt == SAMPLE_FMT_NONE)
        codecCtx->sample_fmt = SAMPLE_FMT_S16;
      retval->mCodecContext = codecCtx;
      retval->mDirection = direction;
      retval->mStream = stream; //do not ref count.
      // Set the private data to this object.
      codecCtx->opaque = retval;
    }
    catch (std::bad_alloc &e)
    {
      VS_REF_RELEASE(retval);
      throw e;
    }
  }
  return retval;
}
StreamCoder * com::xuggle::xuggler::StreamCoder::make (Direction direction, IStreamCoder * copyCoder) [static]
Definition at line 100 of file StreamCoder.cpp.
References com::xuggle::xuggler::IStreamCoder::getCodec(), getStream(), getTimeBase(), make(), mCodecContext, mDirection, mStream, com::xuggle::ferry::RefCounted::release(), setCodec(), VS_LOG_WARN, and VS_REF_RELEASE.
{
  StreamCoder *retval = 0;
  try
  {
    AVCodecContext* codecCtx = avcodec_alloc_context();
    if (!codecCtx)
      throw std::bad_alloc();
    retval = StreamCoder::make();
    if (retval)
    {
      retval->mCodecContext = codecCtx;
      retval->mDirection = direction;
      retval->mStream = 0;
      // Set the private data to this object.
      codecCtx->opaque = retval;
      StreamCoder *coder = dynamic_cast<StreamCoder*> (aCoder);
      if (aCoder && !coder)
        throw std::runtime_error(
            "Passed in stream coder not of expected underlying C++ type");
      if (coder)
      {
        struct AVCodecContext* codec = retval->mCodecContext;
        struct AVCodecContext* icodec = coder->mCodecContext;
        avcodec_copy_context(codec, icodec);
        // In FFmpeg r20623 they started defaulting the sample
        // format to NONE, but Xuggler uses assume S16, so we
        // override that.
        if (codec->sample_fmt == SAMPLE_FMT_NONE)
          codec->sample_fmt = SAMPLE_FMT_S16;
        RefPointer<IStream> stream = coder->getStream();
        RefPointer<IRational> streamBase = stream ? stream->getTimeBase() : 0;
        double base = streamBase ? streamBase->getDouble() : 0;
        if (base && av_q2d(icodec->time_base) * icodec->ticks_per_frame > base
            && base < 1.0 / 1000)
        {
          codec->time_base.num *= icodec->ticks_per_frame;
        }
        if (!codec->time_base.num || !codec->time_base.den)
        {
          RefPointer<IRational> iStreamBase = coder->getTimeBase();
          if (iStreamBase)
          {
            codec->time_base.num = iStreamBase->getNumerator();
            codec->time_base.den = iStreamBase->getDenominator();
          }
        }
        switch (codec->codec_type)
        {
        case AVMEDIA_TYPE_AUDIO:
          if (codec->block_align == 1 && codec->codec_id == CODEC_ID_MP3)
            codec->block_align = 0;
          if (codec->codec_id == CODEC_ID_AC3)
            codec->block_align = 0;
          break;
        default:
          break;
        }
        // set the codec to the codec_id
        ICodec* tempCodec = aCoder->getCodec();
        retval->setCodec(tempCodec);
        tempCodec->release();
      }
      else
      {
        retval->mCodecContext->codec_id = CODEC_ID_PROBE; // Tell FFMPEG we don't know, but to probe to find out
        if (retval->mCodecContext->sample_fmt == SAMPLE_FMT_NONE)
          retval->mCodecContext->sample_fmt = SAMPLE_FMT_S16;
}
    }
  }
  catch (std::bad_alloc &e)
  {
    VS_REF_RELEASE(retval);
    throw e;
  }
  catch (std::exception &e)
  {
    VS_LOG_WARN("Error: %s", e.what());
    VS_REF_RELEASE(retval);
  }
  return retval;
}
int32_t com::xuggle::xuggler::StreamCoder::setStream (Stream * stream, bool assumeOnlyStream)
Definition at line 1776 of file StreamCoder.cpp.
References com::xuggle::xuggler::Stream::getAVStream().
Referenced by com::xuggle::xuggler::Stream::setStreamCoder().
{
  int32_t retval = -1;
  if (assumeOnlyStream)
    mStream = stream;
  AVStream *avStream = stream ? stream->getAVStream() : 0;
  if (avStream)
  {
    // This handles the case where FFMPEG actually alloced a stream
    // codeccontext and thinks it'll free it later when the input
    // file closes.  in this case, we free the old value because
    // we're about to overwrite it.
    if (avStream->codec)
      av_free(avStream->codec);
    avStream->codec = mCodecContext;
  }
  retval = 0;
  return retval;
}
int32_t com::xuggle::xuggler::StreamCoder::streamClosed (Stream * stream)
Definition at line 1636 of file StreamCoder.cpp.
Referenced by com::xuggle::xuggler::Stream::containerClosed(), and com::xuggle::xuggler::Stream::setStreamCoder().
{
  int32_t retval = 0;
  if (stream == mStream)
  {
    reset();
  }
  return retval;
}
int64_t com::xuggle::xuggler::StreamCoder::getNumDroppedFrames () [virtual]
Get the number of frames this StreamCoder had to drop to encode at the specified getTimeBase().
IStreamCoder objects can encode audio and video, but guarantee that every packet outputted has monotonically increasing timestamps (i.e. 0, 1, 2, 3, 4, 5, etc. without repeats). Sometimes data is passed too quickly into an IStreamCoder via encodeVideo or encodeAudio, and the underlying codec can't handle it that quickly. In those cases the IStreamCoder must drop the most recent frame of data.
If you're seeing a lot of dropped frames you can try either sending less frequent data to the IStreamCoder, or adjusting the getTimeBase() to the highest possible resolution. Be warned though; some codecs (such as MPEG2) require fixed time-bases (like 1/25) and so setting a higher resolution time base might end up with the codec not able to encode any data.
Returns:
the number of frames dropped.
Since:
3.1
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1797 of file StreamCoder.cpp.
{
  return mNumDroppedFrames;
}
void com::xuggle::xuggler::StreamCoder::setAutomaticallyStampPacketsForStream (bool value) [virtual]
Should the IStreamCoder automatically adjust time stamps on output packets for the IStream it is ultimately destined for.
If this IStreamCoder does not know which IStream it is destined for, or this IStreamCoder isn't used with an IStream at all, then this setting is ignored.
Parameters:
value true to automatically adjust.
Since:
3.2
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1803 of file StreamCoder.cpp.
{
  //  VS_LOG_DEBUG("setAutomaticallyStampPacketsForStream: %d", value);
  mAutomaticallyStampPacketsForStream = value;
}
bool com::xuggle::xuggler::StreamCoder::getAutomaticallyStampPacketsForStream () [virtual]
Does this IStreamCoder automatically adjust time stamps on output packets for the IStream it is ultimately destined for.
Returns:
true for yes; false for no
See also:
setAutomaticallyStampPacketsForStream(boolean)
Since:
3.2
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1810 of file StreamCoder.cpp.
{
  return mAutomaticallyStampPacketsForStream;
}
int32_t com::xuggle::xuggler::StreamCoder::acquire () [virtual]
Internal Only.
DO NOT USE FROM JAVA.
Acquire a reference to this object. This increments the native internal ref count in native code by +1.
This method is called internally by Ferry in Java, and you should not call it without knowing what you are doing. But if you do call it, make sure you call release() once for each call you make to this method.
Returns:
The refcount after the acquire. Note due to multi-threaded issues, you should not rely on this value, as it may change before the method returns to you.
Reimplemented from com::xuggle::ferry::RefCounted.
Definition at line 1648 of file StreamCoder.cpp.
References com::xuggle::ferry::RefCounted::acquire(), and VS_LOG_TRACE.
{
  int32_t retval = 0;
  retval = RefCounted::acquire();
  VS_LOG_TRACE("Acquired %p: %d", this, retval);
  return retval;
}
int32_t com::xuggle::xuggler::StreamCoder::release () [virtual]
Internal Only.
DO NOT USE FROM JAVA.
This decrements the native internal ref count by -1; the object is destroyed if its ref count reaches zero.
This method is called internally by Ferry in Java, and you should not call it without knowing what you are doing. But if you do call it, make sure you had previously called acquire() once for each call to release() you make.
Returns:
The ref count after the release. Note due to multi-threaded issues, you should not rely on this value, as it may change before the method returns to you.
Reimplemented from com::xuggle::ferry::RefCounted.
Definition at line 1657 of file StreamCoder.cpp.
References com::xuggle::ferry::RefCounted::release(), and VS_LOG_TRACE.
{
  int32_t retval = 0;
  retval = RefCounted::release();
  VS_LOG_TRACE("Released %p: %d", this, retval);
  return retval;
}
int32_t com::xuggle::xuggler::StreamCoder::setExtraData (com::xuggle::ferry::IBuffer * src, int32_t offset, int32_t length, bool allocNew) [virtual]
Copies data from the given buffer into the extra-data area maintained by encoders.
This is an extremely advanced method, and incorrect usage can result in Java crashes so take care. In general people should not need to use this.
For some codecs (e.g. for H264, this is global header information and for rv10 it is additional flags), Xuggler maintains extra information about the codec in a extra data buffer. In general Xuggler will allocate this data as needed and you never need to set it (or get it). But if you know what you're doing, you can ask Xuggler to replace the existing extra data for the given codec with a copy of the data in the given buffer.
You should call this method after you call open() but before you encode or decode any media.
Parameters:
src The data to copy
offset The position, in bytes, to start copying data from src
length The number of bytes to copy from data
allocNew If true, and there is not enough space in the existing extra data buffer, then Xuggler will discard the old buffer and allocate a new buffer. If false, then Xuggler will attempt to copy the data into the existing buffer and if there is not enough space in the existing buffer, no bytes will be copied and an error will be returned. In general, you should set this to false if that works for you.
Returns:
The number of bytes copied, or < 0 on error.
Since:
3.3
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1816 of file StreamCoder.cpp.
References com::xuggle::ferry::IBuffer::getBytes().
{
  if (!mCodecContext || !src)
    return -1;
  void* bytes = src->getBytes(offset, numBytes);
  if (!bytes)
    return -1;
  if (mCodecContext->extradata_size < numBytes || !mCodecContext->extradata)
  {
    if (allocNew)
    {
      av_free(mCodecContext->extradata);
      mCodecContext->extradata_size = 0;
      mCodecContext->extradata = (uint8_t*) av_malloc(numBytes
          + FF_INPUT_BUFFER_PADDING_SIZE);
      if (!mCodecContext->extradata)
      {
        return -1;
      }
      mCodecContext->extradata_size = numBytes;
    }
    else
      return -1;
  }
  memcpy(mCodecContext->extradata, bytes, numBytes);
  return numBytes;
}
int32_t com::xuggle::xuggler::StreamCoder::getExtraData (com::xuggle::ferry::IBuffer * dest, int32_t offset, int32_t maxBytesToCopy) [virtual]
Copies the current content of the extra-data buffer maintained by this codec (e.g.
header bytes) into the dest buffer.
Parameters:
dest The buffer to copy to.
offset The position, in bytes, to start writing data to in dest.
maxBytesToCopy The maximum number of bytes to copy.
Returns:
The number of bytes copied, or < 0 on error.
Since:
3.3
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1847 of file StreamCoder.cpp.
References com::xuggle::ferry::IBuffer::getBytes().
{
  if (!mCodecContext || !mCodecContext->extradata
      || mCodecContext->extradata_size <= 0 || !dest || offset < 0
      || maxBytesToCopy < 0 || dest->getSize() < offset + maxBytesToCopy)
    return 0;
  int32_t bytesToCopy = FFMIN(maxBytesToCopy, mCodecContext->extradata_size);
  if (bytesToCopy <= 0)
    return 0;
  void* bytes = dest->getBytes(offset, bytesToCopy);
  if (!bytes)
    return 0;
  memcpy(bytes, mCodecContext->extradata, bytesToCopy);
  return bytesToCopy;
}
int32_t com::xuggle::xuggler::StreamCoder::getExtraDataSize () [virtual]
Gets the current number of bytes of data maintained in the coder extra-data area.
Returns:
The number of bytes. If 0, then no data is currently available.
Since:
3.3
Implements com::xuggle::xuggler::IStreamCoder.
Definition at line 1866 of file StreamCoder.cpp.
{
  if (mCodecContext)
    return mCodecContext->extradata_size;
  return 0;
}
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/StreamCoder.h
csrc/com/xuggle/xuggler/StreamCoder.cpp