Xuggle: com::xuggle::xuggler::IPixelFormat Class Reference
com::xuggle::xuggler::IPixelFormat Class Reference
#include <IPixelFormat.h>
Detailed Description
Information about how video data is formatted in an IVideoPicture object.
This specifies the color space and how many bits pixel data takes. It also includes some utility methods for dealing with Type#YUV420P data; the most common type of encoding used in video files I've run across.
Definition at line 38 of file IPixelFormat.h.
Public Types
enum Type {
NONE = -1, YUV420P, YUYV422, RGB24,
BGR24, YUV422P, YUV444P, YUV410P,
YUV411P, GRAY8, MONOWHITE, MONOBLACK,
PAL8, YUVJ420P, YUVJ422P, YUVJ444P,
XVMC_MPEG2_MC, XVMC_MPEG2_IDCT, UYVY422, UYYVYY411,
BGR8, BGR4, BGR4_BYTE, RGB8,
RGB4, RGB4_BYTE, NV12, NV21,
ARGB, RGBA, ABGR, BGRA,
GRAY16BE, GRAY16LE, YUV440P, YUVJ440P,
YUVA420P, VDPAU_H264, VDPAU_MPEG1, VDPAU_MPEG2,
VDPAU_WMV3, VDPAU_VC1, RGB48BE, RGB48LE,
RGB565BE, RGB565LE, RGB555BE, RGB555LE,
BGR565BE, BGR565LE, BGR555BE, BGR555LE,
VAAPI_MOCO, VAAPI_IDCT, VAAPI_VLD, YUV420PLE,
YUV420PBE, YUV422PLE, YUV422PBE, YUV444PLE,
YUV444PBE, NB
}
Pixel format.
enum YUVColorComponent { YUV_Y = 0, YUV_U = 1, YUV_V = 2 }
typedef enum
com::xuggle::xuggler::IPixelFormat::Type Type
Static Public Member Functions
static unsigned char getYUV420PPixel (IVideoPicture *frame, int x, int y, YUVColorComponent c)
Returns the byte for the coordinates at x and y for the color component c.
static void setYUV420PPixel (IVideoPicture *frame, int x, int y, YUVColorComponent c, unsigned char value)
Sets the value of the color component c at the coordinates x and y in the given frame.
static int getYUV420PPixelOffset (IVideoPicture *frame, int x, int y, YUVColorComponent c)
For a given x and y in a frame, and a given color components, this method tells you how far into the actual data you'd have to go to find the byte that represents that color/coordinate combination.
Protected Member Functions
IPixelFormat ()
virtual ~IPixelFormat ()
Member Typedef Documentation
typedef enum com::xuggle::xuggler::IPixelFormat::Type com::xuggle::xuggler::IPixelFormat::Type
Member Enumeration Documentation
enum com::xuggle::xuggler::IPixelFormat::Type
Pixel format.
Notes:
RGB32 is handled in an endian-specific manner. A RGBA color is put together as: (A << 24) | (R << 16) | (G << 8) | B This is stored as BGRA on little endian CPU architectures and ARGB on big endian CPUs.
When the pixel format is palettized RGB (PAL8), the palettized image data is stored in AVFrame.data[0]. The palette is transported in AVFrame.data[1] and, is 1024 bytes long (256 4-byte entries) and is formatted the same as in RGB32 described above (i.e., it is also endian-specific). Note also that the individual RGB palette components stored in AVFrame.data[1] should be in the range 0..255. This is important as many custom PAL8 video codecs that were designed to run on the IBM VGA graphics adapter use 6-bit palette components.
Enumerator:
NONE
YUV420P
YUYV422
RGB24
BGR24
YUV422P
YUV444P
YUV410P
YUV411P
GRAY8
MONOWHITE
MONOBLACK
PAL8
YUVJ420P
YUVJ422P
YUVJ444P
XVMC_MPEG2_MC
XVMC_MPEG2_IDCT
UYVY422
UYYVYY411
BGR8
BGR4
BGR4_BYTE
RGB8
RGB4
RGB4_BYTE
NV12
NV21
ARGB
RGBA
ABGR
BGRA
GRAY16BE
GRAY16LE
YUV440P
YUVJ440P
YUVA420P
VDPAU_H264
VDPAU_MPEG1
VDPAU_MPEG2
VDPAU_WMV3
VDPAU_VC1
RGB48BE
RGB48LE
RGB565BE
RGB565LE
RGB555BE
RGB555LE
BGR565BE
BGR565LE
BGR555BE
BGR555LE
VAAPI_MOCO
VAAPI_IDCT
VAAPI_VLD
YUV420PLE
YUV420PBE
YUV422PLE
YUV422PBE
YUV444PLE
YUV444PBE
NB
Definition at line 58 of file IPixelFormat.h.
                      {
      NONE= -1,
      YUV420P,
      YUYV422,
      RGB24,
      BGR24,
      YUV422P,
      YUV444P,
      YUV410P,
      YUV411P,
      GRAY8,
      MONOWHITE,
      MONOBLACK,
      PAL8,
      YUVJ420P,
      YUVJ422P,
      YUVJ444P,
      XVMC_MPEG2_MC,
      XVMC_MPEG2_IDCT,
      UYVY422,
      UYYVYY411,
      BGR8,
      BGR4,
      BGR4_BYTE,
      RGB8,
      RGB4,
      RGB4_BYTE,
      NV12,
      NV21,
      ARGB,
      RGBA,
      ABGR,
      BGRA,
      GRAY16BE,
      GRAY16LE,
      YUV440P,
      YUVJ440P,
      YUVA420P,
      VDPAU_H264,
      VDPAU_MPEG1,
      VDPAU_MPEG2,
      VDPAU_WMV3,
      VDPAU_VC1,
      RGB48BE,
      RGB48LE,
      RGB565BE,
      RGB565LE,
      RGB555BE,
      RGB555LE,
      BGR565BE,
      BGR565LE,
      BGR555BE,
      BGR555LE,
      VAAPI_MOCO,
      VAAPI_IDCT,
      VAAPI_VLD,
      YUV420PLE,
      YUV420PBE,
      YUV422PLE,
      YUV422PBE,
      YUV444PLE,
      YUV444PBE,
      NB,
    } Type;
enum com::xuggle::xuggler::IPixelFormat::YUVColorComponent
Enumerator:
YUV_Y
YUV_U
YUV_V
Definition at line 130 of file IPixelFormat.h.
                 {
      YUV_Y=0,
      YUV_U=1,
      YUV_V=2,
    } YUVColorComponent;
Constructor & Destructor Documentation
com::xuggle::xuggler::IPixelFormat::IPixelFormat () [protected]
Definition at line 35 of file IPixelFormat.cpp.
  {
  }
com::xuggle::xuggler::IPixelFormat::~IPixelFormat () [protected, virtual]
Definition at line 40 of file IPixelFormat.cpp.
  {
  }
Member Function Documentation
unsigned char com::xuggle::xuggler::IPixelFormat::getYUV420PPixel (IVideoPicture * frame, int x, int y, YUVColorComponent c) [static]
Returns the byte for the coordinates at x and y for the color component c.
Parameters:
frame The frame to get the byte from
x X coordinate in pixels, where 0 is the left hand edge of the image.
y Y coordinate in pixels, where 0 is the top edge of the image.
c YUVColor component
Exceptions:
std::exception frame is null, the coordinates are invalid, or if the pixel format is not YUV420P
Returns:
the pixel byte for that x, y, c combination
Definition at line 46 of file IPixelFormat.cpp.
References com::xuggle::xuggler::IMediaData::getData(), and getYUV420PPixelOffset().
  {
    unsigned char result = 0;
    int offset = getYUV420PPixelOffset(frame, x, y, c);
    RefPointer<IBuffer> buffer = frame->getData();
    unsigned char * bytes = (unsigned char*)buffer->getBytes(0, offset+1);
    if (!bytes)
      throw std::runtime_error("could not find bytes in frame");
    result = bytes[offset];
    return result;
  }
void com::xuggle::xuggler::IPixelFormat::setYUV420PPixel (IVideoPicture * frame, int x, int y, YUVColorComponent c, unsigned char value) [static]
Sets the value of the color component c at the coordinates x and y in the given frame.
Parameters:
frame The frame to set the byte in
x X coordinate in pixels, where 0 is the left hand edge of the image.
y Y coordinate in pixels, where 0 is the top edge of the image.
c YUVColor component to set
value The new value of that pixel color component
Exceptions:
std::exception frame is null, the coordinates are invalid, or if the pixel format is not YUV420P
Definition at line 61 of file IPixelFormat.cpp.
References com::xuggle::xuggler::IMediaData::getData(), getYUV420PPixelOffset(), and VS_LOG_DEBUG.
  {
    int offset = getYUV420PPixelOffset(frame, x, y, c);
    RefPointer<IBuffer> buffer = frame->getData();
    unsigned char * bytes = (unsigned char*)buffer->getBytes(0, offset+1);
    if (!bytes)
    {
      VS_LOG_DEBUG("Could not find buffer of length: %d", offset+1);
      throw std::runtime_error("could not find bytes in frame");
    }
    bytes[offset] = value;
  }
int com::xuggle::xuggler::IPixelFormat::getYUV420PPixelOffset (IVideoPicture * frame, int x, int y, YUVColorComponent c) [static]
For a given x and y in a frame, and a given color components, this method tells you how far into the actual data you'd have to go to find the byte that represents that color/coordinate combination.
Parameters:
frame The frame to get the byte from
x X coordinate in pixels, where 0 is the left hand edge of the image.
y Y coordinate in pixels, where 0 is the top edge of the image.
c YUVColor component
Exceptions:
std::exception frame is null, the coordinates are invalid, or if the pixel format is not YUV420P
Returns:
the offset in bytes, starting from the start of the frame data, where the data for this pixel resides.
Definition at line 76 of file IPixelFormat.cpp.
References com::xuggle::xuggler::PixelFormat::getFastYUV420PPixelOffset(), com::xuggle::xuggler::IVideoPicture::getHeight(), com::xuggle::xuggler::IVideoPicture::getPixelType(), com::xuggle::xuggler::IVideoPicture::getWidth(), VS_LOG_TRACE, and YUV420P.
Referenced by getYUV420PPixel(), and setYUV420PPixel().
  {
    if (!frame)
      throw std::runtime_error("no frame");
    int width = frame->getWidth();
    if (x < 0 || x >= width)
      throw std::runtime_error("x value invalid for input frame");
    int height = frame->getHeight();
    if (y < 0 || y >= height)
      throw std::runtime_error("y value invalid for input frame");
    if (frame->getPixelType() != YUV420P)
      throw std::runtime_error("pixel type of input frame is incorrect");
    int offset = PixelFormat::getFastYUV420PPixelOffset(frame->getWidth(), frame->getHeight(), x, y, c);
    VS_LOG_TRACE("w: %d; h: %d; x: %d; y: %d; c: %d; offset: %d",
        frame->getWidth(), frame->getHeight(), x, y, c, offset);
    return offset;
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/IPixelFormat.h
csrc/com/xuggle/xuggler/IPixelFormat.cpp