Xuggle: com::xuggle::xuggler::Container Class Reference
com::xuggle::xuggler::Container Class Reference
#include <Container.h>
Detailed Description
Definition at line 35 of file Container.h.
Public Member Functions
virtual int32_t setInputBufferLength (uint32_t size)
Set the buffer length Xuggler will suggest to FFMPEG for reading inputs.
virtual uint32_t getInputBufferLength ()
Return the input buffer length.
virtual bool isOpened ()
Is this container opened?
virtual bool isHeaderWritten ()
Has a header been successfully written?
virtual int32_t open (const char *url, Type type, IContainerFormat *pContainerFormat)
Open this container and make it ready for reading or writing.
virtual int32_t open (const char *url, Type type, IContainerFormat *pContainerFormat, bool, bool)
Open this container and make it ready for reading or writing, optionally reading as far into the container as necessary to find all streams.
virtual IContainerFormat * getContainerFormat ()
Returns the IContainerFormat object being used for this IContainer, or null if the IContainer doesn't yet know.
virtual Type getType ()
Find out the type of this container.
virtual int32_t close ()
Close the container.
virtual int32_t close (bool)
virtual int32_t getNumStreams ()
The number of streams in this container.
virtual IStream * getStream (uint32_t position)
Get the stream at the given position.
virtual IStream * addNewStream (int32_t id)
Creates a new stream in this container and returns it.
virtual int32_t readNextPacket (IPacket *packet)
Reads the next packet into the IPacket.
virtual int32_t writePacket (IPacket *packet, bool forceInterleave)
Writes the contents of the packet to the container.
virtual int32_t writePacket (IPacket *packet)
Writes the contents of the packet to the container, but make sure the packets are interleaved.
virtual int32_t writeHeader ()
Adds a header, if needed, for this container.
virtual int32_t writeTrailer ()
Adds a trailer, if needed, for this container.
AVFormatContext * getFormatContext ()
virtual int32_t queryStreamMetaData ()
Attempts to read all the meta data in this stream, potentially by reading ahead and decoding packets.
virtual int32_t seekKeyFrame (int streamIndex, int64_t timestamp, int32_t flags)
virtual int64_t getDuration ()
Gets the duration, if known, of this container.
virtual int64_t getStartTime ()
Get the starting timestamp in microseconds of the first packet of the earliest stream in this container.
virtual int64_t getFileSize ()
Get the file size in bytes of this container.
virtual int32_t getBitRate ()
Get the calculated overall bit rate of this file.
virtual int32_t setPreload (int32_t preload)
If the container has not already been opened, sets the AVFormatContext.preload property which can be useful in some circumstances such as when dealing with mpeg formats.
virtual int32_t getPreload ()
The amount container will attemtp to preload.
virtual int32_t setMaxDelay (int32_t maxdelay)
Sets the max delay for the AVFormatContext.max_delay property.
virtual int32_t getMaxDelay ()
Gets the AVFormatContext.max_delay property if possible.
virtual int32_t getNumProperties ()
Returns the total number of settable properties on this object.
virtual IProperty * getPropertyMetaData (int32_t propertyNo)
Returns the name of the numbered property.
virtual IProperty * getPropertyMetaData (const char *name)
Returns the name of the numbered property.
virtual int32_t setProperty (const char *name, const char *value)
Sets a property on this Object.
virtual int32_t setProperty (const char *name, double value)
Looks up the property 'name' and sets the value of the property to 'value'.
virtual int32_t setProperty (const char *name, int64_t value)
Looks up the property 'name' and sets the value of the property to 'value'.
virtual int32_t setProperty (const char *name, bool value)
Looks up the property 'name' and sets the value of the property to 'value'.
virtual int32_t setProperty (const char *name, IRational *value)
Looks up the property 'name' and sets the value of the property to 'value'.
virtual char * getPropertyAsString (const char *name)
Gets a property on this Object.
virtual double getPropertyAsDouble (const char *name)
Gets the value of this property, and returns as a double;.
virtual int64_t getPropertyAsLong (const char *name)
Gets the value of this property, and returns as an long;.
virtual IRational * getPropertyAsRational (const char *name)
Gets the value of this property, and returns as an IRational;.
virtual bool getPropertyAsBoolean (const char *name)
Gets the value of this property, and returns as a boolean.
virtual int32_t getFlags ()
Get the flags associated with this object.
virtual void setFlags (int32_t newFlags)
Set the flags to use with this object.
virtual bool getFlag (Flags flag)
Get the setting for the specified flag.
virtual void setFlag (Flags flag, bool value)
Set the flag.
virtual const char * getURL ()
Get the URL the IContainer was opened with.
virtual int32_t flushPackets ()
Flush all packets to output.
virtual int32_t getReadRetryCount ()
Get the number of times IContainer#readNextPacket(IPacket) will retry a read if it gets a IError.Type#ERROR_AGAIN value back.
virtual void setReadRetryCount (int32_t count)
Sets the read retry count.
virtual IContainerParameters * getParameters ()
Get the parameters that will be used when opening.
virtual void setParameters (IContainerParameters *parameters)
Set the parameters for this container.
virtual bool canStreamsBeAddedDynamically ()
Can streams be added dynamically to this container?
virtual IMetaData * getMetaData ()
Get the IMetaData for this object, or null if none.
virtual void setMetaData (IMetaData *metaData)
Set the IMetaData on this object, overriding any previous meta data.
virtual int32_t createSDPData (com::xuggle::ferry::IBuffer *buffer)
Fills the given buffer with a null-terminated ASCII set of bytes representing SDP data that is suitable for use with an RTSP-based system.
virtual int32_t setForcedAudioCodec (ICodec::ID id)
Forces the IContainer to assume all audio streams are encoded with the given audio codec when demuxing.
virtual int32_t setForcedVideoCodec (ICodec::ID id)
Forces the IContainer to assume all video streams are encoded with the given video codec when demuxing.
virtual int32_t setForcedSubtitleCodec (ICodec::ID id)
Forces the IContainer to assume all subtitle streams are encoded with the given subtitle codec when demuxing.
virtual int32_t seekKeyFrame (int32_t streamIndex, int64_t minTimeStamp, int64_t targetTimeStamp, int64_t maxTimeStamp, int32_t flags)
EXPERIMENTAL - Seeks to timestamp in the container.
Protected Member Functions
virtual ~Container ()
Container ()
Constructor & Destructor Documentation
com::xuggle::xuggler::Container::~Container () [protected, virtual]
Definition at line 71 of file Container.cpp.
References VS_LOG_TRACE.
  {
    reset();
    if (mFormatContext)
      avformat_free_context(mFormatContext);
    VS_LOG_TRACE("Destroyed container: %p", this);
  }
com::xuggle::xuggler::Container::Container () [protected]
Definition at line 55 of file Container.cpp.
References com::xuggle::xuggler::IContainerParameters::make(), and VS_LOG_TRACE.
  {
    VS_LOG_TRACE("Making container: %p", this);
    mFormatContext = avformat_alloc_context();
    if (!mFormatContext)
      throw std::bad_alloc();
    mIsOpened = false;
    mIsMetaDataQueried=false;
    mNeedTrailerWrite = false;
    mNumStreams = 0;
    mInputBufferLength = 0;
    mReadRetryCount = 1;
    mParameters = IContainerParameters::make();
  }
Member Function Documentation
int32_t com::xuggle::xuggler::Container::setInputBufferLength (uint32_t size) [virtual]
Set the buffer length Xuggler will suggest to FFMPEG for reading inputs.
If called when a IContainer is open, the call is ignored and -1 is returned.
Parameters:
size The suggested buffer size.
Returns:
size on success; <0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 97 of file Container.cpp.
References VS_LOG_WARN.
  {
    int32_t retval = -1;
    if (mIsOpened)
    {
      VS_LOG_WARN("Attempting to set input buffer length while file is opened; ignoring");
    }
    else
    {
      mInputBufferLength = size;
      retval = size;
    }
    return retval;
  }
uint32_t com::xuggle::xuggler::Container::getInputBufferLength () [virtual]
Return the input buffer length.
Returns:
The input buffer length Xuggler's told FFMPEG to assume. 0 means FFMPEG should choose it's own size (and it'll probably be 32768).
Implements com::xuggle::xuggler::IContainer.
Definition at line 113 of file Container.cpp.
  {
    return mInputBufferLength;
  }
bool com::xuggle::xuggler::Container::isOpened () [virtual]
Is this container opened?
Returns:
true if opened; false if not.
Implements com::xuggle::xuggler::IContainer.
Definition at line 119 of file Container.cpp.
Referenced by addNewStream().
  {
    return mIsOpened;
  }
bool com::xuggle::xuggler::Container::isHeaderWritten () [virtual]
Has a header been successfully written?
Returns:
true if yes, false if no.
Implements com::xuggle::xuggler::IContainer.
Definition at line 125 of file Container.cpp.
Referenced by addNewStream().
  {
    return (mIsOpened && mNeedTrailerWrite);
  }
int32_t com::xuggle::xuggler::Container::open (const char * url, Type type, IContainerFormat * pContainerFormat) [virtual]
Open this container and make it ready for reading or writing.
The caller must call close() when done, but if not, the IContainer will eventually close them later but warn to the logging system.
This just forwards to open(String, Type, IContainerFormat, boolean, boolean) passing false for aStreamsCanBeAddedDynamically, and true for aLookForAllStreams.
If the current thread is interrupted while this blocking method is running the method will return with a negative value. To check if the method exited because of an interruption pass the return value to IError#make(int) and then check IError#getType() to see if it is IError.Type#ERROR_INTERRUPTED.
Parameters:
url The resource to open; The format of this string is any url that FFMPEG supports (including additional protocols if added through the xuggler.io library).
type The type of this container.
pContainerFormat A pointer to a ContainerFormat object specifying the format of this container, or 0 (NULL) if you want us to guess.
Returns:
>= 0 on success; < 0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 131 of file Container.cpp.
  {
    return open(url, type, pContainerFormat, false, true);
  }
int32_t com::xuggle::xuggler::Container::open (const char * url, Type type, IContainerFormat * pContainerFormat, bool aStreamsCanBeAddedDynamically, bool aQueryStreamMetaData) [virtual]
Open this container and make it ready for reading or writing, optionally reading as far into the container as necessary to find all streams.
The caller must call close() when done, but if not, the IContainer will eventually close them later but warn to the logging system.
If the current thread is interrupted while this blocking method is running the method will return with a negative value. To check if the method exited because of an interruption pass the return value to IError#make(int) and then check IError#getType() to see if it is IError.Type#ERROR_INTERRUPTED.
Parameters:
url The resource to open; The format of this string is any url that FFMPEG supports (including additional protocols if added through the xuggler.io library).
type The type of this container.
pContainerFormat A pointer to a ContainerFormat object specifying the format of this container, or 0 (NULL) if you want us to guess.
aStreamsCanBeAddedDynamically If true, open() will expect that new streams can be added at any time, even after the format header has been read.
aQueryStreamMetaData If true, open() will call queryStreamMetaData() on this container, which will potentially block until it has ready enough data to find all streams in a container. If false, it will only block to read a minimal header for this container format.
Returns:
>= 0 on success; < 0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 138 of file Container.cpp.
References com::xuggle::xuggler::IContainer::READ, VS_ASSERT, com::xuggle::xuggler::IContainer::WRITE, and XUGGLER_CHECK_INTERRUPT.
  {
    int32_t retval = -1;
    // reset if an open is called before a close.
    reset();
    if (!mFormatContext)
    {
      // always reset to a new one
      mFormatContext = avformat_alloc_context();
      if (!mFormatContext)
        throw std::bad_alloc();
    }
    if (url && *url)
    {
      if (type == WRITE)
      {
        retval = openOutputURL(url, pContainerFormat,
            aStreamsCanBeAddedDynamically);
      } else if (type == READ)
      {
        retval = openInputURL(url, pContainerFormat,
            aStreamsCanBeAddedDynamically, aLookForAllStreams);
      }
      else
      {
        VS_ASSERT(false, "Invalid type for open");
        retval = -1;
      }
    }
    XUGGLER_CHECK_INTERRUPT(retval);
    return retval;
  }
IContainerFormat * com::xuggle::xuggler::Container::getContainerFormat () [virtual]
Returns the IContainerFormat object being used for this IContainer, or null if the IContainer doesn't yet know.
Returns:
the IContainerFormat object, or null.
Implements com::xuggle::xuggler::IContainer.
Definition at line 177 of file Container.cpp.
References com::xuggle::xuggler::IContainerFormat::make(), com::xuggle::xuggler::ContainerFormat::setInputFormat(), and com::xuggle::xuggler::ContainerFormat::setOutputFormat().
Referenced by writeHeader().
  {
    ContainerFormat *retval = ContainerFormat::make();
    if (retval)
    {
      if (mFormatContext)
      {
        if (mFormatContext->iformat)
          retval->setInputFormat(mFormatContext->iformat);
        if (mFormatContext->oformat)
          retval->setOutputFormat(mFormatContext->oformat);
      }
    }
    return retval;
  }
IContainer::Type com::xuggle::xuggler::Container::getType () [virtual]
Find out the type of this container.
Returns:
The Type of this container. IContainer.Type#READ if not yet opened.
Implements com::xuggle::xuggler::IContainer.
Definition at line 348 of file Container.cpp.
References com::xuggle::xuggler::IContainer::READ, and com::xuggle::xuggler::IContainer::WRITE.
Referenced by close(), flushPackets(), getMetaData(), writeHeader(), writePacket(), and writeTrailer().
  {
    return (!mFormatContext ? READ :
        (mFormatContext->oformat ? WRITE: READ));
  }
int32_t com::xuggle::xuggler::Container::close () [virtual]
Close the container.
open() must have been called first, or else an error is returned.
If the current thread is interrupted while this blocking method is running the method will return with a negative value. To check if the method exited because of an interruption pass the return value to IError#make(int) and then check IError#getType() to see if it is IError.Type#ERROR_INTERRUPTED.
If this method exits because of an interruption, all resources will be closed anyway.
Returns:
>= 0 on success; < 0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 414 of file Container.cpp.
  {
    return close(false);
  }
int32_t com::xuggle::xuggler::Container::close (bool dangling) [virtual]
Definition at line 420 of file Container.cpp.
References getType(), com::xuggle::xuggler::IContainer::READ, VS_ASSERT, VS_LOG_DEBUG, VS_LOG_ERROR, writeTrailer(), and XUGGLER_CHECK_INTERRUPT.
  {
    int32_t retval = -1;
    mMetaData.reset();
    if (mFormatContext && mIsOpened)
    {
      VS_ASSERT(mNumStreams == mStreams.size(),
          "unexpected number of streams");
      if (mNeedTrailerWrite)
      {
        if (dangling)
          // don't actually write the trailer when dangling; we could
          // block on that, which could occur inside a finalizer thread
          // or other unexpected thread
          VS_LOG_ERROR("Disposing of dangling container but could not write trailer");
        else {
          VS_LOG_DEBUG("Writing dangling trailer");
          (void) this->writeTrailer();
        }
        mNeedTrailerWrite = false;
      }
      mOpenCoders.clear();
      while(mStreams.size() > 0)
      {
        RefPointer<Stream> * stream=mStreams.back();
        VS_ASSERT(stream && *stream, "no stream?");
        if (stream && *stream) {
          (*stream)->containerClosed(this);
          delete stream;
        }
        mStreams.pop_back();
      }
      mNumStreams = 0;
      if (this->getType() == READ)
      {
        av_close_input_file(mFormatContext);
        retval = 0;
        mFormatContext = 0;
      } else
      {
        retval = avio_close(mFormatContext->pb);
        avformat_free_context(mFormatContext);
        mFormatContext = 0;
      }
      mIsOpened = false;
      mIsMetaDataQueried=false;
    }
    XUGGLER_CHECK_INTERRUPT(retval);
    return retval;
  }
int32_t com::xuggle::xuggler::Container::getNumStreams () [virtual]
The number of streams in this container.
If opened in IContainer.Type#READ mode, this will query the stream and find out how many streams are in it.
If opened in IContainer.Type#WRITE mode, this will return the number of streams the caller has added to date.
If the current thread is interrupted while this blocking method is running the method will return with a negative value. To check if the method exited because of an interruption pass the return value to IError#make(int) and then check IError#getType() to see if it is IError.Type#ERROR_INTERRUPTED.
Returns:
The number of streams in this container.
Implements com::xuggle::xuggler::IContainer.
Definition at line 355 of file Container.cpp.
References XUGGLER_CHECK_INTERRUPT.
Referenced by writeHeader().
  {
    int32_t retval = 0;
    if (mFormatContext)
    {
      if (mFormatContext->nb_streams != mNumStreams)
        setupAllInputStreams();
      retval = mFormatContext->nb_streams;
    }
    XUGGLER_CHECK_INTERRUPT(retval);
    return retval;
  }
IStream * com::xuggle::xuggler::Container::getStream (uint32_t streamIndex) [virtual]
Get the stream at the given position.
Parameters:
streamIndex the index of this stream in the container
Returns:
The stream at that position in the container, or null if none there.
Implements com::xuggle::xuggler::IContainer.
Definition at line 477 of file Container.cpp.
Referenced by readNextPacket(), and writeHeader().
  {
    Stream *retval = 0;
    if (mFormatContext)
    {
      if (mFormatContext->nb_streams != mNumStreams)
        setupAllInputStreams();
      if (position < mNumStreams)
      {
        // will acquire for caller.
        retval = (*mStreams.at(position)).get();
      }
    }
    return retval;
  }
IStream * com::xuggle::xuggler::Container::addNewStream (int32_t id) [virtual]
Creates a new stream in this container and returns it.
Parameters:
id A format-dependent id for this stream.
Returns:
A new stream.
Implements com::xuggle::xuggler::IContainer.
Definition at line 369 of file Container.cpp.
References com::xuggle::ferry::RefPointer< T >::get(), isHeaderWritten(), isOpened(), com::xuggle::xuggler::Stream::make(), com::xuggle::xuggler::IStream::OUTBOUND, VS_LOG_DEBUG, and VS_REF_RELEASE.
  {
    Stream *retval=0;
    try
    {
      if (!mFormatContext)
        throw std::runtime_error("no format context");
      if (!isOpened())
        throw std::runtime_error("attempted to add stream to "
            " unopened container");
      if (isHeaderWritten())
        throw std::runtime_error("cannot add stream after header is written"
            );
      AVStream * stream=0;
      stream = av_new_stream(mFormatContext, id);
      if (!stream)
        throw std::runtime_error("could not allocate stream");
      RefPointer<Stream>* p = new RefPointer<Stream>(
          Stream::make(this, stream, IStream::OUTBOUND)
      );
      if (!p) throw std::bad_alloc();
      if (*p)
      {
        mStreams.push_back(p);
        mNumStreams++;
        retval = p->get(); // acquire for caller
      }
      else
      {
        delete p;
        throw std::bad_alloc();
      }
    } catch (std::exception & e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
int32_t com::xuggle::xuggler::Container::readNextPacket (IPacket * packet) [virtual]
Reads the next packet into the IPacket.
This method will release any buffers currently held by this packet and allocate new ones.
If the current thread is interrupted while this blocking method is running the method will return with a negative value. To check if the method exited because of an interruption pass the return value to IError#make(int) and then check IError#getType() to see if it is IError.Type#ERROR_INTERRUPTED.
Parameters:
packet [In/Out] The packet the IContainer will read into.
Returns:
0 if successful, or <0 if not.
Implements com::xuggle::xuggler::IContainer.
Definition at line 495 of file Container.cpp.
References com::xuggle::xuggler::Packet::getAVPacket(), com::xuggle::xuggler::Packet::getDts(), com::xuggle::xuggler::Packet::getDuration(), com::xuggle::xuggler::Packet::getFlags(), com::xuggle::xuggler::Packet::getPosition(), com::xuggle::xuggler::Packet::getPts(), com::xuggle::xuggler::Packet::getSize(), getStream(), com::xuggle::xuggler::Packet::getStreamIndex(), com::xuggle::xuggler::Packet::reset(), com::xuggle::xuggler::Packet::setTimeBase(), com::xuggle::ferry::RefPointer< T >::value(), VS_LOG_TRACE, com::xuggle::xuggler::Packet::wrapAVPacket(), and XUGGLER_CHECK_INTERRUPT.
  {
    int32_t retval = -1;
    Packet* pkt = dynamic_cast<Packet*>(ipkt);
    if (mFormatContext && pkt)
    {
      AVPacket tmpPacket;
      AVPacket* packet=0;
      packet = &tmpPacket;
      av_init_packet(packet);
      pkt->reset();
      int32_t numReads=0;
      do
      {
        retval = av_read_frame(mFormatContext,
            packet);
        ++numReads;
      }
      while (retval == AVERROR(EAGAIN) &&
          (mReadRetryCount < 0 || numReads <= mReadRetryCount));
      if (retval >= 0)
        pkt->wrapAVPacket(packet);
      av_free_packet(packet);
      // Get a pointer to the wrapped packet
      packet = pkt->getAVPacket();
      // and dump it's contents
      VS_LOG_TRACE("read-packet: %lld, %lld, %d, %d, %d, %lld, %lld: %p",
          pkt->getDts(),
          pkt->getPts(),
          pkt->getFlags(),
          pkt->getStreamIndex(),
          pkt->getSize(),
          pkt->getDuration(),
          pkt->getPosition(),
          packet->data);
      // and let's try to set the packet time base if known
      if (pkt->getStreamIndex() >= 0)
      {
        RefPointer<IStream> stream = this->getStream(pkt->getStreamIndex());
        if (stream)
        {
          RefPointer<IRational> streamBase = stream->getTimeBase();
          if (streamBase)
          {
            pkt->setTimeBase(streamBase.value());
          }
        }
      }
    }
    XUGGLER_CHECK_INTERRUPT(retval);
    return retval;
  }
int32_t com::xuggle::xuggler::Container::writePacket (IPacket * packet, bool forceInterleave) [virtual]
Writes the contents of the packet to the container.
If the current thread is interrupted while this blocking method is running the method will return with a negative value. To check if the method exited because of an interruption pass the return value to IError#make(int) and then check IError#getType() to see if it is IError.Type#ERROR_INTERRUPTED.
Parameters:
packet [In] The packet to write out.
forceInterleave [In] If true, then this IContainer will make sure all packets are interleaved by DTS (even across streams in a container). If false, the IContainer won't, and it's up to the caller to interleave if necessary.
Returns:
# of bytes written if successful, or <0 if not.
Implements com::xuggle::xuggler::IContainer.
Definition at line 557 of file Container.cpp.
References com::xuggle::xuggler::Packet::getSize(), com::xuggle::xuggler::Packet::getStreamIndex(), getType(), com::xuggle::xuggler::Packet::isComplete(), com::xuggle::xuggler::IPacket::make(), com::xuggle::xuggler::Stream::stampOutputPacket(), com::xuggle::ferry::RefPointer< T >::value(), VS_LOG_ERROR, com::xuggle::xuggler::IContainer::WRITE, and XUGGLER_CHECK_INTERRUPT.
Referenced by writePacket().
  {
    int32_t retval = -1;
    Packet *pkt = dynamic_cast<Packet*>(ipkt);
    try
    {
      if (this->getType() != WRITE)
        throw std::runtime_error("cannot write packet to read only container");
      if (!mFormatContext)
        throw std::logic_error("no format context");
      if (!pkt)
        throw std::runtime_error("cannot write missing packet");
      if (!pkt->isComplete())
        throw std::runtime_error("cannot write incomplete packet");
      if (!pkt->getSize())
        throw std::runtime_error("cannot write empty packet");
      if (!mNeedTrailerWrite)
        throw std::runtime_error("container has not written header yet");
      int32_t pktIndex = pkt->getStreamIndex();
      if ((uint32_t)pktIndex >= mNumStreams)
        throw std::runtime_error("packet being written to stream that doesn't exist");
      RefPointer<Stream> *streamPtr = mStreams.at(pktIndex);
      if (!streamPtr || !*streamPtr)
        throw std::runtime_error("no stream set up for this packet");
      Stream* stream = streamPtr->value();
      // Create a new packet that wraps the input data; this
      // just copies meta-data
      RefPointer<Packet> outPacket = Packet::make(pkt, false);
      // Stamp it with the stream data
      if (stream->stampOutputPacket(outPacket.value()) <0)
        throw std::runtime_error("could not stamp output packet");
      AVPacket *packet = 0;
      packet = outPacket->getAVPacket();
      if (!packet || !packet->data)
        throw std::runtime_error("no data in packet");
      /*
      VS_LOG_DEBUG("write-packet: %lld, %lld, %d, %d, %d, %lld, %lld: %p",
          pkt->getDts(),
          pkt->getPts(),
          pkt->getFlags(),
          pkt->getStreamIndex(),
          pkt->getSize(),
          pkt->getDuration(),
          pkt->getPosition(),
          packet->data);
          */
      if (forceInterleave)
        retval =  av_interleaved_write_frame(mFormatContext, packet);
      else
        retval = av_write_frame(mFormatContext, packet);
    }
    catch (std::exception & e)
    {
      VS_LOG_ERROR("Error: %s", e.what());
      retval = -1;
    }
    XUGGLER_CHECK_INTERRUPT(retval);
    return retval;
  }
int32_t com::xuggle::xuggler::Container::writePacket (IPacket * packet) [virtual]
Writes the contents of the packet to the container, but make sure the packets are interleaved.
This means the IContainer may have to queue up packets from one stream while waiting for packets from another.
If the current thread is interrupted while this blocking method is running the method will return with a negative value. To check if the method exited because of an interruption pass the return value to IError#make(int) and then check IError#getType() to see if it is IError.Type#ERROR_INTERRUPTED.
Parameters:
packet [In] The packet to write out.
Returns:
# of bytes written if successful, or <0 if not.
Implements com::xuggle::xuggler::IContainer.
Definition at line 552 of file Container.cpp.
References writePacket().
  {
    return writePacket(ipkt, true);
  }
int32_t com::xuggle::xuggler::Container::writeHeader () [virtual]
Adds a header, if needed, for this container.
Call this AFTER you've added all streams you want to add, opened all IStreamCoders for those streams (with proper configuration) and before you write the first frame. If you attempt to write a header but haven't opened all codecs, this method will log a warning, and your output file will likely be corrupt.
If the current thread is interrupted while this blocking method is running the method will return with a negative value. To check if the method exited because of an interruption pass the return value to IError#make(int) and then check IError#getType() to see if it is IError.Type#ERROR_INTERRUPTED.
Returns:
0 if successful. < 0 if not. Always -1 if this is a READ container.
Implements com::xuggle::xuggler::IContainer.
Definition at line 631 of file Container.cpp.
References com::xuggle::xuggler::ContainerParameters::getAVParameters(), getContainerFormat(), getNumStreams(), getStream(), getType(), VS_LOG_ERROR, VS_LOG_TRACE, com::xuggle::xuggler::IContainer::WRITE, and XUGGLER_CHECK_INTERRUPT.
  {
    int32_t retval = -1;
    try {
      if (this->getType() != WRITE)
        throw std::runtime_error("cannot write packet to read only container");
      if (!mFormatContext)
        throw std::runtime_error("no format context allocated");
#ifdef VS_DEBUG
      // for shits and giggles, dump the ffmpeg output
      // dump_format(mFormatContext, 0, (mFormatContext ? mFormatContext->filename :0), 1);
#endif // VS_DEBUG
      // This checks to make sure that parameters are set correctly.
      AVFormatParameters* params = 0;
      ContainerParameters* cParams = dynamic_cast<ContainerParameters*>(mParameters.value());
      if (cParams)
        params = cParams->getAVParameters();
      retval = av_set_parameters(mFormatContext, params);
      if (retval < 0)
        throw std::runtime_error("incorrect parameters set on container");
      // now we're going to walk through and record each open stream coder.
      // this is needed to catch a potential error on writeTrailer().
      mOpenCoders.clear();
      int numStreams = getNumStreams();
      if (numStreams < 0 &&
          !(mFormatContext->ctx_flags & AVFMTCTX_NOHEADER))
        throw std::runtime_error("no streams added to container");
      if (numStreams == 0)
      {
        RefPointer<IContainerFormat> format = getContainerFormat();
        if (format)
        {
          const char *shortName = format->getOutputFormatShortName();
          if (shortName && !strcmp(shortName, "mp3"))
            throw std::runtime_error("no streams added to mp3 container");
        }
      }
      for(int i = 0; i < numStreams; i++)
      {
        RefPointer<IStream> stream = this->getStream(i);
        if (stream)
        {
          RefPointer<IStreamCoder> coder = stream->getStreamCoder();
          if (coder)
          {
            if (coder->isOpen())
              // add to our open list
              mOpenCoders.push_back(coder);
            else
              VS_LOG_TRACE("writing Header for container, but at least one codec (%d) is not opened first", i);
          }
        }
      }
      retval = av_write_header(mFormatContext);
      if (retval < 0)
        throw std::runtime_error("could not write header for container");
      // force a flush.
      avio_flush(mFormatContext->pb);
      // and remember that a writeTrailer is needed
      mNeedTrailerWrite = true;
    }
    catch (std::exception & e)
    {
      VS_LOG_ERROR("Error: %s", e.what());
      retval = -1;
    }
    XUGGLER_CHECK_INTERRUPT(retval);
    return retval;
  }
int32_t com::xuggle::xuggler::Container::writeTrailer () [virtual]
Adds a trailer, if needed, for this container.
Call this AFTER you've written all data you're going to write to this container but BEFORE you call IStreamCoder#close() on your IStreamCoder objects.
You must call writeHeader() before you call this (and if you don't, the IContainer will warn loudly and not actually write the trailer).
If you have closed any of the IStreamCoder objects that were open when you called writeHeader(), then this method will fail.
If the current thread is interrupted while this blocking method is running the method will return with a negative value. To check if the method exited because of an interruption pass the return value to IError#make(int) and then check IError#getType() to see if it is IError.Type#ERROR_INTERRUPTED.
Returns:
0 if successful. < 0 if not. Always <0 if this is a READ container.
Implements com::xuggle::xuggler::IContainer.
Definition at line 708 of file Container.cpp.
References getType(), VS_LOG_ERROR, VS_LOG_WARN, com::xuggle::xuggler::IContainer::WRITE, and XUGGLER_CHECK_INTERRUPT.
Referenced by close().
  {
    int32_t retval = -1;
    try
    {
      if (this->getType() != WRITE)
        throw std::runtime_error("cannot write packet to read only container");
      if (!mFormatContext)
        throw std::runtime_error("no format context allocated");
      if (mNeedTrailerWrite)
      {
        while(mOpenCoders.size()>0)
        {
          RefPointer<IStreamCoder> coder = mOpenCoders.front();
          mOpenCoders.pop_front();
          if (!coder->isOpen())
          {
            mOpenCoders.clear();
            throw std::runtime_error("attempt to write trailer, but at least one used codec already closed");
          }
        }
        retval = av_write_trailer(mFormatContext);
        if (retval == 0)
        {
          avio_flush(mFormatContext->pb);
        }
      } else {
        VS_LOG_WARN("writeTrailer() with no matching call to writeHeader()");
      }
    }
    catch (std::exception & e)
    {
      VS_LOG_ERROR("Error: %s", e.what());
      retval = -1;
    }
    // regardless of whether or not the write trailer succeeded, since
    // an attempt has occurred, we shouldn't call it twice.
    mNeedTrailerWrite = false;
    XUGGLER_CHECK_INTERRUPT(retval);
    return retval;
  }
AVFormatContext * com::xuggle::xuggler::Container::getFormatContext ()
Definition at line 91 of file Container.cpp.
  {
    return mFormatContext;
  }
int32_t com::xuggle::xuggler::Container::queryStreamMetaData () [virtual]
Attempts to read all the meta data in this stream, potentially by reading ahead and decoding packets.
Any packets this method reads ahead will be cached and correctly returned when you read packets, but this method can be non-blocking potentially until end of container to get all meta data. Take care when you call it.
After this method is called, other meta data methods like getDuration() should work.
If the current thread is interrupted while this blocking method is running the method will return with a negative value. To check if the method exited because of an interruption pass the return value to IError#make(int) and then check IError#getType() to see if it is IError.Type#ERROR_INTERRUPTED.
Returns:
>= 0 on success; <0 on failure.
Implements com::xuggle::xuggler::IContainer.
Definition at line 753 of file Container.cpp.
References VS_LOG_WARN, and XUGGLER_CHECK_INTERRUPT.
Referenced by getBitRate(), getDuration(), getFileSize(), and getStartTime().
  {
    int retval = -1;
    if (mIsOpened)
    {
      if (!mIsMetaDataQueried)
      {
        retval = av_find_stream_info(mFormatContext);
        // for shits and giggles, dump the ffmpeg output
        // dump_format(mFormatContext, 0, (mFormatContext ? mFormatContext->filename :0), 0);
        mIsMetaDataQueried = true;
      } else {
        retval = 0;
      }
      if (retval >= 0 && mFormatContext->nb_streams > 0)
      {
        setupAllInputStreams();
      } else {
        VS_LOG_WARN("Could not find streams in input container");
      }
    }
    else
    {
      VS_LOG_WARN("Attempt to queryStreamMetaData but container is not open");
    }
    XUGGLER_CHECK_INTERRUPT(retval);
    return retval;
  }
virtual int32_t com::xuggle::xuggler::Container::seekKeyFrame (int streamIndex, int64_t timestamp, int32_t flags) [virtual]
int64_t com::xuggle::xuggler::Container::getDuration () [virtual]
Gets the duration, if known, of this container.
This will only work for non-streamable containers where IContainer can calculate the container size.
Returns:
The duration, or Global#NO_PTS if not known.
Implements com::xuggle::xuggler::IContainer.
Definition at line 831 of file Container.cpp.
References com::xuggle::xuggler::Global::NO_PTS, and queryStreamMetaData().
  {
    int64_t retval = Global::NO_PTS;
    queryStreamMetaData();
    if (mFormatContext)
      retval = mFormatContext->duration;
    return retval;
  }
int64_t com::xuggle::xuggler::Container::getStartTime () [virtual]
Get the starting timestamp in microseconds of the first packet of the earliest stream in this container.
This will only return value values either either (a) for non-streamable containers where IContainer can calculate the container size or (b) after IContainer has actually read the first packet from a streamable source.
Returns:
The starting timestamp in microseconds, or Global#NO_PTS if not known.
Implements com::xuggle::xuggler::IContainer.
Definition at line 841 of file Container.cpp.
References com::xuggle::xuggler::Global::NO_PTS, and queryStreamMetaData().
  {
    int64_t retval = Global::NO_PTS;
    queryStreamMetaData();
    if (mFormatContext)
      retval = mFormatContext->start_time;
    return retval;
  }
int64_t com::xuggle::xuggler::Container::getFileSize () [virtual]
Get the file size in bytes of this container.
This will only return a valid value if the container is non-streamed and supports seek.
Returns:
The file size in bytes, or <0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 851 of file Container.cpp.
References queryStreamMetaData().
  {
    int64_t retval = -1;
    queryStreamMetaData();
    if (mFormatContext)
      retval = mFormatContext->file_size;
    return retval;
  }
int32_t com::xuggle::xuggler::Container::getBitRate () [virtual]
Get the calculated overall bit rate of this file.
This will only return a valid value if the container is non-streamed and supports seek.
Returns:
The overall bit rate in bytes per second, or <0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 861 of file Container.cpp.
References queryStreamMetaData().
  {
    int32_t retval = -1;
    queryStreamMetaData();
    if (mFormatContext)
      retval = mFormatContext->bit_rate;
    return retval;
  }
int32_t com::xuggle::xuggler::Container::setPreload (int32_t preload) [virtual]
If the container has not already been opened, sets the AVFormatContext.preload property which can be useful in some circumstances such as when dealing with mpeg formats.
Parameters:
preload amount to preload
Returns:
>= 0 on success, error code otherwise
Since:
4.0
Implements com::xuggle::xuggler::IContainer.
Definition at line 871 of file Container.cpp.
References VS_LOG_WARN.
  {
    int32_t retval = -1;
    if (mIsOpened || !mFormatContext)
    {
      VS_LOG_WARN("Attempting to set preload while file is opened; ignoring");
    }
    else
    {
      mFormatContext->preload = preload;
      retval = preload;
    }
    return retval;
  }
int32_t com::xuggle::xuggler::Container::getPreload () [virtual]
The amount container will attemtp to preload.
Returns:
The amount to preload, error code otherwise.
Implements com::xuggle::xuggler::IContainer.
Definition at line 887 of file Container.cpp.
  {
    int32_t retval = -1;
    if (mFormatContext)
      retval = mFormatContext->preload;
    return retval;
  }
int32_t com::xuggle::xuggler::Container::setMaxDelay (int32_t maxdelay) [virtual]
Sets the max delay for the AVFormatContext.max_delay property.
Parameters:
maxdelay maximum delay for container
Returns:
>= 0 on success, error code otherwise
Since:
4.0
Implements com::xuggle::xuggler::IContainer.
Definition at line 896 of file Container.cpp.
References VS_LOG_WARN.
  {
    int32_t retval = -1;
    if (mIsOpened || !mFormatContext)
    {
      VS_LOG_WARN("Attempting to set max delay while file is opened; ignoring");
    }
    else
    {
      mFormatContext->max_delay = maxdelay;
      retval = maxdelay;
    }
    return retval;
  }
int32_t com::xuggle::xuggler::Container::getMaxDelay () [virtual]
Gets the AVFormatContext.max_delay property if possible.
Returns:
The max delay, error code otherwise.
Since:
4.0
Implements com::xuggle::xuggler::IContainer.
Definition at line 912 of file Container.cpp.
  {
    int32_t retval = -1;
    if (mFormatContext)
      retval = mFormatContext->max_delay;
    return retval;
  }
int32_t com::xuggle::xuggler::Container::getNumProperties () [virtual]
Returns the total number of settable properties on this object.
Returns:
total number of options (not including constant definitions)
Implements com::xuggle::xuggler::IContainer.
Definition at line 921 of file Container.cpp.
References com::xuggle::xuggler::Property::getNumProperties().
  {
    return Property::getNumProperties(mFormatContext);
  }
IProperty * com::xuggle::xuggler::Container::getPropertyMetaData (int32_t propertyNo) [virtual]
Returns the name of the numbered property.
Parameters:
propertyNo The property number in the options list.
Returns:
an IProperty value for this properties meta-data
Implements com::xuggle::xuggler::IContainer.
Definition at line 927 of file Container.cpp.
References com::xuggle::xuggler::Property::getPropertyMetaData().
  {
    return Property::getPropertyMetaData(mFormatContext, propertyNo);
  }
IProperty * com::xuggle::xuggler::Container::getPropertyMetaData (const char * name) [virtual]
Returns the name of the numbered property.
Parameters:
name The property name.
Returns:
an IProperty value for this properties meta-data
Implements com::xuggle::xuggler::IContainer.
Definition at line 933 of file Container.cpp.
References com::xuggle::xuggler::Property::getPropertyMetaData().
  {
    return Property::getPropertyMetaData(mFormatContext, name);
  }
int32_t com::xuggle::xuggler::Container::setProperty (const char * name, const char * value) [virtual]
Sets a property on this Object.
All AVOptions supported by the underlying AVClass are supported.
Parameters:
name The property name. For example "b" for bit-rate.
value The value of the property.
Returns:
>= 0 if the property was successfully set; <0 on error
Implements com::xuggle::xuggler::IContainer.
Definition at line 939 of file Container.cpp.
References com::xuggle::xuggler::Property::setProperty().
  {
    return Property::setProperty(mFormatContext, aName, aValue);
  }
int32_t com::xuggle::xuggler::Container::setProperty (const char * name, double value) [virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 945 of file Container.cpp.
References com::xuggle::xuggler::Property::setProperty().
  {
    return Property::setProperty(mFormatContext, aName, aValue);
  }
int32_t com::xuggle::xuggler::Container::setProperty (const char * name, int64_t value) [virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 951 of file Container.cpp.
References com::xuggle::xuggler::Property::setProperty().
  {
    return Property::setProperty(mFormatContext, aName, aValue);
  }
int32_t com::xuggle::xuggler::Container::setProperty (const char * name, bool value) [virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 957 of file Container.cpp.
References com::xuggle::xuggler::Property::setProperty().
  {
    return Property::setProperty(mFormatContext, aName, aValue);
  }
int32_t com::xuggle::xuggler::Container::setProperty (const char * name, IRational * value) [virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 964 of file Container.cpp.
References com::xuggle::xuggler::Property::setProperty().
  {
    return Property::setProperty(mFormatContext, aName, aValue);
  }
char * com::xuggle::xuggler::Container::getPropertyAsString (const char * name) [virtual]
Gets a property on this Object.
Note for C++ callers; you must free the returned array with delete[] in order to avoid a memory leak. If you call from Java or any other language, you don't need to worry about this.
Parameters:
name property name
Returns:
an string copy of the option value, or null if the option doesn't exist.
Implements com::xuggle::xuggler::IContainer.
Definition at line 971 of file Container.cpp.
References com::xuggle::xuggler::Property::getPropertyAsString().
  {
    return Property::getPropertyAsString(mFormatContext, aName);
  }
double com::xuggle::xuggler::Container::getPropertyAsDouble (const char * name) [virtual]
Gets the value of this property, and returns as a double;.
Parameters:
name name of option
Returns:
double value of property, or 0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 977 of file Container.cpp.
References com::xuggle::xuggler::Property::getPropertyAsDouble().
  {
    return Property::getPropertyAsDouble(mFormatContext, aName);
  }
int64_t com::xuggle::xuggler::Container::getPropertyAsLong (const char * name) [virtual]
Gets the value of this property, and returns as an long;.
Parameters:
name name of option
Returns:
long value of property, or 0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 983 of file Container.cpp.
References com::xuggle::xuggler::Property::getPropertyAsLong().
  {
    return Property::getPropertyAsLong(mFormatContext, aName);
  }
IRational * com::xuggle::xuggler::Container::getPropertyAsRational (const char * name) [virtual]
Gets the value of this property, and returns as an IRational;.
Parameters:
name name of option
Returns:
long value of property, or 0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 989 of file Container.cpp.
References com::xuggle::xuggler::Property::getPropertyAsRational().
  {
    return Property::getPropertyAsRational(mFormatContext, aName);
  }
bool com::xuggle::xuggler::Container::getPropertyAsBoolean (const char * name) [virtual]
Gets the value of this property, and returns as a boolean.
Parameters:
name name of option
Returns:
boolean value of property, or false on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 995 of file Container.cpp.
References com::xuggle::xuggler::Property::getPropertyAsBoolean().
  {
    return Property::getPropertyAsBoolean(mFormatContext, aName);
  }
int32_t com::xuggle::xuggler::Container::getFlags () [virtual]
Get the flags associated with this object.
Returns:
The (compacted) value of all flags set.
Implements com::xuggle::xuggler::IContainer.
Definition at line 1001 of file Container.cpp.
  {
    return (mFormatContext ? mFormatContext->flags: 0);
  }
void com::xuggle::xuggler::Container::setFlags (int32_t newFlags) [virtual]
Set the flags to use with this object.
All values must be ORed (|) together.
See also:
Flags
Parameters:
newFlags The new set flags for this codec.
Implements com::xuggle::xuggler::IContainer.
Definition at line 1007 of file Container.cpp.
  {
    if (mFormatContext)
      mFormatContext->flags = newFlags;
  }
bool com::xuggle::xuggler::Container::getFlag (Flags flag) [virtual]
Get the setting for the specified flag.
Parameters:
flag The flag you want to find the setting for
Returns:
0 for false; non-zero for true
Implements com::xuggle::xuggler::IContainer.
Definition at line 1014 of file Container.cpp.
  {
    bool result = false;
    if (mFormatContext)
      result = mFormatContext->flags& flag;
    return result;
  }
void com::xuggle::xuggler::Container::setFlag (Flags flag, bool value) [virtual]
Set the flag.
Parameters:
flag The flag to set
value The value to set it to (true or false)
Implements com::xuggle::xuggler::IContainer.
Definition at line 1023 of file Container.cpp.
  {
    if (mFormatContext)
    {
      if (value)
      {
        mFormatContext->flags |= flag;
      }
      else
      {
        mFormatContext->flags &= (~flag);
      }
    }
  }
const char * com::xuggle::xuggler::Container::getURL () [virtual]
Get the URL the IContainer was opened with.
May return null if unknown.
Returns:
the URL opened, or null.
Implements com::xuggle::xuggler::IContainer.
Definition at line 1040 of file Container.cpp.
  {
    return mFormatContext && *mFormatContext->filename ? mFormatContext->filename : 0;
  }
int32_t com::xuggle::xuggler::Container::flushPackets () [virtual]
Flush all packets to output.
Will only work on IContainer.Type#WRITE containers.
If the current thread is interrupted while this blocking method is running the method will return with a negative value. To check if the method exited because of an interruption pass the return value to IError#make(int) and then check IError#getType() to see if it is IError.Type#ERROR_INTERRUPTED.
Returns:
>= 0 on success; <0 on error
Implements com::xuggle::xuggler::IContainer.
Definition at line 1046 of file Container.cpp.
References getType(), VS_LOG_ERROR, com::xuggle::xuggler::IContainer::WRITE, and XUGGLER_CHECK_INTERRUPT.
  {
    int32_t retval = -1;
    try
    {
      if (this->getType() != WRITE)
        throw std::runtime_error("cannot write packet to read only container");
      if (!mFormatContext)
        throw std::runtime_error("no format context allocated");
      // Do the flush
      avio_flush(mFormatContext->pb);
      retval = 0;
    }
    catch (std::exception & e)
    {
      VS_LOG_ERROR("Error: %s", e.what());
      retval = -1;
    }
    XUGGLER_CHECK_INTERRUPT(retval);
    return retval;
  }
int32_t com::xuggle::xuggler::Container::getReadRetryCount () [virtual]
Get the number of times IContainer#readNextPacket(IPacket) will retry a read if it gets a IError.Type#ERROR_AGAIN value back.
Defaults to 1 times. <0 means it will keep retrying indefinitely.
Returns:
the read retry count
Implements com::xuggle::xuggler::IContainer.
Definition at line 1071 of file Container.cpp.
  {
    return mReadRetryCount;
  }
void com::xuggle::xuggler::Container::setReadRetryCount (int32_t count) [virtual]
Sets the read retry count.
See also:
getReadRetryCount()
Parameters:
count The read retry count. <0 means keep trying.
Implements com::xuggle::xuggler::IContainer.
Definition at line 1077 of file Container.cpp.
  {
    mReadRetryCount = aCount;
  }
IContainerParameters * com::xuggle::xuggler::Container::getParameters () [virtual]
Get the parameters that will be used when opening.
See also:
setParameters(IContainerParameters)
Returns:
The parameters
Implements com::xuggle::xuggler::IContainer.
Definition at line 1083 of file Container.cpp.
  {
    return mParameters.get();
  }
void com::xuggle::xuggler::Container::setParameters (IContainerParameters * parameters) [virtual]
Set the parameters for this container.
Normally this is not required, but if you're opening something like a webcam, you need to specify to the IContainer parameters such as a time base, width, height, etc.
Parameters:
parameters The parameters to set. Ignored if null.
Implements com::xuggle::xuggler::IContainer.
Definition at line 1089 of file Container.cpp.
  {
    if (params)
      mParameters.reset(params, true);
  }
bool com::xuggle::xuggler::Container::canStreamsBeAddedDynamically () [virtual]
Can streams be added dynamically to this container?
Returns:
true if streams can be added dynamically
Implements com::xuggle::xuggler::IContainer.
Definition at line 1096 of file Container.cpp.
  {
    if (mFormatContext)
      return mFormatContext->ctx_flags & AVFMTCTX_NOHEADER;
    return false;
  }
IMetaData * com::xuggle::xuggler::Container::getMetaData () [virtual]
Get the IMetaData for this object, or null if none.
If the IContainer or IStream object that this IMetaData came from was opened for reading, then changes via IMetaData#setValue(String, String) will have no effect on the underlying media.
If the IContainer or IStream object that this IMetaData came from was opened for writing, then changes via IMetaData#setValue(String, String) will have no effect after IContainer#writeHeader() is called.
Returns:
the IMetaData.
Implements com::xuggle::xuggler::IContainer.
Definition at line 1104 of file Container.cpp.
References getType(), com::xuggle::xuggler::IMetaData::make(), and com::xuggle::xuggler::IContainer::WRITE.
Referenced by setMetaData().
  {
    if (!mMetaData && mFormatContext)
    {
      if (this->getType() == WRITE)
        mMetaData = MetaData::make(&mFormatContext->metadata);
      else
        // make a read-only copy so when libav deletes the
        // input version we don't delete our copy
        mMetaData = MetaData::make(mFormatContext->metadata);
    }
    return mMetaData.get();
  }
void com::xuggle::xuggler::Container::setMetaData (IMetaData * data) [virtual]
Set the IMetaData on this object, overriding any previous meta data.
You should call this method on writable containers and before you call IContainer#writeHeader, as it probably won't do anything after that.
See also:
getMetaData()
Implements com::xuggle::xuggler::IContainer.
Definition at line 1118 of file Container.cpp.
References com::xuggle::xuggler::MetaData::copy(), getMetaData(), and com::xuggle::ferry::RefCounted::release().
  {
    MetaData* data = dynamic_cast<MetaData*>(getMetaData());
    if (data) {
      data->copy(copy);
      // release for the get above
      data->release();
    }
    return;
  }
int32_t com::xuggle::xuggler::Container::createSDPData (com::xuggle::ferry::IBuffer * buffer) [virtual]
Fills the given buffer with a null-terminated ASCII set of bytes representing SDP data that is suitable for use with an RTSP-based system.
This method only works if Xuggler is linking against a version of FFmpeg that supports RTSP.
Parameters:
buffer the com.xuggle.ferry.IBuffer object to fill with data.
Returns:
the number of bytes written, including the terminating 0 byte, or < 0 on error.
Implements com::xuggle::xuggler::IContainer.
Definition at line 1130 of file Container.cpp.
References com::xuggle::ferry::IBuffer::getBufferSize(), com::xuggle::ferry::IBuffer::getBytes(), and VS_LOG_INFO.
  {
    if (!mFormatContext)
      return -1;
    if (!buffer)
      return -1;
    int32_t bufSize = buffer->getBufferSize();
    if (bufSize <= 0)
      return -1;
    char* bytes = static_cast<char*>(buffer->getBytes(0, bufSize));
    if (!bytes)
      return -1;
    bytes[0] = 0;
    // null terminate the buffer to ensure strlen below doesn't
    // overrun
    bytes[bufSize-1]=0;
    int32_t ret = av_sdp_create(&mFormatContext, 1, bytes, bufSize-1);
    if (ret < 0)
    {
      VS_LOG_INFO("Could not create SDP file: %d", ret);
      return ret;
    }
    // Otherwise, we have to figure out the length, including the
    // terminating null
    ret = strlen(bytes)+1;
    return ret;
  }
int32_t com::xuggle::xuggler::Container::setForcedAudioCodec (ICodec::ID id) [virtual]
Forces the IContainer to assume all audio streams are encoded with the given audio codec when demuxing.
Parameters:
id The codec id
Returns:
< 0 on error (e.g. not an audio codec); >= 0 on success.
Since:
3.3
Implements com::xuggle::xuggler::IContainer.
Definition at line 1163 of file Container.cpp.
References com::xuggle::xuggler::ICodec::CODEC_ID_NONE, com::xuggle::xuggler::ICodec::CODEC_TYPE_AUDIO, and com::xuggle::xuggler::ICodec::findDecodingCodec().
  {
    int32_t retval=-1;
    if (mFormatContext && id != ICodec::CODEC_ID_NONE)
    {
      RefPointer<ICodec> codec = ICodec::findDecodingCodec(id);
      if (codec && codec->getType() == ICodec::CODEC_TYPE_AUDIO)
        mFormatContext->audio_codec_id = (enum CodecID) id;
    }
    return retval;
  }
int32_t com::xuggle::xuggler::Container::setForcedVideoCodec (ICodec::ID id) [virtual]
Forces the IContainer to assume all video streams are encoded with the given video codec when demuxing.
Parameters:
id The codec id
Returns:
< 0 on error (e.g. not an video codec); >= 0 on success.
Since:
3.3
Implements com::xuggle::xuggler::IContainer.
Definition at line 1176 of file Container.cpp.
References com::xuggle::xuggler::ICodec::CODEC_ID_NONE, com::xuggle::xuggler::ICodec::CODEC_TYPE_VIDEO, and com::xuggle::xuggler::ICodec::findDecodingCodec().
  {
    int32_t retval=-1;
    if (mFormatContext && id != ICodec::CODEC_ID_NONE)
    {
      RefPointer<ICodec> codec = ICodec::findDecodingCodec(id);
      if (codec && codec->getType() == ICodec::CODEC_TYPE_VIDEO)
        mFormatContext->video_codec_id = (enum CodecID) id;
    }
    return retval;
  }
int32_t com::xuggle::xuggler::Container::setForcedSubtitleCodec (ICodec::ID id) [virtual]
Forces the IContainer to assume all subtitle streams are encoded with the given subtitle codec when demuxing.
Parameters:
id The codec id
Returns:
< 0 on error (e.g. not an subtitle codec); >= 0 on success.
Since:
3.3
Implements com::xuggle::xuggler::IContainer.
Definition at line 1189 of file Container.cpp.
References com::xuggle::xuggler::ICodec::CODEC_ID_NONE, com::xuggle::xuggler::ICodec::CODEC_TYPE_SUBTITLE, and com::xuggle::xuggler::ICodec::findDecodingCodec().
  {
    int32_t retval=-1;
    if (mFormatContext && id != ICodec::CODEC_ID_NONE)
    {
      RefPointer<ICodec> codec = ICodec::findDecodingCodec(id);
      if (codec && codec->getType() == ICodec::CODEC_TYPE_SUBTITLE)
        mFormatContext->subtitle_codec_id = (enum CodecID) id;
    }
    return retval;
  }
int32_t com::xuggle::xuggler::Container::seekKeyFrame (int32_t streamIndex, int64_t minTimeStamp, int64_t targetTimeStamp, int64_t maxTimeStamp, int32_t flags) [virtual]
EXPERIMENTAL - Seeks to timestamp in the container.
Seeking will be done so that the point from which all active streams can be presented successfully will be closest to targetTimeStamp and within minTimeStamp/maxTimeStamp.
If flags contain SEEK_FLAG_BYTE, then all time stamps are in bytes and are the file position (this may not be supported by all demuxers). If flags contain SEEK_FLAG_FRAME, then all time stamps are in frames in the stream with streamIndex (this may not be supported by all demuxers). Otherwise all time stamps are in units of the stream selected by stream_index or if stream_index is -1, in microseconds. If flags contain SEEK_FLAG_ANY, then non-keyframes are treated as keyframes (this may not be supported by all demuxers). If flags contain SEEK_FLAG_BACKWARDS, then we will attempt to search backwards in the container (this may not be supported by all demuxers and file protocols).
This is part of the new seek API which is still under construction. It may change in future Xuggler versions.
Parameters:
streamIndex index of the stream which is used as time base reference
minTimeStamp smallest acceptable time stamp.
targetTimeStamp target time stamp.
maxTimeStamp largest acceptable time stamp.
flags A bitmask of the SEEK_FLAG_* flags, or 0 to turn all flags off.
Returns:
>=0 on success, error code otherwise
Since:
3.4
Implements com::xuggle::xuggler::IContainer.
Definition at line 805 of file Container.cpp.
References VS_LOG_WARN, and XUGGLER_CHECK_INTERRUPT.
  {
    int32_t retval = -1;
    if (mIsOpened)
    {
      if (streamIndex >= (int32_t)mNumStreams)
        VS_LOG_WARN("Attempt to seek on streamIndex %d but only %d streams known about in container",
            streamIndex, mNumStreams);
      else
        retval = avformat_seek_file(mFormatContext, streamIndex,
            minTimeStamp,
            targetTimeStamp,
            maxTimeStamp,
            flags);
    }
    else
    {
      VS_LOG_WARN("Attempt to seekKeyFrame but container is not open");
    }
    XUGGLER_CHECK_INTERRUPT(retval);
    return retval;
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/Container.h
csrc/com/xuggle/xuggler/Container.cpp