Xuggle: com::xuggle::xuggler::IMediaData Class Reference
com::xuggle::xuggler::IMediaData Class Reference
#include <IMediaData.h>
Detailed Description
The parent class of all media objects than can be gotten from an IStream.
Definition at line 33 of file IMediaData.h.
Public Member Functions
virtual int64_t getTimeStamp ()=0
Get the time stamp of this object in getTimeBase() units.
virtual void setTimeStamp (int64_t aTimeStamp)=0
Set the time stamp for this object in getTimeBase() units.
virtual IRational * getTimeBase ()=0
Get the time base that time stamps of this object are represented in.
virtual void setTimeBase (IRational *aBase)=0
Set the time base that time stamps of this object are represented in.
virtual
com::xuggle::ferry::IBuffer * getData ()=0
Get any underlying raw data available for this object.
virtual int32_t getSize ()=0
Get the size in bytes of the raw data available for this object.
virtual bool isKey ()=0
Is this object a key object? i.e.
virtual void setData (com::xuggle::ferry::IBuffer *buffer)=0
Sets the underlying buffer used by this object.
Protected Member Functions
IMediaData ()
virtual ~IMediaData ()
Constructor & Destructor Documentation
com::xuggle::xuggler::IMediaData::IMediaData () [protected]
Definition at line 24 of file IMediaData.cpp.
{
}
com::xuggle::xuggler::IMediaData::~IMediaData () [protected, virtual]
Definition at line 28 of file IMediaData.cpp.
{
}
Member Function Documentation
virtual int64_t com::xuggle::xuggler::IMediaData::getTimeStamp () [pure virtual]
Get the time stamp of this object in getTimeBase() units.
Returns:
the time stamp
Implemented in com::xuggle::xuggler::AudioSamples, com::xuggle::xuggler::MediaDataWrapper, com::xuggle::xuggler::Packet, and com::xuggle::xuggler::VideoPicture.
Referenced by com::xuggle::xuggler::MediaDataWrapper::wrap().
virtual void com::xuggle::xuggler::IMediaData::setTimeStamp (int64_t aTimeStamp) [pure virtual]
Set the time stamp for this object in getTimeBase() units.
Parameters:
aTimeStamp The time stamp
Implemented in com::xuggle::xuggler::AudioSamples, com::xuggle::xuggler::MediaDataWrapper, com::xuggle::xuggler::Packet, and com::xuggle::xuggler::VideoPicture.
virtual IRational* com::xuggle::xuggler::IMediaData::getTimeBase () [pure virtual]
Get the time base that time stamps of this object are represented in.
Caller must release the returned value.
Returns:
the time base.
Implemented in com::xuggle::xuggler::AudioSamples, com::xuggle::xuggler::MediaDataWrapper, com::xuggle::xuggler::Packet, and com::xuggle::xuggler::VideoPicture.
Referenced by com::xuggle::xuggler::Stream::stampOutputPacket(), and com::xuggle::xuggler::MediaDataWrapper::wrap().
virtual void com::xuggle::xuggler::IMediaData::setTimeBase (IRational * aBase) [pure virtual]
Set the time base that time stamps of this object are represented in.
Parameters:
aBase the new time base. If null an exception is thrown.
Implemented in com::xuggle::xuggler::AudioSamples, com::xuggle::xuggler::MediaDataWrapper, com::xuggle::xuggler::Packet, and com::xuggle::xuggler::VideoPicture.
Referenced by com::xuggle::xuggler::Stream::stampOutputPacket().
virtual com::xuggle::ferry::IBuffer* com::xuggle::xuggler::IMediaData::getData () [pure virtual]
Get any underlying raw data available for this object.
Returns:
The raw data, or null if not accessible.
Implemented in com::xuggle::xuggler::AudioSamples, com::xuggle::xuggler::MediaDataWrapper, com::xuggle::xuggler::Packet, and com::xuggle::xuggler::VideoPicture.
Referenced by com::xuggle::xuggler::IPixelFormat::getYUV420PPixel(), and com::xuggle::xuggler::IPixelFormat::setYUV420PPixel().
virtual int32_t com::xuggle::xuggler::IMediaData::getSize () [pure virtual]
Get the size in bytes of the raw data available for this object.
Returns:
the size in bytes, or -1 if it cannot be computed.
Implemented in com::xuggle::xuggler::AudioSamples, com::xuggle::xuggler::IPacket, com::xuggle::xuggler::IVideoPicture, com::xuggle::xuggler::MediaDataWrapper, com::xuggle::xuggler::Packet, and com::xuggle::xuggler::VideoPicture.
virtual bool com::xuggle::xuggler::IMediaData::isKey () [pure virtual]
Is this object a key object? i.e.
it can be interpreted without needing any other media objects
Returns:
true if it's a key, false if not
Implemented in com::xuggle::xuggler::AudioSamples, com::xuggle::xuggler::MediaDataWrapper, com::xuggle::xuggler::Packet, and com::xuggle::xuggler::VideoPicture.
Referenced by com::xuggle::xuggler::MediaDataWrapper::wrap().
virtual void com::xuggle::xuggler::IMediaData::setData (com::xuggle::ferry::IBuffer * buffer) [pure virtual]
Sets the underlying buffer used by this object.
This is an advanced method and is not recommended for use by those who don't fully understand how IBuffers work. Implementations of IMediaData may behave in undefined ways if the buffer you pass in is not big enough for what you ask them to do (e.g. they may discard your buffer and allocate a larger one if they need more space). It is up to the caller to ensure the buffer passed in is large enough, and is not simultaneously in use by another part of the system.
Parameters:
buffer The buffer to set. If null, this method is ignored.
Implemented in com::xuggle::xuggler::AudioSamples, com::xuggle::xuggler::MediaDataWrapper, com::xuggle::xuggler::Packet, and com::xuggle::xuggler::VideoPicture.
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/IMediaData.h
csrc/com/xuggle/xuggler/IMediaData.cpp