Xuggle: com::xuggle::xuggler::IMediaDataWrapper Class Reference
com::xuggle::xuggler::IMediaDataWrapper Class Reference
#include <IMediaDataWrapper.h>
Detailed Description
This class wraps an IMediaData object, but then allows you to set new TimeStamps and TimeBases.
The underlying wrapped object's time stamps and time bases do not change. This can be useful when you need to use a IMediaObject in a time space that has different time bases than the frame originally expected, and you don't want to change the actual object.
Definition at line 37 of file IMediaDataWrapper.h.
Public Member Functions
virtual IMediaData * get ()=0
Return the object being wrapped.
virtual void wrap (IMediaData *aObj)=0
Set an object to wrap, or null to release the old object.
virtual void setKey (bool aIsKey)=0
Allows you to reset whether the wrapper things this is key or not.
virtual IMediaData * unwrap ()=0
Gets the non IMediaDataWrapper object ultimately wrapped in this wrapper, or null if there isn't one.
Static Public Member Functions
static IMediaDataWrapper * make (IMediaData *obj)
Create a new IMediaDataWrapper object that wraps the given obj.
Protected Member Functions
IMediaDataWrapper ()
virtual ~IMediaDataWrapper ()
Constructor & Destructor Documentation
com::xuggle::xuggler::IMediaDataWrapper::IMediaDataWrapper () [protected]
Definition at line 26 of file IMediaDataWrapper.cpp.
{
}
com::xuggle::xuggler::IMediaDataWrapper::~IMediaDataWrapper () [protected, virtual]
Definition at line 30 of file IMediaDataWrapper.cpp.
{
}
Member Function Documentation
virtual IMediaData* com::xuggle::xuggler::IMediaDataWrapper::get () [pure virtual]
Return the object being wrapped.
Returns:
the wrapped object
Implemented in com::xuggle::xuggler::MediaDataWrapper.
Referenced by com::xuggle::xuggler::MediaDataWrapper::wrap().
virtual void com::xuggle::xuggler::IMediaDataWrapper::wrap (IMediaData * aObj) [pure virtual]
Set an object to wrap, or null to release the old object.
Parameters:
aObj The object to wrap; null just releases the last object
Implemented in com::xuggle::xuggler::MediaDataWrapper.
virtual void com::xuggle::xuggler::IMediaDataWrapper::setKey (bool aIsKey) [pure virtual]
Allows you to reset whether the wrapper things this is key or not.
Note the underlying wrapped object will continue to keep it's prior setting.
Parameters:
aIsKey The new key value.
Implemented in com::xuggle::xuggler::MediaDataWrapper.
IMediaDataWrapper * com::xuggle::xuggler::IMediaDataWrapper::make (IMediaData * obj) [static]
Create a new IMediaDataWrapper object that wraps the given obj.
Parameters:
obj The object to wrap.
Returns:
a new object or null on error.
Reimplemented in com::xuggle::xuggler::MediaDataWrapper.
Definition at line 35 of file IMediaDataWrapper.cpp.
References com::xuggle::xuggler::Global::init(), and com::xuggle::xuggler::MediaDataWrapper::make().
{
  Global::init();
  return MediaDataWrapper::make(obj);
}
virtual IMediaData* com::xuggle::xuggler::IMediaDataWrapper::unwrap () [pure virtual]
Gets the non IMediaDataWrapper object ultimately wrapped in this wrapper, or null if there isn't one.
Returns:
The non IMediaDataWrapper object ultimately wrapped
Implemented in com::xuggle::xuggler::MediaDataWrapper.
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/IMediaDataWrapper.h
csrc/com/xuggle/xuggler/IMediaDataWrapper.cpp