Xuggle: com::xuggle::xuggler::IMetaData Class Reference
com::xuggle::xuggler::IMetaData Class Reference
#include <IMetaData.h>
Detailed Description
Get MetaData about a IContainer or IStream.
MetaData is a bag of key/value pairs that can be embedded in some IContainer or some IStream in an IContainer, and are then written to or read from a media file. Keys must be unique, and any attempt to set a key value replaces any previous values.
An example is the "title" meta-data item in an MP3 file.
Support for IMetaData differs depending upon the IContainer format you're using and the implementation in FFmpeg. For example, MP3 meta-data reading and writing is supported, but (as of the writing of this comment) FLV meta-data writing is not supported.
Definition at line 50 of file IMetaData.h.
Public Types
enum Flags { METADATA_NONE = 0, METADATA_MATCH_CASE = 1 }
Public Member Functions
virtual int32_t getNumKeys ()=0
Get the total number of keys currently in this IMetaData object.
virtual const char * getKey (int32_t position)=0
Get the key at the given position, or null if no such key at that position.
virtual const char * getValue (const char *key, Flags flag)=0
Get the value for the given key.
virtual int32_t setValue (const char *key, const char *value)=0
Sets the value for the given key to value.
Static Public Member Functions
static IMetaData * make ()
Create a new IMetaData bag of properties with no values set.
Protected Member Functions
IMetaData ()
virtual ~IMetaData ()
Member Enumeration Documentation
enum com::xuggle::xuggler::IMetaData::Flags
Enumerator:
METADATA_NONE
METADATA_MATCH_CASE
Definition at line 53 of file IMetaData.h.
               {
    METADATA_NONE=0,
    METADATA_MATCH_CASE=1,
//    METADATA_IGNORE_SUFFIX=2,
  } Flags;
Constructor & Destructor Documentation
com::xuggle::xuggler::IMetaData::IMetaData () [protected]
Definition at line 26 of file IMetaData.cpp.
{
}
com::xuggle::xuggler::IMetaData::~IMetaData () [protected, virtual]
Definition at line 31 of file IMetaData.cpp.
{
}
Member Function Documentation
virtual int32_t com::xuggle::xuggler::IMetaData::getNumKeys () [pure virtual]
Get the total number of keys currently in this IMetaData object.
Returns:
the number of keys.
Implemented in com::xuggle::xuggler::MetaData.
virtual const char* com::xuggle::xuggler::IMetaData::getKey (int32_t position) [pure virtual]
Get the key at the given position, or null if no such key at that position.
Note: positions of keys may change between calls to setValue(String, String) and should be requiried.
Parameters:
position The position. Must be >=0 and < getNumKeys().
Returns:
the key, or null if not found.
Implemented in com::xuggle::xuggler::MetaData.
virtual const char* com::xuggle::xuggler::IMetaData::getValue (const char * key, Flags flag) [pure virtual]
Get the value for the given key.
Parameters:
key The key
flag A flag for how to search
Returns:
The value, or null if none.
Implemented in com::xuggle::xuggler::MetaData.
virtual int32_t com::xuggle::xuggler::IMetaData::setValue (const char * key, const char * value) [pure virtual]
Sets the value for the given key to value.
This overrides any prior setting for key, or adds key to the meta-data if appropriate.
Parameters:
key The key to set.
value The value to set.
Implemented in com::xuggle::xuggler::MetaData.
IMetaData * com::xuggle::xuggler::IMetaData::make () [static]
Create a new IMetaData bag of properties with no values set.
Definition at line 36 of file IMetaData.cpp.
Referenced by com::xuggle::xuggler::Stream::getMetaData(), com::xuggle::xuggler::Container::getMetaData(), and com::xuggle::xuggler::MetaData::make().
{
  return MetaData::make();
}
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/IMetaData.h
csrc/com/xuggle/xuggler/IMetaData.cpp