Xuggle: com::xuggle::ferry::JNIHelper Class Reference
com::xuggle::ferry::JNIHelper Class Reference
#include <JNIHelper.h>
Detailed Description
The JNIHelper object contains a series of methods designed to assist functions when running inside a Java JVM.
There is only one JNIHelper object per shared library loaded.
Definition at line 37 of file JNIHelper.h.
Public Types
typedef void(* CallbackFunc)(JavaVM *jvm, void *closure)
Public Member Functions
VS_API_FERRY JavaVM * getVM ()
VS_API_FERRY void setVM (JavaVM *jvm)
VS_API_FERRY void * getPointer (jobject pointerRef)
VS_API_FERRY void * setPointer (jobject pointerRef, void *newVal)
VS_API_FERRY jobject newLocalRef (jobject ref)
VS_API_FERRY void deleteLocalRef (jobject ref)
VS_API_FERRY jobject newGlobalRef (jobject ref)
VS_API_FERRY void deleteGlobalRef (jobject ref)
VS_API_FERRY jweak newWeakGlobalRef (jobject ref)
VS_API_FERRY void deleteWeakGlobalRef (jweak ref)
VS_API_FERRY jint getJNIVersion ()
VS_API_FERRY JNIEnv * getEnv ()
VS_API_FERRY void registerInitializationCallback (CallbackFunc, void *closure)
VS_API_FERRY void registerTerminationCallback (CallbackFunc, void *closure)
virtual VS_API_FERRY ~JNIHelper ()
VS_API_FERRY JNIHelper ()
VS_API_FERRY void throwOutOfMemoryError ()
VS_API_FERRY int32_t isInterrupted ()
VS_API_FERRY bool isInterruptedException (jthrowable exception)
VS_API_FERRY void interrupt ()
Static Public Member Functions
static VS_API_FERRY JNIHelper * getHelper ()
static JavaVM * sGetVM ()
static void sSetVM (JavaVM *jvm)
static jint sGetJNIVersion ()
static JNIEnv * sGetEnv ()
static void * sGetPointer (jobject pointerRef)
static void * sSetPointer (jobject pointerRef, void *newVal)
static jobject sNewLocalRef (jobject ref)
static void sDeleteLocalRef (jobject ref)
static jobject sNewGlobalRef (jobject ref)
static void sDeleteGlobalRef (jobject ref)
static jweak sNewWeakGlobalRef (jobject ref)
static void sDeleteWeakGlobalRef (jweak ref)
static void sRegisterInitializationCallback (CallbackFunc func, void *closure)
static void sRegisterTerminationCallback (CallbackFunc func, void *closure)
static VS_API_FERRY void shutdownHelper ()
Classes
struct CallbackHelper
Member Typedef Documentation
typedef void(* com::xuggle::ferry::JNIHelper::CallbackFunc)(JavaVM *jvm, void *closure)
Constructor & Destructor Documentation
com::xuggle::ferry::JNIHelper::~JNIHelper () [virtual]
Definition at line 113 of file JNIHelper.cpp.
References getEnv().
  {
    JNIEnv *env;
    processCallbacks(&mInitializationCallbacks, 0, false);
    processCallbacks(&mTerminationCallbacks, mCachedVM, true);
    env = this->getEnv();
    if (env)
    {
      if (mOutOfMemoryErrorSingleton)
      {
        env->DeleteGlobalRef(mOutOfMemoryErrorSingleton);
        mOutOfMemoryErrorSingleton = 0;
      }
      if (mJNIPointerReference_class)
      {
        // Tell the JVM we're done with it.
        env->DeleteWeakGlobalRef(mJNIPointerReference_class);
        mJNIPointerReference_class = 0;
      }
      if (mThread_class)
      {
        env->DeleteWeakGlobalRef(mThread_class);
        mThread_class = 0;
      }
      if (mInterruptedException_class)
      {
        env->DeleteWeakGlobalRef(mInterruptedException_class);
        mInterruptedException_class = 0;
      }
    }
    mCachedVM = 0;
  }
com::xuggle::ferry::JNIHelper::JNIHelper ()
Definition at line 61 of file JNIHelper.cpp.
Referenced by getHelper().
  {
    mCachedVM = 0;
    mVersion = JNI_VERSION_1_2;
    mJNIPointerReference_class = 0;
    // Now, look for our get and set methods.
    mJNIPointerReference_setPointer_mid = 0;
    mJNIPointerReference_getPointer_mid = 0;
    mOutOfMemoryErrorSingleton = 0;
    mThread_class = 0;
    mThread_isInterrupted_mid = 0;
    mThread_currentThread_mid = 0;
    mInterruptedException_class = 0;
  }
Member Function Documentation
JNIHelper * com::xuggle::ferry::JNIHelper::getHelper () [static]
Definition at line 41 of file JNIHelper.cpp.
References JNIHelper().
Referenced by sDeleteGlobalRef(), sDeleteLocalRef(), sDeleteWeakGlobalRef(), sGetEnv(), sGetJNIVersion(), sGetPointer(), sGetVM(), sNewGlobalRef(), sNewLocalRef(), sNewWeakGlobalRef(), sRegisterInitializationCallback(), sRegisterTerminationCallback(), sSetPointer(), and sSetVM().
  {
    JNIHelper *retval = 0;
    retval = sSingleton;
    if (!retval) {
      retval = new JNIHelper();
      sSingleton = retval;
    }
    return retval;
  }
static JavaVM* com::xuggle::ferry::JNIHelper::sGetVM () [inline, static]
Definition at line 45 of file JNIHelper.h.
References getHelper(), and getVM().
Referenced by Java_com_xuggle_xuggler_io_FfmpegIO_init(), and com::xuggle::ferry::Mutex::make().
    {
      return getHelper()->getVM();
    }
static void com::xuggle::ferry::JNIHelper::sSetVM (JavaVM * jvm) [inline, static]
Definition at line 49 of file JNIHelper.h.
References getHelper(), and setVM().
Referenced by Java_com_xuggle_xuggler_io_FfmpegIO_init().
    {
      getHelper()->setVM(jvm);
    }
static jint com::xuggle::ferry::JNIHelper::sGetJNIVersion () [inline, static]
Definition at line 53 of file JNIHelper.h.
References getHelper(), and getJNIVersion().
Referenced by JNI_OnLoad().
    {
      return getHelper()->getJNIVersion();
    }
static JNIEnv* com::xuggle::ferry::JNIHelper::sGetEnv () [inline, static]
Definition at line 57 of file JNIHelper.h.
References getEnv(), and getHelper().
Referenced by com::xuggle::ferry::AtomicInteger::addAndGet(), com::xuggle::ferry::AtomicInteger::compareAndSet(), com::xuggle::ferry::AtomicInteger::decrementAndGet(), com::xuggle::ferry::AtomicInteger::get(), com::xuggle::ferry::AtomicInteger::getAndAdd(), com::xuggle::ferry::AtomicInteger::getAndDecrement(), com::xuggle::ferry::AtomicInteger::getAndIncrement(), com::xuggle::ferry::AtomicInteger::getAndSet(), com::xuggle::ferry::Logger::getLogger(), com::xuggle::ferry::AtomicInteger::incrementAndGet(), com::xuggle::ferry::Mutex::lock(), com::xuggle::ferry::Logger::Logger(), com::xuggle::ferry::Mutex::make(), com::xuggle::ferry::AtomicInteger::set(), com::xuggle::ferry::Mutex::unlock(), com::xuggle::xuggler::io::URLProtocolHandler::url_close(), com::xuggle::xuggler::io::URLProtocolHandler::url_open(), com::xuggle::xuggler::io::URLProtocolHandler::url_read(), com::xuggle::xuggler::io::URLProtocolHandler::url_seek(), com::xuggle::xuggler::io::URLProtocolHandler::url_write(), com::xuggle::ferry::AtomicInteger::~AtomicInteger(), com::xuggle::ferry::Logger::~Logger(), and com::xuggle::ferry::Mutex::~Mutex().
    {
      return getHelper()->getEnv();
    }
static void* com::xuggle::ferry::JNIHelper::sGetPointer (jobject pointerRef) [inline, static]
Definition at line 61 of file JNIHelper.h.
References getHelper(), and getPointer().
    {
      return getHelper()->getPointer(pointerRef);
    }
static void* com::xuggle::ferry::JNIHelper::sSetPointer (jobject pointerRef, void * newVal) [inline, static]
Definition at line 65 of file JNIHelper.h.
References getHelper(), and setPointer().
    {
      return getHelper()->setPointer(pointerRef, newVal);
    }
static jobject com::xuggle::ferry::JNIHelper::sNewLocalRef (jobject ref) [inline, static]
Definition at line 69 of file JNIHelper.h.
References getHelper(), and newLocalRef().
    {
      return getHelper()->newLocalRef(ref);
    }
static void com::xuggle::ferry::JNIHelper::sDeleteLocalRef (jobject ref) [inline, static]
Definition at line 73 of file JNIHelper.h.
References deleteLocalRef(), and getHelper().
    {
      return getHelper()->deleteLocalRef(ref);
    }
static jobject com::xuggle::ferry::JNIHelper::sNewGlobalRef (jobject ref) [inline, static]
Definition at line 77 of file JNIHelper.h.
References getHelper(), and newGlobalRef().
Referenced by com::xuggle::ferry::RefCounted::setJavaAllocator().
    {
      return getHelper()->newGlobalRef(ref);
    }
static void com::xuggle::ferry::JNIHelper::sDeleteGlobalRef (jobject ref) [inline, static]
Definition at line 81 of file JNIHelper.h.
References deleteGlobalRef(), and getHelper().
Referenced by com::xuggle::ferry::RefCounted::setJavaAllocator(), com::xuggle::ferry::RefCounted::~RefCounted(), com::xuggle::xuggler::io::URLProtocolHandler::~URLProtocolHandler(), and com::xuggle::xuggler::io::URLProtocolManager::~URLProtocolManager().
    {
      return getHelper()->deleteGlobalRef(ref);
    }
static jweak com::xuggle::ferry::JNIHelper::sNewWeakGlobalRef (jobject ref) [inline, static]
Definition at line 85 of file JNIHelper.h.
References getHelper(), and newWeakGlobalRef().
    {
      return getHelper()->newWeakGlobalRef(ref);
    }
static void com::xuggle::ferry::JNIHelper::sDeleteWeakGlobalRef (jweak ref) [inline, static]
Definition at line 89 of file JNIHelper.h.
References deleteWeakGlobalRef(), and getHelper().
    {
      return getHelper()->deleteWeakGlobalRef(ref);
    }
static void com::xuggle::ferry::JNIHelper::sRegisterInitializationCallback (CallbackFunc func, void * closure) [inline, static]
Definition at line 93 of file JNIHelper.h.
References getHelper(), and registerInitializationCallback().
    {
      return getHelper()->registerInitializationCallback(func, closure);
    }
static void com::xuggle::ferry::JNIHelper::sRegisterTerminationCallback (CallbackFunc func, void * closure) [inline, static]
Definition at line 98 of file JNIHelper.h.
References getHelper(), and registerTerminationCallback().
Referenced by com::xuggle::ferry::Logger::getStaticLogger().
    {
      return getHelper()->registerTerminationCallback(func, closure);
    }
JavaVM * com::xuggle::ferry::JNIHelper::getVM ()
Definition at line 344 of file JNIHelper.cpp.
Referenced by sGetVM().
  {
    return mCachedVM;
  }
void com::xuggle::ferry::JNIHelper::setVM (JavaVM * jvm)
Definition at line 149 of file JNIHelper.cpp.
References getEnv(), and VSJNI_MemoryManagerInit().
Referenced by sSetVM().
  {
    if (!mCachedVM)
    {
      mCachedVM = jvm;
      // Now, let's cache the commonly used classes.
      JNIEnv *env=this->getEnv();
      // It can be helpful to attach a GDB or Debugger to
      // a Running JVM.  This function attempts to see if that's
      // required.
      waitForDebugger(env);
      jclass cls=0;
      // let's set up a singleton out of memory error for potential
      // reuse later
      cls = env->FindClass("java/lang/OutOfMemoryError");
      if (!cls || env->ExceptionCheck())
        return;
      jmethodID constructor = env->GetMethodID(cls, "<init>", "(Ljava/lang/String;)V");
      if (!constructor || env->ExceptionCheck())
        return;
      jstring errorMessage = env->NewStringUTF(
          "Sorry, but we're all out of native memory.    How out"
          " of native memory are we?  Well, we're so out we're"
          " throwing a exception we allocated at"
          " the beginning of program time, so while the stack trace will"
          " be wrong, at least you get some useful feedback");
      if (!errorMessage)
        return;
      jthrowable exception=static_cast<jthrowable>(
          env->NewObject(cls, constructor, errorMessage));
      env->DeleteLocalRef(errorMessage);
      if (!exception) {
        return;
      }
      mOutOfMemoryErrorSingleton = static_cast<jthrowable>(env->NewGlobalRef(exception));
      if (!mOutOfMemoryErrorSingleton || env->ExceptionCheck())
        return;
      env->DeleteLocalRef(cls);
      cls = env->FindClass("com/xuggle/ferry/JNIPointerReference");
      if (!cls || env->ExceptionCheck())
        return;
      // Keep a reference around
      mJNIPointerReference_class=env->NewWeakGlobalRef(cls);
      if (!mJNIPointerReference_class || env->ExceptionCheck())
        return;
      // Now, look for our get and set mehods.
      mJNIPointerReference_setPointer_mid = env->GetMethodID(cls, "setPointer",
          "(J)J");
      if (!mJNIPointerReference_setPointer_mid || env->ExceptionCheck())
        return;
      mJNIPointerReference_getPointer_mid = env->GetMethodID(cls, "getPointer",
          "()J");
      if (!mJNIPointerReference_getPointer_mid || env->ExceptionCheck())
        return;
      env->DeleteLocalRef(cls);
      cls = env->FindClass("java/lang/Thread");
      if (!cls || env->ExceptionCheck())
        return;
      // Keep a reference around
      mThread_class=env->NewWeakGlobalRef(cls);
      if (!mThread_class || env->ExceptionCheck())
        return;
      // now look for the isInterrupted method
      mThread_currentThread_mid = env->GetStaticMethodID(cls,
          "currentThread", "()Ljava/lang/Thread;");
      if (!mThread_currentThread_mid || env->ExceptionCheck())
        return;
      mThread_isInterrupted_mid = env->GetMethodID(cls,
          "isInterrupted", "()Z");
      if (!mThread_isInterrupted_mid || env->ExceptionCheck())
        return;
      mThread_interrupt_mid = env->GetMethodID(cls,
          "interrupt", "()V");
      if (!mThread_interrupt_mid || env->ExceptionCheck())
        return;
      env->DeleteLocalRef(cls);
      // Are there any pending callbacks?
      processCallbacks(&mInitializationCallbacks, mCachedVM, true);
      // And Initialize the JNI Memory manager;
      // This means that any callbacks will NOT use the
      // JVM for memory management.
      VSJNI_MemoryManagerInit(mCachedVM);
    }
  }
void * com::xuggle::ferry::JNIHelper::getPointer (jobject pointerRef)
Definition at line 350 of file JNIHelper.cpp.
References getEnv().
Referenced by sGetPointer().
  {
    JNIEnv *env = this->getEnv();
    if (!env)
      return 0;
    if (env->ExceptionCheck())
      return 0;
    jlong pointerVal = env->CallLongMethod(pointerRef,
        mJNIPointerReference_getPointer_mid);
    /*
     * What's going on here is inherently unsafe, but is designed
     * to pass pointer values into Java.  It is structured like this
     * to compile without warning on as many OSes as possible
     *
     * It'll only work for 64-bit or lower os'es (what you complaining
     * about -- you got a 65-bit OS you're chomping to try out?).
     *
     * Now stop looking.  Go back to your day job.
     */
    void *retval = (void*)(size_t)pointerVal;
    return retval;
  }
void * com::xuggle::ferry::JNIHelper::setPointer (jobject pointerRef, void * newVal)
Definition at line 378 of file JNIHelper.cpp.
References getEnv().
Referenced by sSetPointer().
  {
    JNIEnv *env = this->getEnv();
    if (!env)
      return 0;
    if (env->ExceptionCheck())
      return 0;
    if (!pointerRef)
      return 0;
    jlong newPointerVal = (jlong)(long)newVal;
    jlong pointerVal = env->CallLongMethod(pointerRef,
        mJNIPointerReference_setPointer_mid, newPointerVal);
    void *retval = (void*)(size_t)pointerVal;
    return retval;
  }
jobject com::xuggle::ferry::JNIHelper::newLocalRef (jobject ref)
Definition at line 414 of file JNIHelper.cpp.
References getEnv().
Referenced by sNewLocalRef().
  {
    jobject retval = 0;
    JNIEnv *env = this->getEnv();
    if (!env)
      return 0;
    if (env->ExceptionCheck())
      return 0;
    retval = env->NewLocalRef(ref);
    if (!retval)
      throw std::runtime_error("could not get JVM LocalRef");
    if (env->ExceptionCheck()) {
      env->DeleteLocalRef(retval);
      throw std::runtime_error("could not get JVM LocalRef");
    }
    return retval;
  }
void com::xuggle::ferry::JNIHelper::deleteLocalRef (jobject ref)
Definition at line 434 of file JNIHelper.cpp.
References getEnv().
Referenced by sDeleteLocalRef().
  {
    JNIEnv *env = this->getEnv();
    if (!env)
      throw std::runtime_error("attempted to delete LocalRef without JVM");
    env->DeleteLocalRef(ref);
  }
jobject com::xuggle::ferry::JNIHelper::newGlobalRef (jobject ref)
Definition at line 443 of file JNIHelper.cpp.
References getEnv().
Referenced by sNewGlobalRef().
  {
    jobject retval = 0;
    JNIEnv *env = this->getEnv();
    if (!env)
      return 0;
    if (env->ExceptionCheck())
      return 0;
    retval = env->NewGlobalRef(ref);
    if (!retval)
      throw std::runtime_error("could not get JVM GlobalRef");
    if (env->ExceptionCheck())
    {
      env->DeleteGlobalRef(retval);
      throw std::runtime_error("could not get JVM GlobalRef");
    }
    return retval;
  }
void com::xuggle::ferry::JNIHelper::deleteGlobalRef (jobject ref)
Definition at line 464 of file JNIHelper.cpp.
References getEnv().
Referenced by sDeleteGlobalRef().
  {
    JNIEnv *env = this->getEnv();
    if (!env)
      throw std::runtime_error("attempted to delete GlobalRef without JVM");
    env->DeleteGlobalRef(ref);
  }
jweak com::xuggle::ferry::JNIHelper::newWeakGlobalRef (jobject ref)
Definition at line 473 of file JNIHelper.cpp.
References getEnv().
Referenced by sNewWeakGlobalRef().
  {
    if (!ref)
      return 0;
    JNIEnv *env = this->getEnv();
    if (!env)
      return 0;
    if (env->ExceptionCheck())
      return 0;
    jweak retval = 0;
    retval = env->NewWeakGlobalRef(ref);
    if (!retval)
      throw std::runtime_error("could not get JVM WeakGlobal ref");
    if (env->ExceptionCheck())
    {
      env->DeleteWeakGlobalRef(retval);
      throw std::runtime_error("could not get JVM WeakGlobal ref");
    }
    return retval;
  }
void com::xuggle::ferry::JNIHelper::deleteWeakGlobalRef (jweak ref)
Definition at line 496 of file JNIHelper.cpp.
References getEnv().
Referenced by sDeleteWeakGlobalRef().
  {
    if (!ref)
      return;
    JNIEnv *env = this->getEnv();
    if (!env)
      throw std::runtime_error("attempted to delete WeakGlobalRef without JVM");
    env->DeleteWeakGlobalRef(ref);
  }
jint com::xuggle::ferry::JNIHelper::getJNIVersion ()
Definition at line 408 of file JNIHelper.cpp.
Referenced by sGetJNIVersion().
  {
    return mVersion;
  }
JNIEnv * com::xuggle::ferry::JNIHelper::getEnv ()
Definition at line 399 of file JNIHelper.cpp.
Referenced by deleteGlobalRef(), deleteLocalRef(), deleteWeakGlobalRef(), getPointer(), interrupt(), isInterrupted(), isInterruptedException(), newGlobalRef(), newLocalRef(), newWeakGlobalRef(), setPointer(), setVM(), sGetEnv(), throwOutOfMemoryError(), and ~JNIHelper().
  {
    JNIEnv *env=0;
    if (mCachedVM)
      mCachedVM->GetEnv((void**)(void*)&env, mVersion);
    return env;
  }
void com::xuggle::ferry::JNIHelper::registerInitializationCallback (CallbackFunc callback, void * closure)
Definition at line 312 of file JNIHelper.cpp.
Referenced by sRegisterInitializationCallback().
  {
    if (callback)
    {
      if (!mCachedVM)
      {
        // we don't have a callback; so save the function
        // call for later.
        addCallback(&mInitializationCallbacks, callback, closure);
      }
      else
      {
       // We have a VM already; just callback immediately.
       callback(mCachedVM, closure);
      }
    }
  }
void com::xuggle::ferry::JNIHelper::registerTerminationCallback (CallbackFunc callback, void * closure)
Definition at line 333 of file JNIHelper.cpp.
Referenced by sRegisterTerminationCallback().
  {
    if (callback)
    {
      addCallback(&mTerminationCallbacks, callback, closure);
    }
  }
void com::xuggle::ferry::JNIHelper::shutdownHelper () [static]
Definition at line 53 of file JNIHelper.cpp.
  {
    if (sSingleton) {
      delete sSingleton;
      sSingleton = 0;
    }
  }
void com::xuggle::ferry::JNIHelper::throwOutOfMemoryError ()
Be VERY careful in this function; it gets call when we're low on memory so you check any allocations of memory, as they are incredibly likely to fail -- and will do so on the most inconvenient OS more often than others.
Definition at line 507 of file JNIHelper.cpp.
References getEnv().
  {
    JNIEnv *env = this->getEnv();
    if (!env)
      return;
    // exception already pending?
    if (env->ExceptionCheck())
      return;
    jclass cls=0;
    // let's set up a singleton out of memory error for potential
    // reuse later
    cls = env->FindClass("java/lang/OutOfMemoryError");
    // couldn't find the class?
    if (cls) {
      int retval = env->ThrowNew(cls, "out of native memory");
      env->DeleteLocalRef(cls);
      if (retval == 0) // success
        return;
    }
    if (!mOutOfMemoryErrorSingleton)
      return;
    env->Throw(mOutOfMemoryErrorSingleton);
  }
int32_t com::xuggle::ferry::JNIHelper::isInterrupted ()
Definition at line 540 of file JNIHelper.cpp.
References getEnv().
  {
    JNIEnv * env = this->getEnv();
    if (!env)
      return 0;
    if (env->ExceptionCheck())
      return 1; // a pending exception interrupts us
    if (!mThread_class ||
        !mThread_isInterrupted_mid ||
        !mThread_currentThread_mid)
      // this is an error if these are not set up, but we're
      // going to assume no interrupt then.
      return 0;
    jclass cls = static_cast<jclass>(env->NewLocalRef(mThread_class));
    if (!cls)
      return 0;
    jobject thread = env->CallStaticObjectMethod(
        cls,
        mThread_currentThread_mid);
    env->DeleteLocalRef(cls);
    if (!thread || env->ExceptionCheck())
      return 1;
    jboolean result = env->CallBooleanMethod(thread,
        mThread_isInterrupted_mid);
    env->DeleteLocalRef(thread);
    if (env->ExceptionCheck())
      result = false;
    if (result != JNI_FALSE)
      return 1;
    return 0;
  }
bool com::xuggle::ferry::JNIHelper::isInterruptedException (jthrowable exception)
Definition at line 606 of file JNIHelper.cpp.
References getEnv().
  {
    JNIEnv * env = this->getEnv();
    if (!env)
      return false;
    if (env->ExceptionCheck())
      return false; // a pending exception interrupts us
    if (!mInterruptedException_class)
      // this is an error if these are not set up, but we're
      // going to assume no interrupt then.
      return false;
    jclass cls = static_cast<jclass>(env->NewLocalRef(mInterruptedException_class));
    if (!cls)
      return false;
    jboolean retval = env->IsInstanceOf(
        exception,
        static_cast<jclass>(cls)
    );
    env->DeleteLocalRef(cls);
    if (retval != JNI_FALSE)
      return true;
    else
      return false;
  }
void com::xuggle::ferry::JNIHelper::interrupt ()
Definition at line 575 of file JNIHelper.cpp.
References getEnv().
  {
    JNIEnv * env = this->getEnv();
    if (!env)
      return;
    if (env->ExceptionCheck())
      return; // a pending exception so we can't continue
    if (!mThread_class ||
        !mThread_interrupt_mid ||
        !mThread_currentThread_mid)
      // this is an error if these are not set up, but we're
      // going to assume no interrupt then.
      return;
    jclass cls = static_cast<jclass>(env->NewLocalRef(mThread_class));
    if (!cls)
      return;
    jobject thread = env->CallStaticObjectMethod(
        cls,
        mThread_currentThread_mid);
    env->DeleteLocalRef(cls);
    if (!thread || env->ExceptionCheck())
      return;
    env->CallVoidMethod(thread,
        mThread_interrupt_mid);
    env->DeleteLocalRef(thread);
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/ferry/JNIHelper.h
csrc/com/xuggle/ferry/JNIHelper.cpp