Xuggle: com::xuggle::ferry::IBuffer Class Reference
com::xuggle::ferry::IBuffer Class Reference
#include <IBuffer.h>
Detailed Description
Allows Java code to get data from a native buffers, and optionally modify native memory directly.
When accessing from Java, you can copy in and out ranges of buffers. You can do this by-copy (which is safer but a little slower) or by-reference where you directly access underlying C++/native memory from Java. Take special care if you decide that native access is required.
When accessing from C++, you get direct access to the underlying buffer.
To make an IBuffer object that is not a Xuggler internal object, pass in null for the RefCounted parameter.
Definition at line 53 of file IBuffer.h.
Public Types
enum Type {
IBUFFER_UINT8, IBUFFER_SINT8, IBUFFER_UINT16, IBUFFER_SINT16,
IBUFFER_UINT32, IBUFFER_SINT32, IBUFFER_UINT64, IBUFFER_SINT64,
IBUFFER_FLT32, IBUFFER_DBL64, IBUFFER_NB
}
typedef void(* FreeFunc)(void *mem, void *closure)
Public Member Functions
virtual void * getBytes (int32_t offset, int32_t length)=0
Returns up to length bytes, starting at offset in the underlying buffer we're managing.
virtual int32_t getBufferSize ()=0
Get the current maximum number of bytes that can be safely placed in this buffer.
virtual Type getType ()=0
Get the type this buffer was created as.
virtual void setType (Type type)=0
Reset the buffer type to a new type.
virtual int32_t getSize ()=0
Returns the size, in units of getType() of this buffer.
Static Public Member Functions
static IBuffer * make (RefCounted *requestor, void *bufToWrap, int32_t bufferSize, FreeFunc freeFunc, void *closure)
Allocate a new buffer by wrapping a native buffer.
static IBuffer * make (com::xuggle::ferry::RefCounted *requestor, int32_t bufferSize)
Allocate a new buffer of at least bufferSize.
static int32_t getTypeSize (Type type)
Returns the size, in bytes, of elements of given Type.
static IBuffer * make (com::xuggle::ferry::RefCounted *requestor, Type type, int32_t numElements, bool zero)
Allocate a new buffer of at least bufferSize.
Protected Member Functions
IBuffer ()
virtual ~IBuffer ()
Member Typedef Documentation
typedef void(* com::xuggle::ferry::IBuffer::FreeFunc)(void *mem, void *closure)
Member Enumeration Documentation
enum com::xuggle::ferry::IBuffer::Type
Enumerator:
IBUFFER_UINT8
IBUFFER_SINT8
IBUFFER_UINT16
IBUFFER_SINT16
IBUFFER_UINT32
IBUFFER_SINT32
IBUFFER_UINT64
IBUFFER_SINT64
IBUFFER_FLT32
IBUFFER_DBL64
IBUFFER_NB
Definition at line 118 of file IBuffer.h.
               {
    IBUFFER_UINT8,
    IBUFFER_SINT8,
    IBUFFER_UINT16,
    IBUFFER_SINT16,
    IBUFFER_UINT32,
    IBUFFER_SINT32,
    IBUFFER_UINT64,
    IBUFFER_SINT64,
    IBUFFER_FLT32,
    IBUFFER_DBL64,
    IBUFFER_NB,
  } Type;
Constructor & Destructor Documentation
com::xuggle::ferry::IBuffer::IBuffer () [protected]
Definition at line 33 of file IBuffer.cpp.
  {
  }
com::xuggle::ferry::IBuffer::~IBuffer () [protected, virtual]
Definition at line 37 of file IBuffer.cpp.
  {
  }
Member Function Documentation
virtual void* com::xuggle::ferry::IBuffer::getBytes (int32_t offset, int32_t length) [pure virtual]
Returns up to length bytes, starting at offset in the underlying buffer we're managing.
Note that with this method you are accessing the direct memory, so be careful.
Parameters:
offset The offset (in bytes) into the buffer managed by this IBuffer
length The requested length (in bytes) you want to access. The buffer returned may actually be longer than length.
Returns:
A pointer to the direct buffer, or 0 if the offset or length would not fit within the buffer we're managing.
Implemented in com::xuggle::ferry::Buffer.
Referenced by com::xuggle::xuggler::Container::createSDPData(), com::xuggle::xuggler::StreamCoder::getExtraData(), com::xuggle::xuggler::VideoPicture::make(), and com::xuggle::xuggler::StreamCoder::setExtraData().
IBuffer * com::xuggle::ferry::IBuffer::make (RefCounted * requestor, void * bufToWrap, int32_t bufferSize, FreeFunc freeFunc, void * closure) [static]
Allocate a new buffer by wrapping a native buffer.
To make an IBuffer object that is not a Xuggler internal object, pass in null for the requestor parameter.
Parameters:
requestor An optional value telling the IBuffer class what object requested it. This is used for debugging memory leaks; it's a marker for the FERRY object (e.g. IPacket) that actually requested the buffer. If you're not an FERRY object, pass in null here.
bufToWrap Buffer to wrap
bufferSize The minimum buffer size you're requesting in bytes; a buffer with a larger size may be returned.
freeFunc A function that will be called when we decide to free the buffer
closure A value that will be passed, along with this, to freeFunc
Returns:
A new buffer, or null on error.
Definition at line 48 of file IBuffer.cpp.
References com::xuggle::ferry::Buffer::make().
Referenced by com::xuggle::xuggler::StreamCoder::open().
  {
    return Buffer::make(requestor, bufToWrap, bufferSize, freeFunc, closure);
  }
virtual int32_t com::xuggle::ferry::IBuffer::getBufferSize () [pure virtual]
Get the current maximum number of bytes that can be safely placed in this buffer.
Returns:
Maximum number of bytes this buffer can manage.
Implemented in com::xuggle::ferry::Buffer.
Referenced by com::xuggle::xuggler::Container::createSDPData(), com::xuggle::xuggler::VideoPicture::make(), and com::xuggle::xuggler::AudioSamples::make().
IBuffer * com::xuggle::ferry::IBuffer::make (com::xuggle::ferry::RefCounted * requestor, int32_t bufferSize) [static]
Allocate a new buffer of at least bufferSize.
Parameters:
requestor An optional value telling the IBuffer class what object requested it. This is used for debugging memory leaks; it's a marker for the FERRY object (e.g. IPacket) that actually requested the buffer. If you're not an FERRY object, pass in null here.
bufferSize The minimum buffer size you're requesting in bytes; a buffer with a larger size may be returned.
Returns:
A new buffer, or null on error.
Reimplemented in com::xuggle::ferry::Buffer.
Definition at line 42 of file IBuffer.cpp.
References com::xuggle::ferry::Buffer::make().
  {
    return Buffer::make(requestor, bufferSize);
  }
virtual Type com::xuggle::ferry::IBuffer::getType () [pure virtual]
Get the type this buffer was created as.
A type is really just a hint. Like objects, IBuffer objects can be cast to and from any type.
Returns:
the type
Implemented in com::xuggle::ferry::Buffer.
virtual void com::xuggle::ferry::IBuffer::setType (Type type) [pure virtual]
Reset the buffer type to a new type.
This method does not do any data conversion, it just changes the reported type (so changing from Type#IBUFFER_UINT8 to Type#IBUFFER_SINT16 is really just a "cast" operation).
Parameters:
type the type to set to.
Implemented in com::xuggle::ferry::Buffer.
int32_t com::xuggle::ferry::IBuffer::getTypeSize (Type type) [static]
Returns the size, in bytes, of elements of given Type.
Returns:
the size in bytes.
Reimplemented in com::xuggle::ferry::Buffer.
Definition at line 65 of file IBuffer.cpp.
References com::xuggle::ferry::Buffer::getTypeSize().
  {
    return Buffer::getTypeSize(type);
  }
virtual int32_t com::xuggle::ferry::IBuffer::getSize () [pure virtual]
Returns the size, in units of getType() of this buffer.
Returns:
number of items of type getType() that will fit in this buffer.
Implemented in com::xuggle::ferry::Buffer.
IBuffer * com::xuggle::ferry::IBuffer::make (com::xuggle::ferry::RefCounted * requestor, Type type, int32_t numElements, bool zero) [static]
Allocate a new buffer of at least bufferSize.
Parameters:
requestor An optional value telling the IBuffer class what object requested it. This is used for debugging memory leaks; it's a marker for the FERRY object (e.g. IPacket) that actually requested the buffer. If you're not an FERRY object, pass in null here.
type The type of buffer.
numElements The minimum number of elements of the specified type you will put in this buffer.
zero If true, we will guarantee the buffer contains only zeros. If false, we will not (it is faster to not, but then the buffer will have garbage-data in it).
Returns:
A new buffer, or null on error.
Reimplemented in com::xuggle::ferry::Buffer.
Definition at line 58 of file IBuffer.cpp.
References com::xuggle::ferry::Buffer::make().
  {
    return Buffer::make(requestor, type, numElements, zero);
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/ferry/IBuffer.h
csrc/com/xuggle/ferry/IBuffer.cpp