Xuggle: com::xuggle::xuggler::ICodec Class Reference
com::xuggle::xuggler::ICodec Class Reference
#include <ICodec.h>
Detailed Description
A "key" to an IStreamCoder that tells it how to encode or decode data.
Use these objects to tell a IStreamCoder you want to use MP3 or NellyMoser for example.
Definition at line 42 of file ICodec.h.
Public Types
enum ID {
CODEC_ID_NONE, CODEC_ID_MPEG1VIDEO, CODEC_ID_MPEG2VIDEO, CODEC_ID_MPEG2VIDEO_XVMC,
CODEC_ID_H261, CODEC_ID_H263, CODEC_ID_RV10, CODEC_ID_RV20,
CODEC_ID_MJPEG, CODEC_ID_MJPEGB, CODEC_ID_LJPEG, CODEC_ID_SP5X,
CODEC_ID_JPEGLS, CODEC_ID_MPEG4, CODEC_ID_RAWVIDEO, CODEC_ID_MSMPEG4V1,
CODEC_ID_MSMPEG4V2, CODEC_ID_MSMPEG4V3, CODEC_ID_WMV1, CODEC_ID_WMV2,
CODEC_ID_H263P, CODEC_ID_H263I, CODEC_ID_FLV1, CODEC_ID_SVQ1,
CODEC_ID_SVQ3, CODEC_ID_DVVIDEO, CODEC_ID_HUFFYUV, CODEC_ID_CYUV,
CODEC_ID_H264, CODEC_ID_INDEO3, CODEC_ID_VP3, CODEC_ID_THEORA,
CODEC_ID_ASV1, CODEC_ID_ASV2, CODEC_ID_FFV1, CODEC_ID_4XM,
CODEC_ID_VCR1, CODEC_ID_CLJR, CODEC_ID_MDEC, CODEC_ID_ROQ,
CODEC_ID_INTERPLAY_VIDEO, CODEC_ID_XAN_WC3, CODEC_ID_XAN_WC4, CODEC_ID_RPZA,
CODEC_ID_CINEPAK, CODEC_ID_WS_VQA, CODEC_ID_MSRLE, CODEC_ID_MSVIDEO1,
CODEC_ID_IDCIN, CODEC_ID_8BPS, CODEC_ID_SMC, CODEC_ID_FLIC,
CODEC_ID_TRUEMOTION1, CODEC_ID_VMDVIDEO, CODEC_ID_MSZH, CODEC_ID_ZLIB,
CODEC_ID_QTRLE, CODEC_ID_SNOW, CODEC_ID_TSCC, CODEC_ID_ULTI,
CODEC_ID_QDRAW, CODEC_ID_VIXL, CODEC_ID_QPEG, CODEC_ID_XVID,
CODEC_ID_PNG, CODEC_ID_PPM, CODEC_ID_PBM, CODEC_ID_PGM,
CODEC_ID_PGMYUV, CODEC_ID_PAM, CODEC_ID_FFVHUFF, CODEC_ID_RV30,
CODEC_ID_RV40, CODEC_ID_VC1, CODEC_ID_WMV3, CODEC_ID_LOCO,
CODEC_ID_WNV1, CODEC_ID_AASC, CODEC_ID_INDEO2, CODEC_ID_FRAPS,
CODEC_ID_TRUEMOTION2, CODEC_ID_BMP, CODEC_ID_CSCD, CODEC_ID_MMVIDEO,
CODEC_ID_ZMBV, CODEC_ID_AVS, CODEC_ID_SMACKVIDEO, CODEC_ID_NUV,
CODEC_ID_KMVC, CODEC_ID_FLASHSV, CODEC_ID_CAVS, CODEC_ID_JPEG2000,
CODEC_ID_VMNC, CODEC_ID_VP5, CODEC_ID_VP6, CODEC_ID_VP6F,
CODEC_ID_TARGA, CODEC_ID_DSICINVIDEO, CODEC_ID_TIERTEXSEQVIDEO, CODEC_ID_TIFF,
CODEC_ID_GIF, CODEC_ID_FFH264, CODEC_ID_DXA, CODEC_ID_DNXHD,
CODEC_ID_THP, CODEC_ID_SGI, CODEC_ID_C93, CODEC_ID_BETHSOFTVID,
CODEC_ID_PTX, CODEC_ID_TXD, CODEC_ID_VP6A, CODEC_ID_AMV,
CODEC_ID_VB, CODEC_ID_PCX, CODEC_ID_SUNRAST, CODEC_ID_INDEO4,
CODEC_ID_INDEO5, CODEC_ID_MIMIC, CODEC_ID_RL2, CODEC_ID_8SVX_EXP,
CODEC_ID_8SVX_FIB, CODEC_ID_ESCAPE124, CODEC_ID_DIRAC, CODEC_ID_BFI,
CODEC_ID_CMV, CODEC_ID_MOTIONPIXELS, CODEC_ID_TGV, CODEC_ID_TGQ,
CODEC_ID_TQI, CODEC_ID_AURA, CODEC_ID_AURA2, CODEC_ID_V210X,
CODEC_ID_TMV, CODEC_ID_V210, CODEC_ID_DPX, CODEC_ID_MAD,
CODEC_ID_FRWU, CODEC_ID_FLASHSV2, CODEC_ID_CDGRAPHICS, CODEC_ID_R210,
CODEC_ID_ANM, CODEC_ID_BINKVIDEO, CODEC_ID_IFF_ILBM, CODEC_ID_IFF_BYTERUN1,
CODEC_ID_KGV1, CODEC_ID_YOP, CODEC_ID_VP8, CODEC_ID_PICTOR,
CODEC_ID_ANSI, CODEC_ID_A64_MULTI, CODEC_ID_A64_MULTI5, CODEC_ID_R10K,
CODEC_ID_MXPEG, CODEC_ID_LAGARITH, CODEC_ID_PRORES, CODEC_ID_JV,
CODEC_ID_DFA, CODEC_ID_8SVX_RAW, CODEC_ID_PCM_S16LE = 0x10000, CODEC_ID_PCM_S16BE,
CODEC_ID_PCM_U16LE, CODEC_ID_PCM_U16BE, CODEC_ID_PCM_S8, CODEC_ID_PCM_U8,
CODEC_ID_PCM_MULAW, CODEC_ID_PCM_ALAW, CODEC_ID_PCM_S32LE, CODEC_ID_PCM_S32BE,
CODEC_ID_PCM_U32LE, CODEC_ID_PCM_U32BE, CODEC_ID_PCM_S24LE, CODEC_ID_PCM_S24BE,
CODEC_ID_PCM_U24LE, CODEC_ID_PCM_U24BE, CODEC_ID_PCM_S24DAUD, CODEC_ID_PCM_ZORK,
CODEC_ID_PCM_S16LE_PLANAR, CODEC_ID_PCM_DVD, CODEC_ID_PCM_F32BE, CODEC_ID_PCM_F32LE,
CODEC_ID_PCM_F64BE, CODEC_ID_PCM_F64LE, CODEC_ID_PCM_BLURAY, CODEC_ID_PCM_LXF,
CODEC_ID_S302M, CODEC_ID_ADPCM_IMA_QT = 0x11000, CODEC_ID_ADPCM_IMA_WAV, CODEC_ID_ADPCM_IMA_DK3,
CODEC_ID_ADPCM_IMA_DK4, CODEC_ID_ADPCM_IMA_WS, CODEC_ID_ADPCM_IMA_SMJPEG, CODEC_ID_ADPCM_MS,
CODEC_ID_ADPCM_4XM, CODEC_ID_ADPCM_XA, CODEC_ID_ADPCM_ADX, CODEC_ID_ADPCM_EA,
CODEC_ID_ADPCM_G726, CODEC_ID_ADPCM_CT, CODEC_ID_ADPCM_SWF, CODEC_ID_ADPCM_YAMAHA,
CODEC_ID_ADPCM_SBPRO_4, CODEC_ID_ADPCM_SBPRO_3, CODEC_ID_ADPCM_SBPRO_2, CODEC_ID_ADPCM_THP,
CODEC_ID_ADPCM_IMA_AMV, CODEC_ID_ADPCM_EA_R1, CODEC_ID_ADPCM_EA_R3, CODEC_ID_ADPCM_EA_R2,
CODEC_ID_ADPCM_IMA_EA_SEAD, CODEC_ID_ADPCM_IMA_EA_EACS, CODEC_ID_ADPCM_EA_XAS, CODEC_ID_ADPCM_EA_MAXIS_XA,
CODEC_ID_ADPCM_IMA_ISS, CODEC_ID_ADPCM_G722, CODEC_ID_AMR_NB = 0x12000, CODEC_ID_AMR_WB,
CODEC_ID_RA_144 = 0x13000, CODEC_ID_RA_288, CODEC_ID_ROQ_DPCM = 0x14000, CODEC_ID_INTERPLAY_DPCM,
CODEC_ID_XAN_DPCM, CODEC_ID_SOL_DPCM, CODEC_ID_MP2 = 0x15000, CODEC_ID_MP3,
CODEC_ID_AAC, CODEC_ID_AC3, CODEC_ID_DTS, CODEC_ID_VORBIS,
CODEC_ID_DVAUDIO, CODEC_ID_WMAV1, CODEC_ID_WMAV2, CODEC_ID_MACE3,
CODEC_ID_MACE6, CODEC_ID_VMDAUDIO, CODEC_ID_SONIC, CODEC_ID_SONIC_LS,
CODEC_ID_FLAC, CODEC_ID_MP3ADU, CODEC_ID_MP3ON4, CODEC_ID_SHORTEN,
CODEC_ID_ALAC, CODEC_ID_WESTWOOD_SND1, CODEC_ID_GSM, CODEC_ID_QDM2,
CODEC_ID_COOK, CODEC_ID_TRUESPEECH, CODEC_ID_TTA, CODEC_ID_SMACKAUDIO,
CODEC_ID_QCELP, CODEC_ID_WAVPACK, CODEC_ID_DSICINAUDIO, CODEC_ID_IMC,
CODEC_ID_MUSEPACK7, CODEC_ID_MLP, CODEC_ID_GSM_MS, CODEC_ID_ATRAC3,
CODEC_ID_VOXWARE, CODEC_ID_APE, CODEC_ID_NELLYMOSER, CODEC_ID_MUSEPACK8,
CODEC_ID_SPEEX, CODEC_ID_WMAVOICE, CODEC_ID_WMAPRO, CODEC_ID_WMALOSSLESS,
CODEC_ID_ATRAC3P, CODEC_ID_EAC3, CODEC_ID_SIPR, CODEC_ID_MP1,
CODEC_ID_TWINVQ, CODEC_ID_TRUEHD, CODEC_ID_MP4ALS, CODEC_ID_ATRAC1,
CODEC_ID_BINKAUDIO_RDFT, CODEC_ID_BINKAUDIO_DCT, CODEC_ID_AAC_LATM, CODEC_ID_QDMC,
CODEC_ID_CELT, CODEC_ID_DVD_SUBTITLE = 0x17000, CODEC_ID_DVB_SUBTITLE, CODEC_ID_TEXT,
CODEC_ID_XSUB, CODEC_ID_SSA, CODEC_ID_MOV_TEXT, CODEC_ID_HDMV_PGS_SUBTITLE,
CODEC_ID_DVB_TELETEXT, CODEC_ID_SRT, CODEC_ID_MICRODVD, CODEC_ID_TTF = 0x18000,
CODEC_ID_PROBE = 0x19000, CODEC_ID_MPEG2TS = 0x20000, CODEC_ID_FFMETADATA = 0x21000
}
These are the codecs this library currently supports.
enum Type {
CODEC_TYPE_UNKNOWN = -1, CODEC_TYPE_VIDEO, CODEC_TYPE_AUDIO, CODEC_TYPE_DATA,
CODEC_TYPE_SUBTITLE, CODEC_TYPE_ATTACHMENT
}
The different types of Codecs that can exist in the system.
enum Capabilities {
CAP_DRAW_HORIZ_BAND = 0x0001, CAP_DR1 = 0x0002, CAP_PARSE_ONLY = 0x0004, CAP_TRUNCATED = 0x0008,
CAP_HWACCEL = 0x0010, CAP_DELAY = 0x0020, CAP_SMALL_LAST_FRAME = 0x0040, CAP_HWACCEL_VDPAU = 0x0080,
CAP_SUBFRAMES = 0x0100
}
Capability flags.
Public Member Functions
virtual const char * getName ()=0
Get the name of the codec.
virtual int getIDAsInt ()=0
Get the ID of this codec, as an integer.
virtual ID getID ()=0
Get the ID of this codec as an enumeration.
virtual Type getType ()=0
Get the type of this codec.
virtual bool canDecode ()=0
Can this codec be used for decoding?
virtual bool canEncode ()=0
Can this codec be used for encoding?
virtual const char * getLongName ()=0
Added for 1.17.
virtual int32_t getCapabilities ()=0
Get the capabilites flag from the codec.
virtual bool hasCapability (Capabilities capability)=0
Convenience method to check individual capability flags.
virtual int32_t getNumSupportedVideoFrameRates ()=0
Get the number of frame rates this codec supports for encoding.
virtual IRational * getSupportedVideoFrameRate (int32_t index)=0
Return the supported frame rate at the given index.
virtual int32_t getNumSupportedVideoPixelFormats ()=0
Get the number of supported video pixel formats this codec supports for encoding.
virtual IPixelFormat::Type getSupportedVideoPixelFormat (int32_t index)=0
Return the supported video pixel format at the given index.
virtual int32_t getNumSupportedAudioSampleRates ()=0
Get the number of different audio sample rates this codec supports for encoding.
virtual int32_t getSupportedAudioSampleRate (int32_t index)=0
Return the support audio sample rate at the given index.
virtual int32_t getNumSupportedAudioSampleFormats ()=0
Get the number of different audio sample formats this codec supports for encoding.
virtual IAudioSamples::Format getSupportedAudioSampleFormat (int32_t index)=0
Get the supported sample format at this index.
virtual int32_t getNumSupportedAudioChannelLayouts ()=0
Get the number of different audio channel layouts this codec supports for encoding.
virtual int64_t getSupportedAudioChannelLayout (int32_t index)=0
Get the supported audio channel layout at this index.
Static Public Member Functions
static ICodec * findEncodingCodec (ICodec::ID id)
Find a codec that can be used for encoding.
static ICodec * findEncodingCodecByIntID (int id)
Find a codec that can be used for encoding.
static ICodec * findEncodingCodecByName (const char *id)
Find a codec that can be used for encoding.
static ICodec * findDecodingCodec (ICodec::ID id)
Find a codec that can be used for decoding.
static ICodec * findDecodingCodecByIntID (int id)
Find a codec that can be used for decoding.
static ICodec * findDecodingCodecByName (const char *id)
Find a codec that can be used for decoding.
static ICodec * guessEncodingCodec (IContainerFormat *fmt, const char *shortName, const char *url, const char *mimeType, ICodec::Type type)
Ask us to guess an encoding codec based on the inputs passed in.
static int32_t getNumInstalledCodecs ()
Get the number of installed codecs on this system.
static ICodec * getInstalledCodec (int32_t index)
Get the ICodec at the given index.
Protected Member Functions
ICodec ()
virtual ~ICodec ()
Member Enumeration Documentation
enum com::xuggle::xuggler::ICodec::ID
These are the codecs this library currently supports.
These are based on FFMPEG Git versions later than this: 391a1327bd076c25c2b2509ab7ae0081c443b94e
Enumerator:
CODEC_ID_NONE
CODEC_ID_MPEG1VIDEO
CODEC_ID_MPEG2VIDEO
CODEC_ID_MPEG2VIDEO_XVMC
CODEC_ID_H261
CODEC_ID_H263
CODEC_ID_RV10
CODEC_ID_RV20
CODEC_ID_MJPEG
CODEC_ID_MJPEGB
CODEC_ID_LJPEG
CODEC_ID_SP5X
CODEC_ID_JPEGLS
CODEC_ID_MPEG4
CODEC_ID_RAWVIDEO
CODEC_ID_MSMPEG4V1
CODEC_ID_MSMPEG4V2
CODEC_ID_MSMPEG4V3
CODEC_ID_WMV1
CODEC_ID_WMV2
CODEC_ID_H263P
CODEC_ID_H263I
CODEC_ID_FLV1
CODEC_ID_SVQ1
CODEC_ID_SVQ3
CODEC_ID_DVVIDEO
CODEC_ID_HUFFYUV
CODEC_ID_CYUV
CODEC_ID_H264
CODEC_ID_INDEO3
CODEC_ID_VP3
CODEC_ID_THEORA
CODEC_ID_ASV1
CODEC_ID_ASV2
CODEC_ID_FFV1
CODEC_ID_4XM
CODEC_ID_VCR1
CODEC_ID_CLJR
CODEC_ID_MDEC
CODEC_ID_ROQ
CODEC_ID_INTERPLAY_VIDEO
CODEC_ID_XAN_WC3
CODEC_ID_XAN_WC4
CODEC_ID_RPZA
CODEC_ID_CINEPAK
CODEC_ID_WS_VQA
CODEC_ID_MSRLE
CODEC_ID_MSVIDEO1
CODEC_ID_IDCIN
CODEC_ID_8BPS
CODEC_ID_SMC
CODEC_ID_FLIC
CODEC_ID_TRUEMOTION1
CODEC_ID_VMDVIDEO
CODEC_ID_MSZH
CODEC_ID_ZLIB
CODEC_ID_QTRLE
CODEC_ID_SNOW
CODEC_ID_TSCC
CODEC_ID_ULTI
CODEC_ID_QDRAW
CODEC_ID_VIXL
CODEC_ID_QPEG
CODEC_ID_XVID
CODEC_ID_PNG
CODEC_ID_PPM
CODEC_ID_PBM
CODEC_ID_PGM
CODEC_ID_PGMYUV
CODEC_ID_PAM
CODEC_ID_FFVHUFF
CODEC_ID_RV30
CODEC_ID_RV40
CODEC_ID_VC1
CODEC_ID_WMV3
CODEC_ID_LOCO
CODEC_ID_WNV1
CODEC_ID_AASC
CODEC_ID_INDEO2
CODEC_ID_FRAPS
CODEC_ID_TRUEMOTION2
CODEC_ID_BMP
CODEC_ID_CSCD
CODEC_ID_MMVIDEO
CODEC_ID_ZMBV
CODEC_ID_AVS
CODEC_ID_SMACKVIDEO
CODEC_ID_NUV
CODEC_ID_KMVC
CODEC_ID_FLASHSV
CODEC_ID_CAVS
CODEC_ID_JPEG2000
CODEC_ID_VMNC
CODEC_ID_VP5
CODEC_ID_VP6
CODEC_ID_VP6F
CODEC_ID_TARGA
CODEC_ID_DSICINVIDEO
CODEC_ID_TIERTEXSEQVIDEO
CODEC_ID_TIFF
CODEC_ID_GIF
CODEC_ID_FFH264
CODEC_ID_DXA
CODEC_ID_DNXHD
CODEC_ID_THP
CODEC_ID_SGI
CODEC_ID_C93
CODEC_ID_BETHSOFTVID
CODEC_ID_PTX
CODEC_ID_TXD
CODEC_ID_VP6A
CODEC_ID_AMV
CODEC_ID_VB
CODEC_ID_PCX
CODEC_ID_SUNRAST
CODEC_ID_INDEO4
CODEC_ID_INDEO5
CODEC_ID_MIMIC
CODEC_ID_RL2
CODEC_ID_8SVX_EXP
CODEC_ID_8SVX_FIB
CODEC_ID_ESCAPE124
CODEC_ID_DIRAC
CODEC_ID_BFI
CODEC_ID_CMV
CODEC_ID_MOTIONPIXELS
CODEC_ID_TGV
CODEC_ID_TGQ
CODEC_ID_TQI
CODEC_ID_AURA
CODEC_ID_AURA2
CODEC_ID_V210X
CODEC_ID_TMV
CODEC_ID_V210
CODEC_ID_DPX
CODEC_ID_MAD
CODEC_ID_FRWU
CODEC_ID_FLASHSV2
CODEC_ID_CDGRAPHICS
CODEC_ID_R210
CODEC_ID_ANM
CODEC_ID_BINKVIDEO
CODEC_ID_IFF_ILBM
CODEC_ID_IFF_BYTERUN1
CODEC_ID_KGV1
CODEC_ID_YOP
CODEC_ID_VP8
CODEC_ID_PICTOR
CODEC_ID_ANSI
CODEC_ID_A64_MULTI
CODEC_ID_A64_MULTI5
CODEC_ID_R10K
CODEC_ID_MXPEG
CODEC_ID_LAGARITH
CODEC_ID_PRORES
CODEC_ID_JV
CODEC_ID_DFA
CODEC_ID_8SVX_RAW
CODEC_ID_PCM_S16LE
CODEC_ID_PCM_S16BE
CODEC_ID_PCM_U16LE
CODEC_ID_PCM_U16BE
CODEC_ID_PCM_S8
CODEC_ID_PCM_U8
CODEC_ID_PCM_MULAW
CODEC_ID_PCM_ALAW
CODEC_ID_PCM_S32LE
CODEC_ID_PCM_S32BE
CODEC_ID_PCM_U32LE
CODEC_ID_PCM_U32BE
CODEC_ID_PCM_S24LE
CODEC_ID_PCM_S24BE
CODEC_ID_PCM_U24LE
CODEC_ID_PCM_U24BE
CODEC_ID_PCM_S24DAUD
CODEC_ID_PCM_ZORK
CODEC_ID_PCM_S16LE_PLANAR
CODEC_ID_PCM_DVD
CODEC_ID_PCM_F32BE
CODEC_ID_PCM_F32LE
CODEC_ID_PCM_F64BE
CODEC_ID_PCM_F64LE
CODEC_ID_PCM_BLURAY
CODEC_ID_PCM_LXF
CODEC_ID_S302M
CODEC_ID_ADPCM_IMA_QT
CODEC_ID_ADPCM_IMA_WAV
CODEC_ID_ADPCM_IMA_DK3
CODEC_ID_ADPCM_IMA_DK4
CODEC_ID_ADPCM_IMA_WS
CODEC_ID_ADPCM_IMA_SMJPEG
CODEC_ID_ADPCM_MS
CODEC_ID_ADPCM_4XM
CODEC_ID_ADPCM_XA
CODEC_ID_ADPCM_ADX
CODEC_ID_ADPCM_EA
CODEC_ID_ADPCM_G726
CODEC_ID_ADPCM_CT
CODEC_ID_ADPCM_SWF
CODEC_ID_ADPCM_YAMAHA
CODEC_ID_ADPCM_SBPRO_4
CODEC_ID_ADPCM_SBPRO_3
CODEC_ID_ADPCM_SBPRO_2
CODEC_ID_ADPCM_THP
CODEC_ID_ADPCM_IMA_AMV
CODEC_ID_ADPCM_EA_R1
CODEC_ID_ADPCM_EA_R3
CODEC_ID_ADPCM_EA_R2
CODEC_ID_ADPCM_IMA_EA_SEAD
CODEC_ID_ADPCM_IMA_EA_EACS
CODEC_ID_ADPCM_EA_XAS
CODEC_ID_ADPCM_EA_MAXIS_XA
CODEC_ID_ADPCM_IMA_ISS
CODEC_ID_ADPCM_G722
CODEC_ID_AMR_NB
CODEC_ID_AMR_WB
CODEC_ID_RA_144
CODEC_ID_RA_288
CODEC_ID_ROQ_DPCM
CODEC_ID_INTERPLAY_DPCM
CODEC_ID_XAN_DPCM
CODEC_ID_SOL_DPCM
CODEC_ID_MP2
CODEC_ID_MP3
CODEC_ID_AAC
CODEC_ID_AC3
CODEC_ID_DTS
CODEC_ID_VORBIS
CODEC_ID_DVAUDIO
CODEC_ID_WMAV1
CODEC_ID_WMAV2
CODEC_ID_MACE3
CODEC_ID_MACE6
CODEC_ID_VMDAUDIO
CODEC_ID_SONIC
CODEC_ID_SONIC_LS
CODEC_ID_FLAC
CODEC_ID_MP3ADU
CODEC_ID_MP3ON4
CODEC_ID_SHORTEN
CODEC_ID_ALAC
CODEC_ID_WESTWOOD_SND1
CODEC_ID_GSM
CODEC_ID_QDM2
CODEC_ID_COOK
CODEC_ID_TRUESPEECH
CODEC_ID_TTA
CODEC_ID_SMACKAUDIO
CODEC_ID_QCELP
CODEC_ID_WAVPACK
CODEC_ID_DSICINAUDIO
CODEC_ID_IMC
CODEC_ID_MUSEPACK7
CODEC_ID_MLP
CODEC_ID_GSM_MS
CODEC_ID_ATRAC3
CODEC_ID_VOXWARE
CODEC_ID_APE
CODEC_ID_NELLYMOSER
CODEC_ID_MUSEPACK8
CODEC_ID_SPEEX
CODEC_ID_WMAVOICE
CODEC_ID_WMAPRO
CODEC_ID_WMALOSSLESS
CODEC_ID_ATRAC3P
CODEC_ID_EAC3
CODEC_ID_SIPR
CODEC_ID_MP1
CODEC_ID_TWINVQ
CODEC_ID_TRUEHD
CODEC_ID_MP4ALS
CODEC_ID_ATRAC1
CODEC_ID_BINKAUDIO_RDFT
CODEC_ID_BINKAUDIO_DCT
CODEC_ID_AAC_LATM
CODEC_ID_QDMC
CODEC_ID_CELT
CODEC_ID_DVD_SUBTITLE
CODEC_ID_DVB_SUBTITLE
CODEC_ID_TEXT
CODEC_ID_XSUB
CODEC_ID_SSA
CODEC_ID_MOV_TEXT
CODEC_ID_HDMV_PGS_SUBTITLE
CODEC_ID_DVB_TELETEXT
CODEC_ID_SRT
CODEC_ID_MICRODVD
CODEC_ID_TTF
CODEC_ID_PROBE
CODEC_ID_MPEG2TS
CODEC_ID_FFMETADATA
Definition at line 50 of file ICodec.h.
  {
    CODEC_ID_NONE,
    CODEC_ID_MPEG1VIDEO,
    CODEC_ID_MPEG2VIDEO,
    CODEC_ID_MPEG2VIDEO_XVMC,
    CODEC_ID_H261,
    CODEC_ID_H263,
    CODEC_ID_RV10,
    CODEC_ID_RV20,
    CODEC_ID_MJPEG,
    CODEC_ID_MJPEGB,
    CODEC_ID_LJPEG,
    CODEC_ID_SP5X,
    CODEC_ID_JPEGLS,
    CODEC_ID_MPEG4,
    CODEC_ID_RAWVIDEO,
    CODEC_ID_MSMPEG4V1,
    CODEC_ID_MSMPEG4V2,
    CODEC_ID_MSMPEG4V3,
    CODEC_ID_WMV1,
    CODEC_ID_WMV2,
    CODEC_ID_H263P,
    CODEC_ID_H263I,
    CODEC_ID_FLV1,
    CODEC_ID_SVQ1,
    CODEC_ID_SVQ3,
    CODEC_ID_DVVIDEO,
    CODEC_ID_HUFFYUV,
    CODEC_ID_CYUV,
    CODEC_ID_H264,
    CODEC_ID_INDEO3,
    CODEC_ID_VP3,
    CODEC_ID_THEORA,
    CODEC_ID_ASV1,
    CODEC_ID_ASV2,
    CODEC_ID_FFV1,
    CODEC_ID_4XM,
    CODEC_ID_VCR1,
    CODEC_ID_CLJR,
    CODEC_ID_MDEC,
    CODEC_ID_ROQ,
    CODEC_ID_INTERPLAY_VIDEO,
    CODEC_ID_XAN_WC3,
    CODEC_ID_XAN_WC4,
    CODEC_ID_RPZA,
    CODEC_ID_CINEPAK,
    CODEC_ID_WS_VQA,
    CODEC_ID_MSRLE,
    CODEC_ID_MSVIDEO1,
    CODEC_ID_IDCIN,
    CODEC_ID_8BPS,
    CODEC_ID_SMC,
    CODEC_ID_FLIC,
    CODEC_ID_TRUEMOTION1,
    CODEC_ID_VMDVIDEO,
    CODEC_ID_MSZH,
    CODEC_ID_ZLIB,
    CODEC_ID_QTRLE,
    CODEC_ID_SNOW,
    CODEC_ID_TSCC,
    CODEC_ID_ULTI,
    CODEC_ID_QDRAW,
    CODEC_ID_VIXL,
    CODEC_ID_QPEG,
#if LIBAVCODEC_VERSION_MAJOR < 53
    CODEC_ID_XVID,
#endif
    CODEC_ID_PNG,
    CODEC_ID_PPM,
    CODEC_ID_PBM,
    CODEC_ID_PGM,
    CODEC_ID_PGMYUV,
    CODEC_ID_PAM,
    CODEC_ID_FFVHUFF,
    CODEC_ID_RV30,
    CODEC_ID_RV40,
    CODEC_ID_VC1,
    CODEC_ID_WMV3,
    CODEC_ID_LOCO,
    CODEC_ID_WNV1,
    CODEC_ID_AASC,
    CODEC_ID_INDEO2,
    CODEC_ID_FRAPS,
    CODEC_ID_TRUEMOTION2,
    CODEC_ID_BMP,
    CODEC_ID_CSCD,
    CODEC_ID_MMVIDEO,
    CODEC_ID_ZMBV,
    CODEC_ID_AVS,
    CODEC_ID_SMACKVIDEO,
    CODEC_ID_NUV,
    CODEC_ID_KMVC,
    CODEC_ID_FLASHSV,
    CODEC_ID_CAVS,
    CODEC_ID_JPEG2000,
    CODEC_ID_VMNC,
    CODEC_ID_VP5,
    CODEC_ID_VP6,
    CODEC_ID_VP6F,
    CODEC_ID_TARGA,
    CODEC_ID_DSICINVIDEO,
    CODEC_ID_TIERTEXSEQVIDEO,
    CODEC_ID_TIFF,
    CODEC_ID_GIF,
    CODEC_ID_FFH264,
    CODEC_ID_DXA,
    CODEC_ID_DNXHD,
    CODEC_ID_THP,
    CODEC_ID_SGI,
    CODEC_ID_C93,
    CODEC_ID_BETHSOFTVID,
    CODEC_ID_PTX,
    CODEC_ID_TXD,
    CODEC_ID_VP6A,
    CODEC_ID_AMV,
    CODEC_ID_VB,
    CODEC_ID_PCX,
    CODEC_ID_SUNRAST,
    CODEC_ID_INDEO4,
    CODEC_ID_INDEO5,
    CODEC_ID_MIMIC,
    CODEC_ID_RL2,
    CODEC_ID_8SVX_EXP,
    CODEC_ID_8SVX_FIB,
    CODEC_ID_ESCAPE124,
    CODEC_ID_DIRAC,
    CODEC_ID_BFI,
    CODEC_ID_CMV,
    CODEC_ID_MOTIONPIXELS,
    CODEC_ID_TGV,
    CODEC_ID_TGQ,
    CODEC_ID_TQI,
    CODEC_ID_AURA,
    CODEC_ID_AURA2,
    CODEC_ID_V210X,
    CODEC_ID_TMV,
    CODEC_ID_V210,
    CODEC_ID_DPX,
    CODEC_ID_MAD,
    CODEC_ID_FRWU,
    CODEC_ID_FLASHSV2,
    CODEC_ID_CDGRAPHICS,
    CODEC_ID_R210,
    CODEC_ID_ANM,
    CODEC_ID_BINKVIDEO,
    CODEC_ID_IFF_ILBM,
    CODEC_ID_IFF_BYTERUN1,
    CODEC_ID_KGV1,
    CODEC_ID_YOP,
    CODEC_ID_VP8,
    CODEC_ID_PICTOR,
    CODEC_ID_ANSI,
    CODEC_ID_A64_MULTI,
    CODEC_ID_A64_MULTI5,
    CODEC_ID_R10K,
    CODEC_ID_MXPEG,
    CODEC_ID_LAGARITH,
    CODEC_ID_PRORES,
    CODEC_ID_JV,
    CODEC_ID_DFA,
    CODEC_ID_8SVX_RAW,
    CODEC_ID_PCM_S16LE= 0x10000,
    CODEC_ID_PCM_S16BE,
    CODEC_ID_PCM_U16LE,
    CODEC_ID_PCM_U16BE,
    CODEC_ID_PCM_S8,
    CODEC_ID_PCM_U8,
    CODEC_ID_PCM_MULAW,
    CODEC_ID_PCM_ALAW,
    CODEC_ID_PCM_S32LE,
    CODEC_ID_PCM_S32BE,
    CODEC_ID_PCM_U32LE,
    CODEC_ID_PCM_U32BE,
    CODEC_ID_PCM_S24LE,
    CODEC_ID_PCM_S24BE,
    CODEC_ID_PCM_U24LE,
    CODEC_ID_PCM_U24BE,
    CODEC_ID_PCM_S24DAUD,
    CODEC_ID_PCM_ZORK,
    CODEC_ID_PCM_S16LE_PLANAR,
    CODEC_ID_PCM_DVD,
    CODEC_ID_PCM_F32BE,
    CODEC_ID_PCM_F32LE,
    CODEC_ID_PCM_F64BE,
    CODEC_ID_PCM_F64LE,
    CODEC_ID_PCM_BLURAY,
    CODEC_ID_PCM_LXF,
    CODEC_ID_S302M,
    CODEC_ID_ADPCM_IMA_QT= 0x11000,
    CODEC_ID_ADPCM_IMA_WAV,
    CODEC_ID_ADPCM_IMA_DK3,
    CODEC_ID_ADPCM_IMA_DK4,
    CODEC_ID_ADPCM_IMA_WS,
    CODEC_ID_ADPCM_IMA_SMJPEG,
    CODEC_ID_ADPCM_MS,
    CODEC_ID_ADPCM_4XM,
    CODEC_ID_ADPCM_XA,
    CODEC_ID_ADPCM_ADX,
    CODEC_ID_ADPCM_EA,
    CODEC_ID_ADPCM_G726,
    CODEC_ID_ADPCM_CT,
    CODEC_ID_ADPCM_SWF,
    CODEC_ID_ADPCM_YAMAHA,
    CODEC_ID_ADPCM_SBPRO_4,
    CODEC_ID_ADPCM_SBPRO_3,
    CODEC_ID_ADPCM_SBPRO_2,
    CODEC_ID_ADPCM_THP,
    CODEC_ID_ADPCM_IMA_AMV,
    CODEC_ID_ADPCM_EA_R1,
    CODEC_ID_ADPCM_EA_R3,
    CODEC_ID_ADPCM_EA_R2,
    CODEC_ID_ADPCM_IMA_EA_SEAD,
    CODEC_ID_ADPCM_IMA_EA_EACS,
    CODEC_ID_ADPCM_EA_XAS,
    CODEC_ID_ADPCM_EA_MAXIS_XA,
    CODEC_ID_ADPCM_IMA_ISS,
    CODEC_ID_ADPCM_G722,
    CODEC_ID_AMR_NB= 0x12000,
    CODEC_ID_AMR_WB,
    CODEC_ID_RA_144= 0x13000,
    CODEC_ID_RA_288,
    CODEC_ID_ROQ_DPCM= 0x14000,
    CODEC_ID_INTERPLAY_DPCM,
    CODEC_ID_XAN_DPCM,
    CODEC_ID_SOL_DPCM,
    CODEC_ID_MP2= 0x15000,
    CODEC_ID_MP3,
    CODEC_ID_AAC,
    CODEC_ID_AC3,
    CODEC_ID_DTS,
    CODEC_ID_VORBIS,
    CODEC_ID_DVAUDIO,
    CODEC_ID_WMAV1,
    CODEC_ID_WMAV2,
    CODEC_ID_MACE3,
    CODEC_ID_MACE6,
    CODEC_ID_VMDAUDIO,
    CODEC_ID_SONIC,
    CODEC_ID_SONIC_LS,
    CODEC_ID_FLAC,
    CODEC_ID_MP3ADU,
    CODEC_ID_MP3ON4,
    CODEC_ID_SHORTEN,
    CODEC_ID_ALAC,
    CODEC_ID_WESTWOOD_SND1,
    CODEC_ID_GSM,
    CODEC_ID_QDM2,
    CODEC_ID_COOK,
    CODEC_ID_TRUESPEECH,
    CODEC_ID_TTA,
    CODEC_ID_SMACKAUDIO,
    CODEC_ID_QCELP,
    CODEC_ID_WAVPACK,
    CODEC_ID_DSICINAUDIO,
    CODEC_ID_IMC,
    CODEC_ID_MUSEPACK7,
    CODEC_ID_MLP,
    CODEC_ID_GSM_MS,
    CODEC_ID_ATRAC3,
    CODEC_ID_VOXWARE,
    CODEC_ID_APE,
    CODEC_ID_NELLYMOSER,
    CODEC_ID_MUSEPACK8,
    CODEC_ID_SPEEX,
    CODEC_ID_WMAVOICE,
    CODEC_ID_WMAPRO,
    CODEC_ID_WMALOSSLESS,
    CODEC_ID_ATRAC3P,
    CODEC_ID_EAC3,
    CODEC_ID_SIPR,
    CODEC_ID_MP1,
    CODEC_ID_TWINVQ,
    CODEC_ID_TRUEHD,
    CODEC_ID_MP4ALS,
    CODEC_ID_ATRAC1,
    CODEC_ID_BINKAUDIO_RDFT,
    CODEC_ID_BINKAUDIO_DCT,
    CODEC_ID_AAC_LATM,
    CODEC_ID_QDMC,
    CODEC_ID_CELT,
    CODEC_ID_DVD_SUBTITLE= 0x17000,
    CODEC_ID_DVB_SUBTITLE,
    CODEC_ID_TEXT,
    CODEC_ID_XSUB,
    CODEC_ID_SSA,
    CODEC_ID_MOV_TEXT,
    CODEC_ID_HDMV_PGS_SUBTITLE,
    CODEC_ID_DVB_TELETEXT,
    CODEC_ID_SRT,
    CODEC_ID_MICRODVD,
    CODEC_ID_TTF= 0x18000,
    CODEC_ID_PROBE= 0x19000,
    CODEC_ID_MPEG2TS= 0x20000,
    CODEC_ID_FFMETADATA=0x21000,
  } ID;
enum com::xuggle::xuggler::ICodec::Type
The different types of Codecs that can exist in the system.
Enumerator:
CODEC_TYPE_UNKNOWN
CODEC_TYPE_VIDEO
CODEC_TYPE_AUDIO
CODEC_TYPE_DATA
CODEC_TYPE_SUBTITLE
CODEC_TYPE_ATTACHMENT
Definition at line 363 of file ICodec.h.
  {
    CODEC_TYPE_UNKNOWN = -1,
    CODEC_TYPE_VIDEO,
    CODEC_TYPE_AUDIO,
    CODEC_TYPE_DATA,
    CODEC_TYPE_SUBTITLE,
    CODEC_TYPE_ATTACHMENT
  } Type;
enum com::xuggle::xuggler::ICodec::Capabilities
Capability flags.
Enumerator:
CAP_DRAW_HORIZ_BAND
CAP_DR1
CAP_PARSE_ONLY
CAP_TRUNCATED
CAP_HWACCEL
CAP_DELAY
CAP_SMALL_LAST_FRAME
CAP_HWACCEL_VDPAU
CAP_SUBFRAMES
Definition at line 503 of file ICodec.h.
  {
    CAP_DRAW_HORIZ_BAND = 0x0001,
    CAP_DR1 = 0x0002,
    CAP_PARSE_ONLY = 0x0004,
    CAP_TRUNCATED = 0x0008,
    CAP_HWACCEL = 0x0010,
    CAP_DELAY = 0x0020,
    CAP_SMALL_LAST_FRAME = 0x0040,
    CAP_HWACCEL_VDPAU = 0x0080,
    CAP_SUBFRAMES =0x0100,
  } Capabilities;
Constructor & Destructor Documentation
com::xuggle::xuggler::ICodec::ICodec () [protected]
Definition at line 29 of file ICodec.cpp.
  {
  }
com::xuggle::xuggler::ICodec::~ICodec () [protected, virtual]
Definition at line 33 of file ICodec.cpp.
  {
  }
Member Function Documentation
virtual const char* com::xuggle::xuggler::ICodec::getName () [pure virtual]
Get the name of the codec.
Returns:
The name of this Codec.
Implemented in com::xuggle::xuggler::Codec.
virtual int com::xuggle::xuggler::ICodec::getIDAsInt () [pure virtual]
Get the ID of this codec, as an integer.
Returns:
the ID of this codec, as an integer.
Implemented in com::xuggle::xuggler::Codec.
virtual ID com::xuggle::xuggler::ICodec::getID () [pure virtual]
Get the ID of this codec as an enumeration.
Returns:
the ID of this codec, an enum ID
Implemented in com::xuggle::xuggler::Codec.
virtual Type com::xuggle::xuggler::ICodec::getType () [pure virtual]
Get the type of this codec.
Returns:
The type of this Codec, as a enum Type
Implemented in com::xuggle::xuggler::Codec.
virtual bool com::xuggle::xuggler::ICodec::canDecode () [pure virtual]
Can this codec be used for decoding?
Returns:
Can this Codec decode?
Implemented in com::xuggle::xuggler::Codec.
virtual bool com::xuggle::xuggler::ICodec::canEncode () [pure virtual]
Can this codec be used for encoding?
Returns:
Can this Codec encode?
Implemented in com::xuggle::xuggler::Codec.
ICodec * com::xuggle::xuggler::ICodec::findEncodingCodec (ICodec::ID id) [static]
Find a codec that can be used for encoding.
Parameters:
id The id of the codec
Returns:
the codec, or null if we can't find it.
Reimplemented in com::xuggle::xuggler::Codec.
Definition at line 38 of file ICodec.cpp.
References com::xuggle::xuggler::Codec::findEncodingCodec(), and com::xuggle::xuggler::Global::init().
  {
    Global::init();
    return Codec::findEncodingCodec(id);
  }
ICodec * com::xuggle::xuggler::ICodec::findEncodingCodecByIntID (int id) [static]
Find a codec that can be used for encoding.
Parameters:
id The id of the codec, as an integer.
Returns:
the codec, or null if we can't find it.
Reimplemented in com::xuggle::xuggler::Codec.
Definition at line 45 of file ICodec.cpp.
References com::xuggle::xuggler::Codec::findEncodingCodecByIntID(), and com::xuggle::xuggler::Global::init().
  {
    Global::init();
    return Codec::findEncodingCodecByIntID(id);
  }
ICodec * com::xuggle::xuggler::ICodec::findEncodingCodecByName (const char * id) [static]
Find a codec that can be used for encoding.
Parameters:
id The id of the codec, as a FFMPEG short-name string (for example, "mpeg4").
Returns:
the codec, or null if we can't find it.
Reimplemented in com::xuggle::xuggler::Codec.
Definition at line 52 of file ICodec.cpp.
References com::xuggle::xuggler::Codec::findEncodingCodecByName(), and com::xuggle::xuggler::Global::init().
  {
    Global::init();
    return Codec::findEncodingCodecByName(name);
  }
ICodec * com::xuggle::xuggler::ICodec::findDecodingCodec (ICodec::ID id) [static]
Find a codec that can be used for decoding.
Parameters:
id The id of the codec
Returns:
the codec, or null if we can't find it.
Reimplemented in com::xuggle::xuggler::Codec.
Definition at line 59 of file ICodec.cpp.
References com::xuggle::xuggler::Codec::findDecodingCodec(), and com::xuggle::xuggler::Global::init().
Referenced by com::xuggle::xuggler::Container::setForcedAudioCodec(), com::xuggle::xuggler::Container::setForcedSubtitleCodec(), and com::xuggle::xuggler::Container::setForcedVideoCodec().
  {
    Global::init();
    return Codec::findDecodingCodec(id);
  }
ICodec * com::xuggle::xuggler::ICodec::findDecodingCodecByIntID (int id) [static]
Find a codec that can be used for decoding.
Parameters:
id The id of the codec, as an integer
Returns:
the codec, or null if we can't find it.
Reimplemented in com::xuggle::xuggler::Codec.
Definition at line 66 of file ICodec.cpp.
References com::xuggle::xuggler::Codec::findDecodingCodecByIntID(), and com::xuggle::xuggler::Global::init().
  {
    Global::init();
    return Codec::findDecodingCodecByIntID(id);
  }
ICodec * com::xuggle::xuggler::ICodec::findDecodingCodecByName (const char * id) [static]
Find a codec that can be used for decoding.
Parameters:
id The id of the codec, as a FFMPEG short-name string (for example, "mpeg4")
Returns:
the codec, or null if we can't find it.
Reimplemented in com::xuggle::xuggler::Codec.
Definition at line 73 of file ICodec.cpp.
References com::xuggle::xuggler::Codec::findDecodingCodecByName(), and com::xuggle::xuggler::Global::init().
  {
    Global::init();
    return Codec::findDecodingCodecByName(name);
  }
ICodec * com::xuggle::xuggler::ICodec::guessEncodingCodec (IContainerFormat * fmt, const char * shortName, const char * url, const char * mimeType, ICodec::Type type) [static]
Ask us to guess an encoding codec based on the inputs passed in.
You must pass in at least one non null fmt, shortName, url or mime_type.
Parameters:
fmt An IContainerFormat for the container you'll want to encode into.
shortName The FFMPEG short name of the codec (e.g. "mpeg4").
url The URL you'll be writing packets to.
mimeType The mime type of the container.
type The codec type.
Returns:
the codec, or null if we can't find it.
Reimplemented in com::xuggle::xuggler::Codec.
Definition at line 80 of file ICodec.cpp.
References com::xuggle::xuggler::Codec::guessEncodingCodec(), and com::xuggle::xuggler::Global::init().
  {
    Global::init();
    return Codec::guessEncodingCodec(fmt, shortName, url, mimeType, type);
  }
virtual const char* com::xuggle::xuggler::ICodec::getLongName () [pure virtual]
Added for 1.17.
Get the long name for this codec.
Returns:
the long name.
Implemented in com::xuggle::xuggler::Codec.
virtual int32_t com::xuggle::xuggler::ICodec::getCapabilities () [pure virtual]
Get the capabilites flag from the codec.
Returns:
the capabilities flag
Implemented in com::xuggle::xuggler::Codec.
virtual bool com::xuggle::xuggler::ICodec::hasCapability (Capabilities capability) [pure virtual]
Convenience method to check individual capability flags.
Parameters:
capability the capability
Returns:
true if flag is set; false otherwise.
Implemented in com::xuggle::xuggler::Codec.
int32_t com::xuggle::xuggler::ICodec::getNumInstalledCodecs () [static]
Get the number of installed codecs on this system.
Returns:
the number of installed codecs.
Definition at line 91 of file ICodec.cpp.
References com::xuggle::xuggler::Global::init().
  {
    Global::init();
    int32_t numInstalledCodecs = 0;
    AVCodec * codec = 0;
    while((codec = av_codec_next(codec))!=0)
      ++numInstalledCodecs;
    return numInstalledCodecs;
  }
ICodec * com::xuggle::xuggler::ICodec::getInstalledCodec (int32_t index) [static]
Get the ICodec at the given index.
Parameters:
index the index in our list
Returns:
the codec, or null if index < 0 or index >= getNumInstalledCodecs()
Definition at line 102 of file ICodec.cpp.
References com::xuggle::xuggler::Global::init(), and com::xuggle::xuggler::Codec::make().
  {
    Global::init();
    if (index < 0)
      return 0;
    AVCodec * codec = 0;
    for(int32_t i = 0; (codec = av_codec_next(codec))!=0; i++)
    {
      if (i == index)
        return Codec::make(codec);
    }
    return 0;
  }
virtual int32_t com::xuggle::xuggler::ICodec::getNumSupportedVideoFrameRates () [pure virtual]
Get the number of frame rates this codec supports for encoding.
Not all codecs will report this number.
Returns:
the number or 0 if we don't know.
Implemented in com::xuggle::xuggler::Codec.
virtual IRational* com::xuggle::xuggler::ICodec::getSupportedVideoFrameRate (int32_t index) [pure virtual]
Return the supported frame rate at the given index.
Parameters:
index the index in our list.
Returns:
the frame rate, or null if unknown, if index <0 or if index >= getNumSupportedVideoFrameRates()
Implemented in com::xuggle::xuggler::Codec.
virtual int32_t com::xuggle::xuggler::ICodec::getNumSupportedVideoPixelFormats () [pure virtual]
Get the number of supported video pixel formats this codec supports for encoding.
Not all codecs will report this.
Returns:
the number or 0 if we don't know.
Implemented in com::xuggle::xuggler::Codec.
virtual IPixelFormat::Type com::xuggle::xuggler::ICodec::getSupportedVideoPixelFormat (int32_t index) [pure virtual]
Return the supported video pixel format at the given index.
Parameters:
index the index in our list.
Returns:
the pixel format, or IPixelFormat.Type#NONE if unknown, if index <0 or if index >= getNumSupportedVideoPixelFormats()
Implemented in com::xuggle::xuggler::Codec.
virtual int32_t com::xuggle::xuggler::ICodec::getNumSupportedAudioSampleRates () [pure virtual]
Get the number of different audio sample rates this codec supports for encoding.
Not all codecs will report this.
Returns:
the number or 0 if we don't know.
Implemented in com::xuggle::xuggler::Codec.
virtual int32_t com::xuggle::xuggler::ICodec::getSupportedAudioSampleRate (int32_t index) [pure virtual]
Return the support audio sample rate at the given index.
Parameters:
index the index in our list.
Returns:
the sample rate, or 0 if unknown, index < 0 or index >= getNumSupportedAudioSampleRates()
Implemented in com::xuggle::xuggler::Codec.
virtual int32_t com::xuggle::xuggler::ICodec::getNumSupportedAudioSampleFormats () [pure virtual]
Get the number of different audio sample formats this codec supports for encoding.
Not all codecs will report this.
Returns:
the number or 0 if we don't know.
Implemented in com::xuggle::xuggler::Codec.
virtual IAudioSamples::Format com::xuggle::xuggler::ICodec::getSupportedAudioSampleFormat (int32_t index) [pure virtual]
Get the supported sample format at this index.
Parameters:
index the index in our list.
Returns:
the format, or IAudioSamples.Format.FMT_NONE if unknown, index < 0 or index >= getNumSupportedAudioSampleFormats().
Implemented in com::xuggle::xuggler::Codec.
virtual int32_t com::xuggle::xuggler::ICodec::getNumSupportedAudioChannelLayouts () [pure virtual]
Get the number of different audio channel layouts this codec supports for encoding.
Not all codecs will report this.
Returns:
the number or 0 if we don't know.
Implemented in com::xuggle::xuggler::Codec.
virtual int64_t com::xuggle::xuggler::ICodec::getSupportedAudioChannelLayout (int32_t index) [pure virtual]
Get the supported audio channel layout at this index.
The value returned is a bit flag representing the different types of audio layout this codec can support. Test the values by bit-comparing them to the IAudioSamples.ChannelLayout enum types.
Parameters:
index the index
Returns:
the channel layout, or 0 if unknown, index < 0 or index >= getNumSupportedAudioChannelLayouts.
Implemented in com::xuggle::xuggler::Codec.
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/ICodec.h
csrc/com/xuggle/xuggler/ICodec.cpp