Xuggle: com::xuggle::xuggler::AudioSamples Class Reference
com::xuggle::xuggler::AudioSamples Class Reference
#include <AudioSamples.h>
Detailed Description
Definition at line 32 of file AudioSamples.h.
Public Member Functions
virtual int64_t getTimeStamp ()
Get the time stamp of this object in getTimeBase() units.
virtual void setTimeStamp (int64_t aTimeStamp)
Set the time stamp for this object in getTimeBase() units.
virtual IRational * getTimeBase ()
Get the time base that time stamps of this object are represented in.
virtual void setTimeBase (IRational *aBase)
Set the time base that time stamps of this object are represented in.
virtual int32_t getSize ()
Get the size in bytes of the raw data available for this object.
virtual bool isKey ()
Is this object a key object? i.e.
virtual bool isComplete ()
Returns whether or not we think this buffer has been filled with data.
virtual int32_t getSampleRate ()
Find the sample rate of the samples in this audio buffer.
virtual int32_t getChannels ()
Return the number of channels of the samples in this buffer.
virtual Format getFormat ()
Find the Format of the samples in this buffer.
virtual uint32_t getSampleBitDepth ()
Find out the bit-depth of the samples in this buffer.
virtual uint32_t getNumSamples ()
Get the number of samples in this video.
virtual uint32_t getMaxBufferSize ()
virtual uint32_t getSampleSize ()
virtual uint32_t getMaxSamples ()
virtual
com::xuggle::ferry::IBuffer * getData ()
Get any underlying raw data available for this object.
virtual int64_t getPts ()
What is the Presentation Time Stamp of this set of audio samples.
virtual void setPts (int64_t aValue)
Set the Presentation Time Stamp for this set of samples.
virtual int64_t getNextPts ()
What would be the next Presentation Time Stamp after all the samples in this buffer were played?
virtual int32_t setSample (uint32_t sampleIndex, int32_t channel, Format format, int32_t sample)
Sets the sample at the given index and channel to the sample.
virtual int32_t getSample (uint32_t sampleIndex, int32_t channel, Format format)
Get the sample at the given sampleIndex and channel, and return it in the asked for format.
virtual void setData (com::xuggle::ferry::IBuffer *buffer)
Sets the underlying buffer used by this object.
virtual void setComplete (bool complete, uint32_t numSamples, int32_t sampleRate, int32_t channels, Format sampleFmt, int64_t pts)
Call this if you modify the samples and are now done.
virtual short * getRawSamples (uint32_t startingSample)
virtual int32_t ensureCapacity (int32_t capacityInBytes)
Called by decoder before decoding to ensure sufficient space.
Static Public Member Functions
static AudioSamples * make (uint32_t numSamples, uint32_t numChannels)
Get a new audio samples buffer.
static AudioSamples * make (uint32_t numSamples, uint32_t numChannels, IAudioSamples::Format)
Get a new audio samples buffer.
static AudioSamples * make (com::xuggle::ferry::IBuffer *buffer, int channels, IAudioSamples::Format format)
Creates an IAudioSamples object by wrapping an object.
Protected Member Functions
AudioSamples ()
virtual ~AudioSamples ()
Constructor & Destructor Documentation
com::xuggle::xuggler::AudioSamples::AudioSamples () [protected]
Definition at line 35 of file AudioSamples.cpp.
References com::xuggle::xuggler::IAudioSamples::FMT_S16, com::xuggle::xuggler::IRational::make(), and com::xuggle::xuggler::Global::NO_PTS.
  {
    mSamples = 0;
    mNumSamples = 0;
    mSampleRate = 0;
    mChannels = 1;
    mIsComplete = false;
    mSampleFmt = FMT_S16;
    mPts = Global::NO_PTS;
    mRequestedSamples = 0;
    mTimeBase = IRational::make(1, 1000000);
  }
com::xuggle::xuggler::AudioSamples::~AudioSamples () [protected, virtual]
Definition at line 48 of file AudioSamples.cpp.
References com::xuggle::xuggler::IAudioSamples::FMT_S16, and com::xuggle::xuggler::Global::NO_PTS.
  {
    mSamples = 0;
    mNumSamples = 0;
    mSampleRate = 0;
    mChannels = 1;
    mIsComplete = false;
    mSampleFmt = FMT_S16;
    mPts = Global::NO_PTS;
    mRequestedSamples = 0;
  }
Member Function Documentation
virtual int64_t com::xuggle::xuggler::AudioSamples::getTimeStamp () [inline, virtual]
Get the time stamp of this object in getTimeBase() units.
Returns:
the time stamp
Implements com::xuggle::xuggler::IMediaData.
Definition at line 37 of file AudioSamples.h.
References getPts().
Referenced by com::xuggle::xuggler::StreamCoder::encodeAudio().
{ return getPts(); }
virtual void com::xuggle::xuggler::AudioSamples::setTimeStamp (int64_t aTimeStamp) [inline, virtual]
Set the time stamp for this object in getTimeBase() units.
Parameters:
aTimeStamp The time stamp
Implements com::xuggle::xuggler::IMediaData.
Definition at line 38 of file AudioSamples.h.
References setPts().
{ setPts(aTimeStamp); }
virtual IRational* com::xuggle::xuggler::AudioSamples::getTimeBase () [inline, virtual]
Get the time base that time stamps of this object are represented in.
Caller must release the returned value.
Returns:
the time base.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 39 of file AudioSamples.h.
{ return mTimeBase.get(); }
virtual void com::xuggle::xuggler::AudioSamples::setTimeBase (IRational * aBase) [inline, virtual]
Set the time base that time stamps of this object are represented in.
Parameters:
aBase the new time base. If null an exception is thrown.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 40 of file AudioSamples.h.
{ mTimeBase.reset(aBase, true); }
virtual int32_t com::xuggle::xuggler::AudioSamples::getSize () [inline, virtual]
Get the size in bytes of the raw data available for this object.
Returns:
the size in bytes, or -1 if it cannot be computed.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 41 of file AudioSamples.h.
References getNumSamples(), and getSampleSize().
{ return getNumSamples()*getSampleSize(); }
virtual bool com::xuggle::xuggler::AudioSamples::isKey () [inline, virtual]
Is this object a key object? i.e.
it can be interpreted without needing any other media objects
Returns:
true if it's a key, false if not
Implements com::xuggle::xuggler::IMediaData.
Definition at line 42 of file AudioSamples.h.
{ return true; }
bool com::xuggle::xuggler::AudioSamples::isComplete () [virtual]
Returns whether or not we think this buffer has been filled with data.
Returns:
Has setComplete() been called and the buffer populated.
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 194 of file AudioSamples.cpp.
Referenced by com::xuggle::xuggler::StreamCoder::encodeAudio(), and com::xuggle::xuggler::AudioResampler::resample().
  {
    return mIsComplete;
  }
int32_t com::xuggle::xuggler::AudioSamples::getSampleRate () [virtual]
Find the sample rate of the samples in this audio buffer.
Returns:
The Sampling Rate of the samples in this buffer (e.g. 22050).
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 206 of file AudioSamples.cpp.
Referenced by com::xuggle::xuggler::StreamCoder::encodeAudio(), getNextPts(), and com::xuggle::xuggler::AudioResampler::resample().
  {
    return mSampleRate;
  }
int32_t com::xuggle::xuggler::AudioSamples::getChannels () [virtual]
Return the number of channels of the samples in this buffer.
For example, 1 is mono, 2 is stereo.
Returns:
The number of channels.
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 212 of file AudioSamples.cpp.
Referenced by com::xuggle::xuggler::StreamCoder::encodeAudio(), getSampleSize(), and com::xuggle::xuggler::AudioResampler::resample().
  {
    return mChannels;
  }
IAudioSamples::Format com::xuggle::xuggler::AudioSamples::getFormat () [virtual]
Find the Format of the samples in this buffer.
Right now only FMT_S16 is supported.
Returns:
The format of the samples.
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 200 of file AudioSamples.cpp.
Referenced by com::xuggle::xuggler::AudioResampler::resample().
  {
    return mSampleFmt;
  }
uint32_t com::xuggle::xuggler::AudioSamples::getSampleBitDepth () [virtual]
Find out the bit-depth of the samples in this buffer.
Returns:
Number of bits in a raw sample (per channel)
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 231 of file AudioSamples.cpp.
References com::xuggle::xuggler::IAudioSamples::findSampleBitDepth().
Referenced by getSampleSize(), and com::xuggle::xuggler::AudioResampler::resample().
  {
    return IAudioSamples::findSampleBitDepth(mSampleFmt);
  }
uint32_t com::xuggle::xuggler::AudioSamples::getNumSamples () [virtual]
Get the number of samples in this video.
For example, if you have 100 bytes of stereo (2-channel) 16-bit audio in this buffer, there are 25 samples. If you have 100 bytes of mono (1-channel) 16-bit audio in this buffer, you have 50 samples.
Returns:
The number of samples.
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 218 of file AudioSamples.cpp.
Referenced by com::xuggle::xuggler::StreamCoder::encodeAudio(), getNextPts(), getSample(), getSize(), and com::xuggle::xuggler::AudioResampler::resample().
  {
    return mNumSamples;
  }
uint32_t com::xuggle::xuggler::AudioSamples::getMaxBufferSize () [virtual]
Returns:
Maximum number of bytes that can be put in this buffer. To get the number of samples you can put in this IAudioSamples instance, do the following num_samples = getMaxBufferSize() / (getSampleSize())
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 224 of file AudioSamples.cpp.
References VS_AUDIOSAMPLES_BUFFER_PADDING.
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), getMaxSamples(), com::xuggle::xuggler::AudioResampler::resample(), and setComplete().
  {
    allocInternalSamples();
    return mSamples->getBufferSize()-VS_AUDIOSAMPLES_BUFFER_PADDING;
  }
uint32_t com::xuggle::xuggler::AudioSamples::getSampleSize () [virtual]
Returns:
Number of bytes in a single sample of audio (including channels). You can also get this by getSampleBitDepth()*getChannels()/8.
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 237 of file AudioSamples.cpp.
References getChannels(), and getSampleBitDepth().
Referenced by com::xuggle::xuggler::StreamCoder::encodeAudio(), ensureCapacity(), getMaxSamples(), getRawSamples(), getSize(), and setComplete().
  {
    uint32_t bits = getSampleBitDepth();
    if (bits < 8)
      bits = 8;
    return bits/8 * getChannels();
  }
uint32_t com::xuggle::xuggler::AudioSamples::getMaxSamples () [virtual]
Returns:
Maximum number of samples this buffer can hold.
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 257 of file AudioSamples.cpp.
References getMaxBufferSize(), and getSampleSize().
Referenced by setSample().
  {
    return getMaxBufferSize() / getSampleSize();
  }
com::xuggle::ferry::IBuffer * com::xuggle::xuggler::AudioSamples::getData () [virtual]
Get any underlying raw data available for this object.
Returns:
The raw data, or null if not accessible.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 247 of file AudioSamples.cpp.
References com::xuggle::ferry::RefPointer< T >::get().
  {
    allocInternalSamples();
    IBuffer* retval = mSamples.get();
    if (!retval)
      throw std::bad_alloc();
    return retval;
  }
int64_t com::xuggle::xuggler::AudioSamples::getPts () [virtual]
What is the Presentation Time Stamp of this set of audio samples.
Returns:
the presentation time stamp (pts)
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 299 of file AudioSamples.cpp.
Referenced by getTimeStamp(), and com::xuggle::xuggler::AudioResampler::resample().
  {
    return mPts;
  }
void com::xuggle::xuggler::AudioSamples::setPts (int64_t aValue) [virtual]
Set the Presentation Time Stamp for this set of samples.
Parameters:
aValue the new value
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 305 of file AudioSamples.cpp.
Referenced by setComplete(), and setTimeStamp().
  {
    mPts = aValue;
  }
int64_t com::xuggle::xuggler::AudioSamples::getNextPts () [virtual]
What would be the next Presentation Time Stamp after all the samples in this buffer were played?
Returns:
the next presentation time stamp (pts)
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 311 of file AudioSamples.cpp.
References getNumSamples(), getSampleRate(), com::xuggle::xuggler::Global::NO_PTS, and com::xuggle::xuggler::IAudioSamples::samplesToDefaultPts().
  {
    int64_t retval = Global::NO_PTS;
    if (mPts != Global::NO_PTS)
      retval = mPts + IAudioSamples::samplesToDefaultPts(this->getNumSamples(), this->getSampleRate());
    return retval;
  }
int32_t com::xuggle::xuggler::AudioSamples::setSample (uint32_t sampleIndex, int32_t channel, Format format, int32_t sample) [virtual]
Sets the sample at the given index and channel to the sample.
In theory we assume input is the given Format, and will convert if needed, but right now we only support FMT_S16 anyway.
Parameters:
sampleIndex The zero-based index into the set of samples
channel The zero-based channel number. If this set of samples doesn't have that given channel, an error is returned.
format The format of the given sample
sample The actual sample
Returns:
>= 0 on success; -1 on error.
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 321 of file AudioSamples.cpp.
References com::xuggle::xuggler::IAudioSamples::FMT_S16, getMaxSamples(), getRawSamples(), and VS_LOG_DEBUG.
  {
    int32_t retval = -1;
    try {
      if (channel < 0 || channel >= mChannels)
        throw std::invalid_argument("cannot setSample for given channel");
      if (format != FMT_S16)
        throw std::invalid_argument("only support format: FMT_S16");
      if (sampleIndex >= this->getMaxSamples())
        throw std::invalid_argument("sampleIndex out of bounds");
      short *rawSamples = this->getRawSamples(0);
      if (!rawSamples)
        throw std::runtime_error("no samples buffer set in AudioSamples");
      rawSamples[sampleIndex*mChannels + channel] = (short)sample;
      retval = 0;
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      retval = -1;
    }
    return retval;
  }
int32_t com::xuggle::xuggler::AudioSamples::getSample (uint32_t sampleIndex, int32_t channel, Format format) [virtual]
Get the sample at the given sampleIndex and channel, and return it in the asked for format.
Parameters:
sampleIndex The zero-based index into this set of samples.
channel The zero-based channel to get the sample from
format The format to return in
Returns:
The sample if available. If that sample is not available (e.g. because the channel doesn't exist, or the samples have not been setComplete(bool, uint32_t, int32_t, int32_t, Format, int64_t)), then this method returns 0. It is up to the caller to ensure the inputs are valid given that 0 is also a valid sample value.
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 348 of file AudioSamples.cpp.
References com::xuggle::xuggler::IAudioSamples::FMT_S16, getNumSamples(), getRawSamples(), and VS_LOG_DEBUG.
  {
    int32_t retval = 0;
    try
    {
      if (channel < 0 || channel >= mChannels)
        throw std::invalid_argument("cannot getSample for given channel");
      if (format != FMT_S16)
        throw std::invalid_argument("only support format: FMT_S16");
      if (sampleIndex >= this->getNumSamples())
        throw std::invalid_argument("sampleIndex out of bounds");
      short *rawSamples = this->getRawSamples(0);
      if (!rawSamples)
        throw std::runtime_error("no samples buffer set in AudioSamples");
      retval = rawSamples[sampleIndex*mChannels + channel];
    }
    catch(std::exception & e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      retval = 0;
    }
    return retval;
  }
void com::xuggle::xuggler::AudioSamples::setData (com::xuggle::ferry::IBuffer * buffer) [virtual]
Sets the underlying buffer used by this object.
This is an advanced method and is not recommended for use by those who don't fully understand how IBuffers work. Implementations of IMediaData may behave in undefined ways if the buffer you pass in is not big enough for what you ask them to do (e.g. they may discard your buffer and allocate a larger one if they need more space). It is up to the caller to ensure the buffer passed in is large enough, and is not simultaneously in use by another part of the system.
Parameters:
buffer The buffer to set. If null, this method is ignored.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 186 of file AudioSamples.cpp.
References com::xuggle::ferry::RefPointer< T >::reset().
Referenced by make().
  {
    if (!buffer) return;
    mSamples.reset(buffer, true);
    setBufferType(mSampleFmt, buffer);
  }
void com::xuggle::xuggler::AudioSamples::setComplete (bool complete, uint32_t numSamples, int32_t sampleRate, int32_t channels, Format format, int64_t pts) [virtual]
Call this if you modify the samples and are now done.
This updates the pertinent information in the structure.
Parameters:
complete Is this set of samples complete?
numSamples Number of samples in this update (note that 4 shorts of 16-bit audio in stereo is actually 1 sample).
sampleRate The sample rate (in Hz) of this set of samples.
channels The number of channels in this set of samples.
format The sample-format of this set of samples.
pts The presentation time stamp of the starting sample in this buffer. Caller must ensure pts is in units of 1/1,000,000 of a second
Implements com::xuggle::xuggler::IAudioSamples.
Definition at line 263 of file AudioSamples.cpp.
References getMaxBufferSize(), getRawSamples(), getSampleSize(), setPts(), com::xuggle::ferry::RefPointer< T >::value(), and VS_LOG_DEBUG.
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), and com::xuggle::xuggler::AudioResampler::resample().
  {
    mIsComplete = complete;
    if (channels <= 0)
      channels = 1;
    mChannels = channels;
    mSampleRate = sampleRate;
    mSampleFmt = format;
    if (mSamples)
      // if we've allocated a buffer, reset the type
      setBufferType(mSampleFmt, mSamples.value());
    if (mIsComplete)
    {
      mNumSamples = FFMIN(numSamples,
          getMaxBufferSize()/(getSampleSize()));
#if 0
      {
        short* samps = this->getRawSamples(0);
        for(uint32_t i = 0; i < mNumSamples;i++)
        {
          int32_t samp = samps[i];
          VS_LOG_DEBUG("i: %d; samp: %d", i, samp);
        }
      }
#endif // VS_DEBUG
    } else {
      mNumSamples = 0;
    }
    setPts(pts);
  }
short * com::xuggle::xuggler::AudioSamples::getRawSamples (uint32_t startingSample) [virtual]
Definition at line 107 of file AudioSamples.cpp.
References getSampleSize().
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), com::xuggle::xuggler::StreamCoder::encodeAudio(), getSample(), com::xuggle::xuggler::AudioResampler::resample(), setComplete(), and setSample().
  {
    short *retval = 0;
    allocInternalSamples();
    if (mSamples)
    {
      uint32_t startingOffset = startingSample*getSampleSize();
      uint32_t bufLen = (mNumSamples*getSampleSize())-startingOffset;
      retval = (short*)mSamples->getBytes(startingOffset, bufLen);
    }
    return retval;
  }
int32_t com::xuggle::xuggler::AudioSamples::ensureCapacity (int32_t capacityInBytes) [virtual]
Called by decoder before decoding to ensure sufficient space.
Definition at line 88 of file AudioSamples.cpp.
References getSampleSize(), and VS_AUDIOSAMPLES_BUFFER_PADDING.
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), and com::xuggle::xuggler::AudioResampler::resample().
  {
    if (mSamples &&
        mSamples->getBufferSize() < (capacity + VS_AUDIOSAMPLES_BUFFER_PADDING))
    {
      // crap; need to ditch and re-recreate
      mSamples=0;
    }
    int32_t sampleSize = getSampleSize();
    int32_t requiredSamples;
    if (sampleSize > 0)
      requiredSamples = capacity / getSampleSize();
    else
      requiredSamples = AVCODEC_MAX_AUDIO_FRAME_SIZE;
    mRequestedSamples = requiredSamples;
    return 0;
  }
AudioSamples * com::xuggle::xuggler::AudioSamples::make (uint32_t numSamples, uint32_t numChannels) [static]
Get a new audio samples buffer.
Note that any buffers this objects needs will be lazily allocated (i.e. we won't actually grab all the memory until we need it).
Parameters:
numSamples The minimum number of samples you're going to want to put in this buffer. We may (and probably will) return a larger buffer, but you cannot assume that.
numChannels The number of channels in the audio you'll want to put in this buffer.
Returns:
A new object, or null if we can't allocate one.
Reimplemented from com::xuggle::xuggler::IAudioSamples.
Definition at line 121 of file AudioSamples.cpp.
References com::xuggle::xuggler::IAudioSamples::FMT_S16.
Referenced by com::xuggle::xuggler::IAudioSamples::make(), and make().
  {
    return make(numSamples, numChannels, IAudioSamples::FMT_S16);
  }
AudioSamples * com::xuggle::xuggler::AudioSamples::make (uint32_t numSamples, uint32_t numChannels, IAudioSamples::Format format) [static]
Get a new audio samples buffer.
Note that any buffers this objects needs will be lazily allocated (i.e. we won't actually grab all the memory until we need it).
Parameters:
numSamples The minimum number of samples you're going to want to put in this buffer. We may (and probably will) return a larger buffer, but you cannot assume that.
numChannels The number of channels in the audio you'll want to put in this buffer.
format The format of this buffer
Returns:
A new object, or null if we can't allocate one.
Reimplemented from com::xuggle::xuggler::IAudioSamples.
Definition at line 128 of file AudioSamples.cpp.
References make(), mChannels, mRequestedSamples, and mSampleFmt.
  {
    AudioSamples *retval=0;
    if (numSamples > 0 && numChannels > 0)
    {
      retval = AudioSamples::make();
      if (retval)
      {
        // FFMPEG actually requires a minimum buffer size, so we
        // make sure we're always at least that large.
        retval->mChannels = numChannels;
        retval->mSampleFmt = format;
        retval->mRequestedSamples = numSamples;
      }
    }
    return retval;
  }
AudioSamples * com::xuggle::xuggler::AudioSamples::make (com::xuggle::ferry::IBuffer * buffer, int channels, IAudioSamples::Format format) [static]
Creates an IAudioSamples object by wrapping an object.
If you are decoding into this buffer, the buffer must be at least 192k*channels large (an FFmpeg requirement) or the decodeAudio call on IStreamCoder will fail with an error. If you are encoding from, any size should do.
Parameters:
buffer the buffer to wrap
channels the number of channels of audio you will put it the buffer
format the audio sample format
Returns:
a new IAudioSamples object, or null on error.
Reimplemented from com::xuggle::xuggler::IAudioSamples.
Definition at line 149 of file AudioSamples.cpp.
References com::xuggle::xuggler::IAudioSamples::findSampleBitDepth(), com::xuggle::xuggler::IAudioSamples::FMT_NONE, com::xuggle::ferry::IBuffer::getBufferSize(), make(), setData(), VS_LOG_DEBUG, and VS_REF_RELEASE.
  {
    if (!buffer)
      return 0;
    if (format == IAudioSamples::FMT_NONE)
      return 0;
    if (channels < 0)
      return 0;
    if (buffer->getBufferSize()<= 0)
      return 0;
    int bytesPerSample = IAudioSamples::findSampleBitDepth(format)/8*channels;
    int samplesRequested = buffer->getBufferSize()/bytesPerSample;
    AudioSamples* retval = 0;
    try
    {
      retval = make(samplesRequested, channels, format);
      if (!retval)
        return 0;
      retval->setData(buffer);
    }
    catch (std::bad_alloc &e)
    {
      VS_REF_RELEASE(retval);
      throw e;
    }
    catch (std::exception& e)
    {
      VS_LOG_DEBUG("error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/AudioSamples.h
csrc/com/xuggle/xuggler/AudioSamples.cpp