Xuggle: com::xuggle::xuggler::AudioResampler Class Reference
com::xuggle::xuggler::AudioResampler Class Reference
#include <AudioResampler.h>
Detailed Description
Definition at line 30 of file AudioResampler.h.
Public Member Functions
virtual int getOutputChannels ()
number of channels in output audio.
virtual int getOutputRate ()
sample rate of output audio.
virtual int getInputChannels ()
number of channels expected in input audio.
virtual int getInputRate ()
sample rate expected in input audio.
virtual int resample (IAudioSamples *pOutputSamples, IAudioSamples *pInputSamples, unsigned int numSamples)
virtual IAudioSamples::Format getOutputFormat ()
virtual IAudioSamples::Format getInputFormat ()
virtual int32_t getFilterLen ()
virtual int32_t getLog2PhaseCount ()
virtual bool isLinear ()
virtual double getCutoffFrequency ()
virtual int32_t getMinimumNumSamplesRequiredInOutputSamples (IAudioSamples *inSamples)
virtual int32_t getMinimumNumSamplesRequiredInOutputSamples (int32_t numSamples)
Static Public Member Functions
static AudioResampler * make (int32_t outputChannels, int32_t inputChannels, int32_t outputRate, int32_t inputRate)
static AudioResampler * make (int32_t outputChannels, int32_t inputChannels, int32_t outputRate, int32_t inputRate, IAudioSamples::Format outputFmt, IAudioSamples::Format inputFmt)
static AudioResampler * make (int32_t outputChannels, int32_t inputChannels, int32_t outputRate, int32_t inputRate, IAudioSamples::Format outputFmt, IAudioSamples::Format inputFmt, int32_t filterLen, int32_t log2PhaseCount, bool isLinear, double cutoff)
Protected Member Functions
AudioResampler ()
virtual ~AudioResampler ()
Constructor & Destructor Documentation
com::xuggle::xuggler::AudioResampler::AudioResampler () [protected]
Definition at line 34 of file AudioResampler.cpp.
References com::xuggle::xuggler::IAudioSamples::FMT_S16, and com::xuggle::xuggler::Global::NO_PTS.
  {
    mContext = 0;
    mOChannels=0;
    mOSampleRate=0;
    mIChannels=0;
    mISampleRate=0;
    mPtsOffset=0;
    mOFmt = IAudioSamples::FMT_S16;
    mIFmt = IAudioSamples::FMT_S16;
    mFilterLen = 0;
    mLog2PhaseCount = 0;
    mIsLinear = false;
    mCutoff = 1.0;
    mNextPts = Global::NO_PTS;
  }
com::xuggle::xuggler::AudioResampler::~AudioResampler () [protected, virtual]
Definition at line 51 of file AudioResampler.cpp.
  {
    if (mContext)
      audio_resample_close(mContext);
  }
Member Function Documentation
int com::xuggle::xuggler::AudioResampler::getOutputChannels () [virtual]
number of channels in output audio.
Returns:
Number of channels we'll resample the output to.
Implements com::xuggle::xuggler::IAudioResampler.
Definition at line 158 of file AudioResampler.cpp.
References VS_ASSERT.
  {
    VS_ASSERT(mContext, "no context");
    return mOChannels;
  }
int com::xuggle::xuggler::AudioResampler::getOutputRate () [virtual]
sample rate of output audio.
Returns:
Sample Rate we'll resample the output to.
Implements com::xuggle::xuggler::IAudioResampler.
Definition at line 165 of file AudioResampler.cpp.
References VS_ASSERT.
  {
    VS_ASSERT(mContext, "no context");
    return mOSampleRate;
  }
int com::xuggle::xuggler::AudioResampler::getInputChannels () [virtual]
number of channels expected in input audio.
Returns:
Number of channels we'll expect in the input samples
Implements com::xuggle::xuggler::IAudioResampler.
Definition at line 172 of file AudioResampler.cpp.
References VS_ASSERT.
  {
    VS_ASSERT(mContext, "no context");
    return mIChannels;
  }
int com::xuggle::xuggler::AudioResampler::getInputRate () [virtual]
sample rate expected in input audio.
Returns:
Sample rate we'll expect in the input samples
Implements com::xuggle::xuggler::IAudioResampler.
Definition at line 179 of file AudioResampler.cpp.
References VS_ASSERT.
  {
    VS_ASSERT(mContext, "no context");
    return mISampleRate;
  }
int com::xuggle::xuggler::AudioResampler::resample (IAudioSamples * pOutputSamples, IAudioSamples * pInputSamples, unsigned int numSamples) [virtual]
Definition at line 271 of file AudioResampler.cpp.
References com::xuggle::xuggler::AudioSamples::ensureCapacity(), com::xuggle::xuggler::IAudioSamples::findSampleBitDepth(), com::xuggle::xuggler::AudioSamples::getChannels(), com::xuggle::xuggler::AudioSamples::getFormat(), com::xuggle::xuggler::AudioSamples::getMaxBufferSize(), getMinimumNumSamplesRequiredInOutputSamples(), com::xuggle::xuggler::AudioSamples::getNumSamples(), com::xuggle::xuggler::AudioSamples::getPts(), com::xuggle::xuggler::AudioSamples::getRawSamples(), com::xuggle::xuggler::AudioSamples::getSampleBitDepth(), com::xuggle::xuggler::AudioSamples::getSampleRate(), com::xuggle::xuggler::AudioSamples::isComplete(), com::xuggle::xuggler::Global::NO_PTS, com::xuggle::xuggler::IAudioSamples::samplesToDefaultPts(), com::xuggle::xuggler::AudioSamples::setComplete(), VS_ASSERT, VS_LOG_DEBUG, and VS_LOG_TRACE.
  {
    int retval = -1;
    AudioSamples* outSamples = dynamic_cast<AudioSamples*>(pOutSamples);
    AudioSamples* inSamples = dynamic_cast<AudioSamples*>(pInSamples);
    unsigned int sampleSize=0;
    try {
      if (!outSamples)
        throw std::invalid_argument("no output samples");
      if (outSamples == inSamples)
        throw std::invalid_argument("resampling into the same IAudioSamples is not allowed");
      // null out the output samples.
      outSamples->setComplete(false, 0, mOSampleRate, mOChannels,
          mOFmt, Global::NO_PTS);
      if (inSamples)
      {
        if (!inSamples->isComplete())
          throw std::invalid_argument("input samples are not complete");
        if (inSamples->getSampleRate() != mISampleRate)
          throw std::invalid_argument("unexpected input sample rate");
        if (inSamples->getChannels() != mIChannels)
          throw std::invalid_argument("unexpected # of input channels");
        if (inSamples->getFormat() != mIFmt)
          throw std::invalid_argument("unexpected sample format");
        if (numSamples == 0)
          numSamples = inSamples->getNumSamples();
        else
          numSamples = FFMIN(numSamples, inSamples->getNumSamples());
        sampleSize = inSamples->getSampleBitDepth()/8;
      } else {
        numSamples = 0;
        sampleSize = IAudioSamples::findSampleBitDepth(mIFmt)/8;
      }
      int32_t neededSamples = getMinimumNumSamplesRequiredInOutputSamples(numSamples);
      int32_t bytesPerOutputSample = mOChannels*IAudioSamples::findSampleBitDepth(mOFmt)/8;
      int32_t neededBytes = neededSamples * bytesPerOutputSample;
      // This causes a buffer resize to occur if needed
      if (outSamples->ensureCapacity(neededBytes) < 0)
        throw std::runtime_error("attempted to resize output buffer but failed");
      uint32_t outBufSize = outSamples->getMaxBufferSize();
      int32_t gap = (neededSamples*bytesPerOutputSample)-outBufSize;
      if (gap > 0) {
//        VS_LOG_ERROR("maxBufferSize: %d; neededSampleRoom: %d; sampleSize: %d; numSamples: %d; conversionRatio: %f;",
//            (int32_t)outSamples->getMaxBufferSize(),
//            neededSampleRoom,
//            sampleSize,
//            numSamples,
//            conversionRatio);
        throw std::invalid_argument("not enough room in output buffer");
      }
      short * inBuf = inSamples ? inSamples->getRawSamples(0) : 0;
      short *outBuf = outSamples->getRawSamples(0);
      if (!outBuf)
        throw std::invalid_argument("could not get output bytes");
      VS_ASSERT(mContext, "Should have been set at initialization");
      if (!mContext)
        throw std::invalid_argument("programmer error");
      // Now we should be far enough along that we can safely try a resample.
      retval = audio_resample(mContext, outBuf, inBuf, numSamples);
#if 0
      if (retval >0){
        char string[2048*16+1];
        unsigned int i=0;
        for (i = 0; i < sizeof(string)-1; i++)
          string[i] = 'X';
        bool allZero = true;
        for (i=0; i< FFMIN(numSamples, 2000);i++)
        {
          snprintf(string+(5*i), sizeof(string)-5*i, "%04hX.", inBuf[i]);
          if (inBuf[i] != 0)
            allZero = false;
        }
        VS_LOG_DEBUG("Input Buffer (%d): %s", numSamples, string);
        for (i=0; i< FFMIN((unsigned int)retval, 2000);i++)
        {
          snprintf(string+(9*i), sizeof(string)-9*i, "%04hX%04hX.",
              outBuf[2*i], outBuf[2*i+1]);
          if (outBuf[2*i] != 0 || outBuf[2*i+1] != 0)
            allZero = false;
        }
        VS_LOG_DEBUG("Output Buffer (%d): %s", retval, string);
        if (!allZero)
          VS_LOG_DEBUG("Got an audio buffer with content");
      }
#endif // 0
      if (retval >= 0)
      {
        // copy the Pts
        int64_t pts = Global::NO_PTS;
        if (inSamples)
        {
          pts = inSamples->getPts();
          mNextPts = pts + IAudioSamples::samplesToDefaultPts(retval, mOSampleRate);
        }
        else
        {
          pts = mNextPts;
        }
        if (pts != Global::NO_PTS)
          pts += mPtsOffset;
        outSamples->setComplete(true, retval,
            mOSampleRate, mOChannels,
            mOFmt,
            pts);
        int expectedSamples = 0;
        if (inSamples)
        {
          double top = mOSampleRate;
          double bottom = mISampleRate;
          double sampleOnlyConverstionRatio = top / bottom;
          expectedSamples = (int)(numSamples * sampleOnlyConverstionRatio);
        }
        else
        {
          VS_LOG_TRACE("Got null samples; outputted all cached and set pts offset from %lld to 0",
              mPtsOffset);
          expectedSamples = retval;
          // and reset the offset
          mPtsOffset = 0;
        }
        if (retval != expectedSamples)
        {
          // we got a different number of samples than expected; we need to update
          // our pts offset
          int sampleDelta = retval - expectedSamples;
          int64_t ptsDelta = IAudioSamples::samplesToDefaultPts(sampleDelta, mOSampleRate);
          mPtsOffset += ptsDelta;
        }
      }
    }
    catch (std::invalid_argument & e)
    {
      VS_LOG_DEBUG("invalid argument: %s", e.what());
      retval = -1;
    }
    return retval;
  }
IAudioSamples::Format com::xuggle::xuggler::AudioResampler::getOutputFormat () [virtual]
Definition at line 434 of file AudioResampler.cpp.
  {
    return mOFmt;
  }
IAudioSamples::Format com::xuggle::xuggler::AudioResampler::getInputFormat () [virtual]
Definition at line 440 of file AudioResampler.cpp.
  {
    return mIFmt;
  }
int32_t com::xuggle::xuggler::AudioResampler::getFilterLen () [virtual]
Definition at line 446 of file AudioResampler.cpp.
  {
    return mFilterLen;
  }
int32_t com::xuggle::xuggler::AudioResampler::getLog2PhaseCount () [virtual]
Definition at line 452 of file AudioResampler.cpp.
  {
    return mLog2PhaseCount;
  }
bool com::xuggle::xuggler::AudioResampler::isLinear () [virtual]
Definition at line 458 of file AudioResampler.cpp.
  {
    return mIsLinear;
  }
double com::xuggle::xuggler::AudioResampler::getCutoffFrequency () [virtual]
Definition at line 464 of file AudioResampler.cpp.
  {
    return mCutoff;
  }
AudioResampler * com::xuggle::xuggler::AudioResampler::make (int32_t outputChannels, int32_t inputChannels, int32_t outputRate, int32_t inputRate) [static]
Definition at line 58 of file AudioResampler.cpp.
References com::xuggle::xuggler::IAudioSamples::FMT_S16.
Referenced by make().
  {
    return make(outputChannels, inputChannels, outputRate, inputRate,
        IAudioSamples::FMT_S16, IAudioSamples::FMT_S16);
  }
AudioResampler * com::xuggle::xuggler::AudioResampler::make (int32_t outputChannels, int32_t inputChannels, int32_t outputRate, int32_t inputRate, IAudioSamples::Format outputFmt, IAudioSamples::Format inputFmt) [static]
Definition at line 68 of file AudioResampler.cpp.
References make().
  {
    return make(outputChannels, inputChannels, outputRate, inputRate,
        outputFmt, inputFmt,
        16, 10, 0, 0.8);
  }
AudioResampler * com::xuggle::xuggler::AudioResampler::make (int32_t outputChannels, int32_t inputChannels, int32_t outputRate, int32_t inputRate, IAudioSamples::Format outputFmt, IAudioSamples::Format inputFmt, int32_t filterLen, int32_t log2PhaseCount, bool isLinear, double cutoff) [static]
Definition at line 80 of file AudioResampler.cpp.
References make(), mContext, mCutoff, mFilterLen, mIChannels, mIFmt, mISampleRate, mIsLinear, mLog2PhaseCount, mOChannels, mOFmt, mOSampleRate, VS_LOG_ERROR, and VS_REF_RELEASE.
  {
    AudioResampler* retval = 0;
    try {
      if (outputChannels <= 0)
        throw std::invalid_argument("outputChannels <= 0");
      if (inputChannels <= 0)
        throw std::invalid_argument("inputChannels <= 0");
      if (outputChannels > 2)
        throw std::invalid_argument("outputChannels > 2; unsupported");
      if (inputChannels > 2)
        throw std::invalid_argument("inputChannels > 2; unsupported");
      if (outputRate <= 0)
        throw std::invalid_argument("outputRate <= 0");
      if (inputRate <= 0)
        throw std::invalid_argument("inputRate <= 0");
      if (filterLen <= 0)
        throw std::invalid_argument("filterLen <= 0");
      if (log2PhaseCount < 0)
        throw std::invalid_argument("log2PhaseCount < 0");
      if (cutoff < 0)
        throw std::invalid_argument("cutoffFrequency < 0");
      retval = AudioResampler::make();
      if (retval)
      {
        retval->mContext = av_audio_resample_init(outputChannels, inputChannels,
            outputRate, inputRate,
            (enum SampleFormat) outputFmt, (enum SampleFormat) inputFmt,
            filterLen, log2PhaseCount, (int)linear, cutoff);
        if (retval->mContext)
        {
          retval->mOChannels = outputChannels;
          retval->mOSampleRate = outputRate;
          retval->mIChannels = inputChannels;
          retval->mISampleRate = inputRate;
          retval->mOFmt = outputFmt;
          retval->mIFmt = inputFmt;
          retval->mFilterLen = filterLen;
          retval->mLog2PhaseCount = log2PhaseCount;
          retval->mIsLinear = linear;
          retval->mCutoff = cutoff;
        }
        else
        {
          VS_REF_RELEASE(retval);
        }
      }
    }
    catch (std::bad_alloc & e)
    {
      VS_LOG_ERROR("Error: %s", e.what());
      VS_REF_RELEASE(retval);
      throw e;
    }
    catch (std::exception & e)
    {
      VS_LOG_ERROR("Error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
int32_t com::xuggle::xuggler::AudioResampler::getMinimumNumSamplesRequiredInOutputSamples (IAudioSamples * inSamples) [virtual]
Definition at line 186 of file AudioResampler.cpp.
References com::xuggle::xuggler::IAudioSamples::getChannels(), com::xuggle::xuggler::IAudioSamples::getFormat(), com::xuggle::xuggler::IAudioSamples::getNumSamples(), com::xuggle::xuggler::IAudioSamples::getSampleRate(), com::xuggle::xuggler::IAudioSamples::isComplete(), and VS_LOG_DEBUG.
Referenced by resample().
  {
    int32_t retval = -1;
    try {
      int32_t numSamples = 0;
      if (inSamples)
      {
        if (!inSamples->isComplete())
          throw std::invalid_argument("input samples are not complete");
        if (inSamples->getSampleRate() != mISampleRate)
          throw std::invalid_argument("unexpected input sample rate");
        if (inSamples->getChannels() != mIChannels)
          throw std::invalid_argument("unexpected # of input channels");
        if (inSamples->getFormat() != mIFmt)
          throw std::invalid_argument("unexpected sample format");
        numSamples = inSamples->getNumSamples();
      } else {
        numSamples = 0;
      }
      retval = getMinimumNumSamplesRequiredInOutputSamples(numSamples);
    }
    catch (std::invalid_argument & e)
    {
      VS_LOG_DEBUG("invalid argument: %s", e.what());
      retval = -1;
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("Unknown exception: %s", e.what());
    }
    return retval;
  }
int32_t com::xuggle::xuggler::AudioResampler::getMinimumNumSamplesRequiredInOutputSamples (int32_t numSamples) [virtual]
Definition at line 225 of file AudioResampler.cpp.
References VS_ASSERT, VS_FFMPEG_AUDIO_RESAMPLER_LEADIN, and VS_LOG_DEBUG.
  {
    int32_t retval = -1;
    try
    {
      if (numSamples < 0)
        throw std::invalid_argument("numSamples < 0 not allowed");
      double conversionRatio = 1;
      {
        double top = mOSampleRate;
        VS_ASSERT(top, "should never be zero");
        double bot = mISampleRate;
        VS_ASSERT(bot, "should never be zero");
        conversionRatio = top/bot;
        VS_ASSERT(conversionRatio > 0, "the variables used should have been checked on construction");
      }
      if (conversionRatio <= 0)
        throw std::invalid_argument("programmer error");
      // FFMPEG's re-sample function doesn't let you specify the size of your
      // output buffer, but does use up all the space you might expect
      // plus 16-bytes as a lead-in/lead-out for it to seed the resampler.
      // Hence, the hard-coded 16 here.
      // NOTE: 16 might change IF the value of filters in the audio_resample
      // method in libavcodec/resample.c changes.
#define VS_FFMPEG_AUDIO_RESAMPLER_LEADIN 16
      retval =
          (int32_t)((numSamples * conversionRatio)+VS_FFMPEG_AUDIO_RESAMPLER_LEADIN+0.5);
    }
    catch (std::invalid_argument & e)
    {
      VS_LOG_DEBUG("invalid argument: %s", e.what());
      retval = -1;
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("Unknown exception: %s", e.what());
    }
    return retval;
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/AudioResampler.h
csrc/com/xuggle/xuggler/AudioResampler.cpp