Xuggle: com::xuggle::ferry::Mutex Class Reference
com::xuggle::ferry::Mutex Class Reference
#include <Mutex.h>
Detailed Description
Internal Only.
This object exists so that Native code can get access to thread safe locking objects if they need it.
Implements a blocking Mutually-Exclusive lock by wrapping a Java lock.
If not running inside Java, lock() and unlock() are NO-OPs.
Definition at line 41 of file Mutex.h.
Public Member Functions
void lock ()
void unlock ()
Static Public Member Functions
static Mutex * make ()
Protected Member Functions
Mutex ()
virtual ~Mutex ()
Constructor & Destructor Documentation
com::xuggle::ferry::Mutex::Mutex () [protected]
Definition at line 36 of file Mutex.cpp.
Referenced by make().
{
  mLock = 0;
  mSpinCount = 0;
}
com::xuggle::ferry::Mutex::~Mutex () [protected, virtual]
Definition at line 42 of file Mutex.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv(), and unlock().
{
  JNIEnv *env = JNIHelper::sGetEnv();
  if (env)
  {
    if (mSpinCount > 0)
    {
      // OK, this is bad; someone left us in a bad
      // condition
      fprintf(stderr, "Destroying monitor %p with non-zero spin count\n",
          this);
      while (mSpinCount > 0)
      {
        this->unlock();
      }
    }
    if (mLock)
      env->DeleteGlobalRef(mLock);
  }
  mLock = 0;
}
Member Function Documentation
Mutex * com::xuggle::ferry::Mutex::make () [static]
Definition at line 171 of file Mutex.cpp.
References com::xuggle::ferry::RefCounted::acquire(), mLock, Mutex(), com::xuggle::ferry::JNIHelper::sGetEnv(), com::xuggle::ferry::JNIHelper::sGetVM(), and VS_REF_RELEASE.
{
  Mutex* retval = 0;
  jobject newValue = 0;
  JNIEnv *env = 0;
  try
  {
    if (!mInitialized)
      Mutex::init();
    env = JNIHelper::sGetEnv();
    if (env)
    {
      if (!mClass)
      {
        // we're being called BEFORE our initialization
        // callback was called, but during someone
        // elses initialization route, so we can be
        // sure we have a JVM.
        Mutex::initJavaBindings(JNIHelper::sGetVM(), 0);
      }
      if (mClass && mConstructorMethod)
      {
        retval = new Mutex();
        if (!retval)
          throw std::bad_alloc();
        retval->acquire();
        if (env->ExceptionCheck())
          throw std::bad_alloc();
        // we're running within Java
        newValue = env->NewObject(mClass, mConstructorMethod);
        if (!newValue)
          throw std::bad_alloc();
        if (env->ExceptionCheck())
          throw std::bad_alloc();
        retval->mLock = env->NewGlobalRef(newValue);
        if (!retval->mLock)
          throw std::bad_alloc();
        if (env->ExceptionCheck())
          throw std::bad_alloc();
        env->DeleteLocalRef(newValue);
        newValue = 0;
      }
    }
  }
  catch (std::bad_alloc & e)
  {
    VS_REF_RELEASE(retval);
    throw e;
  }
  catch (std::exception &e)
  {
    fprintf(stderr, "got uncaught error creating mutex: %p", retval);
    VS_REF_RELEASE(retval);
  }
  if (env && newValue)
    env->DeleteLocalRef(newValue);
  return retval;
}
void com::xuggle::ferry::Mutex::lock ()
Definition at line 96 of file Mutex.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
Referenced by com::xuggle::xuggler::Global::lock().
{
  if (!mInitialized)
    Mutex::init();
  if (mLock)
  {
    JNIEnv *env = JNIHelper::sGetEnv();
    if (env)
    {
      //fprintf(stderr, " PRE-ENTER: %p\n", mLock);
      if (env->ExceptionCheck())
      {
        // have a pending java exception; don't try the lock
        throw std::runtime_error("pending java exception; not locking");
      }
      // testing that a thrown ERROR doesn't cause core-dumps
      // throw std::runtime_error("bad panda; no shoots for you");
      if (env->MonitorEnter(mLock) != JNI_OK)
      {
        fprintf(stderr, "Could not enter lock: %p\n", mLock);
        throw std::runtime_error("failed to enter monitor; not locking");
      }
      else
      {
        if (env->ExceptionCheck()) {
          env->MonitorExit(mLock);
          throw std::runtime_error("failed to enter monitor due to "
              "pending exception; not locking");
        } else {
          // we're in the lock now!
          ++mSpinCount;
        }
      }
      //fprintf(stderr, "POST-ENTER: %p\n", mLock);
    }
  }
}
void com::xuggle::ferry::Mutex::unlock ()
Definition at line 137 of file Mutex.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
Referenced by com::xuggle::xuggler::Global::unlock(), and ~Mutex().
{
  if (!mInitialized)
    Mutex::init();
  if (mLock)
  {
    JNIEnv *env = JNIHelper::sGetEnv();
    if (env)
    {
      //fprintf(stderr, "  PRE-EXIT: %p\n", mLock);
      if (mSpinCount <= 0)
      {
        // we called unlock without a matching successful lock;
        // we must fail.
        throw std::runtime_error("unlock attempt on unlocked mutex");
      }
      // reduce the spin count regardless of result while still under
      // the lock
      --mSpinCount;
      if (env->MonitorExit(mLock) != JNI_OK)
      {
        // this can fail in out of memory situations but there's not much
        // we can do.
        //fprintf(stderr, "Could not exit lock: %p\n", mLock);
        throw std::runtime_error("failed attempt to unlock mutex");
      }
      //fprintf(stderr, " POST-EXIT: %p\n", mLock);
    }
  }
}
The documentation for this class was generated from the following files:
csrc/com/xuggle/ferry/Mutex.h
csrc/com/xuggle/ferry/Mutex.cpp