Xuggle: com::xuggle::xuggler::Rational Class Reference
com::xuggle::xuggler::Rational Class Reference
#include <Rational.h>
Detailed Description
Definition at line 29 of file Rational.h.
Public Member Functions
virtual IRational * copy ()
Creates a new IRational object by copying (by value) this object.
virtual int32_t getNumerator ()
Get the numerator for this rational.
virtual int32_t getDenominator ()
Get the denominator for this rational.
virtual int32_t compareTo (IRational *other)
Compare a rational to this rational.
virtual double getDouble ()
Rational to double conversion.
virtual int32_t reduce (int64_t num, int64_t den, int64_t max)
Reduce a fraction to it's lowest common denominators.
virtual IRational * multiply (IRational *arg)
Multiplies this number by arg.
virtual IRational * divide (IRational *arg)
Divides this rational by arg.
virtual IRational * subtract (IRational *arg)
Subtracts arg from this rational.
virtual IRational * add (IRational *arg)
Adds arg to this rational.
virtual int64_t rescale (int64_t origValue, IRational *origBase)
Takes a value scaled in increments of origBase and gives the equivalent value scaled in terms of this Rational.
virtual int64_t rescale (int64_t origValue, IRational *origBase, Rounding rounding)
Takes a value scaled in increments of origBase and gives the equivalent value scaled in terms of this Rational.
virtual void setNumerator (int32_t value)
Sets the numerator on this object.
virtual void setDenominator (int32_t value)
Sets the denominator on this object.
virtual void setValue (double value)
Sets the numerator and denominator on this object by reducing the double to the closest integer numerator and denominator.
virtual double getValue ()
An alias for getDouble() but matching JavaBean conventions.
virtual bool isFinalized ()
Returns true if init() has been called and this object is now considered finalized and immutable.
virtual void init ()
Marks this object as finalized and immutable.
Static Public Member Functions
static Rational * make (double d)
Converts a double precision floating point number to a rational.
static Rational * make (AVRational *src)
Create a Rational from an AVRational struct.
static Rational * make (Rational *src)
Creates copy of a Rational from another Rational.
static Rational * make (int32_t num, int32_t den)
Create a rational from a numerator and denominator.
static int64_t rescale (int64_t srcValue, int32_t dstNumerator, int32_t dstDenominator, int32_t srcNumerator, int32_t srcDenominator, Rounding rounding)
Rescales a long value to another long value.
Protected Member Functions
Rational ()
virtual ~Rational ()
Constructor & Destructor Documentation
com::xuggle::xuggler::Rational::Rational () [protected]
Definition at line 28 of file Rational.cpp.
  {
    // default to 0 for the value.
    mRational.den = 1;
    mRational.num = 0;
    mInitialized = false;
  }
com::xuggle::xuggler::Rational::~Rational () [protected, virtual]
Definition at line 36 of file Rational.cpp.
  {
  }
Member Function Documentation
IRational * com::xuggle::xuggler::Rational::copy () [virtual]
Creates a new IRational object by copying (by value) this object.
Returns:
the new object
Implements com::xuggle::xuggler::IRational.
Definition at line 92 of file Rational.cpp.
References com::xuggle::xuggler::IRational::make().
  {
    return Rational::make(this);
  }
virtual int32_t com::xuggle::xuggler::Rational::getNumerator () [inline, virtual]
Get the numerator for this rational.
Returns:
the numerator.
Implements com::xuggle::xuggler::IRational.
Definition at line 36 of file Rational.h.
{ return mRational.num; }
virtual int32_t com::xuggle::xuggler::Rational::getDenominator () [inline, virtual]
Get the denominator for this rational.
Returns:
the denominator.
Implements com::xuggle::xuggler::IRational.
Definition at line 37 of file Rational.h.
{ return mRational.den; }
int32_t com::xuggle::xuggler::Rational::compareTo (IRational * other) [virtual]
Compare a rational to this rational.
Parameters:
other second rational
Returns:
0 if this==other, 1 if this>other and -1 if this<other.
Implements com::xuggle::xuggler::IRational.
Definition at line 141 of file Rational.cpp.
References mRational.
  {
    int32_t result = 0;
    Rational *arg=dynamic_cast<Rational*>(other);
    if (arg)
      result = av_cmp_q(mRational, arg->mRational);
    return result;
  }
double com::xuggle::xuggler::Rational::getDouble () [virtual]
Rational to double conversion.
Returns:
(double) a
Implements com::xuggle::xuggler::IRational.
Definition at line 151 of file Rational.cpp.
Referenced by getValue().
  {
    double result = 0;
    // On some runs in Linux calling av_q2d will raise
    // a FPE instead of returning back NaN or infinity,
    // so we try to short-circuit that here.
    if (mRational.den == 0)
      if (mRational.num == 0)
        result = std::numeric_limits<double>::quiet_NaN();
      else
        result = std::numeric_limits<double>::infinity();
    else
      result =  av_q2d(mRational);
    return result;
  }
int32_t com::xuggle::xuggler::Rational::reduce (int64_t num, int64_t den, int64_t max) [virtual]
Reduce a fraction to it's lowest common denominators.
This is useful for framerate calculations.
Parameters:
num the src numerator.
den the src denominator.
max the maximum allowed for nom & den in the reduced fraction.
Returns:
1 if exact, 0 otherwise
Implements com::xuggle::xuggler::IRational.
Definition at line 168 of file Rational.cpp.
Referenced by init().
  {
    int32_t result = 0;
    result =  av_reduce(&mRational.num, &mRational.den,
        num, den, max);
    return result;
  }
IRational * com::xuggle::xuggler::Rational::multiply (IRational * arg) [virtual]
Multiplies this number by arg.
Parameters:
arg number to mulitply by.
Returns:
this*arg.
Implements com::xuggle::xuggler::IRational.
Definition at line 177 of file Rational.cpp.
References com::xuggle::xuggler::IRational::make(), and mRational.
  {
    Rational *result = 0;
    Rational *arg=dynamic_cast<Rational*>(other);
    if (arg)
    {
      result = Rational::make();
      if (result)
      {
        result->mRational = av_mul_q(this->mRational,
            arg->mRational);
      }
    }
    return result;
  }
IRational * com::xuggle::xuggler::Rational::divide (IRational * arg) [virtual]
Divides this rational by arg.
Parameters:
arg The divisor to use.
Returns:
this/arg.
Implements com::xuggle::xuggler::IRational.
Definition at line 194 of file Rational.cpp.
References com::xuggle::xuggler::IRational::make(), and mRational.
  {
    Rational *result = 0;
    Rational *arg=dynamic_cast<Rational*>(other);
    if (arg)
    {
      result = Rational::make();
      if (result)
      {
        result->mRational = av_div_q(this->mRational,
            arg->mRational);
      }
    }
    return result;
  }
IRational * com::xuggle::xuggler::Rational::subtract (IRational * arg) [virtual]
Subtracts arg from this rational.
Parameters:
arg The amount to subtract from this.
Returns:
this-arg.
Implements com::xuggle::xuggler::IRational.
Definition at line 211 of file Rational.cpp.
References com::xuggle::xuggler::IRational::make(), and mRational.
  {
    Rational *result = 0;
    Rational *arg=dynamic_cast<Rational*>(other);
    if (arg)
    {
      result = Rational::make();
      if (result)
      {
        result->mRational = av_sub_q(this->mRational,
            arg->mRational);
      }
    }
    return result;
  }
IRational * com::xuggle::xuggler::Rational::add (IRational * arg) [virtual]
Adds arg to this rational.
Parameters:
arg The amount to add to this.
Returns:
this+arg.
Implements com::xuggle::xuggler::IRational.
Definition at line 227 of file Rational.cpp.
References com::xuggle::xuggler::IRational::make(), and mRational.
  {
    Rational *result = 0;
    Rational *arg=dynamic_cast<Rational*>(other);
    if (arg)
    {
      result = Rational::make();
      if (result)
      {
        result->mRational = av_add_q(this->mRational,
            arg->mRational);
      }
    }
    return result;
  }
int64_t com::xuggle::xuggler::Rational::rescale (int64_t origValue, IRational * origBase) [virtual]
Takes a value scaled in increments of origBase and gives the equivalent value scaled in terms of this Rational.
Parameters:
origValue The original int64_t value you care about.
origBase The original base Rational that origValue is scaled with.
Returns:
The new integer value, scaled in units of this IRational.
Implements com::xuggle::xuggler::IRational.
Definition at line 244 of file Rational.cpp.
References mRational.
Referenced by com::xuggle::xuggler::IRational::rescale().
  {
    int64_t retval=origValue;
    Rational *arg=dynamic_cast<Rational*>(origBase);
    if (arg)
    {
      retval = av_rescale_q(origValue, arg->mRational, this->mRational);
    }
    return retval;
  }
Rational * com::xuggle::xuggler::Rational::make (double d) [static]
Converts a double precision floating point number to a rational.
Parameters:
d double to convert
Returns:
A new Rational; caller must release() when done.
Reimplemented from com::xuggle::xuggler::IRational.
Definition at line 52 of file Rational.cpp.
References init(), com::xuggle::xuggler::IRational::make(), and setValue().
  {
    Rational *result=0;
    result = Rational::make();
    if (result) {
      result->setValue(d);
      result->init();
    }
    return result;
  }
Rational * com::xuggle::xuggler::Rational::make (AVRational * src) [static]
Create a Rational from an AVRational struct.
Parameters:
src The source AVRational object.
Returns:
A new Rational; caller must release() when done. Null if src is null.
Definition at line 77 of file Rational.cpp.
References init(), com::xuggle::xuggler::IRational::make(), and mRational.
  {
    Rational *result=0;
    if (src)
    {
      result = Rational::make();
      if (result) {
        result->mRational = *src;
        result->init();
      }
    }
    return result;
  }
Rational * com::xuggle::xuggler::Rational::make (Rational * src) [static]
Creates copy of a Rational from another Rational.
Note: This is a NEW object. To just keep tabs on the original, use acquire() to keep a reference.
Parameters:
src The source Rational to copy.
Returns:
A new Rational; caller must call release. Returns null if src is null.
Definition at line 98 of file Rational.cpp.
References init(), com::xuggle::xuggler::IRational::make(), and mRational.
  {
    Rational *result=0;
    if (src)
    {
      result = Rational::make();
      if (result) {
        result->mRational = src->mRational;
        result->init();
      }
    }
    return result;
  }
Rational * com::xuggle::xuggler::Rational::make (int32_t num, int32_t den) [static]
Create a rational from a numerator and denominator.
We will always reduce this to the lowest num/den pair we can, but never having den exceed what was passed in.
Parameters:
num The numerator of the resulting Rational
den The denominator of the resulting Rational
Returns:
A new Rational; caller must call release.
Reimplemented from com::xuggle::xuggler::IRational.
Definition at line 129 of file Rational.cpp.
References init(), com::xuggle::xuggler::IRational::make(), setDenominator(), and setNumerator().
  {
    Rational *result=0;
    result = Rational::make();
    if (result) {
      result->setNumerator(num);
      result->setDenominator(den);
      result->init();
    }
    return result;
  }
int64_t com::xuggle::xuggler::Rational::rescale (int64_t origValue, IRational * origBase, Rounding rounding) [virtual]
Takes a value scaled in increments of origBase and gives the equivalent value scaled in terms of this Rational.
Parameters:
origValue The original int64_t value you care about.
origBase The original base Rational that origValue is scaled with.
rounding How you want rounding to occur
Returns:
The new integer value, scaled in units of this IRational.
Implements com::xuggle::xuggler::IRational.
Definition at line 257 of file Rational.cpp.
References mRational.
  {
    int64_t retval=origValue;
    Rational *arg=dynamic_cast<Rational*>(origBase);
    if (arg)
    {
      int64_t b = arg->mRational.num  * (int64_t)this->mRational.den;
      int64_t c = this->mRational.num * (int64_t)arg->mRational.den;
      retval = av_rescale_rnd(origValue, b,
          c, (enum AVRounding)rounding);
    }
    return retval;
  }
int64_t com::xuggle::xuggler::Rational::rescale (int64_t srcValue, int32_t dstNumerator, int32_t dstDenominator, int32_t srcNumerator, int32_t srcDenominator, Rounding rounding) [static]
Rescales a long value to another long value.
This method doesn't use IRational values, but instead uses numerators and denominators passed in by the caller. It will not result in any memory allocations.
Parameters:
srcValue The value to rescale.
dstNumerator The numerator of the units you want to scale to. Must be non-zero.
dstDenominator The denominator of the units you want to scale to. Must be non-zero.
srcNumerator The numerator of the units srcValue is expressed in. Must be non-zero.
srcDenominator The denominator of the units srcValue is expressed in. Must be non-zero.
rounding How you want rounding to occur
Returns:
The new integer value, scaled in units of dstNumerator/dstNumerator, or 0 if there is a parameter error.
Reimplemented from com::xuggle::xuggler::IRational.
Definition at line 275 of file Rational.cpp.
  {
    int64_t retval = srcValue;
    if (!dstNumerator || !dstDenominator ||
        !srcNumerator || !srcDenominator)
      return 0;
    int64_t b = srcNumerator * (int64_t)dstDenominator;
    int64_t c = dstNumerator * (int64_t)srcDenominator;
    retval = av_rescale_rnd(srcValue, b,
        c, (enum AVRounding)rounding);
    return retval;
  }
void com::xuggle::xuggler::Rational::setNumerator (int32_t value) [virtual]
Sets the numerator on this object.
If isFinalized is true, then this method is ignored.
Since:
3.2
Implements com::xuggle::xuggler::IRational.
Definition at line 112 of file Rational.cpp.
Referenced by make().
  {
    if (!mInitialized)
      mRational.num = num;
  }
void com::xuggle::xuggler::Rational::setDenominator (int32_t value) [virtual]
Sets the denominator on this object.
If isFinalized is true, then this method is ignored.
Since:
3.2
Implements com::xuggle::xuggler::IRational.
Definition at line 118 of file Rational.cpp.
Referenced by make().
  {
    if (!mInitialized)
      mRational.den = den;
  }
void com::xuggle::xuggler::Rational::setValue (double value) [virtual]
Sets the numerator and denominator on this object by reducing the double to the closest integer numerator and denominator.
If isFinalized is true, then this method is ignored.
Since:
3.2
Implements com::xuggle::xuggler::IRational.
Definition at line 64 of file Rational.cpp.
Referenced by make().
  {
    if (!mInitialized)
      mRational = av_d2q(d, 0x7fffffff);
  }
double com::xuggle::xuggler::Rational::getValue () [virtual]
An alias for getDouble() but matching JavaBean conventions.
Since:
3.2
Implements com::xuggle::xuggler::IRational.
Definition at line 71 of file Rational.cpp.
References getDouble().
  {
    return getDouble();
  }
bool com::xuggle::xuggler::Rational::isFinalized () [virtual]
Returns true if init() has been called and this object is now considered finalized and immutable.
Since:
3.2
Implements com::xuggle::xuggler::IRational.
Definition at line 124 of file Rational.cpp.
  {
    return mInitialized;
  }
void com::xuggle::xuggler::Rational::init () [virtual]
Marks this object as finalized and immutable.
Any setters called after the first init() call will be ignored.
Most make methods will call this method automatically, with the exception of the blank factory method make().
Since:
3.2
Implements com::xuggle::xuggler::IRational.
Definition at line 41 of file Rational.cpp.
References reduce().
Referenced by make().
  {
    if (!mInitialized) {
      (void) reduce(mRational.num,
          mRational.den,
          FFMAX(mRational.den, mRational.num));
    }
    mInitialized = true;
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/Rational.h
csrc/com/xuggle/xuggler/Rational.cpp