Xuggle: com::xuggle::xuggler::ContainerFormat Class Reference
com::xuggle::xuggler::ContainerFormat Class Reference
#include <ContainerFormat.h>
Detailed Description
Definition at line 29 of file ContainerFormat.h.
Public Member Functions
virtual int32_t setInputFormat (const char *shortName)
Sets the input format for this container.
virtual int32_t setOutputFormat (const char *shortName, const char *url, const char *mimeType)
Sets the output format for this container.
virtual const char * getInputFormatShortName ()
Get the short name for the input format.
virtual const char * getInputFormatLongName ()
Get the long name for the input format.
virtual const char * getOutputFormatShortName ()
Get the short name for the output format.
virtual const char * getOutputFormatLongName ()
Get the long name for the output format.
virtual const char * getOutputFormatMimeType ()
Get the mime type for the output format.
AVInputFormat * getInputFormat ()
AVOutputFormat * getOutputFormat ()
void setInputFormat (AVInputFormat *)
void setOutputFormat (AVOutputFormat *)
virtual int32_t getInputFlags ()
Get the input flags associated with this object.
virtual void setInputFlags (int32_t newFlags)
Set the input flags to use with this object.
virtual bool getInputFlag (Flags flag)
Get the input setting for the specified flag.
virtual void setInputFlag (Flags flag, bool value)
Set the input flag.
virtual int32_t getOutputFlags ()
Get the output flags associated with this object.
virtual void setOutputFlags (int32_t newFlags)
Set the output flags to use with this object.
virtual bool getOutputFlag (Flags flag)
Get the output setting for the specified flag.
virtual void setOutputFlag (Flags flag, bool value)
Set the output flag.
virtual bool isOutput ()
Is this an output container format?
virtual bool isInput ()
Is this an input container format?
virtual const char * getOutputExtensions ()
Get the filename extensions that this output format prefers (most common first).
virtual ICodec::ID getOutputDefaultAudioCodec ()
Get the default audio codec this container prefers, if known.
virtual ICodec::ID getOutputDefaultVideoCodec ()
Get the default video codec this container prefers, if known.
virtual ICodec::ID getOutputDefaultSubtitleCodec ()
Get the default subtitle codec this container prefers, if known.
virtual int32_t getOutputNumCodecsSupported ()
Gets the number of different codecs this container can include for encoding.
virtual ICodec::ID getOutputCodecID (int32_t index)
Queries for a supported codec id from the list of codecs that can be encoded into this ContainerFormat.
virtual int32_t getOutputCodecTag (int32_t index)
Queries for a supported codec tag from the list of codecs that can be encoded into this ContainerFormat.
virtual int32_t getOutputCodecTag (ICodec::ID id)
Get the 4-byte tag the container would output for the given codec id.
virtual bool isCodecSupportedForOutput (ICodec::ID id)
Returns true if this container format can output media encoded with the given codec.
Protected Member Functions
ContainerFormat ()
virtual ~ContainerFormat ()
Constructor & Destructor Documentation
com::xuggle::xuggler::ContainerFormat::ContainerFormat () [protected]
Definition at line 40 of file ContainerFormat.cpp.
  {
    mInputFormat = NULL;
    mOutputFormat = NULL;
  }
com::xuggle::xuggler::ContainerFormat::~ContainerFormat () [protected, virtual]
Definition at line 46 of file ContainerFormat.cpp.
  {
  }
Member Function Documentation
int32_t com::xuggle::xuggler::ContainerFormat::setInputFormat (const char * shortName) [virtual]
Sets the input format for this container.
Parameters:
shortName The short name for this container (using FFMPEG's short name).
Returns:
>= 0 on success. < 0 if shortName cannot be found.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 51 of file ContainerFormat.cpp.
Referenced by com::xuggle::xuggler::Container::getContainerFormat(), and com::xuggle::xuggler::IContainerFormat::getInstalledInputFormat().
  {
    if (shortName && *shortName)
    {
      mInputFormat = av_find_input_format(shortName);
    } else {
      mInputFormat = NULL;
    }
    return (mInputFormat == NULL ? -1 : 0);
  }
int32_t com::xuggle::xuggler::ContainerFormat::setOutputFormat (const char * shortName, const char * url, const char * mimeType) [virtual]
Sets the output format for this container.
We'll look at the shortName, url and mimeType and try to guess a valid output container format.
Parameters:
shortName The short name for this container (using FFMPEG's short name).
url The URL for this container.
mimeType The mime type for this container.
Returns:
>= 0 on success. < 0 if we cannot find a good container.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 62 of file ContainerFormat.cpp.
Referenced by com::xuggle::xuggler::Container::getContainerFormat(), and com::xuggle::xuggler::IContainerFormat::getInstalledOutputFormat().
  {
    if ((shortName && *shortName) ||
        (url && *url) ||
        (mimeType && *mimeType))
    {
      mOutputFormat = av_guess_format(shortName, url, mimeType);
    } else {
      mOutputFormat = NULL;
    }
    return (mOutputFormat == NULL ? -1 : 0);
  }
const char * com::xuggle::xuggler::ContainerFormat::getInputFormatShortName () [virtual]
Get the short name for the input format.
Returns:
The short name for the input format, or null if none.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 77 of file ContainerFormat.cpp.
  {
    return (mInputFormat ? mInputFormat->name : 0);
  }
const char * com::xuggle::xuggler::ContainerFormat::getInputFormatLongName () [virtual]
Get the long name for the input format.
Returns:
The long name for the input format, or null if none.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 82 of file ContainerFormat.cpp.
  {
    return (mInputFormat ? mInputFormat->long_name : 0);
  }
const char * com::xuggle::xuggler::ContainerFormat::getOutputFormatShortName () [virtual]
Get the short name for the output format.
Returns:
The short name for the output format, or null if none.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 87 of file ContainerFormat.cpp.
  {
    return (mOutputFormat ? mOutputFormat->name : 0);
  }
const char * com::xuggle::xuggler::ContainerFormat::getOutputFormatLongName () [virtual]
Get the long name for the output format.
Returns:
The long name for the output format, or null if none.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 92 of file ContainerFormat.cpp.
  {
    return (mOutputFormat ? mOutputFormat->long_name : 0);
  }
const char * com::xuggle::xuggler::ContainerFormat::getOutputFormatMimeType () [virtual]
Get the mime type for the output format.
Returns:
The mime type for the output format, or null if none.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 97 of file ContainerFormat.cpp.
  {
    return (mOutputFormat ? mOutputFormat->mime_type : 0);
  }
AVInputFormat * com::xuggle::xuggler::ContainerFormat::getInputFormat ()
Definition at line 102 of file ContainerFormat.cpp.
  {
    return mInputFormat;
  }
AVOutputFormat * com::xuggle::xuggler::ContainerFormat::getOutputFormat ()
Definition at line 107 of file ContainerFormat.cpp.
  {
    return mOutputFormat;
  }
void com::xuggle::xuggler::ContainerFormat::setInputFormat (AVInputFormat * fmt)
Definition at line 112 of file ContainerFormat.cpp.
  {
    mInputFormat = fmt;
  }
void com::xuggle::xuggler::ContainerFormat::setOutputFormat (AVOutputFormat * fmt)
Definition at line 117 of file ContainerFormat.cpp.
  {
    mOutputFormat = fmt;
  }
int32_t com::xuggle::xuggler::ContainerFormat::getInputFlags () [virtual]
Get the input flags associated with this object.
Returns:
The (compacted) value of all flags set.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 123 of file ContainerFormat.cpp.
  {
    return (mInputFormat ? mInputFormat->flags : 0);
  }
void com::xuggle::xuggler::ContainerFormat::setInputFlags (int32_t newFlags) [virtual]
Set the input flags to use with this object.
All values must be ORed (|) together.
See also:
Flags
Parameters:
newFlags The new set flags for this codec.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 129 of file ContainerFormat.cpp.
  {
    if (mInputFormat)
      mInputFormat->flags = newFlags;
  }
bool com::xuggle::xuggler::ContainerFormat::getInputFlag (Flags flag) [virtual]
Get the input setting for the specified flag.
Parameters:
flag The flag you want to find the setting for
Returns:
0 for false; non-zero for true
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 136 of file ContainerFormat.cpp.
  {
    bool result = false;
    if (mInputFormat)
      result = mInputFormat->flags & flag;
    return result;
  }
void com::xuggle::xuggler::ContainerFormat::setInputFlag (Flags flag, bool value) [virtual]
Set the input flag.
Parameters:
flag The flag to set
value The value to set it to (true or false)
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 145 of file ContainerFormat.cpp.
  {
    if (mInputFormat)
    {
      if (value)
      {
        mInputFormat->flags |= flag;
      }
      else
      {
        mInputFormat->flags &= (~flag);
      }
    }
  }
int32_t com::xuggle::xuggler::ContainerFormat::getOutputFlags () [virtual]
Get the output flags associated with this object.
Returns:
The (compacted) value of all flags set.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 161 of file ContainerFormat.cpp.
  {
    return (mOutputFormat ? mOutputFormat->flags : 0);
  }
void com::xuggle::xuggler::ContainerFormat::setOutputFlags (int32_t newFlags) [virtual]
Set the output flags to use with this object.
All values must be ORed (|) together.
See also:
Flags
Parameters:
newFlags The new set flags for this codec.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 167 of file ContainerFormat.cpp.
  {
    if (mOutputFormat)
      mOutputFormat->flags = newFlags;
  }
bool com::xuggle::xuggler::ContainerFormat::getOutputFlag (Flags flag) [virtual]
Get the output setting for the specified flag.
Parameters:
flag The flag you want to find the setting for
Returns:
0 for false; non-zero for true
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 174 of file ContainerFormat.cpp.
  {
    bool result = false;
    if (mOutputFormat)
      result = mOutputFormat->flags & flag;
    return result;
  }
void com::xuggle::xuggler::ContainerFormat::setOutputFlag (Flags flag, bool value) [virtual]
Set the output flag.
Parameters:
flag The flag to set
value The value to set it to (true or false)
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 183 of file ContainerFormat.cpp.
  {
    if (mOutputFormat)
    {
      if (value)
      {
        mOutputFormat->flags |= flag;
      }
      else
      {
        mOutputFormat->flags &= (~flag);
      }
    }
  }
bool com::xuggle::xuggler::ContainerFormat::isOutput () [virtual]
Is this an output container format?
Returns:
true if output; false it not
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 198 of file ContainerFormat.cpp.
  {
    return mOutputFormat;
  }
bool com::xuggle::xuggler::ContainerFormat::isInput () [virtual]
Is this an input container format?
Returns:
true if input; false it not
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 204 of file ContainerFormat.cpp.
  {
    return mInputFormat;
  }
const char * com::xuggle::xuggler::ContainerFormat::getOutputExtensions () [virtual]
Get the filename extensions that this output format prefers (most common first).
Returns:
a command separated string of output extensions, or null if none.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 210 of file ContainerFormat.cpp.
  {
    if (!mOutputFormat || !mOutputFormat->extensions ||
        !*mOutputFormat->extensions)
      return 0;
    return mOutputFormat->extensions;
  }
ICodec::ID com::xuggle::xuggler::ContainerFormat::getOutputDefaultAudioCodec () [virtual]
Get the default audio codec this container prefers, if known.
Returns:
the default audio codec id, or ICodec.ID#CODEC_ID_NONE if unknown.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 219 of file ContainerFormat.cpp.
References com::xuggle::xuggler::ICodec::CODEC_ID_NONE.
  {
    if (!mOutputFormat)
      return ICodec::CODEC_ID_NONE;
    return (ICodec::ID)mOutputFormat->audio_codec;
  }
ICodec::ID com::xuggle::xuggler::ContainerFormat::getOutputDefaultVideoCodec () [virtual]
Get the default video codec this container prefers, if known.
Returns:
the default video codec id, or ICodec.ID#CODEC_ID_NONE if unknown.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 227 of file ContainerFormat.cpp.
References com::xuggle::xuggler::ICodec::CODEC_ID_NONE.
  {
    if (!mOutputFormat)
      return ICodec::CODEC_ID_NONE;
    return (ICodec::ID)mOutputFormat->video_codec;
  }
ICodec::ID com::xuggle::xuggler::ContainerFormat::getOutputDefaultSubtitleCodec () [virtual]
Get the default subtitle codec this container prefers, if known.
Returns:
the default subtitle codec id, or ICodec.ID#CODEC_ID_NONE if unknown.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 235 of file ContainerFormat.cpp.
References com::xuggle::xuggler::ICodec::CODEC_ID_NONE.
  {
    if (!mOutputFormat)
      return ICodec::CODEC_ID_NONE;
    return (ICodec::ID)mOutputFormat->subtitle_codec;
  }
int32_t com::xuggle::xuggler::ContainerFormat::getOutputNumCodecsSupported () [virtual]
Gets the number of different codecs this container can include for encoding.
This can be used as an upper bound when using the getOutputCodecID(int) and getOutputCodecTag(int) methods to dynamically query the actual codecs.
Returns:
The total number of different codec types that can be encoded into this container format.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 243 of file ContainerFormat.cpp.
References com::xuggle::xuggler::ICodec::CODEC_ID_NONE.
  {
    if (!mOutputFormat)
      return 0;
    const struct AVCodecTag * const*tags = mOutputFormat->codec_tag;
    if (!tags)
      return 0;
    int numCodecs = 0;
    for(int i = 0;
        tags[i];
        i++)
    {
      for(const struct AVCodecTag * tag = tags[i];
          tag && tag->id != ICodec::CODEC_ID_NONE;
          ++tag)
      {
        ++numCodecs;
      }
    }
    return numCodecs;
  }
ICodec::ID com::xuggle::xuggler::ContainerFormat::getOutputCodecID (int32_t index) [virtual]
Queries for a supported codec id from the list of codecs that can be encoded into this ContainerFormat.
Parameters:
index The index in our lookup table. Index >= 0 and < getOutputNumCodecsSupported(). Index values may change between releases, so always query.
Returns:
The codec id at this position, or ICodec.ID#CODEC_ID_NONE if there is none.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 268 of file ContainerFormat.cpp.
References com::xuggle::xuggler::ICodec::CODEC_ID_NONE.
  {
    if (index < 0)
      return ICodec::CODEC_ID_NONE;
    const struct AVCodecTag * const*tags = mOutputFormat->codec_tag;
    if (!tags)
      return ICodec::CODEC_ID_NONE;
    int numCodecs = 0;
    for(int i = 0;
        tags[i];
        i++)
    {
      for(
          const struct AVCodecTag * tag = tags[i];
          tag && tag->id != ICodec::CODEC_ID_NONE;
          ++tag, ++numCodecs)
      {
        if (numCodecs == index)
          return (ICodec::ID)tag->id;
      }
    }
    return ICodec::CODEC_ID_NONE;
  }
int32_t com::xuggle::xuggler::ContainerFormat::getOutputCodecTag (int32_t index) [virtual]
Queries for a supported codec tag from the list of codecs that can be encoded into this ContainerFormat.
Tags are 4-byte values that are often used as markers in a container format for a codec type.
Parameters:
index The index in our lookup table. Index >= 0 and < getOutputNumCodecsSupported(). Index values may change between releases, so always query.
Returns:
The codec id tag this position, or 0 if there is none.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 296 of file ContainerFormat.cpp.
References com::xuggle::xuggler::ICodec::CODEC_ID_NONE.
Referenced by isCodecSupportedForOutput().
  {
    if (index < 0)
      return ICodec::CODEC_ID_NONE;
    const struct AVCodecTag * const*tags = mOutputFormat->codec_tag;
    if (!tags)
      return ICodec::CODEC_ID_NONE;
    int numCodecs = 0;
    for(int i = 0;
        tags[i];
        i++)
    {
      for(
          const struct AVCodecTag * tag = tags[i];
          tag && tag->id != ICodec::CODEC_ID_NONE;
          ++tag, ++numCodecs)
      {
        if (numCodecs == index)
          return tag->tag;
      }
    }
    return ICodec::CODEC_ID_NONE;
  }
int32_t com::xuggle::xuggler::ContainerFormat::getOutputCodecTag (ICodec::ID id) [virtual]
Get the 4-byte tag the container would output for the given codec id.
Parameters:
id the codec you are about
Returns:
the 4-byte codec tag, or 0 if that id is not supported.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 330 of file ContainerFormat.cpp.
  {
    if (!mOutputFormat)
      return 0;
    return (int32_t)av_codec_get_tag(mOutputFormat->codec_tag,
        (enum CodecID)id);
  }
bool com::xuggle::xuggler::ContainerFormat::isCodecSupportedForOutput (ICodec::ID id) [virtual]
Returns true if this container format can output media encoded with the given codec.
Parameters:
id the codec you care about.
Returns:
true if the codec can be put in this output container; false otherwise.
Implements com::xuggle::xuggler::IContainerFormat.
Definition at line 324 of file ContainerFormat.cpp.
References getOutputCodecTag().
  {
    return getOutputCodecTag(id);
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/ContainerFormat.h
csrc/com/xuggle/xuggler/ContainerFormat.cpp