Xuggle: com::xuggle::ferry::Logger Class Reference
com::xuggle::ferry::Logger Class Reference
#include <Logger.h>
Detailed Description
Internal Only.
C++ wrapper to SLF4J Java Logging frame work.
If not running inside a JVM, then this class just does a rudimentary printout of log messages to stderr.
Otherwise, it forwards to Java's SLF4J logging framework.
Definition at line 48 of file Logger.h.
Public Types
enum Level {
LEVEL_ERROR = 0, LEVEL_WARN = 1, LEVEL_INFO = 2, LEVEL_DEBUG = 3,
LEVEL_TRACE = 4
}
Different logging levels (noiseness) supported by us.
typedef enum
com::xuggle::ferry::Logger::Level Level
Public Member Functions
bool log (const char *filename, int lineNo, Level level, const char *format,...)
Log the message to the logger, using sprintf() format strings.
bool logVA (const char *filename, int lineNo, Level level, const char *format, va_list ap)
bool error (const char *filename, int lineNo, const char *format,...)
bool warn (const char *filename, int lineNo, const char *format,...)
bool info (const char *filename, int lineNo, const char *format,...)
bool debug (const char *filename, int lineNo, const char *format,...)
bool trace (const char *filename, int lineNo, const char *format,...)
bool isLogging (Level level)
void setIsLogging (Level level, bool value)
const char * getName ()
virtual ~Logger ()
Static Public Member Functions
static Logger * getLogger (const char *aLoggerName)
Returns a new Logger object for this loggerName.
static Logger * getStaticLogger (const char *aLoggerName)
Get a Logger object, but ask the Logger code to free it up once the JavaVM shuts down.
static bool isGlobalLogging (Level level)
static void setGlobalIsLogging (Level level, bool value)
Protected Member Functions
Logger (const char *loggerName, jobject aJavaLogger)
Member Typedef Documentation
typedef enum com::xuggle::ferry::Logger::Level com::xuggle::ferry::Logger::Level
Member Enumeration Documentation
enum com::xuggle::ferry::Logger::Level
Different logging levels (noiseness) supported by us.
Enumerator:
LEVEL_ERROR
LEVEL_WARN
LEVEL_INFO
LEVEL_DEBUG
LEVEL_TRACE
Definition at line 54 of file Logger.h.
    {
      LEVEL_ERROR=0,
      LEVEL_WARN=1,
      LEVEL_INFO=2,
      LEVEL_DEBUG=3,
      LEVEL_TRACE=4
    } Level;
Constructor & Destructor Documentation
com::xuggle::ferry::Logger::~Logger () [virtual]
Definition at line 78 of file Logger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
  {
    JNIEnv *env=JNIHelper::sGetEnv();
    if (env)
    {
      if (mJavaLogger)
        env->DeleteGlobalRef(mJavaLogger);
    }
    mJavaLogger = 0;
  }
com::xuggle::ferry::Logger::Logger (const char * loggerName, jobject aJavaLogger) [protected]
Definition at line 62 of file Logger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
Referenced by getLogger().
  {
    Logger::init();
    for(unsigned int i =0 ; i< sizeof(mIsLogging)/sizeof(bool); i++)
      mIsLogging[i] = true;
    strncpy(mLoggerName, loggerName, sizeof(mLoggerName));
    mJavaLogger = 0;
    JNIEnv *env=JNIHelper::sGetEnv();
    if (env && javaLogger)
    {
      mJavaLogger = env->NewGlobalRef(javaLogger);
    }
  }
Member Function Documentation
Logger * com::xuggle::ferry::Logger::getLogger (const char * aLoggerName) [static]
Returns a new Logger object for this loggerName.
Parameters:
aLoggerName A name (no spaces allowed) for this logger.
Returns:
a New logger for logging; caller must delete when done.
Definition at line 143 of file Logger.cpp.
References Logger(), and com::xuggle::ferry::JNIHelper::sGetEnv().
Referenced by getStaticLogger().
  {
    Logger* retval = 0;
    if (loggerName && *loggerName)
    {
      if (mGetLoggerMethod)
      {
        JNIEnv *env=JNIHelper::sGetEnv();
        if (env)
        {
          jobject javaLogger = 0;
          jstring jLoggerName = env->NewStringUTF(loggerName);
          // Time to get a Java Logger
          javaLogger = env->CallStaticObjectMethod(mClass,
              mGetLoggerMethod, jLoggerName);
          env->DeleteLocalRef(jLoggerName);
          jLoggerName = 0;
          retval = new Logger(loggerName, javaLogger);
          if (javaLogger)
            env->DeleteLocalRef(javaLogger);
          javaLogger = 0;
        }
      } else {
        retval = new Logger(loggerName, 0);
      }
    }
    return retval;
  }
Logger * com::xuggle::ferry::Logger::getStaticLogger (const char * aLoggerName) [static]
Get a Logger object, but ask the Logger code to free it up once the JavaVM shuts down.
Use at your own risk.
Parameters:
aLoggerName A name (no spaces allowed) for this logger.
Returns:
A new logger for logging; caller must not call delete and must not use the logger once the JavaVM (or main) has exited.
Definition at line 177 of file Logger.cpp.
References getLogger(), and com::xuggle::ferry::JNIHelper::sRegisterTerminationCallback().
  {
    Logger* logger = 0;
    logger = Logger::getLogger(aLoggerName);
    if (logger)
    {
        // Register a function to kill it when the JNIHelper says we
        // can
        JNIHelper::sRegisterTerminationCallback(Logger::shutdownJavaBindings,
            logger);
    }
    return logger;
  }
bool com::xuggle::ferry::Logger::log (const char * filename, int lineNo, Level level, const char * format, ...)
Log the message to the logger, using sprintf() format strings.
Parameters:
filename The filename that is logging, or NULL.
lineNo The line number where this log statement is executed from. or 0.
level Level to log at.
format A format specification string, in sprintf format.
Returns:
if the message was actually logged.
Definition at line 324 of file Logger.cpp.
References logVA().
  {
    bool didLog = false;
    va_list ap;
    va_start(ap, fmt);
    didLog = this->logVA(filename, line, level, fmt, ap);
    va_end(ap);
    return didLog;
  }
bool com::xuggle::ferry::Logger::logVA (const char * filename, int lineNo, Level level, const char * format, va_list ap)
Definition at line 336 of file Logger.cpp.
Referenced by log().
  {
    bool didLog = false;
    if (mGlobalIsLogging[level] && mIsLogging[level])
    {
      char msg[cMaxLogMessageLength+1];
      formatMsg(msg, sizeof(msg), filename, line, fmt, ap);
      didLog = this->doLog(level, msg);
    }
    return didLog;
  }
bool com::xuggle::ferry::Logger::error (const char * filename, int lineNo, const char * format, ...)
bool com::xuggle::ferry::Logger::warn (const char * filename, int lineNo, const char * format, ...)
bool com::xuggle::ferry::Logger::info (const char * filename, int lineNo, const char * format, ...)
bool com::xuggle::ferry::Logger::debug (const char * filename, int lineNo, const char * format, ...)
bool com::xuggle::ferry::Logger::trace (const char * filename, int lineNo, const char * format, ...)
bool com::xuggle::ferry::Logger::isLogging (Level level)
Definition at line 266 of file Logger.cpp.
  {
    return mGlobalIsLogging[level] && mIsLogging[level];
  }
void com::xuggle::ferry::Logger::setIsLogging (Level level, bool value)
Definition at line 193 of file Logger.cpp.
  {
    mIsLogging[level] = value;
  }
bool com::xuggle::ferry::Logger::isGlobalLogging (Level level) [static]
Definition at line 272 of file Logger.cpp.
Referenced by com::xuggle::ferry::LoggerStack::LoggerStack().
  {
    return mGlobalIsLogging[level];
  }
void com::xuggle::ferry::Logger::setGlobalIsLogging (Level level, bool value) [static]
Definition at line 199 of file Logger.cpp.
Referenced by com::xuggle::ferry::LoggerStack::setGlobalLevel(), and com::xuggle::ferry::LoggerStack::~LoggerStack().
  {
    mGlobalIsLogging[level] = value;
  }
const char * com::xuggle::ferry::Logger::getName ()
Definition at line 278 of file Logger.cpp.
  {
    return mLoggerName;
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/ferry/Logger.h
csrc/com/xuggle/ferry/Logger.cpp