Xuggle: com::xuggle::xuggler::IError Class Reference
com::xuggle::xuggler::IError Class Reference
#include <IError.h>
Detailed Description
Maps from int return codes to defined Error values.
This class is used to map from Xuggler return codes (for example on IContainer#readNextPacket(IPacket) into an enum type if the error is known and a text description.
WARNING: Do not write code that depends on the integer values returned from Xuggler; instead use the integer value to create one of these objects. That's because integer values returned from methods can have different meanings on different OS systems (for example, ERROR_AGAIN is -11 on Linux, but a different value on MacOS). This class maps the error to a os-type-safe value.
Also, do not depend on the string messages staying constant. They are for debugging purposes only. And we can't control whether or not they are localized -- that's up to your OS. Sorry.
Definition at line 59 of file IError.h.
Public Types
enum Type {
ERROR_UNKNOWN, ERROR_IO, ERROR_NUMEXPECTED, ERROR_INVALIDDATA,
ERROR_NOMEM, ERROR_NOFMT, ERROR_NOTSUPPORTED, ERROR_NOENT,
ERROR_EOF, ERROR_RANGE, ERROR_AGAIN, ERROR_PATCHWELCOME,
ERROR_INTERRUPTED
}
A set of errors that Xuggler knows about.
Public Member Functions
virtual Type getType ()=0
Get the OS-independent Xuggler type for this error.
virtual const char * getDescription ()=0
Get a text description for this error.
virtual int32_t getErrorNumber ()=0
Return the raw integer value that Xuggler returned and was used to create this IError.
Static Public Member Functions
static IError * make (int32_t errorNumber)
Create a new IError object from a return value passed in from Xuggler.
static IError * make (Type type)
Create a new IError object from an IError.Type enum value.
static Type errorNumberToType (int32_t errorNo)
Translate an error number to a type.
static int32_t typeToErrorNumber (Type type)
Translate an a type to an error number.
Protected Member Functions
IError ()
virtual ~IError ()
Member Enumeration Documentation
enum com::xuggle::xuggler::IError::Type
A set of errors that Xuggler knows about.
Enumerator:
ERROR_UNKNOWN
ERROR_IO
ERROR_NUMEXPECTED
ERROR_INVALIDDATA
ERROR_NOMEM
ERROR_NOFMT
ERROR_NOTSUPPORTED
ERROR_NOENT
ERROR_EOF
ERROR_RANGE
ERROR_AGAIN
ERROR_PATCHWELCOME
ERROR_INTERRUPTED
Definition at line 65 of file IError.h.
               {
    /* Unknown error */
    ERROR_UNKNOWN,
    /* IO error */
    ERROR_IO,
    /* Number expected */
    ERROR_NUMEXPECTED,
    /* Invalid data */
    ERROR_INVALIDDATA,
    /* Out of memory */
    ERROR_NOMEM,
    /* Format not supported */
    ERROR_NOFMT,
    /* Operation not supported */
    ERROR_NOTSUPPORTED,
    /* File not found */
    ERROR_NOENT,
    /* End of file or pipe */
    ERROR_EOF,
    /* Value out of range */
    ERROR_RANGE,
    /* Try again; Not enough data available on this non-blocking call */
    ERROR_AGAIN,
    /* Not supported, and the FFMPEG team wouldn't mind a patch */
    ERROR_PATCHWELCOME,
    /* Thread was interrupted while trying an IO operation */
    ERROR_INTERRUPTED,
  } Type;
Constructor & Destructor Documentation
com::xuggle::xuggler::IError::IError () [protected]
Definition at line 33 of file IError.cpp.
{
}
com::xuggle::xuggler::IError::~IError () [protected, virtual]
Definition at line 38 of file IError.cpp.
{
}
Member Function Documentation
virtual Type com::xuggle::xuggler::IError::getType () [pure virtual]
Get the OS-independent Xuggler type for this error.
Returns:
the type.
Implemented in com::xuggle::xuggler::Error.
virtual const char* com::xuggle::xuggler::IError::getDescription () [pure virtual]
Get a text description for this error.
The description returned will be in whatever language the underlying OS decides to use, and no, we can't support localization here if the OS hasn't already done it.
Sorry.
Returns:
the description.
Implemented in com::xuggle::xuggler::Error.
virtual int32_t com::xuggle::xuggler::IError::getErrorNumber () [pure virtual]
Return the raw integer value that Xuggler returned and was used to create this IError.
Note that this value can have different meanings on different operating systems. Use getType() instead for programmatic decisions.
Returns:
the native error number.
Implemented in com::xuggle::xuggler::Error.
IError * com::xuggle::xuggler::IError::make (int32_t errorNumber) [static]
Create a new IError object from a return value passed in from Xuggler.
Parameters:
errorNumber The error number as returned from another Xuggler call. ErrorNumber must be < 0.
Returns:
a new IError, or null on error.
Reimplemented in com::xuggle::xuggler::Error.
Definition at line 44 of file IError.cpp.
References com::xuggle::xuggler::Error::make().
{
  return Error::make(errorNumber);
}
IError * com::xuggle::xuggler::IError::make (Type type) [static]
Create a new IError object from an IError.Type enum value.
Parameters:
type The type to use for creation.
Returns:
a new IError, or null on error.
Reimplemented in com::xuggle::xuggler::Error.
Definition at line 50 of file IError.cpp.
References com::xuggle::xuggler::Error::make().
{
  return Error::make(type);
}
IError::Type com::xuggle::xuggler::IError::errorNumberToType (int32_t errorNo) [static]
Translate an error number to a type.
Parameters:
errorNo The error returned from Xuggler
Returns:
the type
Reimplemented in com::xuggle::xuggler::Error.
Definition at line 62 of file IError.cpp.
References com::xuggle::xuggler::Error::errorNumberToType().
{
  return Error::errorNumberToType(errNo);
}
int32_t com::xuggle::xuggler::IError::typeToErrorNumber (Type type) [static]
Translate an a type to an error number.
Parameters:
type The type
Returns:
the error number
Reimplemented in com::xuggle::xuggler::Error.
Definition at line 56 of file IError.cpp.
References com::xuggle::xuggler::Error::typeToErrorNumber().
{
  return Error::typeToErrorNumber(type);
}
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/IError.h
csrc/com/xuggle/xuggler/IError.cpp