Xuggle: com::xuggle::xuggler::ContainerParameters Class Reference
com::xuggle::xuggler::ContainerParameters Class Reference
#include <ContainerParameters.h>
Detailed Description
Definition at line 36 of file ContainerParameters.h.
Public Member Functions
virtual IRational * getTimeBase ()
Get the time base.
virtual void setTimeBase (IRational *base)
Set the time base.
virtual int32_t getAudioSampleRate ()
Get the requested audio sample rate.
virtual void setAudioSampleRate (int32_t sampleRate)
Set the requested audio sample rate.
virtual int32_t getAudioChannels ()
Get the requested audio channels.
virtual void setAudioChannels (int32_t channels)
Set the requested audio channels.
virtual int32_t getVideoWidth ()
Get the requested video width.
virtual void setVideoWidth (int32_t width)
Set the requested video width.
virtual int32_t getVideoHeight ()
Get the requested video height.
virtual void setVideoHeight (int32_t height)
Set the requested video height.
virtual IPixelFormat::Type getPixelFormat ()
Get the requested video pixel format.
virtual void setPixelFormat (IPixelFormat::Type type)
Set the requested video pixel format.
virtual int32_t getTVChannel ()
The TV channel requested.
virtual void setTVChannel (int32_t channel)
Set the tv channel.
virtual const char * getTVStandard ()
Get the TV Standard.
virtual void setTVStandard (const char *standard)
Set the TV Standard.
virtual bool isMPEG2TSRaw ()
Are we forcing raw MPEG-2 transport stream output.
virtual void setMPEG2TSRaw (bool setting)
Force raw MPEG-2 transport stream output, if possible.
virtual bool isMPEG2TSComputePCR ()
Are we computing PCR for each transport stream packet?
virtual void setMPEG2TSComputePCR (bool setting)
Compute exact PCR for each transport stream packet (only meaningful if isMPEG2TSRaw() is true).
virtual bool isInitialPause ()
If RTSP, will we pause the stream immediately?
virtual void setInitialPause (bool setting)
Should we pause the RTSP stream on open or immediately start?
virtual AVFormatParameters * getAVParameters ()
Protected Member Functions
ContainerParameters ()
virtual ~ContainerParameters ()
Constructor & Destructor Documentation
com::xuggle::xuggler::ContainerParameters::ContainerParameters () [protected]
Definition at line 32 of file ContainerParameters.cpp.
{
  memset(&mParameters, 0, sizeof(mParameters));
  mStandard[sizeof(mStandard)-1] = 0;
  mStandard[0] = 0;
}
com::xuggle::xuggler::ContainerParameters::~ContainerParameters () [protected, virtual]
Definition at line 39 of file ContainerParameters.cpp.
{
}
Member Function Documentation
IRational * com::xuggle::xuggler::ContainerParameters::getTimeBase () [virtual]
Get the time base.
For container formats such as webcameras, this is used as the requested frame rate.
Returns:
the time base.
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 44 of file ContainerParameters.cpp.
References com::xuggle::xuggler::IRational::make().
{
  return IRational::make(mParameters.time_base.num, mParameters.time_base.den);
}
void com::xuggle::xuggler::ContainerParameters::setTimeBase (IRational * base) [virtual]
Set the time base.
Parameters:
base The time base. Ignored if null.
See also:
getTimeBase()
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 50 of file ContainerParameters.cpp.
References com::xuggle::xuggler::IRational::getDenominator(), and com::xuggle::xuggler::IRational::getNumerator().
{
  if (base) {
    mParameters.time_base.num = base->getNumerator();
    mParameters.time_base.den = base->getDenominator();
  }
}
int32_t com::xuggle::xuggler::ContainerParameters::getAudioSampleRate () [virtual]
Get the requested audio sample rate.
For some container formats, such as Alsa Microphones, this is the sample-rate you want the mic to use.
Returns:
the audio sample rate.
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 59 of file ContainerParameters.cpp.
{
  return mParameters.sample_rate;
}
void com::xuggle::xuggler::ContainerParameters::setAudioSampleRate (int32_t sampleRate) [virtual]
Set the requested audio sample rate.
Parameters:
sampleRate the sample rate.
See also:
getAudioSampleRate()
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 65 of file ContainerParameters.cpp.
{
  if (sampleRate > 0)
    mParameters.sample_rate=sampleRate;
}
int32_t com::xuggle::xuggler::ContainerParameters::getAudioChannels () [virtual]
Get the requested audio channels.
For some container formats, such as DV cameras, this is the number of audio channels you'd like to get samples for.
Returns:
the audio channels.
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 72 of file ContainerParameters.cpp.
{
  return mParameters.channels;
}
void com::xuggle::xuggler::ContainerParameters::setAudioChannels (int32_t channels) [virtual]
Set the requested audio channels.
Parameters:
channels The number of channels.
See also:
getAudioChannels()
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 77 of file ContainerParameters.cpp.
{
  if (channels > 0)
    mParameters.channels = channels;
}
int32_t com::xuggle::xuggler::ContainerParameters::getVideoWidth () [virtual]
Get the requested video width.
For some container formats, such as VFW (Video For Windows) this is the requested webcam video capture width.
Returns:
the video width.
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 84 of file ContainerParameters.cpp.
{
  return mParameters.width;
}
void com::xuggle::xuggler::ContainerParameters::setVideoWidth (int32_t width) [virtual]
Set the requested video width.
Parameters:
width The width in pixels.
See also:
getVideoWidth()
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 90 of file ContainerParameters.cpp.
{
  if (width > 0)
    mParameters.width = width;
}
int32_t com::xuggle::xuggler::ContainerParameters::getVideoHeight () [virtual]
Get the requested video height.
For some container formats, such as VFW (Video For Windows) this is the requested webcam video capture height.
Returns:
the video height.
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 97 of file ContainerParameters.cpp.
{
  return mParameters.height;
}
void com::xuggle::xuggler::ContainerParameters::setVideoHeight (int32_t height) [virtual]
Set the requested video height.
Parameters:
height The height in pixels.
See also:
getVideoHeight()
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 102 of file ContainerParameters.cpp.
{
  if (height > 0)
    mParameters.height = height;
}
IPixelFormat::Type com::xuggle::xuggler::ContainerParameters::getPixelFormat () [virtual]
Get the requested video pixel format.
For some container formats, such as VFW (Video For Windows) this is the requested webcam video capture pixel format.
Returns:
the video pixel format.
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 109 of file ContainerParameters.cpp.
{
  return (IPixelFormat::Type)mParameters.pix_fmt;
}
void com::xuggle::xuggler::ContainerParameters::setPixelFormat (IPixelFormat::Type type) [virtual]
Set the requested video pixel format.
Parameters:
type The pixel format.
See also:
getPixelFormat()
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 114 of file ContainerParameters.cpp.
{
  mParameters.pix_fmt = (enum PixelFormat) type;
}
int32_t com::xuggle::xuggler::ContainerParameters::getTVChannel () [virtual]
The TV channel requested.
Some container formats (well devices really) can have a channel you're requesting. This is it.
Returns:
the TV channel.
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 120 of file ContainerParameters.cpp.
{
  return mParameters.channel;
}
void com::xuggle::xuggler::ContainerParameters::setTVChannel (int32_t channel) [virtual]
Set the tv channel.
Parameters:
channel the tv channel
See also:
getTVChannel()
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 125 of file ContainerParameters.cpp.
{
  if (channel >= 0)
    mParameters.channel = channel;
}
const char * com::xuggle::xuggler::ContainerParameters::getTVStandard () [virtual]
Get the TV Standard.
For some container formats representing television tuners, this is the tv standard they will get data as (e.g. NTSC, PAL, SECAM).
Returns:
the TV standard
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 132 of file ContainerParameters.cpp.
{
  return *mParameters.standard ? mParameters.standard : 0;
}
void com::xuggle::xuggler::ContainerParameters::setTVStandard (const char * standard) [virtual]
Set the TV Standard.
Parameters:
standard The TV standard. Empty strings are treated as null strings.
See also:
getTVStandard()
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 138 of file ContainerParameters.cpp.
{
  if (standard && *standard)
  {
    strncpy(mStandard, standard, sizeof(mStandard)-1);
    mParameters.standard = mStandard;
  } else {
    mParameters.standard = 0;
  }
}
bool com::xuggle::xuggler::ContainerParameters::isMPEG2TSRaw () [virtual]
Are we forcing raw MPEG-2 transport stream output.
Returns:
is MPEG-2 transport stream raw
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 150 of file ContainerParameters.cpp.
{
  return mParameters.mpeg2ts_raw;
}
void com::xuggle::xuggler::ContainerParameters::setMPEG2TSRaw (bool setting) [virtual]
Force raw MPEG-2 transport stream output, if possible.
Parameters:
setting true to try forcing; false to not.
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 156 of file ContainerParameters.cpp.
{
  mParameters.mpeg2ts_raw = setting;
}
bool com::xuggle::xuggler::ContainerParameters::isMPEG2TSComputePCR () [virtual]
Are we computing PCR for each transport stream packet?
Only really meaningful if isMPEG2TSRaw() is true.
Returns:
computing PCR for each transport stream packet.
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 162 of file ContainerParameters.cpp.
{
  return mParameters.mpeg2ts_compute_pcr;
}
void com::xuggle::xuggler::ContainerParameters::setMPEG2TSComputePCR (bool setting) [virtual]
Compute exact PCR for each transport stream packet (only meaningful if isMPEG2TSRaw() is true).
Parameters:
setting true for true; false for false.
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 167 of file ContainerParameters.cpp.
{
  mParameters.mpeg2ts_compute_pcr=setting;
}
bool com::xuggle::xuggler::ContainerParameters::isInitialPause () [virtual]
If RTSP, will we pause the stream immediately?
Returns:
true for yes, false for no.
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 173 of file ContainerParameters.cpp.
{
  return mParameters.initial_pause;
}
void com::xuggle::xuggler::ContainerParameters::setInitialPause (bool setting) [virtual]
Should we pause the RTSP stream on open or immediately start?
Parameters:
setting true to pause; false to not.
Implements com::xuggle::xuggler::IContainerParameters.
Definition at line 179 of file ContainerParameters.cpp.
{
  mParameters.initial_pause=setting;
}
AVFormatParameters * com::xuggle::xuggler::ContainerParameters::getAVParameters () [virtual]
Definition at line 185 of file ContainerParameters.cpp.
Referenced by com::xuggle::xuggler::Container::writeHeader().
{
  return &mParameters;
}
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/ContainerParameters.h
csrc/com/xuggle/xuggler/ContainerParameters.cpp