Xuggle: com::xuggle::xuggler::TimeValue Class Reference
com::xuggle::xuggler::TimeValue Class Reference
#include <TimeValue.h>
Detailed Description
Definition at line 35 of file TimeValue.h.
Public Member Functions
virtual int64_t get (Unit unit)
Get the value of this ITimeValue, in the specified Unit.
virtual int32_t compareTo (ITimeValue *other)
Compare this timeValue to another.
Unit getNativeUnit ()
Static Public Member Functions
static TimeValue * make (int64_t value, Unit unit)
Make a new time value.
static TimeValue * make (TimeValue *src)
static int32_t compare (int64_t thisValue, int64_t thatValue)
And another convenience method that deals with un-unitted long values.
Protected Member Functions
TimeValue ()
virtual ~TimeValue ()
Constructor & Destructor Documentation
com::xuggle::xuggler::TimeValue::TimeValue () [protected]
Definition at line 43 of file TimeValue.cpp.
References com::xuggle::xuggler::ITimeValue::NANOSECONDS.
{
  mValue = 0;
  mUnit = NANOSECONDS;
}
com::xuggle::xuggler::TimeValue::~TimeValue () [protected, virtual]
Definition at line 49 of file TimeValue.cpp.
{
}
Member Function Documentation
int64_t com::xuggle::xuggler::TimeValue::get (Unit unit) [virtual]
Get the value of this ITimeValue, in the specified Unit.
Parameters:
unit The unit you want to get a value as.
Returns:
The value, converted into the appropriate Unit.
Implements com::xuggle::xuggler::ITimeValue.
Definition at line 84 of file TimeValue.cpp.
Referenced by compareTo().
{
  if (mUnit == aUnit)
    return mValue;
  int64_t retval = 0;
  bool multiply = false;
  int64_t factor = sConversionTable[aUnit][mUnit];
  if (!factor)
  {
    factor = sConversionTable[mUnit][aUnit];
    multiply = true;
  }
  if (multiply)
    retval = mValue * factor;
  else
    retval = mValue / factor;
  return retval;
}
int32_t com::xuggle::xuggler::TimeValue::compareTo (ITimeValue * other) [virtual]
Compare this timeValue to another.
This compareTo will compare the values, but will assume that the values can never be more than half of int64_t's MAX_VALUE apart. If they are it will assume long wrapping has occurred. This is required especially if you're using TimeValue's as absolute time stamps, and want to know which is earlier.
Parameters:
other the value to compare to
Returns:
-1 if this < other; +1 if this > other; 0 otherwise
Implements com::xuggle::xuggler::ITimeValue.
Definition at line 106 of file TimeValue.cpp.
References compare(), get(), and getNativeUnit().
{
  int32_t retval = -1;
  TimeValue* that = dynamic_cast<TimeValue*>(aThat);
  if (that)
  {
    // convert both to NANOSECONDS
    Unit thisUnit = this->getNativeUnit();
    Unit thatUnit = that->getNativeUnit();
    // NOTE: Order of the entires in the Enum matters here.
    Unit minUnit = thisUnit > thatUnit ? thisUnit : thatUnit;
    int64_t thisValue = this->get(minUnit);
    int64_t thatValue = that->get(minUnit);
    retval = TimeValue::compare(thisValue, thatValue);
  }
  return retval;
}
ITimeValue::Unit com::xuggle::xuggler::TimeValue::getNativeUnit ()
Definition at line 78 of file TimeValue.cpp.
Referenced by compareTo().
{
  return mUnit;
}
TimeValue * com::xuggle::xuggler::TimeValue::make (int64_t value, Unit unit) [static]
Make a new time value.
Parameters:
value The value.
unit The unit value is expressed in.
Returns:
a new time value.
Reimplemented from com::xuggle::xuggler::ITimeValue.
Definition at line 61 of file TimeValue.cpp.
References set().
Referenced by make(), and com::xuggle::xuggler::ITimeValue::make().
{
  TimeValue *retval = make();
  if (retval)
    retval->set(value, unit);
  return retval;
}
TimeValue * com::xuggle::xuggler::TimeValue::make (TimeValue * src) [static]
Definition at line 70 of file TimeValue.cpp.
References make(), mUnit, and mValue.
{
  if (!src)
    return 0;
  return make(src->mValue, src->mUnit);
}
static int32_t com::xuggle::xuggler::TimeValue::compare (int64_t a, int64_t b) [inline, static]
And another convenience method that deals with un-unitted long values.
Parameters:
a the first object.
b the second object.
Returns:
compare(ITimeValue, ITimeValue) where both a and b are assumed to be MICROSECONDS.
Reimplemented from com::xuggle::xuggler::ITimeValue.
Definition at line 46 of file TimeValue.h.
Referenced by com::xuggle::xuggler::ITimeValue::compare(), and compareTo().
  {
    int64_t retval;
    int64_t adjustment = 1;
    const static int64_t sMaxDistance = LLONG_MAX/2;
    if ((thisValue > sMaxDistance && thatValue <= -sMaxDistance) ||
        (thatValue > sMaxDistance && thisValue <= -sMaxDistance))
      // in these  cases we assume the time value has looped over
      // a int64_t value, and we really want to invert the diff.
      adjustment = -1;
    if (thisValue < thatValue)
      retval = -adjustment;
    else if (thisValue > thatValue)
      retval = adjustment;
    else
      retval = 0;
    return retval;
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/TimeValue.h
csrc/com/xuggle/xuggler/TimeValue.cpp