Xuggle: com::xuggle::xuggler::IAudioSamples Class Reference
com::xuggle::xuggler::IAudioSamples Class Reference
#include <IAudioSamples.h>
Detailed Description
A set of raw (decoded) samples, plus a timestamp for when to play those samples relative to other items in a given IContainer.
The timestamp value in decoded data is always in Microseonds.
Definition at line 37 of file IAudioSamples.h.
Public Types
enum Format {
FMT_NONE = -1, FMT_U8, FMT_S16, FMT_S24,
FMT_S32, FMT_FLT
}
The format we use to represent audio.
enum ChannelLayout {
CH_FRONT_LEFT = 0x00000001, CH_FRONT_RIGHT = 0x00000002, CH_FRONT_CENTER = 0x00000004, CH_LOW_FREQUENCY = 0x00000008,
CH_BACK_LEFT = 0x00000010, CH_BACK_RIGHT = 0x00000020, CH_FRONT_LEFT_OF_CENTER = 0x00000040, CH_FRONT_RIGHT_OF_CENTER = 0x00000080,
CH_BACK_CENTER = 0x00000100, CH_SIDE_LEFT = 0x00000200, CH_SIDE_RIGHT = 0x00000400, CH_TOP_CENTER = 0x00000800,
CH_TOP_FRONT_LEFT = 0x00001000, CH_TOP_FRONT_CENTER = 0x00002000, CH_TOP_FRONT_RIGHT = 0x00004000, CH_TOP_BACK_LEFT = 0x00008000,
CH_TOP_BACK_CENTER = 0x00010000, CH_TOP_BACK_RIGHT = 0x00020000, CH_STEREO_LEFT = 0x20000000, CH_STEREO_RIGHT = 0x40000000,
CH_LAYOUT_MONO = (CH_FRONT_CENTER), CH_LAYOUT_STEREO = (CH_FRONT_LEFT|CH_FRONT_RIGHT), CH_LAYOUT_2_1 = (CH_LAYOUT_STEREO|CH_BACK_CENTER), CH_LAYOUT_SURROUND = (CH_LAYOUT_STEREO|CH_FRONT_CENTER),
CH_LAYOUT_4POINT0 = (CH_LAYOUT_SURROUND|CH_BACK_CENTER), CH_LAYOUT_2_2 = (CH_LAYOUT_STEREO|CH_SIDE_LEFT|CH_SIDE_RIGHT), CH_LAYOUT_QUAD = (CH_LAYOUT_STEREO|CH_BACK_LEFT|CH_BACK_RIGHT), CH_LAYOUT_5POINT0 = (CH_LAYOUT_SURROUND|CH_SIDE_LEFT|CH_SIDE_RIGHT),
CH_LAYOUT_5POINT1 = (CH_LAYOUT_5POINT0|CH_LOW_FREQUENCY), CH_LAYOUT_5POINT0_BACK = (CH_LAYOUT_SURROUND|CH_BACK_LEFT|CH_BACK_RIGHT), CH_LAYOUT_5POINT1_BACK = (CH_LAYOUT_5POINT0_BACK|CH_LOW_FREQUENCY), CH_LAYOUT_7POINT1 = (CH_LAYOUT_5POINT1|CH_BACK_LEFT|CH_BACK_RIGHT),
CH_LAYOUT_7POINT1_WIDE, CH_LAYOUT_STEREO_DOWNMIX = (CH_STEREO_LEFT|CH_STEREO_RIGHT)
}
Public Member Functions
virtual bool isComplete ()=0
Returns whether or not we think this buffer has been filled with data.
virtual int32_t getSampleRate ()=0
Find the sample rate of the samples in this audio buffer.
virtual int32_t getChannels ()=0
Return the number of channels of the samples in this buffer.
virtual uint32_t getSampleBitDepth ()=0
Find out the bit-depth of the samples in this buffer.
virtual Format getFormat ()=0
Find the Format of the samples in this buffer.
virtual uint32_t getNumSamples ()=0
Get the number of samples in this video.
virtual uint32_t getMaxBufferSize ()=0
virtual uint32_t getMaxSamples ()=0
virtual uint32_t getSampleSize ()=0
virtual int64_t getPts ()=0
What is the Presentation Time Stamp of this set of audio samples.
virtual void setPts (int64_t aValue)=0
Set the Presentation Time Stamp for this set of samples.
virtual int64_t getNextPts ()=0
What would be the next Presentation Time Stamp after all the samples in this buffer were played?
virtual void setComplete (bool complete, uint32_t numSamples, int32_t sampleRate, int32_t channels, Format format, int64_t pts)=0
Call this if you modify the samples and are now done.
virtual int32_t setSample (uint32_t sampleIndex, int32_t channel, Format format, int32_t sample)=0
Sets the sample at the given index and channel to the sample.
virtual int32_t getSample (uint32_t sampleIndex, int32_t channel, Format format)=0
Get the sample at the given sampleIndex and channel, and return it in the asked for format.
Static Public Member Functions
static uint32_t findSampleBitDepth (Format format)
A convenience method that returns the # of bits in a given format.
static IAudioSamples * make (uint32_t numSamples, uint32_t numChannels)
Get a new audio samples buffer.
static int64_t samplesToDefaultPts (int64_t samples, int sampleRate)
Converts a number of samples at a given sampleRate into Microseconds.
static int64_t defaultPtsToSamples (int64_t duration, int sampleRate)
Converts a duration in microseconds into a number of samples, assuming a given sampleRate.
static IAudioSamples * make (com::xuggle::ferry::IBuffer *buffer, int channels, IAudioSamples::Format format)
Creates an IAudioSamples object by wrapping an object.
static IAudioSamples * make (uint32_t numSamples, uint32_t numChannels, IAudioSamples::Format format)
Get a new audio samples buffer.
Protected Member Functions
IAudioSamples ()
virtual ~IAudioSamples ()
Member Enumeration Documentation
enum com::xuggle::xuggler::IAudioSamples::Format
The format we use to represent audio.
Today only FMT_S16 (signed integer 16-bit audio) is supported.
Enumerator:
FMT_NONE
FMT_U8
FMT_S16
FMT_S24
FMT_S32
FMT_FLT
Definition at line 46 of file IAudioSamples.h.
                 {
      FMT_NONE = -1,
      FMT_U8,
      FMT_S16,
      FMT_S24,
      FMT_S32,
      FMT_FLT,
    } Format;
enum com::xuggle::xuggler::IAudioSamples::ChannelLayout
Enumerator:
CH_FRONT_LEFT
CH_FRONT_RIGHT
CH_FRONT_CENTER
CH_LOW_FREQUENCY
CH_BACK_LEFT
CH_BACK_RIGHT
CH_FRONT_LEFT_OF_CENTER
CH_FRONT_RIGHT_OF_CENTER
CH_BACK_CENTER
CH_SIDE_LEFT
CH_SIDE_RIGHT
CH_TOP_CENTER
CH_TOP_FRONT_LEFT
CH_TOP_FRONT_CENTER
CH_TOP_FRONT_RIGHT
CH_TOP_BACK_LEFT
CH_TOP_BACK_CENTER
CH_TOP_BACK_RIGHT
CH_STEREO_LEFT
CH_STEREO_RIGHT
CH_LAYOUT_MONO
CH_LAYOUT_STEREO
CH_LAYOUT_2_1
CH_LAYOUT_SURROUND
CH_LAYOUT_4POINT0
CH_LAYOUT_2_2
CH_LAYOUT_QUAD
CH_LAYOUT_5POINT0
CH_LAYOUT_5POINT1
CH_LAYOUT_5POINT0_BACK
CH_LAYOUT_5POINT1_BACK
CH_LAYOUT_7POINT1
CH_LAYOUT_7POINT1_WIDE
CH_LAYOUT_STEREO_DOWNMIX
Definition at line 258 of file IAudioSamples.h.
                 {
      CH_FRONT_LEFT             =0x00000001,
      CH_FRONT_RIGHT            =0x00000002,
      CH_FRONT_CENTER           =0x00000004,
      CH_LOW_FREQUENCY          =0x00000008,
      CH_BACK_LEFT              =0x00000010,
      CH_BACK_RIGHT             =0x00000020,
      CH_FRONT_LEFT_OF_CENTER   =0x00000040,
      CH_FRONT_RIGHT_OF_CENTER  =0x00000080,
      CH_BACK_CENTER            =0x00000100,
      CH_SIDE_LEFT              =0x00000200,
      CH_SIDE_RIGHT             =0x00000400,
      CH_TOP_CENTER             =0x00000800,
      CH_TOP_FRONT_LEFT         =0x00001000,
      CH_TOP_FRONT_CENTER       =0x00002000,
      CH_TOP_FRONT_RIGHT        =0x00004000,
      CH_TOP_BACK_LEFT          =0x00008000,
      CH_TOP_BACK_CENTER        =0x00010000,
      CH_TOP_BACK_RIGHT         =0x00020000,
      CH_STEREO_LEFT            =0x20000000,
      CH_STEREO_RIGHT           =0x40000000,
      /* Audio channel convenience macros */
      CH_LAYOUT_MONO              =(CH_FRONT_CENTER),
      CH_LAYOUT_STEREO            =(CH_FRONT_LEFT|CH_FRONT_RIGHT),
      CH_LAYOUT_2_1               =(CH_LAYOUT_STEREO|CH_BACK_CENTER),
      CH_LAYOUT_SURROUND          =(CH_LAYOUT_STEREO|CH_FRONT_CENTER),
      CH_LAYOUT_4POINT0           =(CH_LAYOUT_SURROUND|CH_BACK_CENTER),
      CH_LAYOUT_2_2               =(CH_LAYOUT_STEREO|CH_SIDE_LEFT|CH_SIDE_RIGHT),
      CH_LAYOUT_QUAD              =(CH_LAYOUT_STEREO|CH_BACK_LEFT|CH_BACK_RIGHT),
      CH_LAYOUT_5POINT0           =(CH_LAYOUT_SURROUND|CH_SIDE_LEFT|CH_SIDE_RIGHT),
      CH_LAYOUT_5POINT1           =(CH_LAYOUT_5POINT0|CH_LOW_FREQUENCY),
      CH_LAYOUT_5POINT0_BACK      =(CH_LAYOUT_SURROUND|CH_BACK_LEFT|CH_BACK_RIGHT),
      CH_LAYOUT_5POINT1_BACK      =(CH_LAYOUT_5POINT0_BACK|CH_LOW_FREQUENCY),
      CH_LAYOUT_7POINT1           =(CH_LAYOUT_5POINT1|CH_BACK_LEFT|CH_BACK_RIGHT),
      CH_LAYOUT_7POINT1_WIDE      =(CH_LAYOUT_5POINT1_BACK|
          CH_FRONT_LEFT_OF_CENTER|CH_FRONT_RIGHT_OF_CENTER
          ),
      CH_LAYOUT_STEREO_DOWNMIX    =(CH_STEREO_LEFT|CH_STEREO_RIGHT),
    } ChannelLayout;
Constructor & Destructor Documentation
com::xuggle::xuggler::IAudioSamples::IAudioSamples () [protected]
Definition at line 29 of file IAudioSamples.cpp.
  {
  }
com::xuggle::xuggler::IAudioSamples::~IAudioSamples () [protected, virtual]
Definition at line 33 of file IAudioSamples.cpp.
  {
  }
Member Function Documentation
virtual bool com::xuggle::xuggler::IAudioSamples::isComplete () [pure virtual]
Returns whether or not we think this buffer has been filled with data.
Returns:
Has setComplete() been called and the buffer populated.
Implemented in com::xuggle::xuggler::AudioSamples.
Referenced by com::xuggle::xuggler::AudioResampler::getMinimumNumSamplesRequiredInOutputSamples().
virtual int32_t com::xuggle::xuggler::IAudioSamples::getSampleRate () [pure virtual]
Find the sample rate of the samples in this audio buffer.
Returns:
The Sampling Rate of the samples in this buffer (e.g. 22050).
Implemented in com::xuggle::xuggler::AudioSamples.
Referenced by com::xuggle::xuggler::AudioResampler::getMinimumNumSamplesRequiredInOutputSamples().
virtual int32_t com::xuggle::xuggler::IAudioSamples::getChannels () [pure virtual]
Return the number of channels of the samples in this buffer.
For example, 1 is mono, 2 is stereo.
Returns:
The number of channels.
Implemented in com::xuggle::xuggler::AudioSamples.
Referenced by com::xuggle::xuggler::AudioResampler::getMinimumNumSamplesRequiredInOutputSamples().
virtual uint32_t com::xuggle::xuggler::IAudioSamples::getSampleBitDepth () [pure virtual]
Find out the bit-depth of the samples in this buffer.
Returns:
Number of bits in a raw sample (per channel)
Implemented in com::xuggle::xuggler::AudioSamples.
virtual Format com::xuggle::xuggler::IAudioSamples::getFormat () [pure virtual]
Find the Format of the samples in this buffer.
Right now only FMT_S16 is supported.
Returns:
The format of the samples.
Implemented in com::xuggle::xuggler::AudioSamples.
Referenced by com::xuggle::xuggler::AudioResampler::getMinimumNumSamplesRequiredInOutputSamples().
virtual uint32_t com::xuggle::xuggler::IAudioSamples::getNumSamples () [pure virtual]
Get the number of samples in this video.
For example, if you have 100 bytes of stereo (2-channel) 16-bit audio in this buffer, there are 25 samples. If you have 100 bytes of mono (1-channel) 16-bit audio in this buffer, you have 50 samples.
Returns:
The number of samples.
Implemented in com::xuggle::xuggler::AudioSamples.
Referenced by com::xuggle::xuggler::AudioResampler::getMinimumNumSamplesRequiredInOutputSamples().
virtual uint32_t com::xuggle::xuggler::IAudioSamples::getMaxBufferSize () [pure virtual]
Returns:
Maximum number of bytes that can be put in this buffer. To get the number of samples you can put in this IAudioSamples instance, do the following num_samples = getMaxBufferSize() / (getSampleSize())
Implemented in com::xuggle::xuggler::AudioSamples.
virtual uint32_t com::xuggle::xuggler::IAudioSamples::getMaxSamples () [pure virtual]
Returns:
Maximum number of samples this buffer can hold.
Implemented in com::xuggle::xuggler::AudioSamples.
virtual uint32_t com::xuggle::xuggler::IAudioSamples::getSampleSize () [pure virtual]
Returns:
Number of bytes in a single sample of audio (including channels). You can also get this by getSampleBitDepth()*getChannels()/8.
Implemented in com::xuggle::xuggler::AudioSamples.
virtual int64_t com::xuggle::xuggler::IAudioSamples::getPts () [pure virtual]
What is the Presentation Time Stamp of this set of audio samples.
Returns:
the presentation time stamp (pts)
Implemented in com::xuggle::xuggler::AudioSamples.
virtual void com::xuggle::xuggler::IAudioSamples::setPts (int64_t aValue) [pure virtual]
Set the Presentation Time Stamp for this set of samples.
Parameters:
aValue the new value
Implemented in com::xuggle::xuggler::AudioSamples.
virtual int64_t com::xuggle::xuggler::IAudioSamples::getNextPts () [pure virtual]
What would be the next Presentation Time Stamp after all the samples in this buffer were played?
Returns:
the next presentation time stamp (pts)
Implemented in com::xuggle::xuggler::AudioSamples.
virtual void com::xuggle::xuggler::IAudioSamples::setComplete (bool complete, uint32_t numSamples, int32_t sampleRate, int32_t channels, Format format, int64_t pts) [pure virtual]
Call this if you modify the samples and are now done.
This updates the pertinent information in the structure.
Parameters:
complete Is this set of samples complete?
numSamples Number of samples in this update (note that 4 shorts of 16-bit audio in stereo is actually 1 sample).
sampleRate The sample rate (in Hz) of this set of samples.
channels The number of channels in this set of samples.
format The sample-format of this set of samples.
pts The presentation time stamp of the starting sample in this buffer. Caller must ensure pts is in units of 1/1,000,000 of a second
Implemented in com::xuggle::xuggler::AudioSamples.
virtual int32_t com::xuggle::xuggler::IAudioSamples::setSample (uint32_t sampleIndex, int32_t channel, Format format, int32_t sample) [pure virtual]
Sets the sample at the given index and channel to the sample.
In theory we assume input is the given Format, and will convert if needed, but right now we only support FMT_S16 anyway.
Parameters:
sampleIndex The zero-based index into the set of samples
channel The zero-based channel number. If this set of samples doesn't have that given channel, an error is returned.
format The format of the given sample
sample The actual sample
Returns:
>= 0 on success; -1 on error.
Implemented in com::xuggle::xuggler::AudioSamples.
virtual int32_t com::xuggle::xuggler::IAudioSamples::getSample (uint32_t sampleIndex, int32_t channel, Format format) [pure virtual]
Get the sample at the given sampleIndex and channel, and return it in the asked for format.
Parameters:
sampleIndex The zero-based index into this set of samples.
channel The zero-based channel to get the sample from
format The format to return in
Returns:
The sample if available. If that sample is not available (e.g. because the channel doesn't exist, or the samples have not been setComplete(bool, uint32_t, int32_t, int32_t, Format, int64_t)), then this method returns 0. It is up to the caller to ensure the inputs are valid given that 0 is also a valid sample value.
Implemented in com::xuggle::xuggler::AudioSamples.
uint32_t com::xuggle::xuggler::IAudioSamples::findSampleBitDepth (Format format) [static]
A convenience method that returns the # of bits in a given format.
Be aware that right now this library only supports 16-bit audio.
Parameters:
format The format you want to find the number of bits in.
Returns:
The number of bits (not bytes) in the passed in format.
Definition at line 38 of file IAudioSamples.cpp.
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), com::xuggle::xuggler::StreamCoder::encodeAudio(), com::xuggle::xuggler::AudioSamples::getSampleBitDepth(), com::xuggle::xuggler::AudioSamples::make(), com::xuggle::xuggler::StreamCoder::open(), and com::xuggle::xuggler::AudioResampler::resample().
  {
    int bits = av_get_bits_per_sample_fmt((enum SampleFormat) format);
    return bits;
  }
IAudioSamples * com::xuggle::xuggler::IAudioSamples::make (uint32_t numSamples, uint32_t numChannels) [static]
Get a new audio samples buffer.
Note that any buffers this objects needs will be lazily allocated (i.e. we won't actually grab all the memory until we need it).
Parameters:
numSamples The minimum number of samples you're going to want to put in this buffer. We may (and probably will) return a larger buffer, but you cannot assume that.
numChannels The number of channels in the audio you'll want to put in this buffer.
Returns:
A new object, or null if we can't allocate one.
Reimplemented in com::xuggle::xuggler::AudioSamples.
Definition at line 45 of file IAudioSamples.cpp.
References com::xuggle::xuggler::Global::init(), and com::xuggle::xuggler::AudioSamples::make().
  {
    Global::init();
    return AudioSamples::make(numSamples, numChannels);
  }
int64_t com::xuggle::xuggler::IAudioSamples::samplesToDefaultPts (int64_t samples, int sampleRate) [static]
Converts a number of samples at a given sampleRate into Microseconds.
Parameters:
samples Number of samples.
sampleRate sample rate that those samples are recorded at.
Returns:
number of microseconds it would take to play that audio.
Definition at line 69 of file IAudioSamples.cpp.
References com::xuggle::xuggler::Global::DEFAULT_PTS_PER_SECOND, com::xuggle::xuggler::Global::init(), and com::xuggle::xuggler::Global::NO_PTS.
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), com::xuggle::xuggler::StreamCoder::encodeAudio(), com::xuggle::xuggler::AudioSamples::getNextPts(), and com::xuggle::xuggler::AudioResampler::resample().
  {
    // Note: These need to always round up!  a "partial sample" actually must
    // be whole (and similar with time stamps).
    int64_t retval = Global::NO_PTS;
    Global::init();
    if (sampleRate > 0)
    {
      int64_t num = samples * Global::DEFAULT_PTS_PER_SECOND;
      int64_t den = sampleRate;
      long double calc = ((long double)num)/((long double)den);
      retval = (int64_t)(calc);
    }
    return retval;
  }
int64_t com::xuggle::xuggler::IAudioSamples::defaultPtsToSamples (int64_t duration, int sampleRate) [static]
Converts a duration in microseconds into a number of samples, assuming a given sampleRate.
Parameters:
duration The duration in microseconds.
sampleRate sample rate that you want to use.
Returns:
The number of samples it would take (at the given sampleRate) to take duration microseconds to play.
Definition at line 86 of file IAudioSamples.cpp.
References com::xuggle::xuggler::Global::DEFAULT_PTS_PER_SECOND, com::xuggle::xuggler::Global::init(), and com::xuggle::xuggler::Global::NO_PTS.
  {
    int64_t retval = 0;
    Global::init();
    if (duration != Global::NO_PTS)
    {
      int64_t num = duration * sampleRate;
      int64_t den = Global::DEFAULT_PTS_PER_SECOND;
      long double calc = ((long double)num)/((long double)den);
      retval = (int64_t)(calc);
    }
    return retval;
  }
IAudioSamples * com::xuggle::xuggler::IAudioSamples::make (com::xuggle::ferry::IBuffer * buffer, int channels, IAudioSamples::Format format) [static]
Creates an IAudioSamples object by wrapping an object.
If you are decoding into this buffer, the buffer must be at least 192k*channels large (an FFmpeg requirement) or the decodeAudio call on IStreamCoder will fail with an error. If you are encoding from, any size should do.
Parameters:
buffer the buffer to wrap
channels the number of channels of audio you will put it the buffer
format the audio sample format
Returns:
a new IAudioSamples object, or null on error.
Reimplemented in com::xuggle::xuggler::AudioSamples.
Definition at line 61 of file IAudioSamples.cpp.
References com::xuggle::xuggler::Global::init(), and com::xuggle::xuggler::AudioSamples::make().
  {
    Global::init();
    return AudioSamples::make(buffer, channels, format);
  }
IAudioSamples * com::xuggle::xuggler::IAudioSamples::make (uint32_t numSamples, uint32_t numChannels, IAudioSamples::Format format) [static]
Get a new audio samples buffer.
Note that any buffers this objects needs will be lazily allocated (i.e. we won't actually grab all the memory until we need it).
Parameters:
numSamples The minimum number of samples you're going to want to put in this buffer. We may (and probably will) return a larger buffer, but you cannot assume that.
numChannels The number of channels in the audio you'll want to put in this buffer.
format The format of this buffer
Returns:
A new object, or null if we can't allocate one.
Reimplemented in com::xuggle::xuggler::AudioSamples.
Definition at line 52 of file IAudioSamples.cpp.
References com::xuggle::xuggler::Global::init(), and com::xuggle::xuggler::AudioSamples::make().
  {
    Global::init();
    return AudioSamples::make(numSamples, numChannels, format);
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/IAudioSamples.h
csrc/com/xuggle/xuggler/IAudioSamples.cpp