Xuggle: com::xuggle::ferry::Buffer Class Reference
com::xuggle::ferry::Buffer Class Reference
#include <Buffer.h>
Detailed Description
Definition at line 28 of file Buffer.h.
Public Member Functions
virtual void * getBytes (int32_t offset, int32_t length)
Returns up to length bytes, starting at offset in the underlying buffer we're managing.
virtual int32_t getBufferSize ()
Get the current maximum number of bytes that can be safely placed in this buffer.
virtual Type getType ()
Get the type this buffer was created as.
virtual void setType (Type)
Reset the buffer type to a new type.
virtual int32_t getSize ()
Returns the size, in units of getType() of this buffer.
Static Public Member Functions
static VS_API_FERRY Buffer * make (RefCounted *requestor, int32_t bufferSize)
Allocate a new buffer of at least bufferSize.
static VS_API_FERRY Buffer * make (RefCounted *requestor, void *bufToWrap, int32_t bufferSize, FreeFunc freeFunc, void *closure)
Create an iBuffer that wraps the given buffer, and calls FreeFunc(buffer, closure) on it when we believe it's safe to destruct it.
static Buffer * make (com::xuggle::ferry::RefCounted *requestor, Type type, int32_t numElements, bool zero)
Allocate a new buffer of at least bufferSize.
static int32_t getTypeSize (Type type)
Returns the size, in bytes, of elements of given Type.
Protected Member Functions
Buffer ()
virtual ~Buffer ()
Constructor & Destructor Documentation
com::xuggle::ferry::Buffer::Buffer () [protected]
Definition at line 45 of file Buffer.cpp.
References com::xuggle::ferry::IBuffer::IBUFFER_UINT8.
                   : mBuffer(0), mBufferSize(0)
  {
    mFreeFunc = 0;
    mClosure = 0;
    mInternallyAllocated = false;
    mType = IBUFFER_UINT8; // bytes
  }
com::xuggle::ferry::Buffer::~Buffer () [protected, virtual]
Definition at line 53 of file Buffer.cpp.
References com::xuggle::ferry::JNIMemoryManager::free(), and VS_ASSERT.
  {
    if (mBuffer)
    {
      VS_ASSERT(mBufferSize, "had buffer but no size");
      if (mInternallyAllocated)
        JNIMemoryManager::free(mBuffer);
      else if (mFreeFunc)
        mFreeFunc(mBuffer, mClosure);
      mBuffer = 0;
      mBufferSize = 0;
      mFreeFunc = 0;
      mClosure = 0;
    }
  }
Member Function Documentation
void * com::xuggle::ferry::Buffer::getBytes (int32_t offset, int32_t length) [virtual]
Returns up to length bytes, starting at offset in the underlying buffer we're managing.
Note that with this method you are accessing the direct memory, so be careful.
Parameters:
offset The offset (in bytes) into the buffer managed by this IBuffer
length The requested length (in bytes) you want to access. The buffer returned may actually be longer than length.
Returns:
A pointer to the direct buffer, or 0 if the offset or length would not fit within the buffer we're managing.
Implements com::xuggle::ferry::IBuffer.
Definition at line 71 of file Buffer.cpp.
  {
    void* retval = 0;
    if (length == 0)
      length = mBufferSize - offset;
    if ((length > 0) && (length + offset <= mBufferSize))
      retval = ((unsigned char*) mBuffer)+offset;
    return retval;
  }
int32_t com::xuggle::ferry::Buffer::getBufferSize () [virtual]
Get the current maximum number of bytes that can be safely placed in this buffer.
Returns:
Maximum number of bytes this buffer can manage.
Implements com::xuggle::ferry::IBuffer.
Definition at line 85 of file Buffer.cpp.
Referenced by getSize().
  {
    return mBufferSize;
  }
Buffer * com::xuggle::ferry::Buffer::make (RefCounted * requestor, int32_t bufferSize) [static]
Allocate a new buffer of at least bufferSize.
Reimplemented from com::xuggle::ferry::IBuffer.
Definition at line 91 of file Buffer.cpp.
References com::xuggle::ferry::JNIMemoryManager::free(), com::xuggle::ferry::RefCounted::getJavaAllocator(), com::xuggle::ferry::JNIMemoryManager::malloc(), mBuffer, mBufferSize, and mInternallyAllocated.
Referenced by com::xuggle::xuggler::Packet::allocateNewPayload(), com::xuggle::ferry::IBuffer::make(), and make().
  {
    Buffer* retval = 0;
    if (bufferSize <= 0)
      return 0;
    void * allocator = requestor ? requestor->getJavaAllocator() : 0;
    void *buffer = JNIMemoryManager::malloc(allocator, bufferSize);
    if (!buffer)
      return 0;
    retval = Buffer::make();
    if (!retval) {
      JNIMemoryManager::free(buffer);
      return 0;
    }
    retval->mBuffer = buffer;
    retval->mBufferSize = bufferSize;
    retval->mInternallyAllocated = true;
    return retval;
  }
Buffer * com::xuggle::ferry::Buffer::make (RefCounted * requestor, void * bufToWrap, int32_t bufferSize, FreeFunc freeFunc, void * closure) [static]
Create an iBuffer that wraps the given buffer, and calls FreeFunc(buffer, closure) on it when we believe it's safe to destruct it.
Definition at line 114 of file Buffer.cpp.
References make(), mBuffer, mBufferSize, mClosure, mFreeFunc, and mInternallyAllocated.
  {
    Buffer * retval = 0;
    if (bufToWrap && bufferSize>0)
    {
      retval = Buffer::make();
      if (retval)
      {
        retval->mFreeFunc = freeFunc;
        retval->mClosure = closure;
        retval->mBufferSize = bufferSize;
        retval->mBuffer = bufToWrap;
        retval->mInternallyAllocated = false;
      }
    }
    return retval;
  }
IBuffer::Type com::xuggle::ferry::Buffer::getType () [virtual]
Get the type this buffer was created as.
A type is really just a hint. Like objects, IBuffer objects can be cast to and from any type.
Returns:
the type
Implements com::xuggle::ferry::IBuffer.
Definition at line 135 of file Buffer.cpp.
  {
    return mType;
  }
void com::xuggle::ferry::Buffer::setType (Type type) [virtual]
Reset the buffer type to a new type.
This method does not do any data conversion, it just changes the reported type (so changing from Type#IBUFFER_UINT8 to Type#IBUFFER_SINT16 is really just a "cast" operation).
Parameters:
type the type to set to.
Implements com::xuggle::ferry::IBuffer.
Definition at line 141 of file Buffer.cpp.
  {
    mType = type;
  }
int32_t com::xuggle::ferry::Buffer::getSize () [virtual]
Returns the size, in units of getType() of this buffer.
Returns:
number of items of type getType() that will fit in this buffer.
Implements com::xuggle::ferry::IBuffer.
Definition at line 175 of file Buffer.cpp.
References getBufferSize(), and com::xuggle::ferry::IBuffer::IBUFFER_NB.
  {
    if (mType < 0 || mType >= IBUFFER_NB)
      return 0;
    return getBufferSize()/mTypeSize[(int32_t)mType];
  }
Buffer * com::xuggle::ferry::Buffer::make (com::xuggle::ferry::RefCounted * requestor, Type type, int32_t numElements, bool zero) [static]
Allocate a new buffer of at least bufferSize.
Parameters:
requestor An optional value telling the IBuffer class what object requested it. This is used for debugging memory leaks; it's a marker for the FERRY object (e.g. IPacket) that actually requested the buffer. If you're not an FERRY object, pass in null here.
type The type of buffer.
numElements The minimum number of elements of the specified type you will put in this buffer.
zero If true, we will guarantee the buffer contains only zeros. If false, we will not (it is faster to not, but then the buffer will have garbage-data in it).
Returns:
A new buffer, or null on error.
Reimplemented from com::xuggle::ferry::IBuffer.
Definition at line 147 of file Buffer.cpp.
References com::xuggle::ferry::IBuffer::IBUFFER_NB, and make().
  {
    if (numElements <= 0)
      return 0;
    if (type < 0 || type >= IBUFFER_NB)
      return 0;
    int32_t bytesRequested = numElements*mTypeSize[(int32_t)type];
    Buffer *retval = Buffer::make(requestor, bytesRequested);
    if (retval)
    {
      retval->mType = type;
      if (zero)
        memset(retval->getBytes(0, bytesRequested), 0, bytesRequested);
    }
    return retval;
  }
int32_t com::xuggle::ferry::Buffer::getTypeSize (Type type) [static]
Returns the size, in bytes, of elements of given Type.
Returns:
the size in bytes.
Reimplemented from com::xuggle::ferry::IBuffer.
Definition at line 167 of file Buffer.cpp.
References com::xuggle::ferry::IBuffer::IBUFFER_NB.
Referenced by com::xuggle::ferry::IBuffer::getTypeSize().
  {
    if (type < 0 || type >= IBUFFER_NB)
      return 0;
    return mTypeSize[(int32_t)type];
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/ferry/Buffer.h
csrc/com/xuggle/ferry/Buffer.cpp