Xuggle: com::xuggle::xuggler::Error Class Reference
com::xuggle::xuggler::Error Class Reference
#include <Error.h>
Detailed Description
Definition at line 35 of file Error.h.
Public Member Functions
virtual const char * getDescription ()
Get a text description for this error.
virtual int32_t getErrorNumber ()
Return the raw integer value that Xuggler returned and was used to create this IError.
virtual Type getType ()
Get the OS-independent Xuggler type for this error.
Static Public Member Functions
static Error * make (int32_t errNo)
Create a new IError object from a return value passed in from Xuggler.
static Error * make (Type type)
Create a new IError object from an IError.Type enum value.
static Type errorNumberToType (int32_t errorNo)
Translate an error number to a type.
static int32_t typeToErrorNumber (Type type)
Translate an a type to an error number.
Protected Member Functions
Error ()
virtual ~Error ()
Constructor & Destructor Documentation
com::xuggle::xuggler::Error::Error () [protected]
Definition at line 60 of file Error.cpp.
References com::xuggle::xuggler::IError::ERROR_UNKNOWN.
{
  mType = IError::ERROR_UNKNOWN;
  mErrorNo = 0;
  *mErrorStr = 0;
  mErrorStr[sizeof(mErrorStr)-1]=0;
}
com::xuggle::xuggler::Error::~Error () [protected, virtual]
Definition at line 68 of file Error.cpp.
{
}
Member Function Documentation
const char * com::xuggle::xuggler::Error::getDescription () [virtual]
Get a text description for this error.
The description returned will be in whatever language the underlying OS decides to use, and no, we can't support localization here if the OS hasn't already done it.
Sorry.
Returns:
the description.
Implements com::xuggle::xuggler::IError.
Definition at line 74 of file Error.cpp.
{
  const char* retval = 0;
  if (!*mErrorStr && mErrorNo != 0)
  {
#ifdef HAVE_STRERROR_R
#ifdef STRERROR_R_CHAR_P
    retval = strerror_r(AVUNERROR(mErrorNo), mErrorStr, sizeof(mErrorStr));
#else
    strerror_r(AVUNERROR(mErrorNo), mErrorStr, sizeof(mErrorStr));
    retval = mErrorStr;
#endif
#else
    retval = strerror(AVUNERROR(mErrorNo));
#endif // HAVE_STRERROR_R
    if (retval != (const char*) mErrorStr)
      strncpy(mErrorStr, retval, sizeof(mErrorStr)-1);
  }
  return *mErrorStr ? mErrorStr : 0;
}
int32_t com::xuggle::xuggler::Error::getErrorNumber () [virtual]
Return the raw integer value that Xuggler returned and was used to create this IError.
Note that this value can have different meanings on different operating systems. Use getType() instead for programmatic decisions.
Returns:
the native error number.
Implements com::xuggle::xuggler::IError.
Definition at line 96 of file Error.cpp.
{
  return mErrorNo;
}
IError::Type com::xuggle::xuggler::Error::getType () [virtual]
Get the OS-independent Xuggler type for this error.
Returns:
the type.
Implements com::xuggle::xuggler::IError.
Definition at line 101 of file Error.cpp.
{
  return mType;
}
Error * com::xuggle::xuggler::Error::make (int32_t errorNumber) [static]
Create a new IError object from a return value passed in from Xuggler.
Parameters:
errorNumber The error number as returned from another Xuggler call. ErrorNumber must be < 0.
Returns:
a new IError, or null on error.
Reimplemented from com::xuggle::xuggler::IError.
Definition at line 107 of file Error.cpp.
References errorNumberToType().
Referenced by com::xuggle::xuggler::IError::make(), and make().
{
  if (aErrorNo >= 0)
    return 0;
  return make(aErrorNo, errorNumberToType(aErrorNo));
}
Error * com::xuggle::xuggler::Error::make (Type type) [static]
Create a new IError object from an IError.Type enum value.
Parameters:
type The type to use for creation.
Returns:
a new IError, or null on error.
Reimplemented from com::xuggle::xuggler::IError.
Definition at line 116 of file Error.cpp.
References make(), and typeToErrorNumber().
{
  return make(typeToErrorNumber(aType), aType);
}
IError::Type com::xuggle::xuggler::Error::errorNumberToType (int32_t errorNo) [static]
Translate an error number to a type.
Parameters:
errorNo The error returned from Xuggler
Returns:
the type
Reimplemented from com::xuggle::xuggler::IError.
Definition at line 150 of file Error.cpp.
References com::xuggle::xuggler::IError::ERROR_UNKNOWN.
Referenced by com::xuggle::xuggler::IError::errorNumberToType(), and make().
{
  IError::Type retval = IError::ERROR_UNKNOWN;
  int i = 0;
  for(; i < sErrorMappingTableSize; i++)
  {
    if (sErrorMappingTable[i].mFfmpegError == errNo)
    {
      retval = sErrorMappingTable[i].mXugglerError;
      break;
    }
  }
  if (i >= sErrorMappingTableSize) {
    retval = IError::ERROR_UNKNOWN;
  }
  return retval;
}
int32_t com::xuggle::xuggler::Error::typeToErrorNumber (Type type) [static]
Translate an a type to an error number.
Parameters:
type The type
Returns:
the error number
Reimplemented from com::xuggle::xuggler::IError.
Definition at line 169 of file Error.cpp.
Referenced by make(), and com::xuggle::xuggler::IError::typeToErrorNumber().
{
  int32_t retval = AVERROR(EINVAL);
  int i = 0;
  for(; i < sErrorMappingTableSize; i++)
  {
    if (sErrorMappingTable[i].mXugglerError == type)
    {
      retval = sErrorMappingTable[i].mFfmpegError;
      break;
    }
  }
  if (i >= sErrorMappingTableSize) {
    retval = AVERROR(EINVAL);
  }
  return retval;
}
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/Error.h
csrc/com/xuggle/xuggler/Error.cpp