Xuggle: com::xuggle::xuggler::Stream Class Reference
com::xuggle::xuggler::Stream Class Reference
#include <Stream.h>
Detailed Description
Definition at line 36 of file Stream.h.
Public Member Functions
virtual Direction getDirection ()
Get the Direction this stream is pointing in.
virtual int getIndex ()
Get the relative position this stream has in the hosting IContainer object.
virtual int getId ()
Return a container format specific id for this stream.
virtual IStreamCoder * getStreamCoder ()
Get the StreamCoder than can manipulate this stream.
virtual IRational * getFrameRate ()
Get the (sometimes estimated) frame rate of this container.
virtual IRational * getTimeBase ()
The time base in which all timestamps (e.g.
virtual int64_t getStartTime ()
Return the start time, in getTimeBase() units, when this stream started.
virtual int64_t getDuration ()
Return the duration, in getTimeBase() units, of this stream, or Global#NO_PTS if unknown.
virtual int64_t getCurrentDts ()
The current Decompression Time Stamp that will be used on this stream, in getTimeBase() units.
virtual int getNumIndexEntries ()
Get the number of index entries in this stream.
virtual int64_t getNumFrames ()
Returns the number of encoded frames if known.
virtual void setTimeBase (IRational *)
virtual void setFrameRate (IRational *)
virtual int containerClosed (Container *container)
virtual int32_t acquire ()
Internal Only.
virtual int32_t release ()
Internal Only.
virtual IRational * getSampleAspectRatio ()
Added in 1.17.
virtual void setSampleAspectRatio (IRational *newRatio)
Sets the sample aspect ratio.
virtual const char * getLanguage ()
Get the 4-character language setting for this stream.
virtual void setLanguage (const char *language)
Set the 4-character language setting for this stream.
virtual IContainer * getContainer ()
Get the underlying container for this stream, or null if Xuggler doesn't know.
virtual IStream::ParseType getParseType ()
Get how the decoding codec should parse data from this stream.
virtual void setParseType (ParseType type)
Set the parse type the decoding codec should use.
virtual int32_t setStreamCoder (IStreamCoder *coder)
Sets the stream coder to use for this stream.
virtual AVStream * getAVStream ()
virtual IMetaData * getMetaData ()
Get the IMetaData for this object, or null if none.
virtual void setMetaData (IMetaData *metaData)
Set the IMetaData on this object, overriding any previous meta data.
virtual int32_t stampOutputPacket (IPacket *packet)
Takes a packet destined for this stream, and stamps the stream index, and converts the time stamp to the correct units (adjusting for rounding errors between stream conversions).
virtual int32_t setStreamCoder (IStreamCoder *newCoder, bool assumeOnlyStream)
Sets the stream coder to use for this stream.
virtual IIndexEntry * findTimeStampEntryInIndex (int64_t wantedTimeStamp, int32_t flags)
Search for the given time stamp in the key-frame index for this IStream.
virtual int32_t findTimeStampPositionInIndex (int64_t wantedTimeStamp, int32_t flags)
Search for the given time stamp in the key-frame index for this IStream.
virtual IIndexEntry * getIndexEntry (int32_t position)
Get the IIndexEntry at the given position in this IStream object's index.
virtual int32_t addIndexEntry (IIndexEntry *entry)
Adds an index entry into the stream's sorted index list.
Static Public Member Functions
static Stream * make (Container *container, AVStream *, Direction direction)
Protected Member Functions
Stream ()
virtual ~Stream ()
Constructor & Destructor Documentation
com::xuggle::xuggler::Stream::Stream () [protected]
Definition at line 42 of file Stream.cpp.
References com::xuggle::xuggler::IStream::INBOUND, and com::xuggle::xuggler::Global::NO_PTS.
  {
    mStream = 0;
    mDirection = INBOUND;
    mCoder = 0;
    mContainer = 0;
    mLastDts = Global::NO_PTS;
  }
com::xuggle::xuggler::Stream::~Stream () [protected, virtual]
Definition at line 51 of file Stream.cpp.
  {
    reset();
  }
Member Function Documentation
virtual Direction com::xuggle::xuggler::Stream::getDirection () [inline, virtual]
Get the Direction this stream is pointing in.
Returns:
The direction of this stream.
Implements com::xuggle::xuggler::IStream.
Definition at line 42 of file Stream.h.
{ return mDirection; }
int com::xuggle::xuggler::Stream::getIndex () [virtual]
Get the relative position this stream has in the hosting IContainer object.
Returns:
The Index within the Container of this stream.
Implements com::xuggle::xuggler::IStream.
Definition at line 97 of file Stream.cpp.
Referenced by stampOutputPacket().
  {
    return (mStream ? mStream->index : -1);
  }
int com::xuggle::xuggler::Stream::getId () [virtual]
Return a container format specific id for this stream.
Returns:
The (container format specific) id of this stream.
Implements com::xuggle::xuggler::IStream.
Definition at line 103 of file Stream.cpp.
  {
    return (mStream ? mStream->id : -1);
  }
IStreamCoder * com::xuggle::xuggler::Stream::getStreamCoder () [virtual]
Get the StreamCoder than can manipulate this stream.
If the stream is an INBOUND stream, then the StreamCoder can do a IStreamCoder::DECODE. IF this stream is an OUTBOUND stream, then the StreamCoder can do all IStreamCoder::ENCODE methods.
Returns:
The StreamCoder assigned to this object.
Implements com::xuggle::xuggler::IStream.
Definition at line 109 of file Stream.cpp.
References VS_REF_ACQUIRE.
  {
    StreamCoder *retval = 0;
    // acquire a reference for the caller
    retval = mCoder;
    VS_REF_ACQUIRE(retval);
    return retval;
  }
IRational * com::xuggle::xuggler::Stream::getFrameRate () [virtual]
Get the (sometimes estimated) frame rate of this container.
For variable frame-rate containers (they do exist) this is just an approimation. Better to use getTimeBase().
For contant frame-rate containers, this will be 1 / (getTimeBase())
Returns:
The frame-rate of this container.
Implements com::xuggle::xuggler::IStream.
Definition at line 121 of file Stream.cpp.
References com::xuggle::xuggler::IRational::make().
Referenced by com::xuggle::xuggler::StreamCoder::getFrameRate().
  {
    IRational * result = 0;
    if (mStream)
    {
      result = Rational::make(&mStream->r_frame_rate);
    }
    return result;
  }
IRational * com::xuggle::xuggler::Stream::getTimeBase () [virtual]
The time base in which all timestamps (e.g.
Presentation Time Stamp (PTS) and Decompression Time Stamp (DTS)) are represented. For example if the time base is 1/1000, then the difference between a PTS of 1 and a PTS of 2 is 1 millisecond. If the timebase is 1/1, then the difference between a PTS of 1 and a PTS of 2 is 1 second.
Returns:
The time base of this stream.
Implements com::xuggle::xuggler::IStream.
Definition at line 132 of file Stream.cpp.
References com::xuggle::xuggler::IRational::make().
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), com::xuggle::xuggler::StreamCoder::decodeVideo(), com::xuggle::xuggler::StreamCoder::getTimeBase(), and stampOutputPacket().
  {
    IRational * result = 0;
    if (mStream)
    {
      result = Rational::make(&mStream->time_base);
    }
    return result;
  }
int64_t com::xuggle::xuggler::Stream::getStartTime () [virtual]
Return the start time, in getTimeBase() units, when this stream started.
Returns:
The start time.
Implements com::xuggle::xuggler::IStream.
Definition at line 161 of file Stream.cpp.
References com::xuggle::xuggler::Global::NO_PTS.
  {
    return (mStream ? mStream->start_time : Global::NO_PTS);
  }
int64_t com::xuggle::xuggler::Stream::getDuration () [virtual]
Return the duration, in getTimeBase() units, of this stream, or Global#NO_PTS if unknown.
Returns:
The duration (in getTimeBase units) of this stream, if known.
Implements com::xuggle::xuggler::IStream.
Definition at line 167 of file Stream.cpp.
References com::xuggle::xuggler::Global::NO_PTS.
  {
    return (mStream ? mStream->duration : Global::NO_PTS);
  }
int64_t com::xuggle::xuggler::Stream::getCurrentDts () [virtual]
The current Decompression Time Stamp that will be used on this stream, in getTimeBase() units.
Returns:
The current Decompression Time Stamp that will be used on this stream.
Implements com::xuggle::xuggler::IStream.
Definition at line 173 of file Stream.cpp.
References com::xuggle::xuggler::Global::NO_PTS.
  {
    return (mStream ? mStream->cur_dts : Global::NO_PTS);
  }
int com::xuggle::xuggler::Stream::getNumIndexEntries () [virtual]
Get the number of index entries in this stream.
Returns:
The number of index entries in this stream.
See also:
getIndexEntry(int)
Implements com::xuggle::xuggler::IStream.
Definition at line 184 of file Stream.cpp.
  {
    return (mStream ? mStream->nb_index_entries : 0);
  }
int64_t com::xuggle::xuggler::Stream::getNumFrames () [virtual]
Returns the number of encoded frames if known.
Note that frames here means encoded frames, which can consist of many encoded audio samples, or an encoded video frame.
Returns:
The number of frames (encoded) in this stream.
Implements com::xuggle::xuggler::IStream.
Definition at line 179 of file Stream.cpp.
  {
    return (mStream ? mStream->nb_frames : 0);
  }
Stream * com::xuggle::xuggler::Stream::make (Container * container, AVStream * aStream, Direction direction) [static]
Definition at line 72 of file Stream.cpp.
References com::xuggle::xuggler::IStreamCoder::DECODING, com::xuggle::xuggler::IStreamCoder::ENCODING, com::xuggle::xuggler::IStream::INBOUND, com::xuggle::xuggler::StreamCoder::make(), mCoder, mContainer, mDirection, mStream, and VS_REF_RELEASE.
Referenced by com::xuggle::xuggler::Container::addNewStream().
  {
    // note: make will acquire this for us.
    Stream *newStream = 0;
    if (aStream) {
      try {
        newStream = make();
        newStream->mStream = aStream;
        newStream->mDirection = direction;
        newStream->mCoder = StreamCoder::make(
              direction == INBOUND?IStreamCoder::DECODING :
              IStreamCoder::ENCODING,
              aStream->codec,
              newStream);
        newStream->mContainer = container;
      } catch (std::bad_alloc & e) {
        VS_REF_RELEASE(newStream);
        throw e;
      }
    }
    return newStream;
  }
void com::xuggle::xuggler::Stream::setTimeBase (IRational * src) [virtual]
Definition at line 142 of file Stream.cpp.
References com::xuggle::xuggler::IRational::getDenominator(), and com::xuggle::xuggler::IRational::getNumerator().
  {
    if (mStream && src)
    {
      mStream->time_base.den = src->getDenominator();
      mStream->time_base.num = src->getNumerator();
    }
  }
void com::xuggle::xuggler::Stream::setFrameRate (IRational * src) [virtual]
Definition at line 151 of file Stream.cpp.
References com::xuggle::xuggler::IRational::getDenominator(), and com::xuggle::xuggler::IRational::getNumerator().
Referenced by com::xuggle::xuggler::StreamCoder::setFrameRate().
  {
    if (mStream && src)
    {
      mStream->r_frame_rate.den = src->getDenominator();
      mStream->r_frame_rate.num = src->getNumerator();
    }
  }
int com::xuggle::xuggler::Stream::containerClosed (Container * container) [virtual]
Definition at line 189 of file Stream.cpp.
References com::xuggle::xuggler::StreamCoder::streamClosed().
  {
    // let the coder know we're closed.
    if (mCoder)
      mCoder->streamClosed(this);
    reset();
    return 0;
  }
int32_t com::xuggle::xuggler::Stream::acquire () [virtual]
Internal Only.
DO NOT USE FROM JAVA.
Acquire a reference to this object. This increments the native internal ref count in native code by +1.
This method is called internally by Ferry in Java, and you should not call it without knowing what you are doing. But if you do call it, make sure you call release() once for each call you make to this method.
Returns:
The refcount after the acquire. Note due to multi-threaded issues, you should not rely on this value, as it may change before the method returns to you.
Reimplemented from com::xuggle::ferry::RefCounted.
Definition at line 199 of file Stream.cpp.
References com::xuggle::ferry::RefCounted::acquire(), and VS_LOG_TRACE.
  {
    int retval = 0;
    retval = RefCounted::acquire();
    VS_LOG_TRACE("Acquired %p: %d", this, retval);
    return retval;
  }
int32_t com::xuggle::xuggler::Stream::release () [virtual]
Internal Only.
DO NOT USE FROM JAVA.
This decrements the native internal ref count by -1; the object is destroyed if its ref count reaches zero.
This method is called internally by Ferry in Java, and you should not call it without knowing what you are doing. But if you do call it, make sure you had previously called acquire() once for each call to release() you make.
Returns:
The ref count after the release. Note due to multi-threaded issues, you should not rely on this value, as it may change before the method returns to you.
Reimplemented from com::xuggle::ferry::RefCounted.
Definition at line 208 of file Stream.cpp.
References com::xuggle::ferry::RefCounted::release(), and VS_LOG_TRACE.
  {
    int retval = 0;
    retval = RefCounted::release();
    VS_LOG_TRACE("Released %p: %d", this, retval);
    return retval;
  }
IRational * com::xuggle::xuggler::Stream::getSampleAspectRatio () [virtual]
Added in 1.17.
Gets the sample aspect ratio.
Returns:
The sample aspect ratio.
Implements com::xuggle::xuggler::IStream.
Definition at line 217 of file Stream.cpp.
References com::xuggle::xuggler::IRational::make().
  {
    IRational* retval = 0;
    if (mStream)
    {
      retval = IRational::make(
          mStream->sample_aspect_ratio.num,
          mStream->sample_aspect_ratio.den);
    }
    return retval;
  }
void com::xuggle::xuggler::Stream::setSampleAspectRatio (IRational * newRatio) [virtual]
Sets the sample aspect ratio.
Parameters:
newRatio The new ratio.
Implements com::xuggle::xuggler::IStream.
Definition at line 230 of file Stream.cpp.
References com::xuggle::xuggler::IRational::getDenominator(), and com::xuggle::xuggler::IRational::getNumerator().
  {
    if (aNewValue && mStream)
    {
      mStream->sample_aspect_ratio.num =
        aNewValue->getNumerator();
      mStream->sample_aspect_ratio.den =
        aNewValue->getDenominator();
    }
    return;
  }
const char * com::xuggle::xuggler::Stream::getLanguage () [virtual]
Get the 4-character language setting for this stream.
This will return null if no setting. When calling from C++, callers must ensure that the IStream outlives the value returned.
Implements com::xuggle::xuggler::IStream.
Definition at line 243 of file Stream.cpp.
References getMetaData(), and com::xuggle::xuggler::IMetaData::METADATA_NONE.
  {
    const char*retval = 0;
    com::xuggle::ferry::RefPointer<IMetaData> metaData = getMetaData();
    if (metaData) {
      retval = metaData->getValue("language", IMetaData::METADATA_NONE);
    }
    return retval;
  }
void com::xuggle::xuggler::Stream::setLanguage (const char * language) [virtual]
Set the 4-character language setting for this stream.
If a string longer than 4 characters is passed in, only the first 4 characters is copied.
Parameters:
language The new language setting. null is equivalent to the empty string. strings longer than 4 characters will be truncated to first 4 characters.
Implements com::xuggle::xuggler::IStream.
Definition at line 254 of file Stream.cpp.
References getMetaData().
  {
    com::xuggle::ferry::RefPointer<IMetaData> metaData = getMetaData();
    if (metaData) {
      metaData->setValue("language", aNewValue);
    }
    return;
  }
IContainer * com::xuggle::xuggler::Stream::getContainer () [virtual]
Get the underlying container for this stream, or null if Xuggler doesn't know.
Returns:
the container, or null if we don't know.
Implements com::xuggle::xuggler::IStream.
Definition at line 264 of file Stream.cpp.
References VS_REF_ACQUIRE.
Referenced by com::xuggle::xuggler::StreamCoder::open().
  {
    // add ref for caller
    VS_REF_ACQUIRE(mContainer);
    return mContainer;
  }
IStream::ParseType com::xuggle::xuggler::Stream::getParseType () [virtual]
Get how the decoding codec should parse data from this stream.
Returns:
the parse type.
Since:
3.0
Implements com::xuggle::xuggler::IStream.
Definition at line 315 of file Stream.cpp.
References com::xuggle::xuggler::IStream::PARSE_NONE.
  {
    if (mStream) {
      return (IStream::ParseType)mStream->need_parsing;
    } else {
      return IStream::PARSE_NONE;
    }
  }
void com::xuggle::xuggler::Stream::setParseType (ParseType type) [virtual]
Set the parse type the decoding codec should use.
Set to ParseType#PARSE_NONE if you don't want any parsing to be done.
Warning: do not set this flag unless you know what you're doing, and do not set after you've started decoding.
Parameters:
type The type to set.
Since:
3.0
Implements com::xuggle::xuggler::IStream.
Definition at line 325 of file Stream.cpp.
  {
    if (mStream) {
      mStream->need_parsing = (enum AVStreamParseType)type;
    }
  }
int32_t com::xuggle::xuggler::Stream::setStreamCoder (IStreamCoder * newCoder) [virtual]
Sets the stream coder to use for this stream.
This method will only cause a change if the IStreamCoder currently set on this IStream is not open. Otherwise the call is ignore and an error is returned.
Parameters:
newCoder The new stream coder to use.
Returns:
>= 0 on success; < 0 on error.
Implements com::xuggle::xuggler::IStream.
Definition at line 272 of file Stream.cpp.
  {
    return setStreamCoder(coder, true);
  }
virtual AVStream* com::xuggle::xuggler::Stream::getAVStream () [inline, virtual]
Definition at line 79 of file Stream.h.
Referenced by com::xuggle::xuggler::StreamCoder::setStream().
{ return mStream; }
IMetaData * com::xuggle::xuggler::Stream::getMetaData () [virtual]
Get the IMetaData for this object, or null if none.
If the IContainer or IStream object that this IMetaData came from was opened for reading, then changes via IMetaData#setValue(String, String) will have no effect on the underlying media.
If the IContainer or IStream object that this IMetaData came from was opened for writing, then changes via IMetaData#setValue(String, String) will have no effect after IContainer#writeHeader() is called.
Returns:
the IMetaData.
Since:
3.1
Implements com::xuggle::xuggler::IStream.
Definition at line 333 of file Stream.cpp.
References com::xuggle::xuggler::IMetaData::make(), and com::xuggle::xuggler::IStream::OUTBOUND.
Referenced by getLanguage(), setLanguage(), and setMetaData().
  {
    if (!mMetaData && mStream)
    {
      if (mDirection == IStream::OUTBOUND)
        mMetaData = MetaData::make(&mStream->metadata);
      else
        // make a read-only copy so when libav deletes the
        // input version we don't delete our copy
        mMetaData = MetaData::make(mStream->metadata);
    }
    return mMetaData.get();
  }
void com::xuggle::xuggler::Stream::setMetaData (IMetaData * data) [virtual]
Set the IMetaData on this object, overriding any previous meta data.
You should call this method on writable containers and before you call IContainer#writeHeader, as it probably won't do anything after that.
See also:
getMetaData()
Since:
3.1
Implements com::xuggle::xuggler::IStream.
Definition at line 348 of file Stream.cpp.
References com::xuggle::xuggler::MetaData::copy(), getMetaData(), and com::xuggle::ferry::RefCounted::release().
  {
    MetaData* data = dynamic_cast<MetaData*>(getMetaData());
    if (data) {
      data->copy(copy);
      // release for the get above
      data->release();
    }
    return;
  }
int32_t com::xuggle::xuggler::Stream::stampOutputPacket (IPacket * packet) [virtual]
Takes a packet destined for this stream, and stamps the stream index, and converts the time stamp to the correct units (adjusting for rounding errors between stream conversions).
Parameters:
packet to stamp
Returns:
>= 0 on success; <0 on failure.
Since:
3.2
Implements com::xuggle::xuggler::IStream.
Definition at line 360 of file Stream.cpp.
References com::xuggle::xuggler::IPacket::getDts(), com::xuggle::xuggler::IPacket::getDuration(), getIndex(), com::xuggle::xuggler::IPacket::getPts(), com::xuggle::xuggler::IMediaData::getTimeBase(), getTimeBase(), com::xuggle::xuggler::Global::NO_PTS, com::xuggle::xuggler::IRational::ROUND_DOWN, com::xuggle::xuggler::IPacket::setDts(), com::xuggle::xuggler::IPacket::setDuration(), com::xuggle::xuggler::IPacket::setPts(), com::xuggle::xuggler::IPacket::setStreamIndex(), com::xuggle::xuggler::IMediaData::setTimeBase(), and com::xuggle::ferry::RefPointer< T >::value().
Referenced by com::xuggle::xuggler::Container::writePacket().
  {
    if (!packet)
      return -1;
//    VS_LOG_DEBUG("input:  duration: %lld; dts: %lld; pts: %lld;",
//        packet->getDuration(), packet->getDts(), packet->getPts());
    // Always just reset this; cheaper than checking if it's
    // already set
    packet->setStreamIndex(this->getIndex());
    com::xuggle::ferry::RefPointer<IRational> thisBase = getTimeBase();
    com::xuggle::ferry::RefPointer<IRational> packetBase = packet->getTimeBase();
    if (!thisBase || !packetBase)
      return -1;
    if (thisBase->compareTo(packetBase.value()) == 0) {
//      VS_LOG_DEBUG("Same timebase: %d/%d vs %d/%d",
//          thisBase->getNumerator(), thisBase->getDenominator(),
//          packetBase->getNumerator(), packetBase->getDenominator());
      // it's already got the right time values
      return 0;
    }
    int64_t duration = packet->getDuration();
    int64_t dts = packet->getDts();
    int64_t pts = packet->getPts();
    if (duration >= 0)
      duration = thisBase->rescale(duration, packetBase.value(),
          IRational::ROUND_DOWN);
    if (pts != Global::NO_PTS)
    {
      pts = thisBase->rescale(pts, packetBase.value(), IRational::ROUND_DOWN);
    }
    if (dts != Global::NO_PTS)
    {
      dts = thisBase->rescale(dts, packetBase.value(), IRational::ROUND_DOWN);
      if (mLastDts != Global::NO_PTS && dts == mLastDts)
      {
        // adjust for rounding; we never want to insert a frame that
        // is not monotonically increasing.  Note we only do this if
        // we're off by one; that's because we ROUND_DOWN and then assume
        // that can be off by at most one.  If we're off by more than one
        // then it's really an error on the person muxing to this stream.
        dts = mLastDts+1;
        // and round up pts
        if (pts != Global::NO_PTS)
          ++pts;
        // and if after all that adjusting, pts is less than dts
        // let dts win.
        if (pts == Global::NO_PTS || pts < dts)
          pts = dts;
      }
      mLastDts = dts;
    }
//    VS_LOG_DEBUG("output: duration: %lld; dts: %lld; pts: %lld;",
//        duration, dts, pts);
    packet->setDuration(duration);
    packet->setPts(pts);
    packet->setDts(dts);
    packet->setTimeBase(thisBase.value());
//    VS_LOG_DEBUG("Reset timebase: %d/%d",
//        thisBase->getNumerator(), thisBase->getDenominator());
    return 0;
  }
int32_t com::xuggle::xuggler::Stream::setStreamCoder (IStreamCoder * newCoder, bool assumeOnlyStream) [virtual]
Sets the stream coder to use for this stream.
This method will only cause a change if the IStreamCoder currently set on this IStream is not open. Otherwise the call is ignored and an error is returned.
Parameters:
newCoder The new stream coder to use.
assumeOnlyStream If true then this IStream will notify the IStreamCoder that it is the only stream and the IStreamCoder may use it to determine time stamps to output packets with. If false then the IStreamCoder does not support automatic stamping of packets with stream index IDs and users must call stampOutputPacket(IPacket) themselves.
Returns:
>= 0 on success; < 0 on error.
Since:
3.2
Implements com::xuggle::xuggler::IStream.
Definition at line 277 of file Stream.cpp.
References com::xuggle::xuggler::StreamCoder::isOpen(), com::xuggle::xuggler::StreamCoder::setStream(), com::xuggle::xuggler::StreamCoder::streamClosed(), VS_LOG_ERROR, VS_REF_ACQUIRE, and VS_REF_RELEASE.
  {
    int32_t retval = -1;
    try
    {
      if (mCoder && mCoder->isOpen())
        throw std::runtime_error("cannot call setStreamCoder when current coder is open");
      if (!aCoder)
        throw std::runtime_error("cannot set to a null stream coder");
      StreamCoder *coder = dynamic_cast<StreamCoder*>(aCoder);
      if (!coder)
        throw std::runtime_error("IStreamCoder is not of expected underlying C++ type");
      // Close the old stream coder
      if (mCoder)
      {
        mCoder->streamClosed(this);
      }
      if (coder->setStream(this, assumeOnlyStream) < 0)
        throw std::runtime_error("IStreamCoder doesn't like this stream");
      VS_REF_RELEASE(mCoder);
      mCoder = coder;
      VS_REF_ACQUIRE(mCoder);
      retval = 0;
    }
    catch (std::exception & e)
    {
      VS_LOG_ERROR("Error: %s", e.what());
      retval = -1;
    }
    return retval;
  }
IIndexEntry * com::xuggle::xuggler::Stream::findTimeStampEntryInIndex (int64_t wantedTimeStamp, int32_t flags) [virtual]
Search for the given time stamp in the key-frame index for this IStream.
Not all IContainerFormat implementations maintain key frame indexes, but if they have one, then this method searches in the IStream index to quickly find the byte-offset of the nearest key-frame to the given time stamp.
Parameters:
wantedTimeStamp the time stamp wanted, in the stream's time base units.
flags A bitmask of the SEEK_FLAG_* flags, or 0 to turn all flags off. If IContainer#SEEK_FLAG_BACKWARDS then the returned index will correspond to the time stamp which is <= the requested one (not supported by all demuxers). If IContainer#SEEK_FLAG_BACKWARDS is not set then it will be >=. if IContainer#SEEK_FLAG_ANY seek to any frame, only keyframes otherwise (not supported by all demuxers).
Returns:
The IIndexEntry for the nearest appropriate timestamp in the index, or null if it can't be found.
Since:
3.4
Implements com::xuggle::xuggler::IStream.
Definition at line 430 of file Stream.cpp.
References findTimeStampPositionInIndex(), and getIndexEntry().
  {
    int32_t index = findTimeStampPositionInIndex(wantedTimeStamp, flags);
    // getIndexEntry will check for a negative index and return null if so
    return getIndexEntry(index);
  }
int32_t com::xuggle::xuggler::Stream::findTimeStampPositionInIndex (int64_t wantedTimeStamp, int32_t flags) [virtual]
Search for the given time stamp in the key-frame index for this IStream.
Not all IContainerFormat implementations maintain key frame indexes, but if they have one, then this method searches in the IStream index to quickly find the index entry position of the nearest key-frame to the given time stamp.
Parameters:
wantedTimeStamp the time stamp wanted, in the stream's time base units.
flags A bitmask of the SEEK_FLAG_* flags, or 0 to turn all flags off. If IContainer#SEEK_FLAG_BACKWARDS then the returned index will correspond to the time stamp which is <= the requested one (not supported by all demuxers). If IContainer#SEEK_FLAG_BACKWARDS is not set then it will be >=. if IContainer#SEEK_FLAG_ANY seek to any frame, only keyframes otherwise (not supported by all demuxers).
Returns:
The position in this IStream index, or -1 if it cannot be found or an index is not maintained.
See also:
getIndexEntry(int)
Since:
3.4
Implements com::xuggle::xuggler::IStream.
Definition at line 437 of file Stream.cpp.
Referenced by findTimeStampEntryInIndex().
  {
    int retval = -1;
    if (mStream) {
      retval = av_index_search_timestamp(
          mStream,
          wantedTimeStamp,
          flags);
    }
    return retval;
  }
IIndexEntry * com::xuggle::xuggler::Stream::getIndexEntry (int32_t position) [virtual]
Get the IIndexEntry at the given position in this IStream object's index.
Not all IContainerFormat types maintain IStream indexes, but if they do, this method can return those entries.
Do not modify the IContainer this stream is from between calls to this method and getNumIndexEntries() as indexes may be compacted while processing.
Parameters:
position The position in the index table.
Since:
3.4
Implements com::xuggle::xuggler::IStream.
Definition at line 451 of file Stream.cpp.
References com::xuggle::xuggler::IIndexEntry::make().
Referenced by findTimeStampEntryInIndex().
  {
    IIndexEntry* retval = 0;
    if (mStream->index_entries
        && index >= 0
        && index < mStream->nb_index_entries)
    {
      AVIndexEntry* entry = &(mStream->index_entries[index]);
      if (entry) {
        retval = IIndexEntry::make(
            entry->pos,
            entry->timestamp,
            entry->flags,
            entry->size,
            entry->min_distance
        );
      }
    }
    return retval;
  }
int32_t com::xuggle::xuggler::Stream::addIndexEntry (IIndexEntry * entry) [virtual]
Adds an index entry into the stream's sorted index list.
Updates the entry if the list already contains it.
Parameters:
entry The entry to add.
Returns:
>=0 on success; <0 on error.
Since:
3.4
Implements com::xuggle::xuggler::IStream.
Definition at line 472 of file Stream.cpp.
References com::xuggle::xuggler::IIndexEntry::getFlags(), com::xuggle::xuggler::IIndexEntry::getMinDistance(), com::xuggle::xuggler::IIndexEntry::getPosition(), com::xuggle::xuggler::IIndexEntry::getSize(), and com::xuggle::xuggler::IIndexEntry::getTimeStamp().
  {
    if (!entry)
      return -1;
    if (!mStream)
      return -1;
    return av_add_index_entry(mStream,
        entry->getPosition(),
        entry->getTimeStamp(),
        entry->getSize(),
        entry->getMinDistance(),
        entry->getFlags());
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/Stream.h
csrc/com/xuggle/xuggler/Stream.cpp