Xuggle: com::xuggle::xuggler::io::URLProtocolHandler Class Reference
com::xuggle::xuggler::io::URLProtocolHandler Class Reference
#include <URLProtocolHandler.h>
Detailed Description
Definition at line 28 of file URLProtocolHandler.h.
Public Member Functions
URLProtocolHandler (const char *protoName, jobject aJavaProtocolHandler)
virtual ~URLProtocolHandler ()
int url_open (URLContext *h, const char *url, int flags)
int url_close (URLContext *h)
int url_read (URLContext *h, unsigned char *buf, int size)
int url_write (URLContext *h, const unsigned char *buf, int size)
int64_t url_seek (URLContext *h, int64_t position, int whence)
Constructor & Destructor Documentation
com::xuggle::xuggler::io::URLProtocolHandler::URLProtocolHandler (const char * protoName, jobject aJavaProtocolHandler)
Definition at line 62 of file URLProtocolHandler.cpp.
{
  // We can assume that protoName will outlive this class, so
  // we don't need to copy it.
  mProtoName = protoName;
  cacheJavaMethods(aJavaProtocolHandler);
}
com::xuggle::xuggler::io::URLProtocolHandler::~URLProtocolHandler () [virtual]
Definition at line 72 of file URLProtocolHandler.cpp.
References com::xuggle::ferry::JNIHelper::sDeleteGlobalRef().
{
  if (mJavaProtoHandler)
  {
    JNIHelper::sDeleteGlobalRef(mJavaProtoHandler);
    mJavaProtoHandler = NULL;
    // now all of our other Java refers are invalid as well.
  }
}
Member Function Documentation
int com::xuggle::xuggler::io::URLProtocolHandler::url_open (URLContext * h, const char * url, int flags)
Definition at line 107 of file URLProtocolHandler.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv(), VS_LOG_DEBUG, and VS_LOG_TRACE.
{
  JNIEnv *env = JNIHelper::sGetEnv();
  int retval = -1;
  jboolean url_streaming;
  jstring jUrl = 0;
  try
  {
    URLProtocolHandler_CheckException(env);
    jUrl = env->NewStringUTF(url);
    URLProtocolHandler_CheckException(env);
    retval = env->CallIntMethod(mJavaProtoHandler, mJavaUrlOpen_mid, jUrl,
        flags);
    URLProtocolHandler_CheckException(env);
    // delete your local refs, as this is a running inside another library that likely
    // is not returning to Java soon.
    url_streaming = env->CallBooleanMethod(mJavaProtoHandler,
        mJavaUrlIsStreamed_mid, jUrl, flags);
    URLProtocolHandler_CheckException(env);
    if (url_streaming)
      h->is_streamed = 1;
    else
      h->is_streamed = 0;
  }
  catch (std::exception & e)
  {
    VS_LOG_TRACE("%s", e.what());
    retval = -1;
  }
  catch (...)
  {
    VS_LOG_DEBUG("Got unknown exception");
    retval = -1;
  }
  if (jUrl)
    env->DeleteLocalRef(jUrl);
  return retval;
}
int com::xuggle::xuggler::io::URLProtocolHandler::url_close (URLContext * h)
Definition at line 148 of file URLProtocolHandler.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv(), VS_LOG_DEBUG, and VS_LOG_TRACE.
{
  JNIEnv *env = JNIHelper::sGetEnv();
  int retval = -1;
  try
  {
    URLProtocolHandler_CheckException(env);
    retval = env->CallIntMethod(mJavaProtoHandler, mJavaUrlClose_mid);
    URLProtocolHandler_CheckException(env);
  }
  catch (std::exception & e)
  {
    VS_LOG_TRACE("%s", e.what());
    retval = -1;
  }
  catch (...)
  {
    VS_LOG_DEBUG("Got unknown exception");
    retval = -1;
  }
  return retval;
}
int com::xuggle::xuggler::io::URLProtocolHandler::url_read (URLContext * h, unsigned char * buf, int size)
Definition at line 197 of file URLProtocolHandler.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv(), VS_LOG_DEBUG, and VS_LOG_TRACE.
{
  JNIEnv *env = JNIHelper::sGetEnv();
  int retval = -1;
  jbyteArray byteArray = 0;
  try
  {
    URLProtocolHandler_CheckException(env);
    byteArray = env->NewByteArray(size);
    URLProtocolHandler_CheckException(env);
    // read into the Java byte array
    if (byteArray)
    {
      retval = env->CallIntMethod(mJavaProtoHandler, mJavaUrlRead_mid,
          byteArray, size);
      URLProtocolHandler_CheckException(env);
    }
    // now, copy into the C array, but only up to retval.
    if (retval > 0)
    {
      env->GetByteArrayRegion(byteArray, 0, retval, (jbyte*)buf);
      URLProtocolHandler_CheckException(env);
    }
  }
  catch (std::exception& e)
  {
    VS_LOG_TRACE("%s", e.what());
    retval = -1;
  }
  catch (...)
  {
    VS_LOG_DEBUG("Got unknown exception");
    retval = -1;
  }
  // delete your local refs, as this is a running inside another library that likely
  // is not returning to Java soon.
  if (byteArray)
    env->DeleteLocalRef(byteArray);
  return retval;
}
int com::xuggle::xuggler::io::URLProtocolHandler::url_write (URLContext * h, const unsigned char * buf, int size)
Definition at line 239 of file URLProtocolHandler.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv(), VS_LOG_DEBUG, and VS_LOG_TRACE.
{
  JNIEnv *env = JNIHelper::sGetEnv();
  int retval = -1;
  jbyteArray byteArray = 0;
  try
  {
    URLProtocolHandler_CheckException(env);
    byteArray = env->NewByteArray(size);
    URLProtocolHandler_CheckException(env);
    // copy the data passed into the new java byteArray
    if (byteArray)
    {
      env->SetByteArrayRegion(byteArray, 0, size, (jbyte*)buf);
      URLProtocolHandler_CheckException(env);
      // write from the Java byte array
      retval = env->CallIntMethod(mJavaProtoHandler, mJavaUrlWrite_mid,
          byteArray, size);
      URLProtocolHandler_CheckException(env);
    }
  }
  catch (std::exception & e)
  {
    VS_LOG_TRACE("%s", e.what());
    retval = -1;
  }
  catch (...)
  {
    VS_LOG_DEBUG("Got unknown exception");
    retval = -1;
  }
  // delete your local refs, as this is a running inside another library that likely
  // is not returning to Java soon.
  if (byteArray)
    env->DeleteLocalRef(byteArray);
  return retval;
}
int64_t com::xuggle::xuggler::io::URLProtocolHandler::url_seek (URLContext * h, int64_t position, int whence)
Definition at line 171 of file URLProtocolHandler.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv(), VS_LOG_DEBUG, and VS_LOG_TRACE.
{
  JNIEnv *env = JNIHelper::sGetEnv();
  int64_t retval = -1;
  try
  {
    URLProtocolHandler_CheckException(env);
    retval = env->CallLongMethod(mJavaProtoHandler, mJavaUrlSeek_mid, position,
      whence);
    URLProtocolHandler_CheckException(env);
  }
  catch (std::exception & e)
  {
    VS_LOG_TRACE("%s", e.what());
    retval = -1;
  }
  catch (...)
  {
    VS_LOG_DEBUG("Got unknown exception");
    retval = -1;
  }
  return retval;
}
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/io/URLProtocolHandler.h
csrc/com/xuggle/xuggler/io/URLProtocolHandler.cpp