Xuggle: com::xuggle::xuggler::ITimeValue Class Reference
com::xuggle::xuggler::ITimeValue Class Reference
#include <ITimeValue.h>
Detailed Description
Time (duration) values with units.
This class also has methods that correctly account for long wrapping when comparing time values. . Do not use.
Definition at line 42 of file ITimeValue.h.
Public Types
enum Unit {
DAYS, HOURS, MINUTES, SECONDS,
MILLISECONDS, MICROSECONDS, NANOSECONDS
}
Public Member Functions
virtual int64_t get (Unit unit)=0
Get the value of this ITimeValue, in the specified Unit.
virtual int32_t compareTo (ITimeValue *other)=0
Compare this timeValue to another.
Static Public Member Functions
static ITimeValue * make (int64_t value, Unit unit)
Make a new time value.
static ITimeValue * make (ITimeValue *src)
Make a copy of a time value from another time value.
static int32_t compare (ITimeValue *a, ITimeValue *b)
Convenience method that calls a.compareTo(b).
static int32_t compare (int64_t a, int64_t b)
And another convenience method that deals with un-unitted long values.
Protected Member Functions
ITimeValue ()
virtual ~ITimeValue ()
Member Enumeration Documentation
enum com::xuggle::xuggler::ITimeValue::Unit
Enumerator:
DAYS
HOURS
MINUTES
SECONDS
MILLISECONDS
MICROSECONDS
NANOSECONDS
Definition at line 45 of file ITimeValue.h.
  {
    DAYS,
    HOURS,
    MINUTES,
    SECONDS,
    MILLISECONDS,
    MICROSECONDS,
    NANOSECONDS,
  } Unit;
Constructor & Destructor Documentation
com::xuggle::xuggler::ITimeValue::ITimeValue () [protected]
Definition at line 33 of file ITimeValue.cpp.
{
}
com::xuggle::xuggler::ITimeValue::~ITimeValue () [protected, virtual]
Definition at line 37 of file ITimeValue.cpp.
{
}
Member Function Documentation
ITimeValue * com::xuggle::xuggler::ITimeValue::make (int64_t value, Unit unit) [static]
Make a new time value.
Parameters:
value The value.
unit The unit value is expressed in.
Returns:
a new time value.
Reimplemented in com::xuggle::xuggler::TimeValue.
Definition at line 42 of file ITimeValue.cpp.
References com::xuggle::xuggler::TimeValue::make().
{
  return TimeValue::make(aValue, aUnit);
}
ITimeValue * com::xuggle::xuggler::ITimeValue::make (ITimeValue * src) [static]
Make a copy of a time value from another time value.
Parameters:
src The time value to copy. If 0 this method returns 0.
Returns:
a new time value.
Definition at line 48 of file ITimeValue.cpp.
References com::xuggle::xuggler::TimeValue::make().
{
  return TimeValue::make(dynamic_cast<TimeValue*>(src));
}
virtual int64_t com::xuggle::xuggler::ITimeValue::get (Unit unit) [pure virtual]
Get the value of this ITimeValue, in the specified Unit.
Parameters:
unit The unit you want to get a value as.
Returns:
The value, converted into the appropriate Unit.
Implemented in com::xuggle::xuggler::TimeValue.
virtual int32_t com::xuggle::xuggler::ITimeValue::compareTo (ITimeValue * other) [pure virtual]
Compare this timeValue to another.
This compareTo will compare the values, but will assume that the values can never be more than half of int64_t's MAX_VALUE apart. If they are it will assume long wrapping has occurred. This is required especially if you're using TimeValue's as absolute time stamps, and want to know which is earlier.
Parameters:
other the value to compare to
Returns:
-1 if this < other; +1 if this > other; 0 otherwise
Implemented in com::xuggle::xuggler::TimeValue.
Referenced by compare().
int32_t com::xuggle::xuggler::ITimeValue::compare (ITimeValue * a, ITimeValue * b) [static]
Convenience method that calls a.compareTo(b).
See also:
compareTo(ITimeValue)
Parameters:
a first value.
b second value.
Returns:
-1 if a < b; +1 if a > b; 0 otherwise
Definition at line 54 of file ITimeValue.cpp.
References compareTo().
{
  int32_t retval = 0;
  if (a)
  {
    retval = a->compareTo(b);
  }
  else
  {
    if (b)
      // null is always less than any non-null value
      retval = 1;
    else // both are null
      retval = 0;
  }
  return retval;
}
int32_t com::xuggle::xuggler::ITimeValue::compare (int64_t a, int64_t b) [static]
And another convenience method that deals with un-unitted long values.
Parameters:
a the first object.
b the second object.
Returns:
compare(ITimeValue, ITimeValue) where both a and b are assumed to be MICROSECONDS.
Reimplemented in com::xuggle::xuggler::TimeValue.
Definition at line 74 of file ITimeValue.cpp.
References com::xuggle::xuggler::TimeValue::compare().
{
  return TimeValue::compare(a, b);
}
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/ITimeValue.h
csrc/com/xuggle/xuggler/ITimeValue.cpp