Xuggle: com::xuggle::xuggler::MediaDataWrapper Class Reference
com::xuggle::xuggler::MediaDataWrapper Class Reference
#include <MediaDataWrapper.h>
Detailed Description
Definition at line 28 of file MediaDataWrapper.h.
Public Member Functions
virtual int64_t getTimeStamp ()
Get the time stamp of this object in getTimeBase() units.
virtual void setTimeStamp (int64_t aTimeStamp)
Set the time stamp for this object in getTimeBase() units.
virtual IRational * getTimeBase ()
Get the time base that time stamps of this object are represented in.
virtual void setTimeBase (IRational *aBase)
Set the time base that time stamps of this object are represented in.
virtual
com::xuggle::ferry::IBuffer * getData ()
Get any underlying raw data available for this object.
virtual int32_t getSize ()
Get the size in bytes of the raw data available for this object.
virtual bool isKey ()
Is this object a key object? i.e.
virtual IMediaData * get ()
Return the object being wrapped.
virtual void wrap (IMediaData *aObj)
Set an object to wrap, or null to release the old object.
virtual void setKey (bool aIsKey)
Allows you to reset whether the wrapper things this is key or not.
virtual IMediaData * unwrap ()
Gets the non IMediaDataWrapper object ultimately wrapped in this wrapper, or null if there isn't one.
virtual void setData (com::xuggle::ferry::IBuffer *)
Sets the underlying buffer used by this object.
Static Public Member Functions
static MediaDataWrapper * make (IMediaData *obj)
Create a new IMediaDataWrapper that wraps a given object.
Protected Member Functions
MediaDataWrapper ()
virtual ~MediaDataWrapper ()
Constructor & Destructor Documentation
com::xuggle::xuggler::MediaDataWrapper::MediaDataWrapper () [protected]
Definition at line 30 of file MediaDataWrapper.cpp.
References com::xuggle::xuggler::Global::NO_PTS.
{
  mTimeStamp = Global::NO_PTS;
  mIsKey = true;
}
com::xuggle::xuggler::MediaDataWrapper::~MediaDataWrapper () [protected, virtual]
Definition at line 36 of file MediaDataWrapper.cpp.
{
  mTimeBase = 0;
}
Member Function Documentation
int64_t com::xuggle::xuggler::MediaDataWrapper::getTimeStamp () [virtual]
Get the time stamp of this object in getTimeBase() units.
Returns:
the time stamp
Implements com::xuggle::xuggler::IMediaData.
Definition at line 53 of file MediaDataWrapper.cpp.
{
  return mTimeStamp;
}
void com::xuggle::xuggler::MediaDataWrapper::setTimeStamp (int64_t aTimeStamp) [virtual]
Set the time stamp for this object in getTimeBase() units.
Parameters:
aTimeStamp The time stamp
Implements com::xuggle::xuggler::IMediaData.
Definition at line 59 of file MediaDataWrapper.cpp.
Referenced by wrap().
{
  mTimeStamp = aTimeStamp;
}
IRational * com::xuggle::xuggler::MediaDataWrapper::getTimeBase () [virtual]
Get the time base that time stamps of this object are represented in.
Caller must release the returned value.
Returns:
the time base.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 65 of file MediaDataWrapper.cpp.
{
  return mTimeBase.get();
}
void com::xuggle::xuggler::MediaDataWrapper::setTimeBase (IRational * aBase) [virtual]
Set the time base that time stamps of this object are represented in.
Parameters:
aBase the new time base. If null an exception is thrown.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 71 of file MediaDataWrapper.cpp.
Referenced by wrap().
{
  mTimeBase.reset(aBase, true);
}
IBuffer * com::xuggle::xuggler::MediaDataWrapper::getData () [virtual]
Get any underlying raw data available for this object.
Returns:
The raw data, or null if not accessible.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 77 of file MediaDataWrapper.cpp.
{
  IBuffer* retval=0;
  // forward to wrapped object
  if (mWrapped)
  {
    retval = mWrapped->getData();
  }
  return retval;
}
int32_t com::xuggle::xuggler::MediaDataWrapper::getSize () [virtual]
Get the size in bytes of the raw data available for this object.
Returns:
the size in bytes, or -1 if it cannot be computed.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 89 of file MediaDataWrapper.cpp.
{
  int retval = -1;
  // forward to wrapped object
  if (mWrapped)
  {
    retval = mWrapped->getSize();
  }
  return retval;
}
bool com::xuggle::xuggler::MediaDataWrapper::isKey () [virtual]
Is this object a key object? i.e.
it can be interpreted without needing any other media objects
Returns:
true if it's a key, false if not
Implements com::xuggle::xuggler::IMediaData.
Definition at line 101 of file MediaDataWrapper.cpp.
{
  return mIsKey;
}
IMediaData * com::xuggle::xuggler::MediaDataWrapper::get () [virtual]
Return the object being wrapped.
Returns:
the wrapped object
Implements com::xuggle::xuggler::IMediaDataWrapper.
Definition at line 159 of file MediaDataWrapper.cpp.
{
  return mWrapped.get();
}
void com::xuggle::xuggler::MediaDataWrapper::wrap (IMediaData * aObj) [virtual]
Set an object to wrap, or null to release the old object.
Parameters:
aObj The object to wrap; null just releases the last object
Implements com::xuggle::xuggler::IMediaDataWrapper.
Definition at line 113 of file MediaDataWrapper.cpp.
References com::xuggle::xuggler::IMediaDataWrapper::get(), com::xuggle::xuggler::IMediaData::getTimeBase(), com::xuggle::xuggler::IMediaData::getTimeStamp(), com::xuggle::xuggler::IMediaData::isKey(), com::xuggle::xuggler::Global::NO_PTS, setKey(), setTimeBase(), setTimeStamp(), com::xuggle::ferry::RefPointer< T >::value(), VS_LOG_ERROR, and VS_REF_RELEASE.
Referenced by make().
{
  IMediaDataWrapper* wrapper=dynamic_cast<IMediaDataWrapper*>(aObj);
  // loop detection to make sure we're not wrapping ourselves.
  if (wrapper) {
    RefPointer<IMediaData> obj;
    IMediaDataWrapper *me = static_cast<IMediaDataWrapper*>(this);
    do
    {
      if (wrapper == me)
        break;
      obj = wrapper->get();
    } while (0 != (wrapper = dynamic_cast<IMediaDataWrapper*>(obj.value())));
    if (wrapper == me)
    {
      VS_LOG_ERROR("Attempted to wrap an object that ultimately wraps itself.  Ignoring");
      // we're wrapping ourselves
      return;
    }
  }
  mWrapped.reset(aObj, true);
  if (aObj)
  {
    setTimeStamp(aObj->getTimeStamp());
    IRational *base = aObj->getTimeBase();
    setTimeBase(base);
    VS_REF_RELEASE(base);
    setKey(aObj->isKey());
  }
  else
  {
    setTimeStamp(Global::NO_PTS);
    setTimeBase(0);
    setKey(true);
  }
}
void com::xuggle::xuggler::MediaDataWrapper::setKey (bool aIsKey) [virtual]
Allows you to reset whether the wrapper things this is key or not.
Note the underlying wrapped object will continue to keep it's prior setting.
Parameters:
aIsKey The new key value.
Implements com::xuggle::xuggler::IMediaDataWrapper.
Definition at line 107 of file MediaDataWrapper.cpp.
Referenced by wrap().
{
  mIsKey = aIsKey;
}
IMediaData * com::xuggle::xuggler::MediaDataWrapper::unwrap () [virtual]
Gets the non IMediaDataWrapper object ultimately wrapped in this wrapper, or null if there isn't one.
Returns:
The non IMediaDataWrapper object ultimately wrapped
Implements com::xuggle::xuggler::IMediaDataWrapper.
Definition at line 165 of file MediaDataWrapper.cpp.
References com::xuggle::ferry::RefPointer< T >::get(), and com::xuggle::ferry::RefPointer< T >::value().
{
  RefPointer<IMediaData> unwrapped = get();
  // as long unwrapped points to an IMediaDataWrapper, then unwrap
  while(unwrapped && dynamic_cast<IMediaDataWrapper*>(unwrapped.value()))
    unwrapped = (dynamic_cast<IMediaDataWrapper*>(unwrapped.value()))->get();
  return unwrapped.get();
}
void com::xuggle::xuggler::MediaDataWrapper::setData (com::xuggle::ferry::IBuffer * buffer) [virtual]
Sets the underlying buffer used by this object.
This is an advanced method and is not recommended for use by those who don't fully understand how IBuffers work. Implementations of IMediaData may behave in undefined ways if the buffer you pass in is not big enough for what you ask them to do (e.g. they may discard your buffer and allocate a larger one if they need more space). It is up to the caller to ensure the buffer passed in is large enough, and is not simultaneously in use by another part of the system.
Parameters:
buffer The buffer to set. If null, this method is ignored.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 152 of file MediaDataWrapper.cpp.
{
  if (mWrapped)
    mWrapped->setData(buffer);
}
MediaDataWrapper * com::xuggle::xuggler::MediaDataWrapper::make (IMediaData * obj) [static]
Create a new IMediaDataWrapper that wraps a given object.
Parameters:
obj The object to wrap. Can be null.
Returns:
a new object, or null if we cannot allocate one.
Reimplemented from com::xuggle::xuggler::IMediaDataWrapper.
Definition at line 42 of file MediaDataWrapper.cpp.
References wrap().
Referenced by com::xuggle::xuggler::IMediaDataWrapper::make().
{
  MediaDataWrapper* retval = make();
  if (retval)
  {
    retval->wrap(obj);
  }
  return retval;
}
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/MediaDataWrapper.h
csrc/com/xuggle/xuggler/MediaDataWrapper.cpp