Xuggle: com::xuggle::xuggler::VideoPicture Class Reference
com::xuggle::xuggler::VideoPicture Class Reference
#include <VideoPicture.h>
Detailed Description
Definition at line 33 of file VideoPicture.h.
Public Member Functions
virtual int64_t getTimeStamp ()
Get the time stamp of this object in getTimeBase() units.
virtual void setTimeStamp (int64_t aTimeStamp)
Set the time stamp for this object in getTimeBase() units.
virtual bool isKey ()
Is this object a key object? i.e.
virtual IRational * getTimeBase ()
Get the time base that time stamps of this object are represented in.
virtual void setTimeBase (IRational *aBase)
Set the time base that time stamps of this object are represented in.
virtual bool isKeyFrame ()
Is this a key frame?
virtual void setKeyFrame (bool aIsKey)
Reset if this is a key frame or not.
virtual bool isComplete ()
Is this picture completely decoded?
virtual int getWidth ()
What is the width of the picture.
virtual int getHeight ()
What is the height of the picture.
virtual IPixelFormat::Type getPixelType ()
Returns the pixel format of the picture.
virtual int64_t getPts ()
What is the Presentation Time Stamp (in Microseconds) of this picture.
virtual void setPts (int64_t)
Set the Presentation Time Stamp (in Microseconds) for this picture.
virtual int getQuality ()
This value is the quality setting this VideoPicture had when it was decoded, or is the value to use when this picture is next encoded (if reset with setQuality().
virtual void setQuality (int newQuality)
Set the Quality to a new value.
virtual int32_t getSize ()
Total size in bytes of the decoded picture.
virtual
com::xuggle::ferry::IBuffer * getData ()
Get any underlying raw data available for this object.
virtual int getDataLineSize (int lineNo)
Return the size of each line in the VideoPicture data.
virtual void setComplete (bool aIsComplete, IPixelFormat::Type format, int width, int height, int64_t pts)
After modifying the raw data in this buffer, call this function to let the object know it is now complete.
virtual bool copy (IVideoPicture *srcFrame)
Copy the contents of the given picture into this picture.
virtual void setData (com::xuggle::ferry::IBuffer *buffer)
Sets the underlying buffer used by this object.
void fillAVFrame (AVFrame *frame)
Called by the StreamCoder before it encodes a picture.
void copyAVFrame (AVFrame *frame, IPixelFormat::Type pixel, int32_t width, int32_t height)
Called by the StreamCoder once it's done decoding.
VS_API_XUGGLER AVFrame * getAVFrame ()
Call to get the raw underlying AVFrame we manage; don't pass this to ffmpeg directly as ffmpeg often does weird stuff to these guys.
virtual IVideoPicture::PictType getPictureType ()
Get the picture type.
virtual void setPictureType (IVideoPicture::PictType type)
Set the picture type.
Static Public Member Functions
static VideoPicture * make (IPixelFormat::Type format, int width, int height)
The default factory for a frame.
static VideoPicture * make (com::xuggle::ferry::IBuffer *buffer, IPixelFormat::Type format, int width, int height)
Get a new picture object, by wrapping an existing com.xuggle.ferry.IBuffer.
Protected Member Functions
VideoPicture ()
virtual ~VideoPicture ()
Constructor & Destructor Documentation
com::xuggle::xuggler::VideoPicture::VideoPicture () [protected]
Definition at line 33 of file VideoPicture.cpp.
References com::xuggle::xuggler::IRational::make(), and com::xuggle::xuggler::IPixelFormat::NONE.
  {
    mIsComplete = false;
    mFrame = avcodec_alloc_frame();
    if (!mFrame)
      throw std::bad_alloc();
    // Set the private data pointer to point to me.
    mFrame->opaque = this;
    mWidth = -1;
    mHeight = -1;
    mPixelFormat = IPixelFormat::NONE;
    mTimeBase = IRational::make(1, 1000000);
  }
com::xuggle::xuggler::VideoPicture::~VideoPicture () [protected, virtual]
Definition at line 47 of file VideoPicture.cpp.
  {
    if (mFrame)
      av_free(mFrame);
    mFrame = 0;
  }
Member Function Documentation
virtual int64_t com::xuggle::xuggler::VideoPicture::getTimeStamp () [inline, virtual]
Get the time stamp of this object in getTimeBase() units.
Returns:
the time stamp
Implements com::xuggle::xuggler::IMediaData.
Definition at line 38 of file VideoPicture.h.
References getPts().
{ return getPts(); }
virtual void com::xuggle::xuggler::VideoPicture::setTimeStamp (int64_t aTimeStamp) [inline, virtual]
Set the time stamp for this object in getTimeBase() units.
Parameters:
aTimeStamp The time stamp
Implements com::xuggle::xuggler::IMediaData.
Definition at line 39 of file VideoPicture.h.
References setPts().
{ setPts(aTimeStamp); }
virtual bool com::xuggle::xuggler::VideoPicture::isKey () [inline, virtual]
Is this object a key object? i.e.
it can be interpreted without needing any other media objects
Returns:
true if it's a key, false if not
Implements com::xuggle::xuggler::IMediaData.
Definition at line 40 of file VideoPicture.h.
References isKeyFrame().
{ return isKeyFrame(); }
virtual IRational* com::xuggle::xuggler::VideoPicture::getTimeBase () [inline, virtual]
Get the time base that time stamps of this object are represented in.
Caller must release the returned value.
Returns:
the time base.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 41 of file VideoPicture.h.
{ return mTimeBase.get(); }
virtual void com::xuggle::xuggler::VideoPicture::setTimeBase (IRational * aBase) [inline, virtual]
Set the time base that time stamps of this object are represented in.
Parameters:
aBase the new time base. If null an exception is thrown.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 42 of file VideoPicture.h.
{ mTimeBase.reset(aBase, true); }
bool com::xuggle::xuggler::VideoPicture::isKeyFrame () [virtual]
Is this a key frame?
Returns:
is this a key frame
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 285 of file VideoPicture.cpp.
Referenced by isKey().
  {
    return (mFrame ? mFrame->key_frame : false);
  }
void com::xuggle::xuggler::VideoPicture::setKeyFrame (bool aIsKey) [virtual]
Reset if this is a key frame or not.
Note that regardless of how this flag is set, an IVideoPicture always contains raw video data (hence the key setting isn't really that important).
Parameters:
aIsKey True if a key frame; false if not.
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 291 of file VideoPicture.cpp.
Referenced by make().
  {
    if (mFrame)
      mFrame->key_frame = aIsKey;
  }
virtual bool com::xuggle::xuggler::VideoPicture::isComplete () [inline, virtual]
Is this picture completely decoded?
Returns:
is this picture completely decoded?
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 47 of file VideoPicture.h.
Referenced by com::xuggle::xuggler::VideoResampler::resample().
{ return mIsComplete; }
virtual int com::xuggle::xuggler::VideoPicture::getWidth () [inline, virtual]
What is the width of the picture.
Returns:
the width of the picture
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 48 of file VideoPicture.h.
Referenced by com::xuggle::xuggler::StreamCoder::encodeVideo(), and com::xuggle::xuggler::VideoResampler::resample().
{ return mWidth; }
virtual int com::xuggle::xuggler::VideoPicture::getHeight () [inline, virtual]
What is the height of the picture.
Returns:
the height of the picture
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 49 of file VideoPicture.h.
Referenced by com::xuggle::xuggler::StreamCoder::encodeVideo(), and com::xuggle::xuggler::VideoResampler::resample().
{ return mHeight; }
virtual IPixelFormat::Type com::xuggle::xuggler::VideoPicture::getPixelType () [inline, virtual]
Returns the pixel format of the picture.
Returns:
the pixel format of the picture.
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 50 of file VideoPicture.h.
Referenced by com::xuggle::xuggler::StreamCoder::encodeVideo(), and com::xuggle::xuggler::VideoResampler::resample().
{ return mPixelFormat; }
int64_t com::xuggle::xuggler::VideoPicture::getPts () [virtual]
What is the Presentation Time Stamp (in Microseconds) of this picture.
The PTS is is scaled so that 1 PTS = 1/1,000,000 of a second.
Returns:
the presentation time stamp (pts)
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 298 of file VideoPicture.cpp.
Referenced by com::xuggle::xuggler::StreamCoder::encodeVideo(), getTimeStamp(), and com::xuggle::xuggler::VideoResampler::resample().
  {
    return (mFrame ? mFrame->pts : -1);
  }
void com::xuggle::xuggler::VideoPicture::setPts (int64_t value) [virtual]
Set the Presentation Time Stamp (in Microseconds) for this picture.
See also:
getPts()
Parameters:
value the new timestamp
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 304 of file VideoPicture.cpp.
Referenced by setComplete(), and setTimeStamp().
  {
    if (mFrame)
      mFrame->pts = value;
  }
int com::xuggle::xuggler::VideoPicture::getQuality () [virtual]
This value is the quality setting this VideoPicture had when it was decoded, or is the value to use when this picture is next encoded (if reset with setQuality().
Returns:
The quality.
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 311 of file VideoPicture.cpp.
Referenced by fillAVFrame(), and com::xuggle::xuggler::VideoResampler::resample().
  {
    return (mFrame ? mFrame->quality : FF_LAMBDA_MAX);
  }
void com::xuggle::xuggler::VideoPicture::setQuality (int newQuality) [virtual]
Set the Quality to a new value.
This will be used the next time this VideoPicture is encoded by a StreamCoder
Parameters:
newQuality The new quality.
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 317 of file VideoPicture.cpp.
Referenced by com::xuggle::xuggler::VideoResampler::resample().
  {
    if (newQuality < 0 || newQuality > FF_LAMBDA_MAX)
      newQuality = FF_LAMBDA_MAX;
    if (mFrame)
      mFrame->quality = newQuality;
  }
int32_t com::xuggle::xuggler::VideoPicture::getSize () [virtual]
Total size in bytes of the decoded picture.
Returns:
number of bytes of decoded picture
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 363 of file VideoPicture.cpp.
Referenced by copy(), copyAVFrame(), com::xuggle::xuggler::StreamCoder::encodeVideo(), fillAVFrame(), getAVFrame(), getData(), and make().
  {
    int retval = -1;
    if (mWidth > 0 && mHeight > 0)
      retval = avpicture_get_size((PixelFormat)mPixelFormat, mWidth, mHeight);
    return retval;
  }
com::xuggle::ferry::IBuffer * com::xuggle::xuggler::VideoPicture::getData () [virtual]
Get any underlying raw data available for this object.
Returns:
The raw data, or null if not accessible.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 174 of file VideoPicture.cpp.
References com::xuggle::ferry::RefPointer< T >::get(), getSize(), VS_LOG_DEBUG, and VS_REF_RELEASE.
  {
    com::xuggle::ferry::IBuffer *retval = 0;
    try {
      if (getSize() > 0) {
        if (!mBuffer || mBuffer->getBufferSize() < getSize())
        {
          allocInternalFrameBuffer();
        }
        retval = mBuffer.get();
        if (!retval) {
          throw std::bad_alloc();
        }
      }
    } catch (std::bad_alloc &e) {
      VS_REF_RELEASE(retval);
      throw e;
    } catch (std::exception & e)
    {
      VS_LOG_DEBUG("Error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
int com::xuggle::xuggler::VideoPicture::getDataLineSize (int lineNo) [virtual]
Return the size of each line in the VideoPicture data.
Usually there are no more than 4 lines, but the first line no that returns 0 is the end of the road.
Parameters:
lineNo The line you want to know the (byte) size of.
Returns:
The size (in bytes) of that line in data.
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 274 of file VideoPicture.cpp.
References getAVFrame().
  {
    int retval = -1;
    if (getAVFrame()
        && lineNo >= 0
        && (unsigned int) lineNo < (sizeof(mFrame->linesize)/sizeof(mFrame->linesize[0])))
      retval = mFrame->linesize[lineNo];
    return retval;
  }
void com::xuggle::xuggler::VideoPicture::setComplete (bool aIsComplete, IPixelFormat::Type format, int width, int height, int64_t pts) [virtual]
After modifying the raw data in this buffer, call this function to let the object know it is now complete.
Parameters:
aIsComplete Is this VideoPicture complete
format The pixel format of the data in this picture. Must match what the picture was originally constructed with.
width The width of the data in this picture. Must match what the picture was originally constructed with.
height The height of the data in this picture. Must match what the picture was originally constructed with.
pts The presentation timestamp of the picture that is now complete. The caller must ensure this PTS is in units of 1/1,000,000 seconds.
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 326 of file VideoPicture.cpp.
References com::xuggle::xuggler::IPixelFormat::NONE, setPts(), and VS_LOG_DEBUG.
Referenced by copy(), com::xuggle::xuggler::StreamCoder::decodeVideo(), and com::xuggle::xuggler::VideoResampler::resample().
  {
    try {
      mIsComplete = aIsComplete;
      if (mIsComplete)
      {
        setPts(pts);
      }
      if (format != IPixelFormat::NONE && mPixelFormat != IPixelFormat::NONE && format != mPixelFormat)
        throw std::runtime_error("pixel formats don't match");
      if (width > 0 && mWidth >0 && width != mWidth)
        throw std::runtime_error("width does not match");
      if (height > 0 && mHeight > 0 && height != mHeight)
        throw std::runtime_error("height does not match");
      if (!mFrame)
        throw std::runtime_error("no AVFrame allocated");
      mWidth = width;
      mHeight = height;
      mPixelFormat = format;
    }
    catch (std::exception& e)
    {
      VS_LOG_DEBUG("error: %s", e.what());
    }
  }
bool com::xuggle::xuggler::VideoPicture::copy (IVideoPicture * srcPicture) [virtual]
Copy the contents of the given picture into this picture.
All buffers are copied by value, not be reference.
Parameters:
srcPicture The picture you want to copy.
Returns:
true if a successful copy; false if not.
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 133 of file VideoPicture.cpp.
References com::xuggle::xuggler::IVideoPicture::getHeight(), com::xuggle::xuggler::IVideoPicture::getPixelType(), com::xuggle::xuggler::IVideoPicture::getPts(), getSize(), com::xuggle::xuggler::IVideoPicture::getWidth(), com::xuggle::xuggler::IVideoPicture::isComplete(), mBuffer, setComplete(), and VS_LOG_DEBUG.
  {
    bool result = false;
    try
    {
      if (!srcFrame)
        throw std::runtime_error("empty source frame to copy");
      if (!srcFrame->isComplete())
        throw std::runtime_error("source frame is not complete");
      VideoPicture* src = dynamic_cast<VideoPicture*>(srcFrame);
      if (!src)
        throw std::runtime_error("src frame is not of right subtype");
      // now copy the data
      allocInternalFrameBuffer();
      // get the raw buffers
      unsigned char* srcBuffer = (unsigned char*)src->mBuffer->getBytes(0, src->getSize());
      unsigned char* dstBuffer = (unsigned char*)mBuffer->getBytes(0, getSize());
      if (!srcBuffer || !dstBuffer)
        throw std::runtime_error("could not get buffer to copy");
      memcpy(dstBuffer, srcBuffer, getSize());
      this->setComplete(true,
          srcFrame->getPixelType(),
          srcFrame->getWidth(),
          srcFrame->getHeight(),
          srcFrame->getPts());
      result = true;
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("error: %s", e.what());
      result = false;
    }
    return result;
  }
void com::xuggle::xuggler::VideoPicture::setData (com::xuggle::ferry::IBuffer * buffer) [virtual]
Sets the underlying buffer used by this object.
This is an advanced method and is not recommended for use by those who don't fully understand how IBuffers work. Implementations of IMediaData may behave in undefined ways if the buffer you pass in is not big enough for what you ask them to do (e.g. they may discard your buffer and allocate a larger one if they need more space). It is up to the caller to ensure the buffer passed in is large enough, and is not simultaneously in use by another part of the system.
Parameters:
buffer The buffer to set. If null, this method is ignored.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 125 of file VideoPicture.cpp.
References com::xuggle::ferry::RefPointer< T >::reset().
  {
    if (!buffer) return;
    mBuffer.reset(buffer, true);
  }
void com::xuggle::xuggler::VideoPicture::fillAVFrame (AVFrame * frame)
Called by the StreamCoder before it encodes a picture.
The VideoPicture fills in Ffmpeg's AVFrame structure with the underlying data for the frame we're managing, but we maintain memory management.
Definition at line 200 of file VideoPicture.cpp.
References getQuality(), and getSize().
Referenced by com::xuggle::xuggler::StreamCoder::encodeVideo().
  {
    if (!mBuffer || mBuffer->getBufferSize() < getSize())
      allocInternalFrameBuffer();
    unsigned char* buffer = (unsigned char*)mBuffer->getBytes(0, getSize());
    *frame = *mFrame;
    avpicture_fill((AVPicture*)frame, buffer, (enum PixelFormat) mPixelFormat,
        mWidth, mHeight);
    frame->quality = getQuality();
    frame->type = FF_BUFFER_TYPE_USER;
  }
void com::xuggle::xuggler::VideoPicture::copyAVFrame (AVFrame * frame, IPixelFormat::Type pixel, int32_t width, int32_t height)
Called by the StreamCoder once it's done decoding.
We copy data from the buffers that ffmpeg allocated into our own buffers.
Parameters:
frame The AVFrame that ffmpeg filled in.
pixel The pixel type
width The width of the AVFrame
height The height of the AVFrame
Definition at line 213 of file VideoPicture.cpp.
References getSize(), VS_ASSERT, and VS_LOG_DEBUG.
Referenced by com::xuggle::xuggler::StreamCoder::decodeVideo().
  {
    try
    {
      // Need to copy the contents of frame->data to our
      // internal buffer.
      VS_ASSERT(frame, "no frame?");
      VS_ASSERT(frame->data[0], "no data in frame");
      // resize the frame to the AVFrame
      mWidth = width;
      mHeight = height;
      mPixelFormat = pixel;
      int bufSize = getSize();
      if (bufSize <= 0)
        throw std::runtime_error("invalid size for frame");
      if (!mBuffer || mBuffer->getBufferSize() < bufSize)
        // reuse buffers if we can.
        allocInternalFrameBuffer();
      uint8_t* buffer = (uint8_t*)mBuffer->getBytes(0, bufSize);
      if (!buffer)
        throw std::runtime_error("really?  no buffer");
      if (frame->data[0])
      {
        // Make sure the frame isn't already using our buffer
        if(buffer != frame->data[0])
        {
          avpicture_fill((AVPicture*)mFrame, buffer,
              (enum PixelFormat) mPixelFormat, mWidth, mHeight);
          av_picture_copy((AVPicture*)mFrame, (AVPicture*)frame,
              (PixelFormat)mPixelFormat, mWidth, mHeight);
        }
        mFrame->key_frame = frame->key_frame;
      }
      else
      {
        throw std::runtime_error("no data in frame to copy");
      }
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("error: %s", e.what());
    }
  }
AVFrame * com::xuggle::xuggler::VideoPicture::getAVFrame ()
Call to get the raw underlying AVFrame we manage; don't pass this to ffmpeg directly as ffmpeg often does weird stuff to these guys.
Note: This method is exported out of the DLL because the extras library uses it.
Definition at line 263 of file VideoPicture.cpp.
References getSize().
Referenced by getDataLineSize(), and com::xuggle::xuggler::VideoResampler::resample().
  {
    if (!mBuffer || mBuffer->getBufferSize() < getSize())
    {
      // reuse buffers if we can.
      allocInternalFrameBuffer();
    }
    return mFrame;
  }
VideoPicture * com::xuggle::xuggler::VideoPicture::make (IPixelFormat::Type format, int width, int height) [static]
The default factory for a frame.
We require callers to always tell us the format, width and height of the image they want to store in this VideoPicture.
Parameters:
format The pixel format
width The expected width of this image.
height The expected height of this image.
Returns:
A new frame that can store an image and associated decoding information.
Reimplemented from com::xuggle::xuggler::IVideoPicture.
Definition at line 55 of file VideoPicture.cpp.
References mHeight, mPixelFormat, mWidth, setKeyFrame(), VS_LOG_DEBUG, and VS_REF_RELEASE.
Referenced by make(), and com::xuggle::xuggler::IVideoPicture::make().
  {
    VideoPicture * retval=0;
    try {
      retval = VideoPicture::make();
      retval->mPixelFormat = format;
      retval->mWidth = width;
      retval->mHeight = height;
      // default new frames to be key frames
      retval->setKeyFrame(true);
    }
    catch (std::bad_alloc &e)
    {
      VS_REF_RELEASE(retval);
      throw e;
    }
    catch (std::exception& e)
    {
      VS_LOG_DEBUG("error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
IVideoPicture::PictType com::xuggle::xuggler::VideoPicture::getPictureType () [virtual]
Get the picture type.
This will be set on decoding to tell you what type of packet this was decoded from, and when encoding is a request to the encoder for how to encode the picture.
The request may be ignored by your codec.
Returns:
the picture type.
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 426 of file VideoPicture.cpp.
References com::xuggle::xuggler::IVideoPicture::DEFAULT_TYPE.
  {
    IVideoPicture::PictType retval = IVideoPicture::DEFAULT_TYPE;
    if (mFrame)
      retval = (PictType) mFrame->pict_type;
    return retval;
  }
void com::xuggle::xuggler::VideoPicture::setPictureType (IVideoPicture::PictType type) [virtual]
Set the picture type.
Parameters:
type The type.
See also:
getPictureType()
Implements com::xuggle::xuggler::IVideoPicture.
Definition at line 435 of file VideoPicture.cpp.
  {
    if (mFrame)
      mFrame->pict_type = (enum AVPictureType) type;
  }
VideoPicture * com::xuggle::xuggler::VideoPicture::make (com::xuggle::ferry::IBuffer * buffer, IPixelFormat::Type format, int width, int height) [static]
Get a new picture object, by wrapping an existing com.xuggle.ferry.IBuffer.
Use this method if you have existing video data that you want to have us wrap and pass to FFmpeg. Note that if decoding into this video picture and the decoded data actually takes more space than is in this buffer, this object will release the reference to the passed in buffer and allocate a new buffer instead so the decode can continue.
Due to some decoders assembly optimizations, you should ensure the IBuffer you pass in has at least 8 more bytes than would typically be required based on the format, width and height.
Parameters:
buffer The com.xuggle.ferry.IBuffer to wrap.
format The pixel format (for example, YUV420P).
width The width of the picture, in pixels.
height The height of the picture, in pixels.
Returns:
A new object, or null if we can't allocate one.
Reimplemented from com::xuggle::xuggler::IVideoPicture.
Definition at line 81 of file VideoPicture.cpp.
References com::xuggle::ferry::IBuffer::getBufferSize(), com::xuggle::ferry::IBuffer::getBytes(), getSize(), make(), mBuffer, mFrame, com::xuggle::ferry::RefPointer< T >::reset(), VS_LOG_DEBUG, and VS_REF_RELEASE.
  {
    if (!buffer)
      return 0;
    VideoPicture *retval = 0;
    try {
      retval = make(format, width,height);
      if (!retval)
        throw std::bad_alloc();
      int32_t size = retval->getSize();
      if (size > 0 && size > buffer->getBufferSize())
        throw std::runtime_error("input buffer is not large enough for given picture");
      retval->mBuffer.reset(buffer, true);
      unsigned char* bytes = (unsigned char*)buffer->getBytes(0, size);
      if (!bytes)
        throw std::runtime_error("could not access raw memory in buffer");
      (void) avpicture_fill((AVPicture*)retval->mFrame,
          bytes,
          (enum PixelFormat) format,
          width,
          height);
    }
    catch (std::bad_alloc &e)
    {
      VS_REF_RELEASE(retval);
      throw e;
    }
    catch (std::exception& e)
    {
      VS_LOG_DEBUG("error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/VideoPicture.h
csrc/com/xuggle/xuggler/VideoPicture.cpp