Xuggle: com::xuggle::xuggler::VideoResampler Class Reference
com::xuggle::xuggler::VideoResampler Class Reference
#include <VideoResampler.h>
Detailed Description
Definition at line 36 of file VideoResampler.h.
Public Member Functions
virtual int32_t getInputWidth ()
Get the width in pixels we expect on the input frame to the resampler.
virtual int32_t getInputHeight ()
Get the height in pixels we expect on the input frame to the resampler.
virtual IPixelFormat::Type getInputPixelFormat ()
Get the input pixel format.
virtual int32_t getOutputWidth ()
Get the output width, in pixels.
virtual int32_t getOutputHeight ()
Get the output height, in pixels.
virtual IPixelFormat::Type getOutputPixelFormat ()
Get the output pixel format.
virtual int32_t resample (IVideoPicture *pOutFrame, IVideoPicture *pInFrame)
Resample in to out based on the resampler parameters.
virtual int32_t getNumProperties ()
Returns the total number of settable properties on this object.
virtual IProperty * getPropertyMetaData (int32_t propertyNo)
Returns the name of the numbered property.
virtual IProperty * getPropertyMetaData (const char *name)
Returns the name of the numbered property.
virtual int32_t setProperty (const char *name, const char *value)
Sets a property on this Object.
virtual int32_t setProperty (const char *name, double value)
Looks up the property 'name' and sets the value of the property to 'value'.
virtual int32_t setProperty (const char *name, int64_t value)
Looks up the property 'name' and sets the value of the property to 'value'.
virtual int32_t setProperty (const char *name, bool value)
Looks up the property 'name' and sets the value of the property to 'value'.
virtual int32_t setProperty (const char *name, IRational *value)
Looks up the property 'name' and sets the value of the property to 'value'.
virtual char * getPropertyAsString (const char *name)
Gets a property on this Object.
virtual double getPropertyAsDouble (const char *name)
Gets the value of this property, and returns as a double;.
virtual int64_t getPropertyAsLong (const char *name)
Gets the value of this property, and returns as an long;.
virtual IRational * getPropertyAsRational (const char *name)
Gets the value of this property, and returns as an IRational;.
virtual bool getPropertyAsBoolean (const char *name)
Gets the value of this property, and returns as a boolean.
Static Public Member Functions
static VideoResampler * make (int32_t outputWidth, int32_t outputHeight, IPixelFormat::Type outputFmt, int32_t inputWidth, int32_t inputHeight, IPixelFormat::Type inputFmt)
Get a new video resampler.
Protected Member Functions
VideoResampler ()
virtual ~VideoResampler ()
Constructor & Destructor Documentation
com::xuggle::xuggler::VideoResampler::VideoResampler () [protected]
Definition at line 43 of file VideoResampler.cpp.
References com::xuggle::xuggler::IPixelFormat::NONE.
  {
    mIHeight = 0;
    mIWidth = 0;
    mOHeight = 0;
    mOWidth = 0;
    mIPixelFmt = IPixelFormat::NONE;
    mOPixelFmt = IPixelFormat::NONE;
    mContext = 0;
  }
com::xuggle::xuggler::VideoResampler::~VideoResampler () [protected, virtual]
Definition at line 54 of file VideoResampler.cpp.
  {
    if (mContext)
      sws_freeContext(mContext);
    mContext = 0;
  }
Member Function Documentation
int32_t com::xuggle::xuggler::VideoResampler::getInputWidth () [virtual]
Get the width in pixels we expect on the input frame to the resampler.
Returns:
The width we expect on the input frame to the resampler.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 68 of file VideoResampler.cpp.
  {
    return mIWidth;
  }
int32_t com::xuggle::xuggler::VideoResampler::getInputHeight () [virtual]
Get the height in pixels we expect on the input frame to the resampler.
Returns:
The height we expect on the input frame to the resampler.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 62 of file VideoResampler.cpp.
  {
    return mIHeight;
  }
IPixelFormat::Type com::xuggle::xuggler::VideoResampler::getInputPixelFormat () [virtual]
Get the input pixel format.
Returns:
The pixel format we expect on the input frame to the resampler.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 86 of file VideoResampler.cpp.
  {
    return mIPixelFmt;
  }
int32_t com::xuggle::xuggler::VideoResampler::getOutputWidth () [virtual]
Get the output width, in pixels.
Returns:
The width we will resample the output frame to
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 80 of file VideoResampler.cpp.
  {
    return mOWidth;
  }
int32_t com::xuggle::xuggler::VideoResampler::getOutputHeight () [virtual]
Get the output height, in pixels.
Returns:
The height we will resample the output frame to
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 74 of file VideoResampler.cpp.
  {
    return mOHeight;
  }
IPixelFormat::Type com::xuggle::xuggler::VideoResampler::getOutputPixelFormat () [virtual]
Get the output pixel format.
Returns:
The pixel format we will resample the output frame to
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 92 of file VideoResampler.cpp.
  {
    return mOPixelFmt;
  }
int32_t com::xuggle::xuggler::VideoResampler::resample (IVideoPicture * out, IVideoPicture * in) [virtual]
Resample in to out based on the resampler parameters.
Resamples the in picture based on the parameters set when this resampler was constructed.
Parameters:
out The picture we'll resample to. Check IVideoPicture#isComplete() after the call.
in The picture we'll resample from.
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 98 of file VideoResampler.cpp.
References com::xuggle::xuggler::VideoPicture::getAVFrame(), com::xuggle::xuggler::VideoPicture::getHeight(), com::xuggle::xuggler::VideoPicture::getPixelType(), com::xuggle::xuggler::VideoPicture::getPts(), com::xuggle::xuggler::VideoPicture::getQuality(), com::xuggle::xuggler::VideoPicture::getWidth(), com::xuggle::xuggler::VideoPicture::isComplete(), com::xuggle::xuggler::VideoPicture::setComplete(), com::xuggle::xuggler::VideoPicture::setQuality(), and VS_LOG_DEBUG.
  {
    int32_t retval = -1;
    VideoPicture* outFrame = dynamic_cast<VideoPicture*>(pOutFrame);
    VideoPicture* inFrame  = dynamic_cast<VideoPicture*>(pInFrame);
    try
    {
      if (!outFrame)
        throw std::invalid_argument("invalid output frame");
      if (outFrame->getHeight() != mOHeight)
        throw std::runtime_error("output frame height does not match expected value");
      if (outFrame->getWidth() != mOWidth)
        throw std::runtime_error("output frame width does not match expected value");
      if (outFrame->getPixelType() != mOPixelFmt)
        throw std::runtime_error("output frame pixel format does not match expected value");
      if (!inFrame)
        throw std::invalid_argument("invalid input frame");
      if (inFrame->getHeight() != mIHeight)
        throw std::runtime_error("input frame height does not match expected value");
      if (inFrame->getWidth() != mIWidth)
        throw std::runtime_error("input frame width does not match expected value");
      if (inFrame->getPixelType() != mIPixelFmt)
        throw std::runtime_error("input frame pixel format does not match expected value");
      if (!inFrame->isComplete())
        throw std::runtime_error("incoming frame doesn't have complete data");
      // Allocate our output frame.
      outFrame->setComplete(false, mOPixelFmt, mOWidth, mOHeight,
          inFrame->getPts());
      AVFrame *outAVFrame = outFrame->getAVFrame();
      // Get our input frame; since it's complete() we can pass anything
      // for the argument
      AVFrame *inAVFrame = inFrame->getAVFrame();
      /*
      VS_LOG_DEBUG("%dx%d(%d:%d)=>%dx%d(%d:%d)",
          inFrame->getWidth(), inFrame->getHeight(), inFrame->getPixelType(), inAVFrame->linesize[0],
          outFrame->getWidth(), outFrame->getHeight(), outFrame->getPixelType(), outAVFrame->linesize[0]);
      memset(outAVFrame->data[0], 64*3-1, outAVFrame->linesize[0]);
      */
      // And do the conversion; works around FFmpeg checkin r30306
      const uint8_t* srcFrame[4] = {
          inAVFrame->data[0],
          inAVFrame->data[1],
          inAVFrame->data[2],
          inAVFrame->data[3],
      };
      retval = sws_scale(mContext, srcFrame, inAVFrame->linesize, 0,
          mIHeight, outAVFrame->data, outAVFrame->linesize);
      // and go home happy.
      {
        outFrame->setQuality(inFrame->getQuality());
        outFrame->setComplete(retval >= 0,mOPixelFmt, mOWidth, mOHeight,
            inFrame->getPts());
      }
    }
    catch (std::bad_alloc& e)
    {
      throw e;
    }
    catch (std::exception& e)
    {
      VS_LOG_DEBUG("error: %s", e.what());
      retval = -1;
    }
    return retval;
  }
int32_t com::xuggle::xuggler::VideoResampler::getNumProperties () [virtual]
Returns the total number of settable properties on this object.
Returns:
total number of options (not including constant definitions)
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 296 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::getNumProperties().
  {
    return Property::getNumProperties(mContext);
  }
IProperty * com::xuggle::xuggler::VideoResampler::getPropertyMetaData (int32_t propertyNo) [virtual]
Returns the name of the numbered property.
Parameters:
propertyNo The property number in the options list.
Returns:
an IProperty value for this properties meta-data
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 302 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::getPropertyMetaData().
  {
    return Property::getPropertyMetaData(mContext, propertyNo);
  }
IProperty * com::xuggle::xuggler::VideoResampler::getPropertyMetaData (const char * name) [virtual]
Returns the name of the numbered property.
Parameters:
name The property name.
Returns:
an IProperty value for this properties meta-data
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 308 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::getPropertyMetaData().
  {
    return Property::getPropertyMetaData(mContext, name);
  }
int32_t com::xuggle::xuggler::VideoResampler::setProperty (const char * name, const char * value) [virtual]
Sets a property on this Object.
All AVOptions supported by the underlying AVClass are supported.
Parameters:
name The property name. For example "b" for bit-rate.
value The value of the property.
Returns:
>= 0 if the property was successfully set; <0 on error
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 314 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::setProperty().
  {
    return Property::setProperty(mContext, aName, aValue);
  }
int32_t com::xuggle::xuggler::VideoResampler::setProperty (const char * name, double value) [virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 320 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::setProperty().
  {
    return Property::setProperty(mContext, aName, aValue);
  }
int32_t com::xuggle::xuggler::VideoResampler::setProperty (const char * name, int64_t value) [virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 326 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::setProperty().
  {
    return Property::setProperty(mContext, aName, aValue);
  }
int32_t com::xuggle::xuggler::VideoResampler::setProperty (const char * name, bool value) [virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 332 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::setProperty().
  {
    return Property::setProperty(mContext, aName, aValue);
  }
int32_t com::xuggle::xuggler::VideoResampler::setProperty (const char * name, IRational * value) [virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 339 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::setProperty().
  {
    return Property::setProperty(mContext, aName, aValue);
  }
char * com::xuggle::xuggler::VideoResampler::getPropertyAsString (const char * name) [virtual]
Gets a property on this Object.
Note for C++ callers; you must free the returned array with delete[] in order to avoid a memory leak. Other language folks need not worry.
Parameters:
name property name
Returns:
an string copy of the option value, or null if the option doesn't exist.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 346 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::getPropertyAsString().
  {
    return Property::getPropertyAsString(mContext, aName);
  }
double com::xuggle::xuggler::VideoResampler::getPropertyAsDouble (const char * name) [virtual]
Gets the value of this property, and returns as a double;.
Parameters:
name name of option
Returns:
double value of property, or 0 on error.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 352 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::getPropertyAsDouble().
  {
    return Property::getPropertyAsDouble(mContext, aName);
  }
int64_t com::xuggle::xuggler::VideoResampler::getPropertyAsLong (const char * name) [virtual]
Gets the value of this property, and returns as an long;.
Parameters:
name name of option
Returns:
long value of property, or 0 on error.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 358 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::getPropertyAsLong().
  {
    return Property::getPropertyAsLong(mContext, aName);
  }
IRational * com::xuggle::xuggler::VideoResampler::getPropertyAsRational (const char * name) [virtual]
Gets the value of this property, and returns as an IRational;.
Parameters:
name name of option
Returns:
long value of property, or 0 on error.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 364 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::getPropertyAsRational().
  {
    return Property::getPropertyAsRational(mContext, aName);
  }
bool com::xuggle::xuggler::VideoResampler::getPropertyAsBoolean (const char * name) [virtual]
Gets the value of this property, and returns as a boolean.
Parameters:
name name of option
Returns:
boolean value of property, or false on error.
Implements com::xuggle::xuggler::IVideoResampler.
Definition at line 370 of file VideoResampler.cpp.
References com::xuggle::xuggler::Property::getPropertyAsBoolean().
  {
    return Property::getPropertyAsBoolean(mContext, aName);
  }
VideoResampler * com::xuggle::xuggler::VideoResampler::make (int32_t outputWidth, int32_t outputHeight, IPixelFormat::Type outputFmt, int32_t inputWidth, int32_t inputHeight, IPixelFormat::Type inputFmt) [static]
Get a new video resampler.
Returns null if isSupported(Feature) returns false.
Parameters:
outputWidth The width in pixels you want to output frame to have.
outputHeight The height in pixels you want to output frame to have.
outputFmt The pixel format of the output frame.
inputWidth The width in pixels the input frame will be in.
inputHeight The height in pixels the input frame will be in.
inputFmt The pixel format of the input frame.
Returns:
a new object, or null if we cannot allocate one.
Reimplemented from com::xuggle::xuggler::IVideoResampler.
Definition at line 225 of file VideoResampler.cpp.
References mContext, mIHeight, mIPixelFmt, mIWidth, mOHeight, mOPixelFmt, mOWidth, com::xuggle::xuggler::IPixelFormat::NONE, VS_LOG_DEBUG, and VS_REF_RELEASE.
Referenced by com::xuggle::xuggler::IVideoResampler::make().
  {
    VideoResampler* retval = 0;
    try
    {
      if (outputWidth <= 0)
        throw std::invalid_argument("invalid output width");
      if (outputHeight <= 0)
        throw std::invalid_argument("invalid output height");
      if (outputFmt == IPixelFormat::NONE)
        throw std::invalid_argument("cannot set output pixel format to none");
      if (inputWidth <= 0)
        throw std::invalid_argument("invalid input width");
      if (inputHeight <= 0)
        throw std::invalid_argument("invalid input height");
      if (inputFmt == IPixelFormat::NONE)
        throw std::invalid_argument("cannot set input pixel format to none");
      retval = VideoResampler::make();
      if (retval)
      {
        retval->mOHeight = outputHeight;
        retval->mOWidth = outputWidth;
        retval->mOPixelFmt = outputFmt;
        retval->mIHeight = inputHeight;
        retval->mIWidth = inputWidth;
        retval->mIPixelFmt = inputFmt;
        int32_t flags = 0;
        if (inputWidth < outputWidth)
          // We're upscaling
          flags = SWS_BICUBIC;
        else
          // We're downscaling
          flags = SWS_AREA;
        retval->mContext = xuggleSws_getContext(
            retval->mIWidth, // src width
            retval->mIHeight, // src height
            (PixelFormat)retval->mIPixelFmt, // src pixel type
            retval->mOWidth, // dst width
            retval->mOHeight, // dst height
            (PixelFormat)retval->mOPixelFmt, // dst pixel type
            flags, // Flags
            0, // Source Filter
            0, // Destination Filter
            0 // An array of parameters for filters
            );
        if (!retval->mContext)
          throw std::runtime_error("could not allocate a image rescaler");
      }
    }
    catch (std::bad_alloc& e)
    {
      VS_REF_RELEASE(retval);
    }
    catch (std::exception& e)
    {
      VS_LOG_DEBUG("error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/VideoResampler.h
csrc/com/xuggle/xuggler/VideoResampler.cpp