Xuggle: com::xuggle::xuggler::Global Class Reference
com::xuggle::xuggler::Global Class Reference
#include <Global.h>
Detailed Description
A collection of static functions that refer to the entire package (like version getters).
Definition at line 43 of file Global.h.
Static Public Member Functions
static int64_t getVersion ()
Returns a 64 bit version number for this library.
static int32_t getVersionMajor ()
Get the major version number of this library.
static int32_t getVersionMinor ()
Get the minor version number of this library.
static int32_t getVersionRevision ()
Get the revision number of this library.
static const char * getVersionStr ()
Get a string representation of the version of this library.
static int getAVFormatVersion ()
Get the version of the FFMPEG libavformat library we are compiled against.
static const char * getAVFormatVersionStr ()
Get the version of the FFMPEG libavformat library we are compiled against.
static int getAVCodecVersion ()
Get the version of the FFMPEG libavcodec library we are compiled against.
static const char * getAVCodecVersionStr ()
Get the version of the FFMPEG libavcodec library we are compiled against.
static void lock ()
Performs a global-level lock of the XUGGLER library.
static void unlock ()
Unlock the global lock.
static void init ()
Internal Only.
static void setFFmpegLoggingLevel (int32_t level)
Internal Only.
Static Public Attributes
static const int64_t NO_PTS = 0x8000000000000000LL
A value that means no time stamp is set for a given object.
static const int64_t DEFAULT_PTS_PER_SECOND = 1000000
The default time units per second that we use for decoded IAudioSamples and IVideoPicture objects.
Member Function Documentation
int64_t com::xuggle::xuggler::Global::getVersion () [static]
Returns a 64 bit version number for this library.
Returns:
a 64-bit integer version number for this library. The top 16 bits is the getVersionMajor() value. The next 16-bits are the getVersionMinor() value, and the last 32-bits are the getVersionRevision() value.
Definition at line 213 of file Global.cpp.
References getVersionMajor(), getVersionMinor(), and getVersionRevision().
  {
    return ((int64_t)getVersionMajor())<<48 | ((int64_t)getVersionMinor())<<32 | (int64_t)getVersionRevision();
  }
int32_t com::xuggle::xuggler::Global::getVersionMajor () [static]
Get the major version number of this library.
Returns:
the major version number of this library or 0 if unknown.
Definition at line 218 of file Global.cpp.
References init().
Referenced by getVersion().
  {
    Global::init();
    return VS_LIB_MAJOR_VERSION;
  }
int32_t com::xuggle::xuggler::Global::getVersionMinor () [static]
Get the minor version number of this library.
Returns:
the minor version number of this library or 0 if unknown.
Definition at line 224 of file Global.cpp.
References init().
Referenced by getVersion().
  {
    Global::init();
    return VS_LIB_MINOR_VERSION;
  }
int32_t com::xuggle::xuggler::Global::getVersionRevision () [static]
Get the revision number of this library.
Returns:
the revision number of this library, or 0 if unknown.
Definition at line 230 of file Global.cpp.
References init().
Referenced by getVersion().
  {
    Global::init();
    return VS_REVISION;
  }
const char * com::xuggle::xuggler::Global::getVersionStr () [static]
Get a string representation of the version of this library.
Returns:
the version of this library in string form.
Definition at line 237 of file Global.cpp.
References init(), and VS_STRINGIFY.
  {
    Global::init();
    return PACKAGE_VERSION "."  VS_STRINGIFY(VS_REVISION);
  }
int32_t com::xuggle::xuggler::Global::getAVFormatVersion () [static]
Get the version of the FFMPEG libavformat library we are compiled against.
Returns:
the version.
Definition at line 243 of file Global.cpp.
References init().
  {
    Global::init();
    return LIBAVFORMAT_VERSION_INT;
  }
const char * com::xuggle::xuggler::Global::getAVFormatVersionStr () [static]
Get the version of the FFMPEG libavformat library we are compiled against.
Returns:
the version.
Definition at line 249 of file Global.cpp.
References init().
  {
    Global::init();
    return AV_STRINGIFY(LIBAVFORMAT_VERSION);
  }
int com::xuggle::xuggler::Global::getAVCodecVersion () [static]
Get the version of the FFMPEG libavcodec library we are compiled against.
Returns:
the version.
Definition at line 255 of file Global.cpp.
References init().
  {
    Global::init();
    return LIBAVCODEC_VERSION_INT;
  }
const char * com::xuggle::xuggler::Global::getAVCodecVersionStr () [static]
Get the version of the FFMPEG libavcodec library we are compiled against.
Returns:
the version.
Definition at line 261 of file Global.cpp.
References init().
  {
    Global::init();
    return AV_STRINGIFY(LIBAVCODEC_VERSION);
  }
void com::xuggle::xuggler::Global::lock () [static]
Performs a global-level lock of the XUGGLER library.
While this lock() is held, every other method that calls lock() in the same DLL/SO will block.
Use this sparingly. FFMPEG's libraries have few real global objects, but when they do exist, you must lock.
Lastly, if you lock, make damn sure you call unlock()
Definition at line 197 of file Global.cpp.
References init(), com::xuggle::ferry::Mutex::lock(), and mLock.
Referenced by com::xuggle::xuggler::Codec::findDecodingCodecByIntID(), com::xuggle::xuggler::Codec::findDecodingCodecByName(), com::xuggle::xuggler::Codec::findEncodingCodecByIntID(), and com::xuggle::xuggler::Codec::findEncodingCodecByName().
  {
    Global::init();
    if (sGlobal && sGlobal->mLock)
      sGlobal->mLock->lock();
  }
void com::xuggle::xuggler::Global::unlock () [static]
Unlock the global lock.
See also:
lock()
Definition at line 205 of file Global.cpp.
References init(), mLock, and com::xuggle::ferry::Mutex::unlock().
Referenced by com::xuggle::xuggler::Codec::findDecodingCodecByIntID(), com::xuggle::xuggler::Codec::findDecodingCodecByName(), com::xuggle::xuggler::Codec::findEncodingCodecByIntID(), and com::xuggle::xuggler::Codec::findEncodingCodecByName().
  {
    Global::init();
    if (sGlobal && sGlobal->mLock)
      sGlobal->mLock->unlock();
  }
void com::xuggle::xuggler::Global::init () [static]
Internal Only.
Do not call. Methods using the C++ interface that will not necessarily create other Global object should call this. In general, unless you're extending xuggler directly yourself, ordinary users of this library don't need to call this.
It's main purpose is to ensure any FFmpeg required environment initialization functions are called, and any Xuggler required environmental contexts are set up.
Definition at line 156 of file Global.cpp.
Referenced by com::xuggle::xuggler::IAudioSamples::defaultPtsToSamples(), com::xuggle::xuggler::ICodec::findDecodingCodec(), com::xuggle::xuggler::ICodec::findDecodingCodecByIntID(), com::xuggle::xuggler::ICodec::findDecodingCodecByName(), com::xuggle::xuggler::ICodec::findEncodingCodec(), com::xuggle::xuggler::ICodec::findEncodingCodecByIntID(), com::xuggle::xuggler::ICodec::findEncodingCodecByName(), getAVCodecVersion(), getAVCodecVersionStr(), getAVFormatVersion(), getAVFormatVersionStr(), com::xuggle::xuggler::ICodec::getInstalledCodec(), com::xuggle::xuggler::IContainerFormat::getInstalledInputFormat(), com::xuggle::xuggler::IContainerFormat::getInstalledOutputFormat(), com::xuggle::xuggler::ICodec::getNumInstalledCodecs(), com::xuggle::xuggler::IContainerFormat::getNumInstalledInputFormats(), com::xuggle::xuggler::IContainerFormat::getNumInstalledOutputFormats(), getVersionMajor(), getVersionMinor(), getVersionRevision(), getVersionStr(), com::xuggle::xuggler::ICodec::guessEncodingCodec(), lock(), com::xuggle::xuggler::IVideoResampler::make(), com::xuggle::xuggler::IVideoPicture::make(), com::xuggle::xuggler::IStreamCoder::make(), com::xuggle::xuggler::IRational::make(), com::xuggle::xuggler::IPacket::make(), com::xuggle::xuggler::IMediaDataWrapper::make(), com::xuggle::xuggler::IContainerFormat::make(), com::xuggle::xuggler::IContainer::make(), com::xuggle::xuggler::IAudioSamples::make(), com::xuggle::xuggler::IAudioSamples::samplesToDefaultPts(), setFFmpegLoggingLevel(), and unlock().
  {
    if (!sGlobal)
    {
      av_lockmgr_register(xuggler_lockmgr_cb);
      av_log_set_callback(xuggler_log_callback);
      av_log_set_level(AV_LOG_ERROR); // Only log errors by default
      av_register_all();
      // and set up the device library for webcam support
      avdevice_register_all();
      avio_set_interrupt_cb(xuggler_interrupt_cb);
      // turn down logging
      sGlobal = new Global();
    }
  }
void com::xuggle::xuggler::Global::setFFmpegLoggingLevel (int32_t level) [static]
Internal Only.
This method can be used to turn up or down FFmpeg's logging level.
Parameters:
level An integer value for level. Lower numbers mean less logging. A negative number tells FFmpeg to shut up.
Definition at line 268 of file Global.cpp.
References init().
  {
    Global::init();
    if (level < AV_LOG_PANIC)
      av_log_set_level(AV_LOG_QUIET);
    else if (level < AV_LOG_FATAL)
      av_log_set_level(AV_LOG_PANIC);
    else if (level < AV_LOG_ERROR)
      av_log_set_level(AV_LOG_FATAL);
    else if (level < AV_LOG_WARNING)
      av_log_set_level(AV_LOG_ERROR);
    else if (level < AV_LOG_INFO)
      av_log_set_level(AV_LOG_WARNING);
    else if (level < AV_LOG_VERBOSE)
      av_log_set_level(AV_LOG_INFO);
    else if (level < AV_LOG_DEBUG)
      av_log_set_level(AV_LOG_VERBOSE);
    else
      av_log_set_level(AV_LOG_DEBUG);
//    fprintf(stderr, "FFmpeg logging level = %d\n", av_log_get_level());
  }
Member Data Documentation
const int64_t com::xuggle::xuggler::Global::NO_PTS = 0x8000000000000000LL [static]
A value that means no time stamp is set for a given object.
if the IMediaData#getTimeStamp() method of an object returns this value it means the time stamp wasn't set.
Definition at line 51 of file Global.h.
Referenced by com::xuggle::xuggler::AudioResampler::AudioResampler(), com::xuggle::xuggler::AudioSamples::AudioSamples(), com::xuggle::xuggler::StreamCoder::decodeAudio(), com::xuggle::xuggler::StreamCoder::decodeVideo(), com::xuggle::xuggler::IAudioSamples::defaultPtsToSamples(), com::xuggle::xuggler::StreamCoder::encodeAudio(), com::xuggle::xuggler::StreamCoder::encodeVideo(), com::xuggle::xuggler::Stream::getCurrentDts(), com::xuggle::xuggler::Stream::getDuration(), com::xuggle::xuggler::Container::getDuration(), com::xuggle::xuggler::AudioSamples::getNextPts(), com::xuggle::xuggler::Stream::getStartTime(), com::xuggle::xuggler::Container::getStartTime(), com::xuggle::xuggler::MediaDataWrapper::MediaDataWrapper(), com::xuggle::xuggler::StreamCoder::open(), com::xuggle::xuggler::AudioResampler::resample(), com::xuggle::xuggler::IAudioSamples::samplesToDefaultPts(), com::xuggle::xuggler::Stream::stampOutputPacket(), com::xuggle::xuggler::Stream::Stream(), com::xuggle::xuggler::StreamCoder::StreamCoder(), com::xuggle::xuggler::MediaDataWrapper::wrap(), and com::xuggle::xuggler::AudioSamples::~AudioSamples().
const int64_t com::xuggle::xuggler::Global::DEFAULT_PTS_PER_SECOND = 1000000 [static]
The default time units per second that we use for decoded IAudioSamples and IVideoPicture objects.
This means that 1 tick of a time stamp is 1 Microsecond.
Definition at line 58 of file Global.h.
Referenced by com::xuggle::xuggler::IAudioSamples::defaultPtsToSamples(), and com::xuggle::xuggler::IAudioSamples::samplesToDefaultPts().
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/Global.h
csrc/com/xuggle/xuggler/Global.cpp