Xuggle: com::xuggle::xuggler::IStreamCoder Class Reference
com::xuggle::xuggler::IStreamCoder Class Reference
#include <IStreamCoder.h>
Detailed Description
The work horse of the Xuggler: Takes IPacket data from an IContainer (representing an IStream) and an ICodec and allows you to decode or encode that data.
Definition at line 43 of file IStreamCoder.h.
Public Types
enum Direction { ENCODING, DECODING }
The Direction in which this StreamCoder will work.
enum Flags {
FLAG_QSCALE = 0x0002, FLAG_4MV = 0x0004, FLAG_QPEL = 0x0010, FLAG_GMC = 0x0020,
FLAG_MV0 = 0x0040, FLAG_PART = 0x0080, FLAG_INPUT_PRESERVED = 0x0100, FLAG_PASS1 = 0x0200,
FLAG_PASS2 = 0x0400, FLAG_EXTERN_HUFF = 0x1000, FLAG_GRAY = 0x2000, FLAG_EMU_EDGE = 0x4000,
FLAG_PSNR = 0x8000, FLAG_TRUNCATED = 0x00010000, FLAG_NORMALIZE_AQP = 0x00020000, FLAG_INTERLACED_DCT = 0x00040000,
FLAG_LOW_DELAY = 0x00080000, FLAG_ALT_SCAN = 0x00100000, FLAG_TRELLIS_QUANT = 0x00200000, FLAG_GLOBAL_HEADER = 0x00400000,
FLAG_BITEXACT = 0x00800000, FLAG_AC_PRED = 0x01000000, FLAG_H263P_UMV = 0x02000000, FLAG_CBP_RD = 0x04000000,
FLAG_QP_RD = 0x08000000, FLAG_H263P_AIV = 0x00000008, FLAG_OBMC = 0x00000001, FLAG_LOOP_FILTER = 0x00000800,
FLAG_H263P_SLICE_STRUCT = 0x10000000, FLAG_INTERLACED_ME = 0x20000000, FLAG_SVCD_SCAN_OFFSET = 0x40000000, FLAG_CLOSED_GOP = 0x80000000,
FLAG2_FAST = 0x00000001, FLAG2_STRICT_GOP = 0x00000002, FLAG2_NO_OUTPUT = 0x00000004, FLAG2_LOCAL_HEADER = 0x00000008,
FLAG2_BPYRAMID = 0x00000010, FLAG2_WPRED = 0x00000020, FLAG2_MIXED_REFS = 0x00000040, FLAG2_8X8DCT = 0x00000080,
FLAG2_FASTPSKIP = 0x00000100, FLAG2_AUD = 0x00000200, FLAG2_BRDO = 0x00000400, FLAG2_INTRA_VLC = 0x00000800,
FLAG2_MEMC_ONLY = 0x00001000, FLAG2_DROP_FRAME_TIMECODE = 0x00002000, FLAG2_SKIP_RD = 0x00004000, FLAG2_CHUNKS = 0x00008000,
FLAG2_NON_LINEAR_QUANT = 0x00010000, FLAG2_BIT_RESERVOIR = 0x00020000, FLAG2_MBTREE = 0x00040000, FLAG2_PSY = 0x00080000,
FLAG2_SSIM = 0x00100000, FLAG2_INTRA_REFRESH = 0x00200000
}
XUGGLER Flags that can be passed to the setFlag(Flags, bool) method.
typedef enum
com::xuggle::xuggler::IStreamCoder::Direction Direction
Public Member Functions
virtual Direction getDirection ()=0
Get the direction.
virtual IStream * getStream ()=0
The associated Stream we're working on.
virtual ICodec * getCodec ()=0
The Codec this StreamCoder will use.
virtual ICodec::Type getCodecType ()=0
A short hand for getCodec().getType().
virtual ICodec::ID getCodecID ()=0
A short hand for getCodec().getID().
virtual void setCodec (ICodec *codec)=0
Set the Codec to the passed in Codec, discarding the old Codec if set.
virtual void setCodec (ICodec::ID id)=0
Look up a Codec based on the passed in ID, and then set it.
virtual int32_t getBitRate ()=0
The bit rate.
virtual void setBitRate (int32_t rate)=0
When ENCODING, sets the bit rate to use.
virtual int32_t getBitRateTolerance ()=0
The bit rate tolerance.
virtual void setBitRateTolerance (int32_t tolerance)=0
When ENCODING set the bit rate tolerance.
virtual int32_t getHeight ()=0
The height, in pixels.
virtual void setHeight (int32_t height)=0
Set the height, in pixels.
virtual int32_t getWidth ()=0
The width, in pixels.
virtual void setWidth (int32_t width)=0
Set the width, in pixels.
virtual IRational * getTimeBase ()=0
Get the time base this stream will ENCODE in, or the time base we detect while DECODING.
virtual void setTimeBase (IRational *newTimeBase)=0
Set the time base we'll use to ENCODE with.
virtual IRational * getFrameRate ()=0
Get the frame-rate the attached stream claims to be using when DECODING, or the frame-rate we'll claim we're using when ENCODING.
virtual void setFrameRate (IRational *newFrameRate)=0
Set the frame rate we'll set in the headers of this stream while ENCODING.
virtual int32_t getNumPicturesInGroupOfPictures ()=0
The the number of pictures in this Group of Pictures (GOP).
virtual void setNumPicturesInGroupOfPictures (int32_t gops)=0
Set the GOPS on this stream.
virtual IPixelFormat::Type getPixelType ()=0
For Video streams, get the Pixel Format in use by the stream.
virtual void setPixelType (IPixelFormat::Type pixelFmt)=0
Set the pixel format to ENCODE with.
virtual int32_t getSampleRate ()=0
Get the sample rate we use for this stream.
virtual void setSampleRate (int32_t sampleRate)=0
Set the sample rate to use when ENCODING.
virtual IAudioSamples::Format getSampleFormat ()=0
Get the audio sample format.
virtual void setSampleFormat (IAudioSamples::Format aFormat)=0
Set the sample format when ENCODING.
virtual int32_t getChannels ()=0
Get the number of channels in this audio stream.
virtual void setChannels (int32_t channels)=0
Set the number of channels to use when ENCODING.
virtual int32_t getAudioFrameSize ()=0
For this stream, get the number of audio samples that are represented in a packet of information.
virtual int32_t getGlobalQuality ()=0
Get the Global Quality setting this codec uses for video if a VideoPicture doesn't have a quality set.
virtual void setGlobalQuality (int32_t newQuality)=0
Set the Global Quality to a new value.
virtual int32_t getFlags ()=0
Get the flags associated with this codec.
virtual void setFlags (int32_t newFlags)=0
Set the FFMPEG flags to use with this codec.
virtual bool getFlag (Flags flag)=0
Get the setting for the specified flag.
virtual void setFlag (Flags flag, bool value)=0
Set the flag.
virtual int64_t getNextPredictedPts ()=0
For this stream, get the next Pts that we expect to decode.
virtual int32_t open ()=0
Open the Codec associated with this StreamCoder.
virtual int32_t close ()=0
Close a Codec that was opened on this StreamCoder.
virtual int32_t decodeAudio (IAudioSamples *pOutSamples, IPacket *packet, int32_t byteOffset)=0
Decode this packet into pOutSamples.
virtual int32_t decodeVideo (IVideoPicture *pOutFrame, IPacket *packet, int32_t byteOffset)=0
Decode this packet into pOutFrame.
virtual int32_t encodeVideo (IPacket *pOutPacket, IVideoPicture *pFrame, int32_t suggestedBufferSize)=0
Encode the given frame using this StreamCoder.
virtual int32_t encodeAudio (IPacket *pOutPacket, IAudioSamples *pSamples, uint32_t sampleToStartFrom)=0
Encode the given samples using this StreamCoder.
virtual int32_t getCodecTag ()=0
Returns the 4-byte FOURCC tag (Least Significant Byte first).
virtual void setCodecTag (int32_t fourcc)=0
Set the 4-byte FOURCC tag for this coder.
virtual int32_t getNumProperties ()=0
Returns the total number of settable properties on this object.
virtual IProperty * getPropertyMetaData (int32_t propertyNo)=0
Returns the name of the numbered property.
virtual IProperty * getPropertyMetaData (const char *name)=0
Returns the name of the numbered property.
virtual int32_t setProperty (const char *name, const char *value)=0
Sets a property on this Object.
virtual int32_t setProperty (const char *name, double value)=0
Looks up the property 'name' and sets the value of the property to 'value'.
virtual int32_t setProperty (const char *name, int64_t value)=0
Looks up the property 'name' and sets the value of the property to 'value'.
virtual int32_t setProperty (const char *name, bool value)=0
Looks up the property 'name' and sets the value of the property to 'value'.
virtual int32_t setProperty (const char *name, IRational *value)=0
Looks up the property 'name' and sets the value of the property to 'value'.
virtual char * getPropertyAsString (const char *name)=0
Gets a property on this Object.
virtual double getPropertyAsDouble (const char *name)=0
Gets the value of this property, and returns as a double;.
virtual int64_t getPropertyAsLong (const char *name)=0
Gets the value of this property, and returns as an long;.
virtual IRational * getPropertyAsRational (const char *name)=0
Gets the value of this property, and returns as an IRational;.
virtual bool getPropertyAsBoolean (const char *name)=0
Gets the value of this property, and returns as a boolean.
virtual bool isOpen ()=0
Returns true if this IStreamCoder is currently open.
virtual int32_t getDefaultAudioFrameSize ()=0
Get the default audio frame size (in samples).
virtual void setDefaultAudioFrameSize (int32_t aNewSize)=0
Set the default audio frame size.
virtual int64_t getNumDroppedFrames ()=0
Get the number of frames this StreamCoder had to drop to encode at the specified getTimeBase().
virtual void setAutomaticallyStampPacketsForStream (bool value)=0
Should the IStreamCoder automatically adjust time stamps on output packets for the IStream it is ultimately destined for.
virtual bool getAutomaticallyStampPacketsForStream ()=0
Does this IStreamCoder automatically adjust time stamps on output packets for the IStream it is ultimately destined for.
virtual void setCodecID (ICodec::ID id)=0
Look up a Codec based on the passed in ID, and then set it.
virtual int32_t setExtraData (com::xuggle::ferry::IBuffer *src, int32_t offset, int32_t length, bool allocNew)=0
Copies data from the given buffer into the extra-data area maintained by encoders.
virtual int32_t getExtraData (com::xuggle::ferry::IBuffer *dest, int32_t offset, int32_t maxBytesToCopy)=0
Copies the current content of the extra-data buffer maintained by this codec (e.g.
virtual int32_t getExtraDataSize ()=0
Gets the current number of bytes of data maintained in the coder extra-data area.
Static Public Member Functions
static IStreamCoder * make (Direction direction)
Create a standalone StreamCoder that can decode data without regard to which IStream or IContainer it came from.
static IStreamCoder * make (Direction direction, IStreamCoder *copyCoder)
Creates a new IStreamCoder object by copying all the settings in copyCoder.
Protected Member Functions
IStreamCoder ()
virtual ~IStreamCoder ()
Member Typedef Documentation
typedef enum com::xuggle::xuggler::IStreamCoder::Direction com::xuggle::xuggler::IStreamCoder::Direction
Member Enumeration Documentation
enum com::xuggle::xuggler::IStreamCoder::Direction
The Direction in which this StreamCoder will work.
Enumerator:
ENCODING
DECODING
Definition at line 50 of file IStreamCoder.h.
    {
      ENCODING,
      DECODING
    } Direction;
enum com::xuggle::xuggler::IStreamCoder::Flags
XUGGLER Flags that can be passed to the setFlag(Flags, bool) method.
Enumerator:
FLAG_QSCALE
FLAG_4MV
FLAG_QPEL
FLAG_GMC
FLAG_MV0
FLAG_PART
FLAG_INPUT_PRESERVED
FLAG_PASS1
FLAG_PASS2
FLAG_EXTERN_HUFF
FLAG_GRAY
FLAG_EMU_EDGE
FLAG_PSNR
FLAG_TRUNCATED
FLAG_NORMALIZE_AQP
FLAG_INTERLACED_DCT
FLAG_LOW_DELAY
FLAG_ALT_SCAN
FLAG_TRELLIS_QUANT
FLAG_GLOBAL_HEADER
FLAG_BITEXACT
FLAG_AC_PRED
FLAG_H263P_UMV
FLAG_CBP_RD
FLAG_QP_RD
FLAG_H263P_AIV
FLAG_OBMC
FLAG_LOOP_FILTER
FLAG_H263P_SLICE_STRUCT
FLAG_INTERLACED_ME
FLAG_SVCD_SCAN_OFFSET
FLAG_CLOSED_GOP
FLAG2_FAST
FLAG2_STRICT_GOP
FLAG2_NO_OUTPUT
FLAG2_LOCAL_HEADER
FLAG2_BPYRAMID
FLAG2_WPRED
FLAG2_MIXED_REFS
FLAG2_8X8DCT
FLAG2_FASTPSKIP
FLAG2_AUD
FLAG2_BRDO
FLAG2_INTRA_VLC
FLAG2_MEMC_ONLY
FLAG2_DROP_FRAME_TIMECODE
FLAG2_SKIP_RD
FLAG2_CHUNKS
FLAG2_NON_LINEAR_QUANT
FLAG2_BIT_RESERVOIR
FLAG2_MBTREE
FLAG2_PSY
FLAG2_SSIM
FLAG2_INTRA_REFRESH
Definition at line 59 of file IStreamCoder.h.
                 {
      FLAG_QSCALE =0x0002,  // Use fixed qscale.
      FLAG_4MV    =0x0004,  // 4 MV per MB allowed / advanced prediction for H.263.
      FLAG_QPEL   =0x0010,  // Use qpel MC.
      FLAG_GMC    =0x0020,  // Use GMC.
      FLAG_MV0    =0x0040,  // Always try a MB with MV=<0,0>.
      FLAG_PART   =0x0080,  // Use data partitioning.
      /*
       * The parent program must guarantee that the input for B-frames containing
       * streams is not written to for at least s->max_b_frames+1 frames, if
       * this is not set the input will be copied.
       */
      FLAG_INPUT_PRESERVED =0x0100,
      FLAG_PASS1           =0x0200,   // Use internal 2pass ratecontrol in first pass mode.
      FLAG_PASS2           =0x0400,   // Use internal 2pass ratecontrol in second pass mode.
      FLAG_EXTERN_HUFF     =0x1000,   // Use external Huffman table (for MJPEG).
      FLAG_GRAY            =0x2000,   // Only decode/encode grayscale.
      FLAG_EMU_EDGE        =0x4000,   // Don't draw edges.
      FLAG_PSNR            =0x8000,   // error[?] variables will be set during encoding.
      FLAG_TRUNCATED       =0x00010000, /* Input bitstream might be truncated at a random
                                                  location instead of only at frame boundaries. */
      FLAG_NORMALIZE_AQP  =0x00020000, // Normalize adaptive quantization.
      FLAG_INTERLACED_DCT =0x00040000, // Use interlaced DCT.
      FLAG_LOW_DELAY      =0x00080000, // Force low delay.
      FLAG_ALT_SCAN       =0x00100000, // Use alternate scan.
      FLAG_TRELLIS_QUANT  =0x00200000, // Use trellis quantization.
      FLAG_GLOBAL_HEADER  =0x00400000, // Place global headers in extradata instead of every keyframe.
      FLAG_BITEXACT       =0x00800000, // Use only bitexact stuff (except (I)DCT).
      /* Fx : Flag for h263+ extra options */
      FLAG_AC_PRED        =0x01000000, // H.263 advanced intra coding / MPEG-4 AC prediction
      FLAG_H263P_UMV      =0x02000000, // unlimited motion vector
      FLAG_CBP_RD         =0x04000000, // Use rate distortion optimization for cbp.
      FLAG_QP_RD          =0x08000000, // Use rate distortion optimization for qp selectioon.
      FLAG_H263P_AIV      =0x00000008, // H.263 alternative inter VLC
      FLAG_OBMC           =0x00000001, // OBMC
      FLAG_LOOP_FILTER    =0x00000800, // loop filter
      FLAG_H263P_SLICE_STRUCT =0x10000000,
      FLAG_INTERLACED_ME  =0x20000000, // interlaced motion estimation
      FLAG_SVCD_SCAN_OFFSET =0x40000000, // Will reserve space for SVCD scan offset user data.
      FLAG_CLOSED_GOP     =0x80000000,
      FLAG2_FAST          =0x00000001, // Allow non spec compliant speedup tricks.
      FLAG2_STRICT_GOP    =0x00000002, // Strictly enforce GOP size.
      FLAG2_NO_OUTPUT     =0x00000004, // Skip bitstream encoding.
      FLAG2_LOCAL_HEADER  =0x00000008, // Place global headers at every keyframe instead of in extradata.
      FLAG2_BPYRAMID      =0x00000010, // H.264 allow B-frames to be used as references.
      FLAG2_WPRED         =0x00000020, // H.264 weighted biprediction for B-frames
      FLAG2_MIXED_REFS    =0x00000040, // H.264 one reference per partition, as opposed to one reference per macroblock
      FLAG2_8X8DCT        =0x00000080, // H.264 high profile 8x8 transform
      FLAG2_FASTPSKIP     =0x00000100, // H.264 fast pskip
      FLAG2_AUD           =0x00000200, // H.264 access unit delimiters
      FLAG2_BRDO          =0x00000400, // B-frame rate-distortion optimization
      FLAG2_INTRA_VLC     =0x00000800, // Use MPEG-2 intra VLC table.
      FLAG2_MEMC_ONLY     =0x00001000, // Only do ME/MC (I frames -> ref, P frame -> ME+MC).
      FLAG2_DROP_FRAME_TIMECODE =0x00002000, // timecode is in drop frame format.
      FLAG2_SKIP_RD       =0x00004000, // RD optimal MB level residual skipping
      FLAG2_CHUNKS        =0x00008000, // Input bitstream might be truncated at a packet boundaries instead of only at frame boundaries.
      FLAG2_NON_LINEAR_QUANT =0x00010000, // Use MPEG-2 nonlinear quantizer.
      FLAG2_BIT_RESERVOIR =0x00020000, // Use a bit reservoir when encoding if possible
      FLAG2_MBTREE =0x00040000, // Use macroblock tree ratecontrol (x264 only)
      FLAG2_PSY =0x00080000, // Use psycho visual optimizations.
      FLAG2_SSIM =0x00100000, // Compute SSIM during encoding, error[] values are undefined.
      FLAG2_INTRA_REFRESH=0x00200000,
    } Flags;
Constructor & Destructor Documentation
com::xuggle::xuggler::IStreamCoder::IStreamCoder () [protected]
Definition at line 26 of file IStreamCoder.cpp.
  {
  }
com::xuggle::xuggler::IStreamCoder::~IStreamCoder () [protected, virtual]
Definition at line 30 of file IStreamCoder.cpp.
  {
  }
Member Function Documentation
virtual Direction com::xuggle::xuggler::IStreamCoder::getDirection () [pure virtual]
Get the direction.
Returns:
The direction this StreamCoder works in.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual IStream* com::xuggle::xuggler::IStreamCoder::getStream () [pure virtual]
The associated Stream we're working on.
Returns:
The stream associated with this object.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual ICodec* com::xuggle::xuggler::IStreamCoder::getCodec () [pure virtual]
The Codec this StreamCoder will use.
Returns:
The Codec used by this StreamCoder, or 0 (null) if none.
Implemented in com::xuggle::xuggler::StreamCoder.
Referenced by com::xuggle::xuggler::StreamCoder::make().
virtual ICodec::Type com::xuggle::xuggler::IStreamCoder::getCodecType () [pure virtual]
A short hand for getCodec().getType().
Note for Native (C++) users: If you actually write code like the above from Native code, you'd leak a Codec() since you didn't call release() on it. This method is a short hand way to avoid you having to worry about releasing in between.
Returns:
The Type of the Codec we'll use.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual ICodec::ID com::xuggle::xuggler::IStreamCoder::getCodecID () [pure virtual]
A short hand for getCodec().getID().
Note for Native (C++) users: If you actually write code like the above from Native code, you'd leak a Codec() since you didn't call release() on it. This method is a short hand way to avoid you having to worry about releasing in between.
Returns:
The ID of the Codec we'll use.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setCodec (ICodec * codec) [pure virtual]
Set the Codec to the passed in Codec, discarding the old Codec if set.
Once you call setCodec, all settings on the IStreamCoder are reset to default values. So you probably want to call this first.
Parameters:
codec Codec to set.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setCodec (ICodec::ID id) [pure virtual]
Look up a Codec based on the passed in ID, and then set it.
To see if you actually set the correct ID, call getCodec() and check for 0 (null).
Once you call setCodec, all settings on the IStreamCoder are reset to default values. So you probably want to call this first.
Parameters:
id ID of codec to set.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getBitRate () [pure virtual]
The bit rate.
Returns:
The bit-rate the stream is, or will be, encoded in.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setBitRate (int32_t rate) [pure virtual]
When ENCODING, sets the bit rate to use.
No-op when DECODING.
See also:
getBitRate()
Parameters:
rate The bit rate to use.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getBitRateTolerance () [pure virtual]
The bit rate tolerance.
Returns:
The bit-rate tolerance
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setBitRateTolerance (int32_t tolerance) [pure virtual]
When ENCODING set the bit rate tolerance.
No-op when DECODING.
Parameters:
tolerance The bit rate tolerance
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getHeight () [pure virtual]
The height, in pixels.
Returns:
The height of the video frames in the attached stream or -1 if an audio stream, or we cannot determine the height.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setHeight (int32_t height) [pure virtual]
Set the height, in pixels.
See also:
getHeight()
Parameters:
height Sets the height of video frames we'll encode. No-op when DECODING.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getWidth () [pure virtual]
The width, in pixels.
Returns:
The width of the video frames in the attached stream or -1 if an audio stream, or we cannot determine the width.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setWidth (int32_t width) [pure virtual]
Set the width, in pixels.
See also:
getWidth()
Parameters:
width Sets the width of video frames we'll encode. No-op when DECODING.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual IRational* com::xuggle::xuggler::IStreamCoder::getTimeBase () [pure virtual]
Get the time base this stream will ENCODE in, or the time base we detect while DECODING.
Caller must call release() on the returned value.
Returns:
The time base this StreamCoder is using.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setTimeBase (IRational * newTimeBase) [pure virtual]
Set the time base we'll use to ENCODE with.
A no-op when DECODING.
As a convenience, we forward this call to the Stream::setTimeBase() method.
See also:
getTimeBase()
Parameters:
newTimeBase The new time base to use.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual IRational* com::xuggle::xuggler::IStreamCoder::getFrameRate () [pure virtual]
Get the frame-rate the attached stream claims to be using when DECODING, or the frame-rate we'll claim we're using when ENCODING.
Returns:
The frame rate.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setFrameRate (IRational * newFrameRate) [pure virtual]
Set the frame rate we'll set in the headers of this stream while ENCODING.
Note that you can set whatever frame-rate you'd like, but the TimeBase and the PTS you set on the encoded audio and video frames can override this.
As a convenience, we forward this call to the Stream::setFrameRate() method.
See also:
getFrameRate()
Parameters:
newFrameRate The new frame rate to use.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getNumPicturesInGroupOfPictures () [pure virtual]
The the number of pictures in this Group of Pictures (GOP).
See the MPEG specs for what a GOP is officially, but this is the minimum number of frames between key-frames (or Intra-Frames in MPEG speak).
Returns:
the GOPS for this stream.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setNumPicturesInGroupOfPictures (int32_t gops) [pure virtual]
Set the GOPS on this stream.
Ignored if DECODING.
See also:
getNumPicturesInGroupOfPictures()
Parameters:
gops The new GOPS for the stream we're encoding.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual IPixelFormat::Type com::xuggle::xuggler::IStreamCoder::getPixelType () [pure virtual]
For Video streams, get the Pixel Format in use by the stream.
Returns:
the Pixel format, or IPixelFormat::NONE if audio.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setPixelType (IPixelFormat::Type pixelFmt) [pure virtual]
Set the pixel format to ENCODE with.
Ignored if audio or DECODING.
Parameters:
pixelFmt Pixel format to use.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getSampleRate () [pure virtual]
Get the sample rate we use for this stream.
Returns:
The sample rate (in Hz) we use for this stream, or -1 if unknown or video.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setSampleRate (int32_t sampleRate) [pure virtual]
Set the sample rate to use when ENCODING.
Ignored if DECODING or a non-audio stream.
Parameters:
sampleRate New sample rate (in Hz) to use.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual IAudioSamples::Format com::xuggle::xuggler::IStreamCoder::getSampleFormat () [pure virtual]
Get the audio sample format.
Returns:
The sample format of samples for encoding/decoding.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setSampleFormat (IAudioSamples::Format aFormat) [pure virtual]
Set the sample format when ENCODING.
Ignored if DECODING or if the coder is already open.
Parameters:
aFormat The sample format.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getChannels () [pure virtual]
Get the number of channels in this audio stream.
Returns:
The sample rate (in Hz) we use for this stream, or 0 if unknown.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setChannels (int32_t channels) [pure virtual]
Set the number of channels to use when ENCODING.
Ignored if a non audio stream, or if DECODING.
Parameters:
channels The number of channels we'll encode with.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getAudioFrameSize () [pure virtual]
For this stream, get the number of audio samples that are represented in a packet of information.
Returns:
Number of samples per 'frame' of encoded audio
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getGlobalQuality () [pure virtual]
Get the Global Quality setting this codec uses for video if a VideoPicture doesn't have a quality set.
Returns:
The global quality.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setGlobalQuality (int32_t newQuality) [pure virtual]
Set the Global Quality to a new value.
Parameters:
newQuality The new global quality.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getFlags () [pure virtual]
Get the flags associated with this codec.
Returns:
The (compacted) value of all flags set.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setFlags (int32_t newFlags) [pure virtual]
Set the FFMPEG flags to use with this codec.
All values must be ORed (|) together.
See also:
Flags
Parameters:
newFlags The new set flags for this codec.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual bool com::xuggle::xuggler::IStreamCoder::getFlag (Flags flag) [pure virtual]
Get the setting for the specified flag.
Parameters:
flag The flag you want to find the setting for
Returns:
0 for false; non-zero for true
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setFlag (Flags flag, bool value) [pure virtual]
Set the flag.
Parameters:
flag The flag to set
value The value to set it to (true or false)
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int64_t com::xuggle::xuggler::IStreamCoder::getNextPredictedPts () [pure virtual]
For this stream, get the next Pts that we expect to decode.
Note that this may not actually be the next Pts (for example due to transmission packet drops in the input source). Still it can be a useful tool.
Returns:
The next presentation time stamp we expect to decode on this stream. This is always in units of 1/1,000,000 seconds
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::open () [pure virtual]
Open the Codec associated with this StreamCoder.
You can get the codec through getCodec(...) and set it with setCodec(...). You cannot call any set* methods after you've called open() on this StreamCoder until you close() it.
You must call close() when you're done, but if you don't, the container will clean up after you (but yell at you) when it is closed.
Returns:
>= 0 on success; < 0 on error.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::close () [pure virtual]
Close a Codec that was opened on this StreamCoder.
Returns:
>= 0 on success; < 0 on error.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::decodeAudio (IAudioSamples * pOutSamples, IPacket * packet, int32_t byteOffset) [pure virtual]
Decode this packet into pOutSamples.
It will try to fill up the audio samples object, starting from the byteOffset inside this packet.
The caller is responsible for allocating the IAudioSamples object. This function will overwrite any data in the samples object.
Note that the IAudioSamples object passed in must have a IAudioSamples#getMaxBufferSize() of at least 192kbytes. Sorry, but this requirement is imposed on us via FFmpeg. If the buffer is not large enough, this method will reallocate the underlying buffers to make them at least 192kbytes.
Parameters:
pOutSamples The AudioSamples we decode to
packet The packet we're attempting to decode from.
byteOffset Where in the packet payload to start decoding
Returns:
number of bytes actually processed from the packet, or negative for error
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::decodeVideo (IVideoPicture * pOutFrame, IPacket * packet, int32_t byteOffset) [pure virtual]
Decode this packet into pOutFrame.
The caller is responsible for allocating the IVideoPicture object. This function will potentially overwrite any data in the frame object, but you should pass the same IVideoPicture into this function repeatedly until IVideoPicture::isComplete() is true.
Parameters:
pOutFrame The AudioSamples we decode.
packet The packet we're attempting to decode from.
byteOffset Where in the packet payload to start decoding
Returns:
number of bytes actually processed from the packet, or negative for error
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::encodeVideo (IPacket * pOutPacket, IVideoPicture * pFrame, int32_t suggestedBufferSize) [pure virtual]
Encode the given frame using this StreamCoder.
The VideoPicture will allocate a buffer to use internally for this, and will free it when the frame destroys itself.
Also, when done in order to flush the encoder, caller should call this method passing in 0 (null) for pFrame to tell the encoder to flush any data it was keeping a hold of.
Parameters:
pOutPacket [out] The packet to encode into. It will point to a buffer allocated in the frame. Caller should check IPacket::isComplete() after call to find out if we had enough information to encode a full packet.
pFrame [in/out] The frame to encode
suggestedBufferSize The suggested buffer size to allocate or -1 for choose ourselves. If -1 we'll allocate a buffer exactly the same size (+1) as the decoded frame with the guess that you're encoding a frame because you want to use LESS space than that.
@ return >= 0 on success; <0 on error.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::encodeAudio (IPacket * pOutPacket, IAudioSamples * pSamples, uint32_t sampleToStartFrom) [pure virtual]
Encode the given samples using this StreamCoder.
The VideoPicture will allocate a buffer to use internally for this, and will free it when the frame destroys itself.
Callers should call this repeatedly on a set of samples until we consume all the samples.
Also, when done in order to flush the encoder, caller should call this method passing in 0 (null) for pSamples to tell the encoder to flush any data it was keeping a hold of.
Parameters:
pOutPacket [out] The packet to encode into. It will point to a buffer allocated in the frame. Caller should check IPacket::isComplete() after call to find out if we had enough information to encode a full packet.
pSamples [in] The samples to consume
sampleToStartFrom [in] Which sample you want to start with This is usually zero, but if you're using a codec that packetizes output with small number of samples, you may need to call encodeAudio repeatedly with different starting samples to consume all of your samples.
Returns:
number of samples we consumed when encoding, or negative for errors.
Implemented in com::xuggle::xuggler::StreamCoder.
IStreamCoder * com::xuggle::xuggler::IStreamCoder::make (Direction direction) [static]
Create a standalone StreamCoder that can decode data without regard to which IStream or IContainer it came from.
If you're reading or writing to a XUGGLER file or URL you almost definitely don't want to use this method. Use the IContainer#getStream(long) and IStream#getStreamCoder() methods instead as it will set up the resulting IStreamCoder with sensible defaults. Use of a un-attached StreamCoder returned from this method is for advanced users only.
Parameters:
direction The direction this StreamCoder will work in.
Returns:
a new stream coder, or null if error.
Definition at line 35 of file IStreamCoder.cpp.
References com::xuggle::xuggler::Global::init(), and com::xuggle::xuggler::StreamCoder::make().
  {
    Global::init();
    return StreamCoder::make(direction, 0);
  }
virtual int32_t com::xuggle::xuggler::IStreamCoder::getCodecTag () [pure virtual]
Returns the 4-byte FOURCC tag (Least Significant Byte first).
This is really a packed 4-byte array so it's only useful if you use bit-wise operations on it. Some language wrappings may provide more obvious ways of manipulating, but this is the safest way to do this that will work with all wrappers.
Returns:
the FOURCC tag.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setCodecTag (int32_t fourcc) [pure virtual]
Set the 4-byte FOURCC tag for this coder.
Parameters:
fourcc The FOURCC to set, with Least Significant Byte first.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getNumProperties () [pure virtual]
Returns the total number of settable properties on this object.
Returns:
total number of options (not including constant definitions)
Implemented in com::xuggle::xuggler::StreamCoder.
virtual IProperty* com::xuggle::xuggler::IStreamCoder::getPropertyMetaData (int32_t propertyNo) [pure virtual]
Returns the name of the numbered property.
Parameters:
propertyNo The property number in the options list.
Returns:
an IProperty value for this properties meta-data
Implemented in com::xuggle::xuggler::StreamCoder.
virtual IProperty* com::xuggle::xuggler::IStreamCoder::getPropertyMetaData (const char * name) [pure virtual]
Returns the name of the numbered property.
Parameters:
name The property name.
Returns:
an IProperty value for this properties meta-data
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::setProperty (const char * name, const char * value) [pure virtual]
Sets a property on this Object.
All AVOptions supported by the underlying AVClass are supported.
Parameters:
name The property name. For example "b" for bit-rate.
value The value of the property.
Returns:
>= 0 if the property was successfully set; <0 on error
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::setProperty (const char * name, double value) [pure virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::setProperty (const char * name, int64_t value) [pure virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::setProperty (const char * name, bool value) [pure virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::setProperty (const char * name, IRational * value) [pure virtual]
Looks up the property 'name' and sets the value of the property to 'value'.
Parameters:
name name of option
value Value of option
Returns:
>= 0 on success; <0 on error.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual char* com::xuggle::xuggler::IStreamCoder::getPropertyAsString (const char * name) [pure virtual]
Gets a property on this Object.
Note for C++ callers; you must free the returned array with delete[] in order to avoid a memory leak. Other language folks need not worry.
Parameters:
name property name
Returns:
an string copy of the option value, or null if the option doesn't exist.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual double com::xuggle::xuggler::IStreamCoder::getPropertyAsDouble (const char * name) [pure virtual]
Gets the value of this property, and returns as a double;.
Parameters:
name name of option
Returns:
double value of property, or 0 on error.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int64_t com::xuggle::xuggler::IStreamCoder::getPropertyAsLong (const char * name) [pure virtual]
Gets the value of this property, and returns as an long;.
Parameters:
name name of option
Returns:
long value of property, or 0 on error.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual IRational* com::xuggle::xuggler::IStreamCoder::getPropertyAsRational (const char * name) [pure virtual]
Gets the value of this property, and returns as an IRational;.
Parameters:
name name of option
Returns:
long value of property, or 0 on error.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual bool com::xuggle::xuggler::IStreamCoder::getPropertyAsBoolean (const char * name) [pure virtual]
Gets the value of this property, and returns as a boolean.
Parameters:
name name of option
Returns:
boolean value of property, or false on error.
Implemented in com::xuggle::xuggler::StreamCoder.
virtual bool com::xuggle::xuggler::IStreamCoder::isOpen () [pure virtual]
Returns true if this IStreamCoder is currently open.
Returns:
true if open; false if not
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getDefaultAudioFrameSize () [pure virtual]
Get the default audio frame size (in samples).
Some codecs, especially raw codecs, like PCM, don't have a standard frame size. In those cases, we use the value of this setting to determine how many samples to encode into a single packet.
Returns:
the number of samples in an audio frame size if the codec doesn't specify the size.
Since:
1.21
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setDefaultAudioFrameSize (int32_t aNewSize) [pure virtual]
Set the default audio frame size.
Parameters:
aNewSize The new number of samples to use to encode samples into a packet. This setting is ignored if <= 0 or if the codec requires it's own frame size (e.g. Nellymoser).
See also:
getDefaultAudioFrameSize()
Since:
1.21
Implemented in com::xuggle::xuggler::StreamCoder.
IStreamCoder * com::xuggle::xuggler::IStreamCoder::make (Direction direction, IStreamCoder * copyCoder) [static]
Creates a new IStreamCoder object by copying all the settings in copyCoder.
The new IStreamCoder is created by copying all the current properties on the passed in StreamCoder. If the passed in stream coder is in a different direction than the one you want, this method still set the same codec ID, and the IStreamCoder.open() method will check then to see if it can work in the specified direction.
For example, imagine that direction is ENCODING and the copyCoder is a DECODING StreamCoder that is of the CODEC_ID_VP6 type. The resulting new IStreamCoder has it's code set to CODEC_ID_VP6. However (as of the writing of this comment) we don't support encoding to CODEC_ID_VP6, so when you try to open the codec we will fail.
Parameters:
direction The direction you want the new IStreamCoder to work in.
copyCoder The coder to copy settings from.
Returns:
A new IStreamCoder, or null on error.
Since:
1.22
Definition at line 42 of file IStreamCoder.cpp.
References com::xuggle::xuggler::Global::init(), and com::xuggle::xuggler::StreamCoder::make().
  {
    Global::init();
    return StreamCoder::make(direction, coder);
  }
virtual int64_t com::xuggle::xuggler::IStreamCoder::getNumDroppedFrames () [pure virtual]
Get the number of frames this StreamCoder had to drop to encode at the specified getTimeBase().
IStreamCoder objects can encode audio and video, but guarantee that every packet outputted has monotonically increasing timestamps (i.e. 0, 1, 2, 3, 4, 5, etc. without repeats). Sometimes data is passed too quickly into an IStreamCoder via encodeVideo or encodeAudio, and the underlying codec can't handle it that quickly. In those cases the IStreamCoder must drop the most recent frame of data.
If you're seeing a lot of dropped frames you can try either sending less frequent data to the IStreamCoder, or adjusting the getTimeBase() to the highest possible resolution. Be warned though; some codecs (such as MPEG2) require fixed time-bases (like 1/25) and so setting a higher resolution time base might end up with the codec not able to encode any data.
Returns:
the number of frames dropped.
Since:
3.1
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setAutomaticallyStampPacketsForStream (bool value) [pure virtual]
Should the IStreamCoder automatically adjust time stamps on output packets for the IStream it is ultimately destined for.
If this IStreamCoder does not know which IStream it is destined for, or this IStreamCoder isn't used with an IStream at all, then this setting is ignored.
Parameters:
value true to automatically adjust.
Since:
3.2
Implemented in com::xuggle::xuggler::StreamCoder.
virtual bool com::xuggle::xuggler::IStreamCoder::getAutomaticallyStampPacketsForStream () [pure virtual]
Does this IStreamCoder automatically adjust time stamps on output packets for the IStream it is ultimately destined for.
Returns:
true for yes; false for no
See also:
setAutomaticallyStampPacketsForStream(boolean)
Since:
3.2
Implemented in com::xuggle::xuggler::StreamCoder.
virtual void com::xuggle::xuggler::IStreamCoder::setCodecID (ICodec::ID id) [pure virtual]
Look up a Codec based on the passed in ID, and then set it.
Forwards to setCodecID(com.xuggle.xuggler.ICodec.ID)
To see if you actually set the correct ID, call getCodec() and check for 0 (null).
Once you call setCodec, all settings on the IStreamCoder are reset to default values. So you probably want to call this first.
Parameters:
id ID of codec to set.
Since:
3.2
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::setExtraData (com::xuggle::ferry::IBuffer * src, int32_t offset, int32_t length, bool allocNew) [pure virtual]
Copies data from the given buffer into the extra-data area maintained by encoders.
This is an extremely advanced method, and incorrect usage can result in Java crashes so take care. In general people should not need to use this.
For some codecs (e.g. for H264, this is global header information and for rv10 it is additional flags), Xuggler maintains extra information about the codec in a extra data buffer. In general Xuggler will allocate this data as needed and you never need to set it (or get it). But if you know what you're doing, you can ask Xuggler to replace the existing extra data for the given codec with a copy of the data in the given buffer.
You should call this method after you call open() but before you encode or decode any media.
Parameters:
src The data to copy
offset The position, in bytes, to start copying data from src
length The number of bytes to copy from data
allocNew If true, and there is not enough space in the existing extra data buffer, then Xuggler will discard the old buffer and allocate a new buffer. If false, then Xuggler will attempt to copy the data into the existing buffer and if there is not enough space in the existing buffer, no bytes will be copied and an error will be returned. In general, you should set this to false if that works for you.
Returns:
The number of bytes copied, or < 0 on error.
Since:
3.3
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getExtraData (com::xuggle::ferry::IBuffer * dest, int32_t offset, int32_t maxBytesToCopy) [pure virtual]
Copies the current content of the extra-data buffer maintained by this codec (e.g.
header bytes) into the dest buffer.
Parameters:
dest The buffer to copy to.
offset The position, in bytes, to start writing data to in dest.
maxBytesToCopy The maximum number of bytes to copy.
Returns:
The number of bytes copied, or < 0 on error.
Since:
3.3
Implemented in com::xuggle::xuggler::StreamCoder.
virtual int32_t com::xuggle::xuggler::IStreamCoder::getExtraDataSize () [pure virtual]
Gets the current number of bytes of data maintained in the coder extra-data area.
Returns:
The number of bytes. If 0, then no data is currently available.
Since:
3.3
Implemented in com::xuggle::xuggler::StreamCoder.
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/IStreamCoder.h
csrc/com/xuggle/xuggler/IStreamCoder.cpp