Xuggle: com::xuggle::xuggler::IContainerFormat Class Reference
com::xuggle::xuggler::IContainerFormat Class Reference
#include <IContainerFormat.h>
Detailed Description
Specifies format information than can be used to configure an IContainer for input or output.
Often times XUGGLER can guess the correct formats to put into a given IContainer object, but sometimes it needs help. You can allocate an IContainerFormat object and specify information about input or output containers, and then pass this to IContainer.open(...) to help us guess.
Definition at line 40 of file IContainerFormat.h.
Public Types
enum Flags {
FLAG_NOFILE = 0x0001, FLAG_NEEDNUMBER = 0x0002, FLAG_SHOW_IDS = 0x0008, FLAG_RAWPICTURE = 0x0020,
FLAG_GLOBALHEADER = 0x0040, FLAG_NOTIMESTAMPS = 0x0080, FLAG_GENERIC_INDEX = 0x0100, FLAG_TS_DISCONT = 0x0200
}
Public Member Functions
virtual int32_t setInputFormat (const char *shortName)=0
Sets the input format for this container.
virtual int32_t setOutputFormat (const char *shortName, const char *url, const char *mimeType)=0
Sets the output format for this container.
virtual const char * getInputFormatShortName ()=0
Get the short name for the input format.
virtual const char * getInputFormatLongName ()=0
Get the long name for the input format.
virtual const char * getOutputFormatShortName ()=0
Get the short name for the output format.
virtual const char * getOutputFormatLongName ()=0
Get the long name for the output format.
virtual const char * getOutputFormatMimeType ()=0
Get the mime type for the output format.
virtual int32_t getInputFlags ()=0
Get the input flags associated with this object.
virtual void setInputFlags (int32_t newFlags)=0
Set the input flags to use with this object.
virtual bool getInputFlag (Flags flag)=0
Get the input setting for the specified flag.
virtual void setInputFlag (Flags flag, bool value)=0
Set the input flag.
virtual int32_t getOutputFlags ()=0
Get the output flags associated with this object.
virtual void setOutputFlags (int32_t newFlags)=0
Set the output flags to use with this object.
virtual bool getOutputFlag (Flags flag)=0
Get the output setting for the specified flag.
virtual void setOutputFlag (Flags flag, bool value)=0
Set the output flag.
virtual bool isOutput ()=0
Is this an output container format?
virtual bool isInput ()=0
Is this an input container format?
virtual const char * getOutputExtensions ()=0
Get the filename extensions that this output format prefers (most common first).
virtual ICodec::ID getOutputDefaultAudioCodec ()=0
Get the default audio codec this container prefers, if known.
virtual ICodec::ID getOutputDefaultVideoCodec ()=0
Get the default video codec this container prefers, if known.
virtual ICodec::ID getOutputDefaultSubtitleCodec ()=0
Get the default subtitle codec this container prefers, if known.
virtual int32_t getOutputNumCodecsSupported ()=0
Gets the number of different codecs this container can include for encoding.
virtual ICodec::ID getOutputCodecID (int32_t index)=0
Queries for a supported codec id from the list of codecs that can be encoded into this ContainerFormat.
virtual int32_t getOutputCodecTag (int32_t index)=0
Queries for a supported codec tag from the list of codecs that can be encoded into this ContainerFormat.
virtual int32_t getOutputCodecTag (ICodec::ID id)=0
Get the 4-byte tag the container would output for the given codec id.
virtual bool isCodecSupportedForOutput (ICodec::ID id)=0
Returns true if this container format can output media encoded with the given codec.
Static Public Member Functions
static IContainerFormat * make ()
Create a new IContainerFormat object.
static int32_t getNumInstalledInputFormats ()
Get the number of input formats this install can demultiplex (read) from.
static IContainerFormat * getInstalledInputFormat (int32_t index)
Return an object for the input format at the given index.
static int32_t getNumInstalledOutputFormats ()
Get the number of output formats this install can multiplex (write) to.
static IContainerFormat * getInstalledOutputFormat (int32_t index)
Return an object for the output format at the given index.
Protected Member Functions
virtual ~IContainerFormat ()=0
Member Enumeration Documentation
enum com::xuggle::xuggler::IContainerFormat::Flags
Enumerator:
FLAG_NOFILE
FLAG_NEEDNUMBER
FLAG_SHOW_IDS
FLAG_RAWPICTURE
FLAG_GLOBALHEADER
FLAG_NOTIMESTAMPS
FLAG_GENERIC_INDEX
FLAG_TS_DISCONT
Definition at line 108 of file IContainerFormat.h.
                 {
      FLAG_NOFILE=0x0001,
      FLAG_NEEDNUMBER = 0x0002,
      FLAG_SHOW_IDS=0x0008,
      FLAG_RAWPICTURE=0x0020,
      FLAG_GLOBALHEADER=0x0040,
      FLAG_NOTIMESTAMPS=0x0080,
      FLAG_GENERIC_INDEX=0x0100,
      FLAG_TS_DISCONT=0x0200
    } Flags;
Constructor & Destructor Documentation
com::xuggle::xuggler::IContainerFormat::~IContainerFormat () [protected, pure virtual]
Definition at line 28 of file IContainerFormat.cpp.
  {
  }
Member Function Documentation
virtual int32_t com::xuggle::xuggler::IContainerFormat::setInputFormat (const char * shortName) [pure virtual]
Sets the input format for this container.
Parameters:
shortName The short name for this container (using FFMPEG's short name).
Returns:
>= 0 on success. < 0 if shortName cannot be found.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual int32_t com::xuggle::xuggler::IContainerFormat::setOutputFormat (const char * shortName, const char * url, const char * mimeType) [pure virtual]
Sets the output format for this container.
We'll look at the shortName, url and mimeType and try to guess a valid output container format.
Parameters:
shortName The short name for this container (using FFMPEG's short name).
url The URL for this container.
mimeType The mime type for this container.
Returns:
>= 0 on success. < 0 if we cannot find a good container.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual const char* com::xuggle::xuggler::IContainerFormat::getInputFormatShortName () [pure virtual]
Get the short name for the input format.
Returns:
The short name for the input format, or null if none.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual const char* com::xuggle::xuggler::IContainerFormat::getInputFormatLongName () [pure virtual]
Get the long name for the input format.
Returns:
The long name for the input format, or null if none.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual const char* com::xuggle::xuggler::IContainerFormat::getOutputFormatShortName () [pure virtual]
Get the short name for the output format.
Returns:
The short name for the output format, or null if none.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual const char* com::xuggle::xuggler::IContainerFormat::getOutputFormatLongName () [pure virtual]
Get the long name for the output format.
Returns:
The long name for the output format, or null if none.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual const char* com::xuggle::xuggler::IContainerFormat::getOutputFormatMimeType () [pure virtual]
Get the mime type for the output format.
Returns:
The mime type for the output format, or null if none.
Implemented in com::xuggle::xuggler::ContainerFormat.
IContainerFormat * com::xuggle::xuggler::IContainerFormat::make () [static]
Create a new IContainerFormat object.
Returns:
a new object, or null on error.
Definition at line 33 of file IContainerFormat.cpp.
References com::xuggle::xuggler::Global::init().
Referenced by com::xuggle::xuggler::Container::getContainerFormat(), getInstalledInputFormat(), getInstalledOutputFormat(), and com::xuggle::xuggler::Codec::guessEncodingCodec().
  {
    Global::init();
    return ContainerFormat::make();
  }
virtual int32_t com::xuggle::xuggler::IContainerFormat::getInputFlags () [pure virtual]
Get the input flags associated with this object.
Returns:
The (compacted) value of all flags set.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual void com::xuggle::xuggler::IContainerFormat::setInputFlags (int32_t newFlags) [pure virtual]
Set the input flags to use with this object.
All values must be ORed (|) together.
See also:
Flags
Parameters:
newFlags The new set flags for this codec.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual bool com::xuggle::xuggler::IContainerFormat::getInputFlag (Flags flag) [pure virtual]
Get the input setting for the specified flag.
Parameters:
flag The flag you want to find the setting for
Returns:
0 for false; non-zero for true
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual void com::xuggle::xuggler::IContainerFormat::setInputFlag (Flags flag, bool value) [pure virtual]
Set the input flag.
Parameters:
flag The flag to set
value The value to set it to (true or false)
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual int32_t com::xuggle::xuggler::IContainerFormat::getOutputFlags () [pure virtual]
Get the output flags associated with this object.
Returns:
The (compacted) value of all flags set.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual void com::xuggle::xuggler::IContainerFormat::setOutputFlags (int32_t newFlags) [pure virtual]
Set the output flags to use with this object.
All values must be ORed (|) together.
See also:
Flags
Parameters:
newFlags The new set flags for this codec.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual bool com::xuggle::xuggler::IContainerFormat::getOutputFlag (Flags flag) [pure virtual]
Get the output setting for the specified flag.
Parameters:
flag The flag you want to find the setting for
Returns:
0 for false; non-zero for true
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual void com::xuggle::xuggler::IContainerFormat::setOutputFlag (Flags flag, bool value) [pure virtual]
Set the output flag.
Parameters:
flag The flag to set
value The value to set it to (true or false)
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual bool com::xuggle::xuggler::IContainerFormat::isOutput () [pure virtual]
Is this an output container format?
Returns:
true if output; false it not
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual bool com::xuggle::xuggler::IContainerFormat::isInput () [pure virtual]
Is this an input container format?
Returns:
true if input; false it not
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual const char* com::xuggle::xuggler::IContainerFormat::getOutputExtensions () [pure virtual]
Get the filename extensions that this output format prefers (most common first).
Returns:
a command separated string of output extensions, or null if none.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual ICodec::ID com::xuggle::xuggler::IContainerFormat::getOutputDefaultAudioCodec () [pure virtual]
Get the default audio codec this container prefers, if known.
Returns:
the default audio codec id, or ICodec.ID#CODEC_ID_NONE if unknown.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual ICodec::ID com::xuggle::xuggler::IContainerFormat::getOutputDefaultVideoCodec () [pure virtual]
Get the default video codec this container prefers, if known.
Returns:
the default video codec id, or ICodec.ID#CODEC_ID_NONE if unknown.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual ICodec::ID com::xuggle::xuggler::IContainerFormat::getOutputDefaultSubtitleCodec () [pure virtual]
Get the default subtitle codec this container prefers, if known.
Returns:
the default subtitle codec id, or ICodec.ID#CODEC_ID_NONE if unknown.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual int32_t com::xuggle::xuggler::IContainerFormat::getOutputNumCodecsSupported () [pure virtual]
Gets the number of different codecs this container can include for encoding.
This can be used as an upper bound when using the getOutputCodecID(int) and getOutputCodecTag(int) methods to dynamically query the actual codecs.
Returns:
The total number of different codec types that can be encoded into this container format.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual ICodec::ID com::xuggle::xuggler::IContainerFormat::getOutputCodecID (int32_t index) [pure virtual]
Queries for a supported codec id from the list of codecs that can be encoded into this ContainerFormat.
Parameters:
index The index in our lookup table. Index >= 0 and < getOutputNumCodecsSupported(). Index values may change between releases, so always query.
Returns:
The codec id at this position, or ICodec.ID#CODEC_ID_NONE if there is none.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual int32_t com::xuggle::xuggler::IContainerFormat::getOutputCodecTag (int32_t index) [pure virtual]
Queries for a supported codec tag from the list of codecs that can be encoded into this ContainerFormat.
Tags are 4-byte values that are often used as markers in a container format for a codec type.
Parameters:
index The index in our lookup table. Index >= 0 and < getOutputNumCodecsSupported(). Index values may change between releases, so always query.
Returns:
The codec id tag this position, or 0 if there is none.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual int32_t com::xuggle::xuggler::IContainerFormat::getOutputCodecTag (ICodec::ID id) [pure virtual]
Get the 4-byte tag the container would output for the given codec id.
Parameters:
id the codec you are about
Returns:
the 4-byte codec tag, or 0 if that id is not supported.
Implemented in com::xuggle::xuggler::ContainerFormat.
virtual bool com::xuggle::xuggler::IContainerFormat::isCodecSupportedForOutput (ICodec::ID id) [pure virtual]
Returns true if this container format can output media encoded with the given codec.
Parameters:
id the codec you care about.
Returns:
true if the codec can be put in this output container; false otherwise.
Implemented in com::xuggle::xuggler::ContainerFormat.
int32_t com::xuggle::xuggler::IContainerFormat::getNumInstalledInputFormats () [static]
Get the number of input formats this install can demultiplex (read) from.
Returns:
the number of formats
Definition at line 40 of file IContainerFormat.cpp.
References com::xuggle::xuggler::Global::init().
  {
    Global::init();
    int i = 0;
    for(AVInputFormat* f = 0;
    (f = av_iformat_next(f))!=0;
    ++i)
      ;
    return i;
  }
IContainerFormat * com::xuggle::xuggler::IContainerFormat::getInstalledInputFormat (int32_t index) [static]
Return an object for the input format at the given index.
Parameters:
index an index for the input format list we maintain
Returns:
a format object for that input or null if unknown, index < 0 or index >= getNumInstalledInputFormats()
Definition at line 52 of file IContainerFormat.cpp.
References com::xuggle::xuggler::Global::init(), make(), and com::xuggle::xuggler::ContainerFormat::setInputFormat().
  {
    Global::init();
    int i = 0;
    for(AVInputFormat* f = 0;
    (f = av_iformat_next(f))!=0;
    ++i)
      if (i == index) {
        ContainerFormat * retval = ContainerFormat::make();
        if (retval)
          retval->setInputFormat(f);
        return retval;
      }
    return 0;
  }
int32_t com::xuggle::xuggler::IContainerFormat::getNumInstalledOutputFormats () [static]
Get the number of output formats this install can multiplex (write) to.
Returns:
the number of formats
Definition at line 69 of file IContainerFormat.cpp.
References com::xuggle::xuggler::Global::init().
  {
    Global::init();
    int i = 0;
    for(AVOutputFormat* f = 0;
    (f = av_oformat_next(f))!=0;
    ++i)
      ;
    return i;
  }
IContainerFormat * com::xuggle::xuggler::IContainerFormat::getInstalledOutputFormat (int32_t index) [static]
Return an object for the output format at the given index.
Parameters:
index an index for the output format list we maintain
Returns:
a format object for that output or null if unknown, index < 0 or index >= getNumInstalledOutputFormats()
Definition at line 81 of file IContainerFormat.cpp.
References com::xuggle::xuggler::Global::init(), make(), and com::xuggle::xuggler::ContainerFormat::setOutputFormat().
  {
    Global::init();
    int i = 0;
    for(AVOutputFormat* f = 0;
    (f = av_oformat_next(f))!=0;
    ++i)
      if (i == index)
      {
        ContainerFormat* retval =ContainerFormat::make();
        if (retval)
          retval->setOutputFormat(f);
        return retval;
      }
    return 0;
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/IContainerFormat.h
csrc/com/xuggle/xuggler/IContainerFormat.cpp