Xuggle: com::xuggle::xuggler::IRational Class Reference
com::xuggle::xuggler::IRational Class Reference
#include <IRational.h>
Detailed Description
This class wraps represents a Rational number for the Xuggler.
Video formats often use rational numbers, and converting between them willy nilly can lead to rounding errors, and eventually, out of sync problems. Therefore we use IRational objects to pass around Rational Numbers and avoid conversion until the very last moment.
Note: There are some static convenience methods in this class that start with s*. They start with s (as opposed to overloading methods (e.g. sAdd(...) vs. add(...)).
Definition at line 42 of file IRational.h.
Public Types
enum Rounding {
ROUND_ZERO = 0, ROUND_INF = 1, ROUND_DOWN = 2, ROUND_UP = 3,
ROUND_NEAR_INF = 5
}
typedef enum
com::xuggle::xuggler::IRational::Rounding Rounding
Public Member Functions
virtual int32_t getNumerator ()=0
Get the numerator for this rational.
virtual int32_t getDenominator ()=0
Get the denominator for this rational.
virtual IRational * copy ()=0
Creates a new IRational object by copying (by value) this object.
virtual int32_t compareTo (IRational *other)=0
Compare a rational to this rational.
virtual double getDouble ()=0
Rational to double conversion.
virtual int32_t reduce (int64_t num, int64_t den, int64_t max)=0
Reduce a fraction to it's lowest common denominators.
virtual IRational * multiply (IRational *arg)=0
Multiplies this number by arg.
virtual IRational * divide (IRational *arg)=0
Divides this rational by arg.
virtual IRational * subtract (IRational *arg)=0
Subtracts arg from this rational.
virtual IRational * add (IRational *arg)=0
Adds arg to this rational.
virtual int64_t rescale (int64_t origValue, IRational *origBase)=0
Takes a value scaled in increments of origBase and gives the equivalent value scaled in terms of this Rational.
virtual int64_t rescale (int64_t origValue, IRational *origBase, Rounding rounding)=0
Takes a value scaled in increments of origBase and gives the equivalent value scaled in terms of this Rational.
virtual void setNumerator (int32_t value)=0
Sets the numerator on this object.
virtual void setDenominator (int32_t value)=0
Sets the denominator on this object.
virtual void setValue (double value)=0
Sets the numerator and denominator on this object by reducing the double to the closest integer numerator and denominator.
virtual double getValue ()=0
An alias for getDouble() but matching JavaBean conventions.
virtual bool isFinalized ()=0
Returns true if init() has been called and this object is now considered finalized and immutable.
virtual void init ()=0
Marks this object as finalized and immutable.
Static Public Member Functions
static int32_t sCompareTo (IRational *a, IRational *b)
Compare two rationals.
static int32_t sReduce (IRational *dst, int64_t num, int64_t den, int64_t max)
Reduce a fraction to it's lowest common denominators.
static IRational * sMultiply (IRational *a, IRational *b)
Multiples a by b.
static IRational * sDivide (IRational *a, IRational *b)
Divides a by b.
static IRational * sSubtract (IRational *a, IRational *b)
Subtracts a from b.
static IRational * sAdd (IRational *a, IRational *b)
Adds a to b.
static int64_t sRescale (int64_t origValue, IRational *origBase, IRational *newBase)
Takes a value scaled in increments of origBase and gives the equivalent value scaled in terms of this Rational.
static IRational * make ()
Get a new rational that will be set to 0/0.
static IRational * make (double d)
Converts a double precision floating point number to a rational.
static IRational * make (IRational *src)
Creates deep copy of a Rational from another Rational.
static IRational * make (int32_t num, int32_t den)
Create a rational from a numerator and denominator.
static int64_t sRescale (int64_t origValue, IRational *origBase, IRational *newBase, Rounding rounding)
Takes a value scaled in increments of origBase and gives the equivalent value scaled in terms of this Rational.
static int64_t rescale (int64_t srcValue, int32_t dstNumerator, int32_t dstDenominator, int32_t srcNumerator, int32_t srcDenominator, Rounding rounding)
Rescales a long value to another long value.
Protected Member Functions
IRational ()
virtual ~IRational ()
Member Typedef Documentation
typedef enum com::xuggle::xuggler::IRational::Rounding com::xuggle::xuggler::IRational::Rounding
Member Enumeration Documentation
enum com::xuggle::xuggler::IRational::Rounding
Enumerator:
ROUND_ZERO
ROUND_INF
ROUND_DOWN
ROUND_UP
ROUND_NEAR_INF
Definition at line 233 of file IRational.h.
{
        ROUND_ZERO     = 0,
        ROUND_INF      = 1,
        ROUND_DOWN     = 2,
        ROUND_UP       = 3,
        ROUND_NEAR_INF = 5,
    } Rounding;
Constructor & Destructor Documentation
com::xuggle::xuggler::IRational::IRational () [protected]
Definition at line 27 of file IRational.cpp.
    {
    }
com::xuggle::xuggler::IRational::~IRational () [protected, virtual]
Definition at line 31 of file IRational.cpp.
    {
    }
Member Function Documentation
virtual int32_t com::xuggle::xuggler::IRational::getNumerator () [pure virtual]
Get the numerator for this rational.
Returns:
the numerator.
Implemented in com::xuggle::xuggler::Rational.
Referenced by com::xuggle::xuggler::Stream::setFrameRate(), com::xuggle::xuggler::Property::setProperty(), com::xuggle::xuggler::Stream::setSampleAspectRatio(), com::xuggle::xuggler::StreamCoder::setTimeBase(), com::xuggle::xuggler::Stream::setTimeBase(), and com::xuggle::xuggler::ContainerParameters::setTimeBase().
virtual int32_t com::xuggle::xuggler::IRational::getDenominator () [pure virtual]
Get the denominator for this rational.
Returns:
the denominator.
Implemented in com::xuggle::xuggler::Rational.
Referenced by com::xuggle::xuggler::Stream::setFrameRate(), com::xuggle::xuggler::Property::setProperty(), com::xuggle::xuggler::Stream::setSampleAspectRatio(), com::xuggle::xuggler::StreamCoder::setTimeBase(), com::xuggle::xuggler::Stream::setTimeBase(), and com::xuggle::xuggler::ContainerParameters::setTimeBase().
virtual IRational* com::xuggle::xuggler::IRational::copy () [pure virtual]
Creates a new IRational object by copying (by value) this object.
Returns:
the new object
Implemented in com::xuggle::xuggler::Rational.
virtual int32_t com::xuggle::xuggler::IRational::compareTo (IRational * other) [pure virtual]
Compare a rational to this rational.
Parameters:
other second rational
Returns:
0 if this==other, 1 if this>other and -1 if this<other.
Implemented in com::xuggle::xuggler::Rational.
Referenced by sCompareTo().
int32_t com::xuggle::xuggler::IRational::sCompareTo (IRational * a, IRational * b) [static]
Compare two rationals.
Parameters:
a the first rational
b the second rational
Returns:
0 if a==b, 1 if a>b and -1 if b<a.
Definition at line 36 of file IRational.cpp.
References compareTo().
    {
      return a->compareTo(b);
    }
virtual double com::xuggle::xuggler::IRational::getDouble () [pure virtual]
Rational to double conversion.
Returns:
(double) a
Implemented in com::xuggle::xuggler::Rational.
virtual int32_t com::xuggle::xuggler::IRational::reduce (int64_t num, int64_t den, int64_t max) [pure virtual]
Reduce a fraction to it's lowest common denominators.
This is useful for framerate calculations.
Parameters:
num the src numerator.
den the src denominator.
max the maximum allowed for nom & den in the reduced fraction.
Returns:
1 if exact, 0 otherwise
Implemented in com::xuggle::xuggler::Rational.
Referenced by sReduce().
int32_t com::xuggle::xuggler::IRational::sReduce (IRational * dst, int64_t num, int64_t den, int64_t max) [static]
Reduce a fraction to it's lowest common denominators.
This is useful for framerate calculations.
Parameters:
dst The destination rational
num the src numerator.
den the src denominator.
max the maximum allowed for nom & den in the reduced fraction.
Returns:
1 if exact, 0 otherwise
Definition at line 42 of file IRational.cpp.
References reduce().
    {
      return (dst ? dst->reduce(num, den, max) : 0);
    }
virtual IRational* com::xuggle::xuggler::IRational::multiply (IRational * arg) [pure virtual]
Multiplies this number by arg.
Parameters:
arg number to mulitply by.
Returns:
this*arg.
Implemented in com::xuggle::xuggler::Rational.
Referenced by sMultiply().
IRational * com::xuggle::xuggler::IRational::sMultiply (IRational * a, IRational * b) [static]
Multiples a by b.
Parameters:
a the first number
b the second number.
Returns:
a*b
Definition at line 67 of file IRational.cpp.
References multiply().
    {
      return a->multiply(b);
    }
virtual IRational* com::xuggle::xuggler::IRational::divide (IRational * arg) [pure virtual]
Divides this rational by arg.
Parameters:
arg The divisor to use.
Returns:
this/arg.
Implemented in com::xuggle::xuggler::Rational.
Referenced by sDivide().
IRational * com::xuggle::xuggler::IRational::sDivide (IRational * a, IRational * b) [static]
Divides a by b.
Parameters:
a The first number. b The second number.
Returns:
a/b.
Definition at line 49 of file IRational.cpp.
References divide().
    {
      return a->divide(b);
    }
virtual IRational* com::xuggle::xuggler::IRational::subtract (IRational * arg) [pure virtual]
Subtracts arg from this rational.
Parameters:
arg The amount to subtract from this.
Returns:
this-arg.
Implemented in com::xuggle::xuggler::Rational.
Referenced by sSubtract().
IRational * com::xuggle::xuggler::IRational::sSubtract (IRational * a, IRational * b) [static]
Subtracts a from b.
Parameters:
a The first number. b The second number.
Returns:
a-b.
Definition at line 55 of file IRational.cpp.
References subtract().
    {
      return a->subtract(b);
    }
virtual IRational* com::xuggle::xuggler::IRational::add (IRational * arg) [pure virtual]
Adds arg to this rational.
Parameters:
arg The amount to add to this.
Returns:
this+arg.
Implemented in com::xuggle::xuggler::Rational.
Referenced by sAdd().
IRational * com::xuggle::xuggler::IRational::sAdd (IRational * a, IRational * b) [static]
Adds a to b.
Parameters:
a The first number. b The second number.
Returns:
a+b.
Definition at line 61 of file IRational.cpp.
References add().
    {
      return a->add(b);
    }
virtual int64_t com::xuggle::xuggler::IRational::rescale (int64_t origValue, IRational * origBase) [pure virtual]
Takes a value scaled in increments of origBase and gives the equivalent value scaled in terms of this Rational.
Parameters:
origValue The original int64_t value you care about.
origBase The original base Rational that origValue is scaled with.
Returns:
The new integer value, scaled in units of this IRational.
Implemented in com::xuggle::xuggler::Rational.
Referenced by sRescale().
int64_t com::xuggle::xuggler::IRational::sRescale (int64_t origValue, IRational * origBase, IRational * newBase) [static]
Takes a value scaled in increments of origBase and gives the equivalent value scaled in terms of this Rational.
Parameters:
origValue The original int64_t value you care about.
origBase The original base Rational that origValue is scaled with.
newBase The rational you want to rescale origValue into.
Returns:
The new integer value, scaled in units of this IRational.
Definition at line 73 of file IRational.cpp.
References rescale().
    {
      return newBase->rescale(origValue, origBase);
    }
IRational * com::xuggle::xuggler::IRational::make () [static]
Get a new rational that will be set to 0/0.
The rational will not have init() called and hence will be modifiable by setValue(double) until init() is called.
Returns:
a rational number object
Definition at line 79 of file IRational.cpp.
References com::xuggle::xuggler::Global::init().
Referenced by com::xuggle::xuggler::Rational::add(), com::xuggle::xuggler::AudioSamples::AudioSamples(), com::xuggle::xuggler::Rational::copy(), com::xuggle::xuggler::Rational::divide(), com::xuggle::xuggler::Stream::getFrameRate(), com::xuggle::xuggler::Property::getPropertyAsRational(), com::xuggle::xuggler::Stream::getSampleAspectRatio(), com::xuggle::xuggler::Codec::getSupportedVideoFrameRate(), com::xuggle::xuggler::StreamCoder::getTimeBase(), com::xuggle::xuggler::Stream::getTimeBase(), com::xuggle::xuggler::ContainerParameters::getTimeBase(), com::xuggle::xuggler::Rational::make(), make(), com::xuggle::xuggler::Rational::multiply(), com::xuggle::xuggler::StreamCoder::StreamCoder(), com::xuggle::xuggler::Rational::subtract(), and com::xuggle::xuggler::VideoPicture::VideoPicture().
    {
      Global::init();
      return Rational::make();
    }
IRational * com::xuggle::xuggler::IRational::make (double d) [static]
Converts a double precision floating point number to a rational.
Parameters:
d double to convert
Returns:
A new Rational; caller must release() when done.
Reimplemented in com::xuggle::xuggler::Rational.
Definition at line 86 of file IRational.cpp.
References com::xuggle::xuggler::Global::init(), and make().
    {
      Global::init();
      return Rational::make(d);
    }
IRational * com::xuggle::xuggler::IRational::make (IRational * src) [static]
Creates deep copy of a Rational from another Rational.
Parameters:
src The source Rational to copy.
Returns:
A new Rational; Returns null if src is null.
Definition at line 93 of file IRational.cpp.
References com::xuggle::xuggler::Global::init(), and make().
    {
      Global::init();
      Rational* src = dynamic_cast<Rational*>(aSrc);
      IRational* retval = 0;
      if (src)
      {
        retval = Rational::make(src);
      }
      return retval;
    }
IRational * com::xuggle::xuggler::IRational::make (int32_t num, int32_t den) [static]
Create a rational from a numerator and denominator.
We will always reduce this to the lowest num/den pair we can, but never having den exceed what was passed in.
Parameters:
num The numerator of the resulting Rational
den The denominator of the resulting Rational
Returns:
A new Rational;
Reimplemented in com::xuggle::xuggler::Rational.
Definition at line 106 of file IRational.cpp.
References com::xuggle::xuggler::Global::init(), and make().
    {
      Global::init();
      return Rational::make(num, den);
    }
virtual int64_t com::xuggle::xuggler::IRational::rescale (int64_t origValue, IRational * origBase, Rounding rounding) [pure virtual]
Takes a value scaled in increments of origBase and gives the equivalent value scaled in terms of this Rational.
Parameters:
origValue The original int64_t value you care about.
origBase The original base Rational that origValue is scaled with.
rounding How you want rounding to occur
Returns:
The new integer value, scaled in units of this IRational.
Implemented in com::xuggle::xuggler::Rational.
int64_t com::xuggle::xuggler::IRational::sRescale (int64_t origValue, IRational * origBase, IRational * newBase, Rounding rounding) [static]
Takes a value scaled in increments of origBase and gives the equivalent value scaled in terms of this Rational.
Parameters:
origValue The original int64_t value you care about.
origBase The original base Rational that origValue is scaled with.
newBase The rational you want to rescale origValue into.
rounding How you want rounding to occur
Returns:
The new integer value, scaled in units of this IRational.
Definition at line 113 of file IRational.cpp.
References rescale().
    {
      if (!origBase || !newBase)
        return origValue;
      return newBase->rescale(origValue, origBase, rounding);
    }
int64_t com::xuggle::xuggler::IRational::rescale (int64_t srcValue, int32_t dstNumerator, int32_t dstDenominator, int32_t srcNumerator, int32_t srcDenominator, Rounding rounding) [static]
Rescales a long value to another long value.
This method doesn't use IRational values, but instead uses numerators and denominators passed in by the caller. It will not result in any memory allocations.
Parameters:
srcValue The value to rescale.
dstNumerator The numerator of the units you want to scale to. Must be non-zero.
dstDenominator The denominator of the units you want to scale to. Must be non-zero.
srcNumerator The numerator of the units srcValue is expressed in. Must be non-zero.
srcDenominator The denominator of the units srcValue is expressed in. Must be non-zero.
rounding How you want rounding to occur
Returns:
The new integer value, scaled in units of dstNumerator/dstNumerator, or 0 if there is a parameter error.
Reimplemented in com::xuggle::xuggler::Rational.
Definition at line 123 of file IRational.cpp.
References com::xuggle::xuggler::Rational::rescale().
    {
      return Rational::rescale(srcValue,
          dstNumerator, dstDenominator,
          srcNumerator, srcDenominator,
          rounding);
    }
virtual void com::xuggle::xuggler::IRational::setNumerator (int32_t value) [pure virtual]
Sets the numerator on this object.
If isFinalized is true, then this method is ignored.
Since:
3.2
Implemented in com::xuggle::xuggler::Rational.
virtual void com::xuggle::xuggler::IRational::setDenominator (int32_t value) [pure virtual]
Sets the denominator on this object.
If isFinalized is true, then this method is ignored.
Since:
3.2
Implemented in com::xuggle::xuggler::Rational.
virtual void com::xuggle::xuggler::IRational::setValue (double value) [pure virtual]
Sets the numerator and denominator on this object by reducing the double to the closest integer numerator and denominator.
If isFinalized is true, then this method is ignored.
Since:
3.2
Implemented in com::xuggle::xuggler::Rational.
virtual double com::xuggle::xuggler::IRational::getValue () [pure virtual]
An alias for getDouble() but matching JavaBean conventions.
Since:
3.2
Implemented in com::xuggle::xuggler::Rational.
virtual bool com::xuggle::xuggler::IRational::isFinalized () [pure virtual]
Returns true if init() has been called and this object is now considered finalized and immutable.
Since:
3.2
Implemented in com::xuggle::xuggler::Rational.
virtual void com::xuggle::xuggler::IRational::init () [pure virtual]
Marks this object as finalized and immutable.
Any setters called after the first init() call will be ignored.
Most make methods will call this method automatically, with the exception of the blank factory method make().
Since:
3.2
Implemented in com::xuggle::xuggler::Rational.
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/IRational.h
csrc/com/xuggle/xuggler/IRational.cpp