Xuggle: com::xuggle::xuggler::Packet Class Reference
com::xuggle::xuggler::Packet Class Reference
#include <Packet.h>
Detailed Description
Definition at line 30 of file Packet.h.
Public Member Functions
VS_JNIUTILS_REFCOUNTED_OBJECT (Packet)
virtual int64_t getTimeStamp ()
Get the time stamp of this object in getTimeBase() units.
virtual void setTimeStamp (int64_t aTimeStamp)
Set the time stamp for this object in getTimeBase() units.
virtual bool isKey ()
Is this object a key object? i.e.
virtual IRational * getTimeBase ()
Get the time base that time stamps of this object are represented in.
virtual void setTimeBase (IRational *aBase)
Set the time base that time stamps of this object are represented in.
virtual void reset ()
Clear out any data in this packet, but leaves the buffer available for reuse.
virtual int64_t getPts ()
Get the Presentation Time Stamp (PTS) for this packet.
virtual int64_t getDts ()
Get the Decompression Time Stamp (DTS) for this packet.
virtual int32_t getSize ()
Get the size in bytes of the payload currently in this packet.
virtual int32_t getMaxSize ()
Get the maximum size (in bytes) of payload this packet can hold.
virtual int32_t getStreamIndex ()
Get the container-specific index for the stream this packet is part of.
virtual int32_t getFlags ()
Get any flags set on this packet, as a 4-byte binary-ORed bit-mask.
virtual bool isKeyPacket ()
Does this packet contain Key data? i.e.
virtual int64_t getDuration ()
Return the duration of this packet, in units of getTimeBase().
virtual int64_t getPosition ()
Return the position (in bytes) of this packet in the stream.
virtual
com::xuggle::ferry::IBuffer * getData ()
Get any underlying raw data available for this object.
virtual int32_t allocateNewPayload (int32_t payloadSize)
Discard the current payload and allocate a new payload.
virtual bool isComplete ()
Is this packet complete.
virtual void setKeyPacket (bool keyPacket)
Set if this is a key packet.
virtual void setFlags (int32_t flags)
Set any internal flags.
virtual void setPts (int64_t pts)
Set a new Presentation Time Stamp (PTS) for this packet.
virtual void setDts (int64_t dts)
Set a new Decompression Time Stamp (DTS) for this packet.
virtual void setComplete (bool complete, int32_t size)
Set if this packet is complete, and what the total size of the data should be assumed to be.
virtual void setStreamIndex (int32_t streamIndex)
Set the stream index for this packet.
virtual void setDuration (int64_t duration)
Set the duration.
virtual void setPosition (int64_t position)
Set the position.
virtual int64_t getConvergenceDuration ()
Time difference in IStream#getTimeBase() units from the presentation time stamp of this packet to the point at which the output from the decoder has converged independent from the availability of previous frames.
virtual void setConvergenceDuration (int64_t duration)
Set the convergence duration.
virtual void setData (com::xuggle::ferry::IBuffer *buffer)
Sets the underlying buffer used by this object.
AVPacket * getAVPacket ()
void wrapAVPacket (AVPacket *pkt)
void wrapBuffer (com::xuggle::ferry::IBuffer *buffer)
Static Public Member Functions
static Packet * make (int32_t payloadSize)
Allocate a new packet.
static Packet * make (com::xuggle::ferry::IBuffer *buffer)
Allocate a new packet that wraps an existing IBuffer.
static Packet * make (Packet *packet, bool)
static void freeAVBuffer (void *buf, void *closure)
Protected Member Functions
Packet ()
virtual ~Packet ()
Constructor & Destructor Documentation
com::xuggle::xuggler::Packet::Packet () [protected]
Definition at line 35 of file Packet.cpp.
  {
    mPacket = (AVPacket*)av_malloc(sizeof(AVPacket));
    if (!mPacket)
      throw std::bad_alloc();
    if (mPacket)
    {
      // initialize because ffmpeg doesn't
      av_init_packet(mPacket);
      mPacket->data = 0;
      mPacket->size = 0;
    }
    mIsComplete = false;
  }
com::xuggle::xuggler::Packet::~Packet () [protected, virtual]
Definition at line 51 of file Packet.cpp.
References reset().
  {
    if (mPacket) {
      reset();
      av_free(mPacket);
    }
    mPacket = 0;
  }
Member Function Documentation
com::xuggle::xuggler::Packet::VS_JNIUTILS_REFCOUNTED_OBJECT (Packet)
Packet * com::xuggle::xuggler::Packet::make (int32_t size) [static]
Allocate a new packet.
Note that any buffers this packet needs will be lazily allocated (i.e. we won't actually grab all the memory until we need it).
Parameters:
size The maximum size, in bytes, of data you want to put in this packet.
Returns:
a new packet, or null on error.
Reimplemented from com::xuggle::xuggler::IPacket.
Definition at line 220 of file Packet.cpp.
References allocateNewPayload(), com::xuggle::xuggler::IPacket::make(), and VS_REF_RELEASE.
  {
    Packet *retval= 0;
    try {
      retval = Packet::make();
      if (retval->allocateNewPayload(payloadSize) < 0)
      {
        throw std::bad_alloc();
      }
    }
    catch (std::bad_alloc & e)
    {
      VS_REF_RELEASE(retval);
      throw e;
    }
    return retval;
  }
Packet * com::xuggle::xuggler::Packet::make (com::xuggle::ferry::IBuffer * buffer) [static]
Allocate a new packet that wraps an existing IBuffer.
Parameters:
buffer The IBuffer to wrap.
Returns:
a new packet or null on error.
Reimplemented from com::xuggle::xuggler::IPacket.
Definition at line 240 of file Packet.cpp.
References com::xuggle::xuggler::IPacket::make(), and wrapBuffer().
  {
    Packet *retval= 0;
    retval = Packet::make();
    if (retval)
    {
      retval->wrapBuffer(buffer);
    }
    return retval;
  }
Packet * com::xuggle::xuggler::Packet::make (Packet * packet, bool copyData) [static]
Definition at line 252 of file Packet.cpp.
References getData(), getSize(), getTimeBase(), com::xuggle::xuggler::IPacket::make(), mPacket, setComplete(), setTimeBase(), and VS_REF_RELEASE.
  {
    Packet* retval=0;
    com::xuggle::ferry::IBuffer *buffer=0;
    IRational* timeBase = 0;
    try
    {
      if (!packet)
        throw std::runtime_error("need packet to copy");
      if (copyData)
      {
        int32_t numBytes = packet->getSize();
        retval = make(numBytes);
        if (!retval || !retval->mPacket || !retval->mPacket->data)
          throw std::bad_alloc();
        if (numBytes > 0 && packet->mPacket->data)
          memcpy(retval->mPacket->data, packet->mPacket->data,
              numBytes);
      } else {
        buffer=packet->getData();
        retval = make(buffer);
        if (!retval)
          throw std::bad_alloc();
      }
      // Keep a copy of this, because we're going to nuke
      // it temporarily.
      uint8_t* data_buf = retval->mPacket->data;
      void (*orig_destruct)(struct AVPacket *) = retval->mPacket->destruct;
      // copy all data members, including data and size,
      // but we'll overwrite those next.
      *(retval->mPacket) = *(packet->mPacket);
      retval->mPacket->data = data_buf;
      retval->mPacket->destruct = orig_destruct;
      // separate here to catch addRef()
      timeBase = packet->getTimeBase();
      retval->setTimeBase(timeBase);
      retval->setComplete(retval->mPacket->size > 0,
          retval->mPacket->size);
    }
    catch (std::exception &e)
    {
      VS_REF_RELEASE(retval);
    }
    VS_REF_RELEASE(buffer);
    VS_REF_RELEASE(timeBase);
    return retval;
  }
virtual int64_t com::xuggle::xuggler::Packet::getTimeStamp () [inline, virtual]
Get the time stamp of this object in getTimeBase() units.
Returns:
the time stamp
Implements com::xuggle::xuggler::IMediaData.
Definition at line 46 of file Packet.h.
References getDts().
{ return getDts(); }
virtual void com::xuggle::xuggler::Packet::setTimeStamp (int64_t aTimeStamp) [inline, virtual]
Set the time stamp for this object in getTimeBase() units.
Parameters:
aTimeStamp The time stamp
Implements com::xuggle::xuggler::IMediaData.
Definition at line 47 of file Packet.h.
References setDts().
{ setDts(aTimeStamp); }
virtual bool com::xuggle::xuggler::Packet::isKey () [inline, virtual]
Is this object a key object? i.e.
it can be interpreted without needing any other media objects
Returns:
true if it's a key, false if not
Implements com::xuggle::xuggler::IMediaData.
Definition at line 48 of file Packet.h.
References isKeyPacket().
{ return isKeyPacket(); }
virtual IRational* com::xuggle::xuggler::Packet::getTimeBase () [inline, virtual]
Get the time base that time stamps of this object are represented in.
Caller must release the returned value.
Returns:
the time base.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 49 of file Packet.h.
Referenced by make().
{ return mTimeBase.get(); }
virtual void com::xuggle::xuggler::Packet::setTimeBase (IRational * aBase) [inline, virtual]
Set the time base that time stamps of this object are represented in.
Parameters:
aBase the new time base. If null an exception is thrown.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 50 of file Packet.h.
Referenced by make(), and com::xuggle::xuggler::Container::readNextPacket().
{ mTimeBase.reset(aBase, true); }
void com::xuggle::xuggler::Packet::reset () [virtual]
Clear out any data in this packet, but leaves the buffer available for reuse.
Implements com::xuggle::xuggler::IPacket.
Definition at line 209 of file Packet.cpp.
References setComplete().
Referenced by allocateNewPayload(), com::xuggle::xuggler::StreamCoder::encodeAudio(), com::xuggle::xuggler::StreamCoder::encodeVideo(), com::xuggle::xuggler::Container::readNextPacket(), wrapBuffer(), and ~Packet().
  {
    if (mPacket) {
      av_free_packet(mPacket);
      av_init_packet(mPacket);
    }
    setComplete(false, 0);
    // Don't reset the buffer though; we can potentially reuse it.
  }
int64_t com::xuggle::xuggler::Packet::getPts () [virtual]
Get the Presentation Time Stamp (PTS) for this packet.
This is the time at which the payload for this packet should be presented to the user, in units of getTimeBase(), relative to the start of stream.
Returns:
Get the Presentation Timestamp for this packet.
Implements com::xuggle::xuggler::IPacket.
Definition at line 61 of file Packet.cpp.
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), com::xuggle::xuggler::StreamCoder::decodeVideo(), and com::xuggle::xuggler::Container::readNextPacket().
  {
    return (mPacket ? mPacket->pts : (int64_t)-1);
  }
int64_t com::xuggle::xuggler::Packet::getDts () [virtual]
Get the Decompression Time Stamp (DTS) for this packet.
This is the time at which the payload for this packet should be decompressed, in units of getTimeBase(), relative to the start of stream.
Some media codecs can require packets from the "future" to be decompressed before earliest packets as an additional way to compress data. In general you don't need to worry about this, but if you're curious start reading about the difference between I-Frames, P-Frames and B-Frames (or Bi-Directional Frames). B-Frames can use information from future frames when compressed.
Returns:
Get the Decompression Timestamp (i.e. when this was read relative to the start of reading packets).
Implements com::xuggle::xuggler::IPacket.
Definition at line 73 of file Packet.cpp.
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), com::xuggle::xuggler::StreamCoder::decodeVideo(), getTimeStamp(), and com::xuggle::xuggler::Container::readNextPacket().
  {
    return (mPacket ? mPacket->dts : (int64_t)-1);
  }
int32_t com::xuggle::xuggler::Packet::getSize () [virtual]
Get the size in bytes of the payload currently in this packet.
Returns:
Size (in bytes) of payload currently in packet.
Implements com::xuggle::xuggler::IPacket.
Definition at line 85 of file Packet.cpp.
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), com::xuggle::xuggler::StreamCoder::decodeVideo(), make(), com::xuggle::xuggler::Container::readNextPacket(), and com::xuggle::xuggler::Container::writePacket().
  {
    return (mPacket ? mPacket->size: (int32_t)-1);
  }
int32_t com::xuggle::xuggler::Packet::getMaxSize () [virtual]
Get the maximum size (in bytes) of payload this packet can hold.
Returns:
Get maximum size (in bytes) of payload this packet can hold.
Implements com::xuggle::xuggler::IPacket.
Definition at line 90 of file Packet.cpp.
  {
    return (mBuffer ? mBuffer->getBufferSize() : -1);
  }
int32_t com::xuggle::xuggler::Packet::getStreamIndex () [virtual]
Get the container-specific index for the stream this packet is part of.
Returns:
Stream in container that this packet has data for.
Implements com::xuggle::xuggler::IPacket.
Definition at line 95 of file Packet.cpp.
Referenced by com::xuggle::xuggler::Container::readNextPacket(), and com::xuggle::xuggler::Container::writePacket().
  {
    return (mPacket ? mPacket->stream_index: (int32_t)-1);
  }
int32_t com::xuggle::xuggler::Packet::getFlags () [virtual]
Get any flags set on this packet, as a 4-byte binary-ORed bit-mask.
This is access to raw FFMPEG flags, but it is easier to use the is* methods below.
Returns:
Any flags on the packet.
Implements com::xuggle::xuggler::IPacket.
Definition at line 100 of file Packet.cpp.
Referenced by com::xuggle::xuggler::Container::readNextPacket().
  {
    return (mPacket ? mPacket->flags: (int32_t)-1);
  }
bool com::xuggle::xuggler::Packet::isKeyPacket () [virtual]
Does this packet contain Key data? i.e.
data that needs no other frames or samples to decode.
Returns:
true if key; false otherwise.
Implements com::xuggle::xuggler::IPacket.
Definition at line 105 of file Packet.cpp.
Referenced by isKey().
  {
    return (mPacket ? mPacket->flags & AV_PKT_FLAG_KEY : false);
  }
int64_t com::xuggle::xuggler::Packet::getDuration () [virtual]
Return the duration of this packet, in units of getTimeBase().
Returns:
Duration of this packet, in same time-base as the PTS.
Implements com::xuggle::xuggler::IPacket.
Definition at line 147 of file Packet.cpp.
Referenced by com::xuggle::xuggler::Container::readNextPacket().
  {
    return (mPacket ? mPacket->duration: (int64_t)-1);
  }
int64_t com::xuggle::xuggler::Packet::getPosition () [virtual]
Return the position (in bytes) of this packet in the stream.
Returns:
The position of this packet in the stream, or -1 if unknown.
Implements com::xuggle::xuggler::IPacket.
Definition at line 159 of file Packet.cpp.
Referenced by com::xuggle::xuggler::Container::readNextPacket().
  {
    return (mPacket ? mPacket->pos: (int64_t)-1);
  }
com::xuggle::ferry::IBuffer * com::xuggle::xuggler::Packet::getData () [virtual]
Get any underlying raw data available for this object.
Returns:
The raw data, or null if not accessible.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 171 of file Packet.cpp.
References com::xuggle::ferry::RefPointer< T >::get().
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), com::xuggle::xuggler::StreamCoder::decodeVideo(), com::xuggle::xuggler::StreamCoder::encodeAudio(), com::xuggle::xuggler::StreamCoder::encodeVideo(), and make().
  {
    return mBuffer.get();
  }
int32_t com::xuggle::xuggler::Packet::allocateNewPayload (int32_t payloadSize) [virtual]
Discard the current payload and allocate a new payload.
Note that if any people have access to the old payload using getData(), the memory will continue to be available to them until they release their hold of the IBuffer.
When requesting a packet size, the system may allocate a larger payloadSize.
Parameters:
payloadSize The (minimum) payloadSize of this packet in bytes.
Returns:
>= 0 if successful. < 0 if error.
Implements com::xuggle::xuggler::IPacket.
Definition at line 307 of file Packet.cpp.
References freeAVBuffer(), com::xuggle::ferry::Buffer::make(), reset(), setComplete(), and VS_ASSERT.
Referenced by com::xuggle::xuggler::StreamCoder::encodeAudio(), com::xuggle::xuggler::StreamCoder::encodeVideo(), make(), and wrapAVPacket().
  {
    int32_t retval = -1;
    reset();
    uint8_t* payload = 0;
    // Some FFMPEG encoders will read past the end of a
    // buffer, so you need to allocate extra; yuck.
    if (!mBuffer || mBuffer->getBufferSize() < payloadSize)
    {
      // buffer isn't big enough; we need to make a new one.
      payload = (uint8_t*) av_malloc(payloadSize+FF_INPUT_BUFFER_PADDING_SIZE);
      if (!payload)
        throw std::bad_alloc();
      // we don't use the JVM for packets because Ffmpeg is REAL squirly about that
      mBuffer = Buffer::make(0, payload,
          payloadSize,
          Packet::freeAVBuffer, 0);
      if (!mBuffer) {
        av_free(payload);
        throw std::bad_alloc();
      }
      // and memset the padding area.
      memset(payload + payloadSize,
          0,
          FF_INPUT_BUFFER_PADDING_SIZE);
    } else {
      payload = (uint8_t*)mBuffer->getBytes(0, payloadSize);
    }
    VS_ASSERT(mPacket, "Should already have a packet");
    VS_ASSERT(mBuffer, "Should have allocated a buffer");
    VS_ASSERT(payload, "Should have allocated a payload");
    if (mBuffer && mPacket)
    {
      mPacket->data = payload;
      // And start out at zero.
      mPacket->size = 0;
      this->setComplete(false, 0);
      retval = 0;
    }
    return retval;
  }
bool com::xuggle::xuggler::Packet::isComplete () [virtual]
Is this packet complete.
Returns:
Is this packet full and therefore has valid information.
Implements com::xuggle::xuggler::IPacket.
Definition at line 382 of file Packet.cpp.
Referenced by com::xuggle::xuggler::Container::writePacket().
  {
    return mIsComplete && mPacket->data;
  }
void com::xuggle::xuggler::Packet::setKeyPacket (bool keyPacket) [virtual]
Set if this is a key packet.
Parameters:
keyPacket true for yes, false for no.
Implements com::xuggle::xuggler::IPacket.
Definition at line 111 of file Packet.cpp.
  {
    if (mPacket)
    {
      if (bKeyPacket)
        mPacket->flags |= AV_PKT_FLAG_KEY;
      else
        mPacket->flags = 0;
    }
  }
void com::xuggle::xuggler::Packet::setFlags (int32_t flags) [virtual]
Set any internal flags.
Parameters:
flags Flags to set
Implements com::xuggle::xuggler::IPacket.
Definition at line 123 of file Packet.cpp.
  {
    if (mPacket)
      mPacket->flags = flags;
  }
void com::xuggle::xuggler::Packet::setPts (int64_t aPts) [virtual]
Set a new Presentation Time Stamp (PTS) for this packet.
Parameters:
aPts a new PTS for this packet.
See also:
getPts()
Implements com::xuggle::xuggler::IPacket.
Definition at line 67 of file Packet.cpp.
  {
    if (mPacket) mPacket->pts = aPts;
  }
void com::xuggle::xuggler::Packet::setDts (int64_t aDts) [virtual]
Set a new Decompression Time Stamp (DTS) for this packet.
Parameters:
aDts a new DTS for this packet.
See also:
getDts()
Implements com::xuggle::xuggler::IPacket.
Definition at line 79 of file Packet.cpp.
Referenced by setTimeStamp().
  {
    if (mPacket) mPacket->dts = aDts;
  }
void com::xuggle::xuggler::Packet::setComplete (bool complete, int32_t size) [virtual]
Set if this packet is complete, and what the total size of the data should be assumed to be.
Parameters:
complete True for complete, false for not.
size Size of data in packet.
Implements com::xuggle::xuggler::IPacket.
Definition at line 130 of file Packet.cpp.
Referenced by allocateNewPayload(), make(), reset(), wrapAVPacket(), and wrapBuffer().
  {
    mIsComplete = complete;
    if (mIsComplete)
    {
      if (mPacket)
        mPacket->size = size;
    }
  }
void com::xuggle::xuggler::Packet::setStreamIndex (int32_t streamIndex) [virtual]
Set the stream index for this packet.
Parameters:
streamIndex The stream index, as determined from the IContainer this packet will be written to.
Implements com::xuggle::xuggler::IPacket.
Definition at line 141 of file Packet.cpp.
  {
    if (mPacket)
      mPacket->stream_index = streamIndex;
  }
void com::xuggle::xuggler::Packet::setDuration (int64_t duration) [virtual]
Set the duration.
Parameters:
duration new duration
See also:
getDuration()
Implements com::xuggle::xuggler::IPacket.
Definition at line 153 of file Packet.cpp.
  {
    if (mPacket) mPacket->duration = duration;
  }
void com::xuggle::xuggler::Packet::setPosition (int64_t position) [virtual]
Set the position.
Parameters:
position new position
See also:
getPosition()
Implements com::xuggle::xuggler::IPacket.
Definition at line 165 of file Packet.cpp.
  {
    if (mPacket) mPacket->pos = position;
  }
int64_t com::xuggle::xuggler::Packet::getConvergenceDuration () [virtual]
Time difference in IStream#getTimeBase() units from the presentation time stamp of this packet to the point at which the output from the decoder has converged independent from the availability of previous frames.
That is, the frames are virtually identical no matter if decoding started from the very first frame or from this keyframe. Is Global#NO_PTS if unknown. This field is not the display duration of the current packet.
The purpose of this field is to allow seeking in streams that have no keyframes in the conventional sense. It corresponds to the recovery point SEI in H.264 and match_time_delta in NUT. It is also essential for some types of subtitle streams to ensure that all subtitles are correctly displayed after seeking.
If you didn't follow that, try drinking one to two glasses of Absinthe. It won't help, but it'll be more fun.
Returns:
the convergence duration
Implements com::xuggle::xuggler::IPacket.
Definition at line 398 of file Packet.cpp.
  {
    return (mPacket ? mPacket->convergence_duration : -1);
  }
void com::xuggle::xuggler::Packet::setConvergenceDuration (int64_t duration) [virtual]
Set the convergence duration.
Parameters:
duration the new duration
Implements com::xuggle::xuggler::IPacket.
Definition at line 404 of file Packet.cpp.
  {
    if (mPacket) mPacket->convergence_duration = duration;
  }
void com::xuggle::xuggler::Packet::setData (com::xuggle::ferry::IBuffer * buffer) [virtual]
Sets the underlying buffer used by this object.
This is an advanced method and is not recommended for use by those who don't fully understand how IBuffers work. Implementations of IMediaData may behave in undefined ways if the buffer you pass in is not big enough for what you ask them to do (e.g. they may discard your buffer and allocate a larger one if they need more space). It is up to the caller to ensure the buffer passed in is large enough, and is not simultaneously in use by another part of the system.
Parameters:
buffer The buffer to set. If null, this method is ignored.
Implements com::xuggle::xuggler::IMediaData.
Definition at line 354 of file Packet.cpp.
References wrapBuffer().
  {
    wrapBuffer(buffer);
  }
AVPacket* com::xuggle::xuggler::Packet::getAVPacket () [inline]
Definition at line 81 of file Packet.h.
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), com::xuggle::xuggler::StreamCoder::decodeVideo(), and com::xuggle::xuggler::Container::readNextPacket().
{ return mPacket; }
void com::xuggle::xuggler::Packet::wrapAVPacket (AVPacket * pkt)
Definition at line 177 of file Packet.cpp.
References allocateNewPayload(), setComplete(), and VS_ASSERT.
Referenced by com::xuggle::xuggler::Container::readNextPacket().
  {
    // WE ALWAYS COPY the data; Let Ffmpeg do what it wants
    // to with it's own memory.
    VS_ASSERT(mPacket, "No packet?");
    // Make sure we have a buffer at least as large as this packet
    // This overwrites data, which we'll patch below.
    (void) this->allocateNewPayload(pkt->size);
    // Keep a copy of this, because we're going to nuke
    // it temporarily.
    uint8_t* data_buf = mPacket->data;
    void (*orig_destruct)(struct AVPacket *) = mPacket->destruct;
    // copy all data members, including data and size,
    // but we'll overwrite those next.
    *mPacket = *pkt;
    // Reset the data buf.
    mPacket->data = data_buf;
    mPacket->destruct = orig_destruct;
    mPacket->size = pkt->size;
    // Copy the contents of the new packet into data.
    if (pkt->data && pkt->size)
      memcpy(mPacket->data, pkt->data, pkt->size);
    // And assume we're now complete.
    setComplete(true, mPacket->size);
  }
void com::xuggle::xuggler::Packet::wrapBuffer (com::xuggle::ferry::IBuffer * buffer)
Definition at line 360 of file Packet.cpp.
References com::xuggle::ferry::RefPointer< T >::reset(), reset(), setComplete(), com::xuggle::ferry::RefPointer< T >::value(), and VS_ASSERT.
Referenced by make(), and setData().
  {
    if (buffer != mBuffer.value())
    {
      reset();
      // and acquire this buffer.
      mBuffer.reset(buffer, true);
    }
    if (mBuffer)
    {
      // and patch up our AVPacket
      VS_ASSERT(mPacket, "No AVPacket");
      if (mPacket)
      {
        mPacket->size = mBuffer->getBufferSize();
        mPacket->data = (uint8_t*)mBuffer->getBytes(0, mPacket->size);
        // And assume we're now complete.
        setComplete(true, mPacket->size);
      }
    }
  }
void com::xuggle::xuggler::Packet::freeAVBuffer (void * buf, void * closure) [static]
Definition at line 388 of file Packet.cpp.
Referenced by allocateNewPayload().
  {
    // We know that FFMPEG allocated this with av_malloc, but
    // that might change in future versions; so this is
    // inherently somewhat dangerous.
    (void) closure;
    av_free(buf);
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/Packet.h
csrc/com/xuggle/xuggler/Packet.cpp