Xuggle: com::xuggle::xuggler::IIndexEntry Class Reference
com::xuggle::xuggler::IIndexEntry Class Reference
#include <IIndexEntry.h>
Detailed Description
An index entry for a IStream.
Some ContainerFormats can maintain index of where key-frames (and other interesting frames) can be found in a byte-stream. This is really helpful for implementing efficient seeking (for example, you can find all index entries near a desired timestamp, and you'll find the nearest key-frame).
We don't maintain a complete list of all ContainerFormats that support index, but if they do, you can query the IStream#getNumIndexEntries() method to find how many entires are in the index. Some ContainerFormats can parse the relevant Container message if an index is embedded in the container (for example, the MOV and MP4 demuxer can do this). Other ContainerFormats can create an index automatically as they read the file, even if an index is not embedded in the container (for example the FLV demuxer does this).
See also:
IStream::findTimeStampEntryInIndex(long, int)
IStream::findTimeStampPositionInIndex(long, int)
IStream::getIndexEntry(int)
IStream::getNumIndexEntries()
IStream::getIndexEntries()
Since:
3.4
Definition at line 64 of file IIndexEntry.h.
Public Member Functions
virtual int64_t getPosition ()=0
The position in bytes of the frame corresponding to this index entry in the IContainer.
virtual int64_t getTimeStamp ()=0
The actual time stamp, in units of IStream#getTimeBase(), of the frame this entry points to.
virtual int32_t getFlags ()=0
Flags set for this entry.
virtual int32_t getSize ()=0
The size of bytes of the frame this index entry points to.
virtual int32_t getMinDistance ()=0
Minimum number of index entries between this index entry and the last keyframe in the index, used to avoid unneeded searching.
virtual bool isKeyFrame ()=0
Is this index entry pointing to a key frame.
Static Public Member Functions
static IIndexEntry * make (int64_t position, int64_t timeStamp, int32_t flags, int32_t size, int32_t minDistance)
Create a new IIndexEntry with the specified values.
Static Public Attributes
static const int32_t IINDEX_FLAG_KEYFRAME = 0x0001
A bit mask value that may be set in getFlags.
Protected Member Functions
IIndexEntry ()
virtual ~IIndexEntry ()
Constructor & Destructor Documentation
com::xuggle::xuggler::IIndexEntry::IIndexEntry () [protected]
Definition at line 33 of file IIndexEntry.cpp.
{
}
com::xuggle::xuggler::IIndexEntry::~IIndexEntry () [protected, virtual]
Definition at line 38 of file IIndexEntry.cpp.
{
}
Member Function Documentation
IIndexEntry * com::xuggle::xuggler::IIndexEntry::make (int64_t position, int64_t timeStamp, int32_t flags, int32_t size, int32_t minDistance) [static]
Create a new IIndexEntry with the specified values.
Parameters:
position The value to be returned from getPosition().
timeStamp The value to be returned from getTimeStamp().
flags The value to be returned from getFlags().
size The value to be returned from getSize().
minDistance The value to be returned from getMinDistance().
Reimplemented in com::xuggle::xuggler::IndexEntry.
Definition at line 44 of file IIndexEntry.cpp.
References com::xuggle::xuggler::IndexEntry::make().
Referenced by com::xuggle::xuggler::Stream::getIndexEntry().
{
  return IndexEntry::make(position, timeStamp,
      flags, size, minDistance);
}
virtual int64_t com::xuggle::xuggler::IIndexEntry::getPosition () [pure virtual]
The position in bytes of the frame corresponding to this index entry in the IContainer.
Returns:
The byte-offset from start of the IContainer where the frame for this IIndexEntry can be found.
Implemented in com::xuggle::xuggler::IndexEntry.
Referenced by com::xuggle::xuggler::Stream::addIndexEntry().
virtual int64_t com::xuggle::xuggler::IIndexEntry::getTimeStamp () [pure virtual]
The actual time stamp, in units of IStream#getTimeBase(), of the frame this entry points to.
Returns:
The time stamp for this entry.
Implemented in com::xuggle::xuggler::IndexEntry.
Referenced by com::xuggle::xuggler::Stream::addIndexEntry().
virtual int32_t com::xuggle::xuggler::IIndexEntry::getFlags () [pure virtual]
Flags set for this entry.
See the IINDEX_FLAG* constants above.
Returns:
the flags.
Implemented in com::xuggle::xuggler::IndexEntry.
Referenced by com::xuggle::xuggler::Stream::addIndexEntry().
virtual int32_t com::xuggle::xuggler::IIndexEntry::getSize () [pure virtual]
The size of bytes of the frame this index entry points to.
Returns:
The size in bytes.
Implemented in com::xuggle::xuggler::IndexEntry.
Referenced by com::xuggle::xuggler::Stream::addIndexEntry().
virtual int32_t com::xuggle::xuggler::IIndexEntry::getMinDistance () [pure virtual]
Minimum number of index entries between this index entry and the last keyframe in the index, used to avoid unneeded searching.
Returns:
the minimum distance, in bytes.
Implemented in com::xuggle::xuggler::IndexEntry.
Referenced by com::xuggle::xuggler::Stream::addIndexEntry().
virtual bool com::xuggle::xuggler::IIndexEntry::isKeyFrame () [pure virtual]
Is this index entry pointing to a key frame.
Really shorthand for getFlags() & IINDEX_FLAG_KEYFRAME.
Returns:
True if this index entry is for a key frame.
Implemented in com::xuggle::xuggler::IndexEntry.
Member Data Documentation
const int32_t com::xuggle::xuggler::IIndexEntry::IINDEX_FLAG_KEYFRAME = 0x0001 [static]
A bit mask value that may be set in getFlags.
Definition at line 70 of file IIndexEntry.h.
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/IIndexEntry.h
csrc/com/xuggle/xuggler/IIndexEntry.cpp