Xuggle: com::xuggle::xuggler::IPacket Class Reference
com::xuggle::xuggler::IPacket Class Reference
#include <IPacket.h>
Detailed Description
Represents an encoded piece of data that can be placed in an IContainer for a given IStream of data.
You read this object out of IContainer objects when decoding, and pass to an IStreamCoder object to decode.
You pass this object to a IStreamCoder to encode data, and then pass to an IContainer object to write to a data source.
Lastly, the units of timestamps in an IPacket are determined by the IContainer it came from (or is going to). For example, FLV IPackets are always in milliseconds (1/1000 of a second). You cannot assume these timestamps are in any given timeunit without getting an IStream object and finding out what Time Base that stream operates in.
For convenience, the Xuggler API always uses Microseconds for raw data (IVideoPicture and IAudioSamples objects), and will convert to the right time stamp unit when decoding or encoding data (with an IStreamCoder) from or to an IContainer.
Definition at line 49 of file IPacket.h.
Public Member Functions
virtual void reset ()=0
Clear out any data in this packet, but leaves the buffer available for reuse.
virtual bool isComplete ()=0
Is this packet complete.
virtual int64_t getPts ()=0
Get the Presentation Time Stamp (PTS) for this packet.
virtual void setPts (int64_t aPts)=0
Set a new Presentation Time Stamp (PTS) for this packet.
virtual int64_t getDts ()=0
Get the Decompression Time Stamp (DTS) for this packet.
virtual void setDts (int64_t aDts)=0
Set a new Decompression Time Stamp (DTS) for this packet.
virtual int32_t getSize ()=0
Get the size in bytes of the payload currently in this packet.
virtual int32_t getMaxSize ()=0
Get the maximum size (in bytes) of payload this packet can hold.
virtual int32_t getStreamIndex ()=0
Get the container-specific index for the stream this packet is part of.
virtual int32_t getFlags ()=0
Get any flags set on this packet, as a 4-byte binary-ORed bit-mask.
virtual bool isKeyPacket ()=0
Does this packet contain Key data? i.e.
virtual int64_t getDuration ()=0
Return the duration of this packet, in units of getTimeBase().
virtual int64_t getPosition ()=0
Return the position (in bytes) of this packet in the stream.
virtual int32_t allocateNewPayload (int32_t payloadSize)=0
Discard the current payload and allocate a new payload.
virtual void setKeyPacket (bool keyPacket)=0
Set if this is a key packet.
virtual void setFlags (int32_t flags)=0
Set any internal flags.
virtual void setComplete (bool complete, int32_t size)=0
Set if this packet is complete, and what the total size of the data should be assumed to be.
virtual void setStreamIndex (int32_t streamIndex)=0
Set the stream index for this packet.
virtual void setDuration (int64_t duration)=0
Set the duration.
virtual void setPosition (int64_t position)=0
Set the position.
virtual int64_t getConvergenceDuration ()=0
Time difference in IStream#getTimeBase() units from the presentation time stamp of this packet to the point at which the output from the decoder has converged independent from the availability of previous frames.
virtual void setConvergenceDuration (int64_t duration)=0
Set the convergence duration.
Static Public Member Functions
static IPacket * make ()
Allocate a new packet.
static IPacket * make (com::xuggle::ferry::IBuffer *buffer)
Allocate a new packet that wraps an existing IBuffer.
static IPacket * make (IPacket *packet, bool copyData)
Allocate a new packet wrapping the existing contents of a passed in packet.
static IPacket * make (int32_t size)
Allocate a new packet.
Protected Member Functions
IPacket ()
virtual ~IPacket ()
Constructor & Destructor Documentation
com::xuggle::xuggler::IPacket::IPacket () [protected]
Definition at line 28 of file IPacket.cpp.
  {
  }
com::xuggle::xuggler::IPacket::~IPacket () [protected, virtual]
Definition at line 32 of file IPacket.cpp.
  {
  }
Member Function Documentation
virtual void com::xuggle::xuggler::IPacket::reset () [pure virtual]
Clear out any data in this packet, but leaves the buffer available for reuse.
Implemented in com::xuggle::xuggler::Packet.
virtual bool com::xuggle::xuggler::IPacket::isComplete () [pure virtual]
Is this packet complete.
Returns:
Is this packet full and therefore has valid information.
Implemented in com::xuggle::xuggler::Packet.
virtual int64_t com::xuggle::xuggler::IPacket::getPts () [pure virtual]
Get the Presentation Time Stamp (PTS) for this packet.
This is the time at which the payload for this packet should be presented to the user, in units of getTimeBase(), relative to the start of stream.
Returns:
Get the Presentation Timestamp for this packet.
Implemented in com::xuggle::xuggler::Packet.
Referenced by com::xuggle::xuggler::Stream::stampOutputPacket().
virtual void com::xuggle::xuggler::IPacket::setPts (int64_t aPts) [pure virtual]
Set a new Presentation Time Stamp (PTS) for this packet.
Parameters:
aPts a new PTS for this packet.
See also:
getPts()
Implemented in com::xuggle::xuggler::Packet.
Referenced by com::xuggle::xuggler::Stream::stampOutputPacket().
virtual int64_t com::xuggle::xuggler::IPacket::getDts () [pure virtual]
Get the Decompression Time Stamp (DTS) for this packet.
This is the time at which the payload for this packet should be decompressed, in units of getTimeBase(), relative to the start of stream.
Some media codecs can require packets from the "future" to be decompressed before earliest packets as an additional way to compress data. In general you don't need to worry about this, but if you're curious start reading about the difference between I-Frames, P-Frames and B-Frames (or Bi-Directional Frames). B-Frames can use information from future frames when compressed.
Returns:
Get the Decompression Timestamp (i.e. when this was read relative to the start of reading packets).
Implemented in com::xuggle::xuggler::Packet.
Referenced by com::xuggle::xuggler::Stream::stampOutputPacket().
virtual void com::xuggle::xuggler::IPacket::setDts (int64_t aDts) [pure virtual]
Set a new Decompression Time Stamp (DTS) for this packet.
Parameters:
aDts a new DTS for this packet.
See also:
getDts()
Implemented in com::xuggle::xuggler::Packet.
Referenced by com::xuggle::xuggler::Stream::stampOutputPacket().
virtual int32_t com::xuggle::xuggler::IPacket::getSize () [pure virtual]
Get the size in bytes of the payload currently in this packet.
Returns:
Size (in bytes) of payload currently in packet.
Implements com::xuggle::xuggler::IMediaData.
Implemented in com::xuggle::xuggler::Packet.
virtual int32_t com::xuggle::xuggler::IPacket::getMaxSize () [pure virtual]
Get the maximum size (in bytes) of payload this packet can hold.
Returns:
Get maximum size (in bytes) of payload this packet can hold.
Implemented in com::xuggle::xuggler::Packet.
virtual int32_t com::xuggle::xuggler::IPacket::getStreamIndex () [pure virtual]
Get the container-specific index for the stream this packet is part of.
Returns:
Stream in container that this packet has data for.
Implemented in com::xuggle::xuggler::Packet.
virtual int32_t com::xuggle::xuggler::IPacket::getFlags () [pure virtual]
Get any flags set on this packet, as a 4-byte binary-ORed bit-mask.
This is access to raw FFMPEG flags, but it is easier to use the is* methods below.
Returns:
Any flags on the packet.
Implemented in com::xuggle::xuggler::Packet.
virtual bool com::xuggle::xuggler::IPacket::isKeyPacket () [pure virtual]
Does this packet contain Key data? i.e.
data that needs no other frames or samples to decode.
Returns:
true if key; false otherwise.
Implemented in com::xuggle::xuggler::Packet.
virtual int64_t com::xuggle::xuggler::IPacket::getDuration () [pure virtual]
Return the duration of this packet, in units of getTimeBase().
Returns:
Duration of this packet, in same time-base as the PTS.
Implemented in com::xuggle::xuggler::Packet.
Referenced by com::xuggle::xuggler::Stream::stampOutputPacket().
virtual int64_t com::xuggle::xuggler::IPacket::getPosition () [pure virtual]
Return the position (in bytes) of this packet in the stream.
Returns:
The position of this packet in the stream, or -1 if unknown.
Implemented in com::xuggle::xuggler::Packet.
virtual int32_t com::xuggle::xuggler::IPacket::allocateNewPayload (int32_t payloadSize) [pure virtual]
Discard the current payload and allocate a new payload.
Note that if any people have access to the old payload using getData(), the memory will continue to be available to them until they release their hold of the IBuffer.
When requesting a packet size, the system may allocate a larger payloadSize.
Parameters:
payloadSize The (minimum) payloadSize of this packet in bytes.
Returns:
>= 0 if successful. < 0 if error.
Implemented in com::xuggle::xuggler::Packet.
Referenced by make().
IPacket * com::xuggle::xuggler::IPacket::make () [static]
Allocate a new packet.
Note that any buffers this packet needs will be lazily allocated (i.e. we won't actually grab all the memory until we need it).
Returns:
a new packet, or null on error.
Definition at line 37 of file IPacket.cpp.
References com::xuggle::xuggler::Global::init().
Referenced by com::xuggle::xuggler::Packet::make(), make(), and com::xuggle::xuggler::Container::writePacket().
  {
    Global::init();
    return Packet::make();
  }
IPacket * com::xuggle::xuggler::IPacket::make (com::xuggle::ferry::IBuffer * buffer) [static]
Allocate a new packet that wraps an existing IBuffer.
Parameters:
buffer The IBuffer to wrap.
Returns:
a new packet or null on error.
Reimplemented in com::xuggle::xuggler::Packet.
Definition at line 44 of file IPacket.cpp.
References com::xuggle::xuggler::Global::init(), and make().
  {
    Global::init();
    if (!buffer)
      throw std::invalid_argument("no buffer");
    return Packet::make(buffer);
  }
virtual void com::xuggle::xuggler::IPacket::setKeyPacket (bool keyPacket) [pure virtual]
Set if this is a key packet.
Parameters:
keyPacket true for yes, false for no.
Implemented in com::xuggle::xuggler::Packet.
virtual void com::xuggle::xuggler::IPacket::setFlags (int32_t flags) [pure virtual]
Set any internal flags.
Parameters:
flags Flags to set
Implemented in com::xuggle::xuggler::Packet.
virtual void com::xuggle::xuggler::IPacket::setComplete (bool complete, int32_t size) [pure virtual]
Set if this packet is complete, and what the total size of the data should be assumed to be.
Parameters:
complete True for complete, false for not.
size Size of data in packet.
Implemented in com::xuggle::xuggler::Packet.
virtual void com::xuggle::xuggler::IPacket::setStreamIndex (int32_t streamIndex) [pure virtual]
Set the stream index for this packet.
Parameters:
streamIndex The stream index, as determined from the IContainer this packet will be written to.
Implemented in com::xuggle::xuggler::Packet.
Referenced by com::xuggle::xuggler::Stream::stampOutputPacket().
virtual void com::xuggle::xuggler::IPacket::setDuration (int64_t duration) [pure virtual]
Set the duration.
Parameters:
duration new duration
See also:
getDuration()
Implemented in com::xuggle::xuggler::Packet.
Referenced by com::xuggle::xuggler::Stream::stampOutputPacket().
virtual void com::xuggle::xuggler::IPacket::setPosition (int64_t position) [pure virtual]
Set the position.
Parameters:
position new position
See also:
getPosition()
Implemented in com::xuggle::xuggler::Packet.
virtual int64_t com::xuggle::xuggler::IPacket::getConvergenceDuration () [pure virtual]
Time difference in IStream#getTimeBase() units from the presentation time stamp of this packet to the point at which the output from the decoder has converged independent from the availability of previous frames.
That is, the frames are virtually identical no matter if decoding started from the very first frame or from this keyframe. Is Global#NO_PTS if unknown. This field is not the display duration of the current packet.
The purpose of this field is to allow seeking in streams that have no keyframes in the conventional sense. It corresponds to the recovery point SEI in H.264 and match_time_delta in NUT. It is also essential for some types of subtitle streams to ensure that all subtitles are correctly displayed after seeking.
If you didn't follow that, try drinking one to two glasses of Absinthe. It won't help, but it'll be more fun.
Returns:
the convergence duration
Implemented in com::xuggle::xuggler::Packet.
virtual void com::xuggle::xuggler::IPacket::setConvergenceDuration (int64_t duration) [pure virtual]
Set the convergence duration.
Parameters:
duration the new duration
Implemented in com::xuggle::xuggler::Packet.
IPacket * com::xuggle::xuggler::IPacket::make (IPacket * packet, bool copyData) [static]
Allocate a new packet wrapping the existing contents of a passed in packet.
Callers can then modify getPts(), getDts() and other get/set methods without modifying the original packet.
Parameters:
packet Packet to reuse buffer from and to copy settings from.
copyData if true copy data from packet into our own buffer. If false, share the same data buffer that packet uses
Returns:
a new packet or null on error.
Definition at line 54 of file IPacket.cpp.
References com::xuggle::xuggler::Global::init(), and make().
  {
    Global::init();
    return Packet::make(dynamic_cast<Packet*>(packet), copyData);
  }
IPacket * com::xuggle::xuggler::IPacket::make (int32_t size) [static]
Allocate a new packet.
Note that any buffers this packet needs will be lazily allocated (i.e. we won't actually grab all the memory until we need it).
Parameters:
size The maximum size, in bytes, of data you want to put in this packet.
Returns:
a new packet, or null on error.
Reimplemented in com::xuggle::xuggler::Packet.
Definition at line 61 of file IPacket.cpp.
References allocateNewPayload(), com::xuggle::xuggler::Global::init(), make(), and VS_REF_RELEASE.
  {
    Global::init();
    IPacket* retval = make();
    if (retval) {
      if (retval->allocateNewPayload(size) < 0)
        VS_REF_RELEASE(retval);
    }
    return retval;
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/IPacket.h
csrc/com/xuggle/xuggler/IPacket.cpp