Xuggle: com::xuggle::ferry::AtomicInteger Class Reference
com::xuggle::ferry::AtomicInteger Class Reference
#include <AtomicInteger.h>
Detailed Description
Internal only.
Atomic Integer represents Integers than can be updated atomically from native code.
This object is NOT meant to be called from Java (in fact, that'd be stupid since you'd just be calling from native code back into Java). It's here so that native code inside a JVM can have access to portable thread-safe objects.
And that said, this method is really only Atomic if running inside a Java JVM (or other virtual machine that can provide the functionality). If running in a standalone C++ program there is no current guarantee of Atomicity.
The object just forwards to the Java object: java.util.concurrent.atomic.AtomicInteger
Definition at line 45 of file AtomicInteger.h.
Public Member Functions
AtomicInteger ()
AtomicInteger (int32_t)
~AtomicInteger ()
int32_t get ()
void set (int32_t)
int32_t getAndSet (int32_t)
int32_t getAndIncrement ()
int32_t getAndDecrement ()
int32_t getAndAdd (int32_t)
int32_t incrementAndGet ()
int32_t decrementAndGet ()
int32_t addAndGet (int32_t)
bool compareAndSet (int32_t expected, int32_t update)
Compare the current value to expected, and if they are equal, set the current value to update.
bool isAtomic ()
Friends
class JNIHelper
Constructor & Destructor Documentation
com::xuggle::ferry::AtomicInteger::AtomicInteger ()
Definition at line 117 of file AtomicInteger.cpp.
  {
    initializeObject();
  }
com::xuggle::ferry::AtomicInteger::AtomicInteger (int32_t val)
Definition at line 122 of file AtomicInteger.cpp.
  {
    mNonAtomicValue = 0;
    mAtomicValue = 0;
    initializeObject();
    this->set(val);
  }
com::xuggle::ferry::AtomicInteger::~AtomicInteger ()
Definition at line 130 of file AtomicInteger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
  {
    if (mAtomicValue)
    {
      JNIEnv *env=JNIHelper::sGetEnv();
      if (env)
      {
        env->DeleteGlobalRef(mAtomicValue);
        mAtomicValue = 0;
      }
    }
  }
Member Function Documentation
int32_t com::xuggle::ferry::AtomicInteger::get ()
Definition at line 144 of file AtomicInteger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
Referenced by com::xuggle::ferry::RefCounted::getCurrentRefCount(), and main().
  {
    JNIEnv *env=JNIHelper::sGetEnv();
    int32_t val = 0;
    if (mAtomicValue && env)
      val = env->CallIntMethod(mAtomicValue,
          mGetMethod);
    else
      val = mNonAtomicValue;
    return val;
  }
void com::xuggle::ferry::AtomicInteger::set (int32_t newval)
Definition at line 158 of file AtomicInteger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
  {
    JNIEnv *env=JNIHelper::sGetEnv();
    if (mAtomicValue && env)
      env->CallVoidMethod(mAtomicValue,
          mSetMethod, newval);
    else
      mNonAtomicValue=newval;
  }
int32_t com::xuggle::ferry::AtomicInteger::getAndSet (int32_t newval)
Definition at line 170 of file AtomicInteger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
  {
    JNIEnv *env=JNIHelper::sGetEnv();
    int32_t retval = 0;
    if (mAtomicValue && env)
      retval = env->CallIntMethod(mAtomicValue,
          mGetAndSetMethod, newval);
    else {
      retval = mNonAtomicValue;
      mNonAtomicValue = newval;
    }
    return retval;
  }
int32_t com::xuggle::ferry::AtomicInteger::getAndIncrement ()
Definition at line 186 of file AtomicInteger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
Referenced by main().
  {
    JNIEnv *env=JNIHelper::sGetEnv();
    int32_t retval = 0;
    if (mAtomicValue && env)
      retval = env->CallIntMethod(mAtomicValue,
          mGetAndIncrementMethod);
    else
      retval = mNonAtomicValue++;
    return retval;
  }
int32_t com::xuggle::ferry::AtomicInteger::getAndDecrement ()
Definition at line 200 of file AtomicInteger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
  {
    JNIEnv *env=JNIHelper::sGetEnv();
    int32_t retval = 0;
    if (mAtomicValue && env)
      retval = env->CallIntMethod(mAtomicValue,
          mGetAndDecrementMethod);
    else
      retval = mNonAtomicValue--;
    return retval;
  }
int32_t com::xuggle::ferry::AtomicInteger::getAndAdd (int32_t newval)
Definition at line 214 of file AtomicInteger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
  {
    JNIEnv *env=JNIHelper::sGetEnv();
    int32_t retval = 0;
    if (mAtomicValue && env)
      retval = env->CallIntMethod(mAtomicValue,
          mGetAndAddMethod, newval);
    else {
      retval = mNonAtomicValue;
      mNonAtomicValue += newval;
    }
    return retval;
  }
int32_t com::xuggle::ferry::AtomicInteger::incrementAndGet ()
Definition at line 231 of file AtomicInteger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
Referenced by com::xuggle::ferry::RefCounted::acquire().
  {
    JNIEnv *env=JNIHelper::sGetEnv();
    int32_t retval = 0;
    if (mAtomicValue && env)
      retval = env->CallIntMethod(mAtomicValue,
          mIncrementAndGetMethod);
    else
      retval = (++mNonAtomicValue);
    return retval;
  }
int32_t com::xuggle::ferry::AtomicInteger::decrementAndGet ()
Definition at line 245 of file AtomicInteger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
Referenced by com::xuggle::ferry::RefCounted::release().
  {
    JNIEnv *env=JNIHelper::sGetEnv();
    int32_t retval = 0;
    if (mAtomicValue && env)
      retval = env->CallIntMethod(mAtomicValue,
          mDecrementAndGetMethod);
    else
      retval = (--mNonAtomicValue);
    return retval;
  }
int32_t com::xuggle::ferry::AtomicInteger::addAndGet (int32_t newval)
Definition at line 259 of file AtomicInteger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
  {
    JNIEnv *env=JNIHelper::sGetEnv();
    int32_t retval = 0;
    if (mAtomicValue && env)
      retval = env->CallIntMethod(mAtomicValue,
          mAddAndGetMethod, newval);
    else {
      mNonAtomicValue += newval;
      retval = mNonAtomicValue;
    }
    return retval;
  }
bool com::xuggle::ferry::AtomicInteger::compareAndSet (int32_t expected, int32_t update)
Compare the current value to expected, and if they are equal, set the current value to update.
Parameters:
expected the value expected
update the value to update to
Returns:
true if equal
Definition at line 275 of file AtomicInteger.cpp.
References com::xuggle::ferry::JNIHelper::sGetEnv().
  {
    JNIEnv *env=JNIHelper::sGetEnv();
    bool retval = false;
    if (mAtomicValue && env)
      retval = env->CallBooleanMethod(mAtomicValue,
          mCompareAndSetMethod, expected, update);
    else {
      retval = (mNonAtomicValue == expected);
      if (retval)
      {
        mNonAtomicValue = update;
      }
    }
    return retval;
  }
bool com::xuggle::ferry::AtomicInteger::isAtomic ()
Returns:
true if we're actually able to guarantee atomicity; false if we can't.
Definition at line 294 of file AtomicInteger.cpp.
  {
    return init() && mAtomicValue != 0;
  }
Friends And Related Function Documentation
friend class JNIHelper [friend]
Definition at line 78 of file AtomicInteger.h.
The documentation for this class was generated from the following files:
csrc/com/xuggle/ferry/AtomicInteger.h
csrc/com/xuggle/ferry/AtomicInteger.cpp