Xuggle: com::xuggle::ferry::RefPointer< T > Class Template Reference
com::xuggle::ferry::RefPointer< T > Class Template Reference
#include <RefPointer.h>
Detailed Description
template<class T>
class com::xuggle::ferry::RefPointer< T >
This class is only useful from C++.
If you pass a RefCounted pointer to a RefPointer it assumes you want it to manage the ref-count associated with the RefCounted pointer.
That means, whenever the RefPointer is destroyed, it will RefCounted::release() the pointer it was asked to manage. It will not call acquire() on the pointer for it's own use, but will RefCounted::acquire() it if someone calls get() for the caller to manage.
This can be a handy way to make sure RefCounted::acquire() is called for you in order to reduce the chance of leaking memory from C++ code.
Definition at line 46 of file RefPointer.h.
Public Member Functions
RefPointer ()
Default constructor; sets the managed pointer to 0.
RefPointer (T *ptr)
Construct a RefPointer from a RefCounted object, and take over management of the ref-count this pointer had.
RefPointer (const RefPointer &rPtr)
Copy another RefPointer object.
RefPointer (RefPointer &rPtr)
Copy and acquire.
RefPointer & operator= (const RefPointer &rPtr)
Assignment operator to copy another ref pointer.
RefPointer & operator= (RefPointer &rPtr)
Assignment operator to copy another ref pointer.
RefPointer & operator= (T *ptr)
Assignment from a RefCounted* where we take over ownership of the refcount.
T * operator-> () const
Allow people to def-ref the RefPointer() without RefCounted::acquire() the managed pointer.
operator bool ()
This convenience method allows the use of the following code to determine if the underlying pointer is null or not: RefPointer<Foo> p(someObj); if (p) { // underlying pointer is valid p->DoSomething(); } .
virtual ~RefPointer ()
Always release the ref-count of our underlying pointer.
T * get ()
Call RefCounted::acquire() on the managed pointer and return it.
T * value ()
Return the managed pointer without calling RefCounted::acquire() on it.
void reset (T *ptr=0, bool acquire=false)
Reset the managed pointer, calling RefCounted::release() on the previously managed pointer first.
Constructor & Destructor Documentation
template<class T> com::xuggle::ferry::RefPointer< T >::RefPointer () [inline]
Default constructor; sets the managed pointer to 0.
Definition at line 52 of file RefPointer.h.
                 : mPtr(0)
    {
    }
template<class T> com::xuggle::ferry::RefPointer< T >::RefPointer (T * ptr) [inline]
Construct a RefPointer from a RefCounted object, and take over management of the ref-count this pointer had.
(i.e. it does not RefCounted::acquire() the pointer, but instead assumes it is now the owner. The person who called this method should not call RefCounted::release() on the passed in pointer once this object is managing it).
Parameters:
ptr The pointer to start managing.
Definition at line 67 of file RefPointer.h.
                       : mPtr(ptr)
    {
    }
template<class T> com::xuggle::ferry::RefPointer< T >::RefPointer (const RefPointer< T > & rPtr) [inline]
Copy another RefPointer object.
Since the other RefPointer object will RefCounted::release() its ref-count upon destruction, we RefCounted::acquire() the pointer for ourselves.
Parameters:
rPtr The pointer to RefCounted::acquire() a reference from
Returns:
A new object
Definition at line 80 of file RefPointer.h.
                                       : mPtr(rPtr.mPtr)
    {
      VS_REF_ACQUIRE(mPtr);
    }
template<class T> com::xuggle::ferry::RefPointer< T >::RefPointer (RefPointer< T > & rPtr) [inline]
Copy and acquire.
Parameters:
rPtr The pointer to RefCounted::acquire() a reference from
Returns:
A new object
Definition at line 90 of file RefPointer.h.
                                 : mPtr(rPtr.mPtr)
    {
      VS_REF_ACQUIRE(mPtr);
    }
template<class T> virtual com::xuggle::ferry::RefPointer< T >::~RefPointer () [inline, virtual]
Always release the ref-count of our underlying pointer.
Definition at line 181 of file RefPointer.h.
    {
  #ifdef VS_DEBUG
      {
        if (mPtr)
        {
          // This check should never fail in a multi-thread
          // environment, even though the underlying
          // objects ref can change.
          // If the object is bad, this should cause
          // a READ error in memory tools
          int refCount = mPtr->getCurrentRefCount();
          assert(refCount >= 1);
        }
      }
  #endif // VS_DEBUG
      VS_REF_RELEASE(mPtr);
    }
Member Function Documentation
template<class T> RefPointer& com::xuggle::ferry::RefPointer< T >::operator= (const RefPointer< T > & rPtr) [inline]
Assignment operator to copy another ref pointer.
We RefCounted::acquire() since the other side will RefCounted::release() it's own ref-count later.
Parameters:
rPtr The pointer to assign from
Returns:
A reference to ourself
Definition at line 102 of file RefPointer.h.
    {
      reset(static_cast<T*>(rPtr.mPtr));
      VS_REF_ACQUIRE(mPtr);
      return *this;
    }
template<class T> RefPointer& com::xuggle::ferry::RefPointer< T >::operator= (RefPointer< T > & rPtr) [inline]
Assignment operator to copy another ref pointer.
We RefCounted::acquire() since the other side will RefCounted::release() it's own ref-count later.
Parameters:
rPtr The pointer to assign from
Returns:
A reference to ourself
Definition at line 116 of file RefPointer.h.
    {
      reset(static_cast<T*>(rPtr.mPtr));
      VS_REF_ACQUIRE(mPtr);
      return *this;
    }
template<class T> RefPointer& com::xuggle::ferry::RefPointer< T >::operator= (T * ptr) [inline]
Assignment from a RefCounted* where we take over ownership of the refcount.
This is a pretty handy way of doing: RefPointer<foo> = Obj->getFoo(); Since by convention getFoo() functions should RefCounted::acquire() the returned value for the caller, this ensures you don't accidentally leak a value.
Parameters:
ptr The pointer to take over management of
Returns:
a reference to ourself
Definition at line 138 of file RefPointer.h.
    {
      reset(ptr);
      return *this;
    }
template<class T> T* com::xuggle::ferry::RefPointer< T >::operator-> () const [inline]
Allow people to def-ref the RefPointer() without RefCounted::acquire() the managed pointer.
To avoid the cost of a run-time check, we DON'T check for nullness of the managed pointer.
Returns:
The underlying RefCounted pointer we manage, WITHOUT an extra RefCounted::acquire() call
Definition at line 153 of file RefPointer.h.
    {
      // we don't protect against a null defer here.
      return static_cast<T*>(mPtr);
    }
template<class T> com::xuggle::ferry::RefPointer< T >::operator bool () [inline]
This convenience method allows the use of the following code to determine if the underlying pointer is null or not: RefPointer<Foo> p(someObj); if (p) { // underlying pointer is valid p->DoSomething(); } .
Returns:
true if we're managing a non-null pointer
Definition at line 173 of file RefPointer.h.
    {
      return mPtr!=0;
    }
template<class T> T* com::xuggle::ferry::RefPointer< T >::get () [inline]
Call RefCounted::acquire() on the managed pointer and return it.
Returns:
Return a copy of the managed pointer. We RefCounted::acquire() the pointer for the caller for the caller.
Definition at line 206 of file RefPointer.h.
Referenced by com::xuggle::xuggler::Container::addNewStream(), com::xuggle::xuggler::VideoPicture::getData(), com::xuggle::xuggler::Packet::getData(), com::xuggle::xuggler::AudioSamples::getData(), and com::xuggle::xuggler::MediaDataWrapper::unwrap().
    {
      VS_REF_ACQUIRE(mPtr);
      return static_cast<T*>(mPtr);
    }
template<class T> T* com::xuggle::ferry::RefPointer< T >::value () [inline]
Return the managed pointer without calling RefCounted::acquire() on it.
This is how you pass values to methods expecting a RefCounted*
 void someMethod(RefCounted* arg);
 RefPointer<RefCounted> b = ....;
 someMethod(b.value());
Returns:
Return the managed pointer without calling RefCounted::acquire() on it.
Definition at line 226 of file RefPointer.h.
Referenced by com::xuggle::xuggler::StreamCoder::decodeAudio(), com::xuggle::xuggler::StreamCoder::decodeVideo(), com::xuggle::xuggler::StreamCoder::encodeAudio(), com::xuggle::xuggler::StreamCoder::encodeVideo(), com::xuggle::xuggler::Container::readNextPacket(), com::xuggle::xuggler::AudioSamples::setComplete(), com::xuggle::xuggler::Stream::stampOutputPacket(), com::xuggle::xuggler::MediaDataWrapper::unwrap(), com::xuggle::xuggler::MediaDataWrapper::wrap(), com::xuggle::xuggler::Packet::wrapBuffer(), and com::xuggle::xuggler::Container::writePacket().
    {
      return static_cast<T*>(mPtr);
    }
template<class T> void com::xuggle::ferry::RefPointer< T >::reset (T * ptr = 0, bool acquire = false) [inline]
Reset the managed pointer, calling RefCounted::release() on the previously managed pointer first.
Parameters:
ptr The new value to manage.
acquire should we also acquire a reference? defaults to no (i.e. we take don't call RefCounted::acquire() to take over).
Definition at line 237 of file RefPointer.h.
Referenced by com::xuggle::xuggler::StreamCoder::encodeAudio(), com::xuggle::xuggler::Codec::guessEncodingCodec(), com::xuggle::xuggler::VideoPicture::make(), com::xuggle::ferry::RefPointer< com::xuggle::xuggler::Stream >::operator=(), com::xuggle::xuggler::VideoPicture::setData(), com::xuggle::xuggler::AudioSamples::setData(), and com::xuggle::xuggler::Packet::wrapBuffer().
    {
      VS_REF_RELEASE(mPtr);
      mPtr = ptr;
      if (acquire)
        VS_REF_ACQUIRE(mPtr);
    }
The documentation for this class was generated from the following file:
csrc/com/xuggle/ferry/RefPointer.h