Xuggle: com::xuggle::xuggler::IVideoPicture Class Reference
com::xuggle::xuggler::IVideoPicture Class Reference
#include <IVideoPicture.h>
Detailed Description
Represents one raw (undecoded) picture in a video stream, plus a timestamp for when to display that video picture relative to other items in a IContainer.
All timestamps for this object are always in Microseconds.
Definition at line 39 of file IVideoPicture.h.
Public Types
enum PictType {
DEFAULT_TYPE = 0, I_TYPE = 1, P_TYPE = 2, B_TYPE = 3,
S_TYPE = 4, SI_TYPE = 5, SP_TYPE = 6, BI_TYPE = 7
}
The different types of images that we can set.
Public Member Functions
virtual bool isKeyFrame ()=0
Is this a key frame?
virtual void setKeyFrame (bool aIsKey)=0
Reset if this is a key frame or not.
virtual bool isComplete ()=0
Is this picture completely decoded?
virtual int32_t getSize ()=0
Total size in bytes of the decoded picture.
virtual int getWidth ()=0
What is the width of the picture.
virtual int getHeight ()=0
What is the height of the picture.
virtual IPixelFormat::Type getPixelType ()=0
Returns the pixel format of the picture.
virtual int64_t getPts ()=0
What is the Presentation Time Stamp (in Microseconds) of this picture.
virtual void setPts (int64_t value)=0
Set the Presentation Time Stamp (in Microseconds) for this picture.
virtual int getQuality ()=0
This value is the quality setting this VideoPicture had when it was decoded, or is the value to use when this picture is next encoded (if reset with setQuality().
virtual void setQuality (int newQuality)=0
Set the Quality to a new value.
virtual int getDataLineSize (int lineNo)=0
Return the size of each line in the VideoPicture data.
virtual void setComplete (bool aIsComplete, IPixelFormat::Type format, int width, int height, int64_t pts)=0
After modifying the raw data in this buffer, call this function to let the object know it is now complete.
virtual bool copy (IVideoPicture *srcPicture)=0
Copy the contents of the given picture into this picture.
virtual PictType getPictureType ()=0
Get the picture type.
virtual void setPictureType (PictType type)=0
Set the picture type.
Static Public Member Functions
static IVideoPicture * make (IPixelFormat::Type format, int width, int height)
Get a new picture object.
static IVideoPicture * make (IVideoPicture *src)
Get a new picture by copying the data in an existing frame.
static IVideoPicture * make (com::xuggle::ferry::IBuffer *buffer, IPixelFormat::Type format, int width, int height)
Get a new picture object, by wrapping an existing com.xuggle.ferry.IBuffer.
Protected Member Functions
IVideoPicture ()
virtual ~IVideoPicture ()
Member Enumeration Documentation
enum com::xuggle::xuggler::IVideoPicture::PictType
The different types of images that we can set.
See also:
getPictureType()
Enumerator:
DEFAULT_TYPE
I_TYPE
P_TYPE
B_TYPE
S_TYPE
SI_TYPE
SP_TYPE
BI_TYPE
Definition at line 209 of file IVideoPicture.h.
                 {
      DEFAULT_TYPE=0,
      I_TYPE = 1,
      P_TYPE = 2,
      B_TYPE = 3,
      S_TYPE = 4,
      SI_TYPE = 5,
      SP_TYPE = 6,
      BI_TYPE = 7,
    } PictType;
Constructor & Destructor Documentation
com::xuggle::xuggler::IVideoPicture::IVideoPicture () [protected]
Definition at line 32 of file IVideoPicture.cpp.
  {
  }
com::xuggle::xuggler::IVideoPicture::~IVideoPicture () [protected, virtual]
Definition at line 36 of file IVideoPicture.cpp.
  {
  }
Member Function Documentation
virtual bool com::xuggle::xuggler::IVideoPicture::isKeyFrame () [pure virtual]
Is this a key frame?
Returns:
is this a key frame
Implemented in com::xuggle::xuggler::VideoPicture.
virtual void com::xuggle::xuggler::IVideoPicture::setKeyFrame (bool aIsKey) [pure virtual]
Reset if this is a key frame or not.
Note that regardless of how this flag is set, an IVideoPicture always contains raw video data (hence the key setting isn't really that important).
Parameters:
aIsKey True if a key frame; false if not.
Implemented in com::xuggle::xuggler::VideoPicture.
virtual bool com::xuggle::xuggler::IVideoPicture::isComplete () [pure virtual]
Is this picture completely decoded?
Returns:
is this picture completely decoded?
Implemented in com::xuggle::xuggler::VideoPicture.
Referenced by com::xuggle::xuggler::VideoPicture::copy().
virtual int32_t com::xuggle::xuggler::IVideoPicture::getSize () [pure virtual]
Total size in bytes of the decoded picture.
Returns:
number of bytes of decoded picture
Implements com::xuggle::xuggler::IMediaData.
Implemented in com::xuggle::xuggler::VideoPicture.
virtual int com::xuggle::xuggler::IVideoPicture::getWidth () [pure virtual]
What is the width of the picture.
Returns:
the width of the picture
Implemented in com::xuggle::xuggler::VideoPicture.
Referenced by com::xuggle::xuggler::VideoPicture::copy(), com::xuggle::xuggler::IPixelFormat::getYUV420PPixelOffset(), and make().
virtual int com::xuggle::xuggler::IVideoPicture::getHeight () [pure virtual]
What is the height of the picture.
Returns:
the height of the picture
Implemented in com::xuggle::xuggler::VideoPicture.
Referenced by com::xuggle::xuggler::VideoPicture::copy(), com::xuggle::xuggler::IPixelFormat::getYUV420PPixelOffset(), and make().
virtual IPixelFormat::Type com::xuggle::xuggler::IVideoPicture::getPixelType () [pure virtual]
Returns the pixel format of the picture.
Returns:
the pixel format of the picture.
Implemented in com::xuggle::xuggler::VideoPicture.
Referenced by com::xuggle::xuggler::VideoPicture::copy(), com::xuggle::xuggler::IPixelFormat::getYUV420PPixelOffset(), and make().
virtual int64_t com::xuggle::xuggler::IVideoPicture::getPts () [pure virtual]
What is the Presentation Time Stamp (in Microseconds) of this picture.
The PTS is is scaled so that 1 PTS = 1/1,000,000 of a second.
Returns:
the presentation time stamp (pts)
Implemented in com::xuggle::xuggler::VideoPicture.
Referenced by com::xuggle::xuggler::VideoPicture::copy().
virtual void com::xuggle::xuggler::IVideoPicture::setPts (int64_t value) [pure virtual]
Set the Presentation Time Stamp (in Microseconds) for this picture.
See also:
getPts()
Parameters:
value the new timestamp
Implemented in com::xuggle::xuggler::VideoPicture.
virtual int com::xuggle::xuggler::IVideoPicture::getQuality () [pure virtual]
This value is the quality setting this VideoPicture had when it was decoded, or is the value to use when this picture is next encoded (if reset with setQuality().
Returns:
The quality.
Implemented in com::xuggle::xuggler::VideoPicture.
virtual void com::xuggle::xuggler::IVideoPicture::setQuality (int newQuality) [pure virtual]
Set the Quality to a new value.
This will be used the next time this VideoPicture is encoded by a StreamCoder
Parameters:
newQuality The new quality.
Implemented in com::xuggle::xuggler::VideoPicture.
virtual int com::xuggle::xuggler::IVideoPicture::getDataLineSize (int lineNo) [pure virtual]
Return the size of each line in the VideoPicture data.
Usually there are no more than 4 lines, but the first line no that returns 0 is the end of the road.
Parameters:
lineNo The line you want to know the (byte) size of.
Returns:
The size (in bytes) of that line in data.
Implemented in com::xuggle::xuggler::VideoPicture.
virtual void com::xuggle::xuggler::IVideoPicture::setComplete (bool aIsComplete, IPixelFormat::Type format, int width, int height, int64_t pts) [pure virtual]
After modifying the raw data in this buffer, call this function to let the object know it is now complete.
Parameters:
aIsComplete Is this VideoPicture complete
format The pixel format of the data in this picture. Must match what the picture was originally constructed with.
width The width of the data in this picture. Must match what the picture was originally constructed with.
height The height of the data in this picture. Must match what the picture was originally constructed with.
pts The presentation timestamp of the picture that is now complete. The caller must ensure this PTS is in units of 1/1,000,000 seconds.
Implemented in com::xuggle::xuggler::VideoPicture.
virtual bool com::xuggle::xuggler::IVideoPicture::copy (IVideoPicture * srcPicture) [pure virtual]
Copy the contents of the given picture into this picture.
All buffers are copied by value, not be reference.
Parameters:
srcPicture The picture you want to copy.
Returns:
true if a successful copy; false if not.
Implemented in com::xuggle::xuggler::VideoPicture.
Referenced by make().
IVideoPicture * com::xuggle::xuggler::IVideoPicture::make (IPixelFormat::Type format, int width, int height) [static]
Get a new picture object.
You can specify -1 for width and height, in which case all getData() methods will return error until XUGGLER decodes something into this frame. In general you should always try to specify the width and height.
Note that any buffers this objects needs will be lazily allocated (i.e. we won't actually grab all the memory until we need it).
This is useful because it allows you to hold a IVideoPicture object that remembers things like format, width, and height, but know that it doesn't actually take up a lot of memory until the first time someone tries to access that memory.
Parameters:
format The pixel format (for example, YUV420P).
width The width of the picture, in pixels, or -1 if you want XUGGLER to guess when decoding.
height The height of the picture, in pixels, or -1 if you want XUGGLER to guess when decoding.
Returns:
A new object, or null if we can't allocate one.
Reimplemented in com::xuggle::xuggler::VideoPicture.
Definition at line 41 of file IVideoPicture.cpp.
References com::xuggle::xuggler::Global::init(), and com::xuggle::xuggler::VideoPicture::make().
Referenced by make().
  {
    Global::init();
    return VideoPicture::make(format, width, height);
  }
IVideoPicture * com::xuggle::xuggler::IVideoPicture::make (IVideoPicture * src) [static]
Get a new picture by copying the data in an existing frame.
Parameters:
src The picture to copy.
Returns:
The new picture, or null on error.
Definition at line 58 of file IVideoPicture.cpp.
References copy(), getHeight(), getPixelType(), getWidth(), com::xuggle::xuggler::Global::init(), make(), VS_LOG_DEBUG, and VS_REF_RELEASE.
  {
    IVideoPicture* retval = 0;
    Global::init();
    try
    {
      if (!srcFrame)
        throw std::runtime_error("no source data to copy");
      retval = IVideoPicture::make(srcFrame->getPixelType(), srcFrame->getWidth(), srcFrame->getHeight());
      if (!retval)
        throw std::runtime_error("could not allocate new frame");
      if (!retval->copy(srcFrame))
        throw std::runtime_error("could not copy source frame");
    }
    catch (std::bad_alloc &e)
    {
      VS_REF_RELEASE(retval);
      throw e;
    }
    catch (std::exception & e)
    {
      VS_LOG_DEBUG("got error: %s", e.what());
      VS_REF_RELEASE(retval);
    }
    return retval;
  }
virtual PictType com::xuggle::xuggler::IVideoPicture::getPictureType () [pure virtual]
Get the picture type.
This will be set on decoding to tell you what type of packet this was decoded from, and when encoding is a request to the encoder for how to encode the picture.
The request may be ignored by your codec.
Returns:
the picture type.
Implemented in com::xuggle::xuggler::VideoPicture.
virtual void com::xuggle::xuggler::IVideoPicture::setPictureType (PictType type) [pure virtual]
Set the picture type.
Parameters:
type The type.
See also:
getPictureType()
Implemented in com::xuggle::xuggler::VideoPicture.
IVideoPicture * com::xuggle::xuggler::IVideoPicture::make (com::xuggle::ferry::IBuffer * buffer, IPixelFormat::Type format, int width, int height) [static]
Get a new picture object, by wrapping an existing com.xuggle.ferry.IBuffer.
Use this method if you have existing video data that you want to have us wrap and pass to FFmpeg. Note that if decoding into this video picture and the decoded data actually takes more space than is in this buffer, this object will release the reference to the passed in buffer and allocate a new buffer instead so the decode can continue.
Due to some decoders assembly optimizations, you should ensure the IBuffer you pass in has at least 8 more bytes than would typically be required based on the format, width and height.
Parameters:
buffer The com.xuggle.ferry.IBuffer to wrap.
format The pixel format (for example, YUV420P).
width The width of the picture, in pixels.
height The height of the picture, in pixels.
Returns:
A new object, or null if we can't allocate one.
Reimplemented in com::xuggle::xuggler::VideoPicture.
Definition at line 48 of file IVideoPicture.cpp.
References com::xuggle::xuggler::Global::init(), and com::xuggle::xuggler::VideoPicture::make().
  {
    Global::init();
    return VideoPicture::make(buffer, format, width, height);
  }
The documentation for this class was generated from the following files:
csrc/com/xuggle/xuggler/IVideoPicture.h
csrc/com/xuggle/xuggler/IVideoPicture.cpp