Xuggle: csrc/com/xuggle/xuggler/io/FfmpegIO.cpp File Reference
FfmpegIO.cpp File Reference
#include <stdexcept>
#include <com/xuggle/ferry/JNIHelper.h>
#include <com/xuggle/xuggler/io/FfmpegIO.h>
#include <com/xuggle/xuggler/io/FfmpegIncludes.h>
#include <com/xuggle/xuggler/io/URLProtocolManager.h>
Functions
int ffurl_alloc (URLContext **h, const char *url, int flags)
int ffurl_connect (URLContext *h)
int ffurl_open (URLContext **h, const char *url, int flags)
int ffurl_read (URLContext *h, unsigned char *buf, int size)
int ffurl_read_complete (URLContext *h, unsigned char *buf, int size)
int ffurl_write (URLContext *h, const unsigned char *buf, int size)
int64_t ffurl_seek (URLContext *h, int64_t pos, int whence)
int ffurl_close (URLContext *h)
int64_t ffurl_size (URLContext *h)
int ffurl_get_file_handle (URLContext *h)
int ffurl_register_protocol (URLProtocol *protocol, int size)
JNIEXPORT jint JNICALL JNI_OnLoad (JavaVM *, void *)
JNIEXPORT void JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_init (JNIEnv *env, jclass)
JNIEXPORT jint JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_native_1registerProtocolHandler (JNIEnv *jenv, jclass, jstring aProtoName, jobject aProtoMgr)
JNIEXPORT jint JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1open (JNIEnv *jenv, jclass, jobject handle, jstring url, jint flags)
JNIEXPORT jint JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1read (JNIEnv *jenv, jclass, jobject handle, jbyteArray javaBuf, jint buflen)
JNIEXPORT jint JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1write (JNIEnv *jenv, jclass, jobject handle, jbyteArray javaBuf, jint buflen)
JNIEXPORT jlong JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1seek (JNIEnv *jenv, jclass, jobject handle, jlong position, jint whence)
JNIEXPORT jint JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1close (JNIEnv *jenv, jclass, jobject handle)
Function Documentation
int ffurl_alloc (URLContext ** h, const char * url, int flags)
int ffurl_close (URLContext * h)
Referenced by Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1close().
int ffurl_connect (URLContext * h)
int ffurl_get_file_handle (URLContext * h)
int ffurl_open (URLContext ** h, const char * url, int flags)
Referenced by Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1open().
int ffurl_read (URLContext * h, unsigned char * buf, int size)
Referenced by Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1read().
int ffurl_read_complete (URLContext * h, unsigned char * buf, int size)
int ffurl_register_protocol (URLProtocol * protocol, int size)
Referenced by Java_com_xuggle_xuggler_io_FfmpegIO_native_1registerProtocolHandler().
int64_t ffurl_seek (URLContext * h, int64_t pos, int whence)
Referenced by Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1seek().
int64_t ffurl_size (URLContext * h)
int ffurl_write (URLContext * h, const unsigned char * buf, int size)
Referenced by Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1write().
JNIEXPORT void JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_init (JNIEnv * env, jclass)
Definition at line 55 of file FfmpegIO.cpp.
References com::xuggle::ferry::JNIHelper::sGetVM(), and com::xuggle::ferry::JNIHelper::sSetVM().
{
  JavaVM* vm=0;
  if (!com::xuggle::ferry::JNIHelper::sGetVM()) {
    env->GetJavaVM(&vm);
    com::xuggle::ferry::JNIHelper::sSetVM(vm);
    av_register_all();
  }
}
JNIEXPORT jint JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_native_1registerProtocolHandler (JNIEnv * jenv, jclass , jstring aProtoName, jobject aProtoMgr)
Definition at line 65 of file FfmpegIO.cpp.
References ffurl_register_protocol(), and com::xuggle::xuggler::io::URLProtocolManager::getURLProtocol().
{
  int retval = -1;
  const char *protoName= NULL;
  protoName = jenv->GetStringUTFChars(aProtoName, NULL);
  if (protoName != NULL)
  {
    URLProtocolManager* mgr = new URLProtocolManager(protoName, aProtoMgr);
    URLProtocol* proto = mgr->getURLProtocol();
    retval = ffurl_register_protocol(proto, sizeof(URLProtocolWrapper));
    jenv->ReleaseStringUTFChars(aProtoName, protoName);
    protoName = NULL;
    // Yes, we deliberately leak the URLProtocolManager...
  }
  return retval;
}
JNIEXPORT jint JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1close (JNIEnv * jenv, jclass , jobject handle)
Definition at line 246 of file FfmpegIO.cpp.
References ffurl_close().
{
  URLContext*handleVal= NULL;
  jint retval = -1;
  handleVal = (URLContext*)JNIHelper::sGetPointer(handle);
  try
  {
    retval = ffurl_close(handleVal);
  }
  catch(std::exception & e)
  {
    // we don't let a native exception override a java exception
    if (!jenv->ExceptionCheck())
    {
      jclass cls=jenv->FindClass("java/lang/RuntimeException");
      jenv->ThrowNew(cls, e.what());
    }
    retval = -1;
  }
  catch(...)
  {
    // we don't let a native exception override a java exception
    if (!jenv->ExceptionCheck())
    {
      jclass cls=jenv->FindClass("java/lang/RuntimeException");
      jenv->ThrowNew(cls, "Unhandled and unknown native exception");
    }
    retval = -1;
  }
  return retval;
}
JNIEXPORT jint JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1open (JNIEnv * jenv, jclass , jobject handle, jstring url, jint flags)
Definition at line 87 of file FfmpegIO.cpp.
References ffurl_open().
{
  URLContext*handleVal= NULL;
  const char *nativeURL= NULL;
  jint retval = -1;
  nativeURL = jenv->GetStringUTFChars(url, NULL);
  if (nativeURL != NULL)
  {
    try
    {
      retval = ffurl_open(&handleVal, nativeURL, flags);
    }
    catch(std::exception & e)
    {
      // we don't let a native exception override a java exception
      if (!jenv->ExceptionCheck())
      {
        jclass cls=jenv->FindClass("java/lang/RuntimeException");
        jenv->ThrowNew(cls, e.what());
      }
      retval = -1;
    }
    catch(...)
    {
      // we don't let a native exception override a java exception
      if (!jenv->ExceptionCheck())
      {
        jclass cls=jenv->FindClass("java/lang/RuntimeException");
        jenv->ThrowNew(cls, "Unhandled and unknown native exception");
      }
      retval = -1;
    }
    // regardless of what the function returns, set the pointer
    JNIHelper::sSetPointer(handle, handleVal);
  }
  // free the string
  if (nativeURL != NULL)
  {
    jenv->ReleaseStringUTFChars(url, nativeURL);
    nativeURL = NULL;
  }
  return retval;
}
JNIEXPORT jint JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1read (JNIEnv * jenv, jclass , jobject handle, jbyteArray javaBuf, jint buflen)
Definition at line 135 of file FfmpegIO.cpp.
References ffurl_read().
{
  URLContext*handleVal= NULL;
  jint retval = -1;
  handleVal = (URLContext*)JNIHelper::sGetPointer(handle);
  jbyte *byteArray = jenv->GetByteArrayElements(javaBuf, NULL);
  try
  {
    retval = ffurl_read(handleVal, (unsigned char*)byteArray, buflen);
  }
  catch(std::exception & e)
  {
    // we don't let a native exception override a java exception
    if (!jenv->ExceptionCheck())
    {
      jclass cls=jenv->FindClass("java/lang/RuntimeException");
      jenv->ThrowNew(cls, e.what());
    }
    retval = -1;
  }
  catch(...)
  {
    // we don't let a native exception override a java exception
    if (!jenv->ExceptionCheck())
    {
      jclass cls=jenv->FindClass("java/lang/RuntimeException");
      jenv->ThrowNew(cls, "Unhandled and unknown native exception");
    }
    retval = -1;
  }
  jenv->ReleaseByteArrayElements(javaBuf, byteArray, 0);
  return retval;
}
JNIEXPORT jlong JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1seek (JNIEnv * jenv, jclass , jobject handle, jlong position, jint whence)
Definition at line 211 of file FfmpegIO.cpp.
References ffurl_seek().
{
  URLContext*handleVal= NULL;
  jint retval = -1;
  handleVal = (URLContext*)JNIHelper::sGetPointer(handle);
  try
  {
    retval = ffurl_seek(handleVal, position, whence);
  }
  catch(std::exception & e)
  {
    // we don't let a native exception override a java exception
    if (!jenv->ExceptionCheck())
    {
      jclass cls=jenv->FindClass("java/lang/RuntimeException");
      jenv->ThrowNew(cls, e.what());
    }
    retval = -1;
  }
  catch(...)
  {
    // we don't let a native exception override a java exception
    if (!jenv->ExceptionCheck())
    {
      jclass cls=jenv->FindClass("java/lang/RuntimeException");
      jenv->ThrowNew(cls, "Unhandled and unknown native exception");
    }
    retval = -1;
  }
  return retval;
}
JNIEXPORT jint JNICALL Java_com_xuggle_xuggler_io_FfmpegIO_native_1url_1write (JNIEnv * jenv, jclass , jobject handle, jbyteArray javaBuf, jint buflen)
Definition at line 173 of file FfmpegIO.cpp.
References ffurl_write().
{
  URLContext*handleVal= NULL;
  jint retval = -1;
  handleVal = (URLContext*)JNIHelper::sGetPointer(handle);
  jbyte *byteArray = jenv->GetByteArrayElements(javaBuf, NULL);
  try
  {
    retval = ffurl_write(handleVal, (unsigned char*)byteArray, buflen);
  }
  catch(std::exception & e)
  {
    // we don't let a native exception override a java exception
    if (!jenv->ExceptionCheck())
    {
      jclass cls=jenv->FindClass("java/lang/RuntimeException");
      jenv->ThrowNew(cls, e.what());
    }
    retval = -1;
  }
  catch(...)
  {
    // we don't let a native exception override a java exception
    if (!jenv->ExceptionCheck())
    {
      jclass cls=jenv->FindClass("java/lang/RuntimeException");
      jenv->ThrowNew(cls, "Unhandled and unknown native exception");
    }
    retval = -1;
  }
  jenv->ReleaseByteArrayElements(javaBuf, byteArray, 0);
  return retval;
}
JNIEXPORT jint JNICALL JNI_OnLoad (JavaVM * , void *)
Definition at line 47 of file FfmpegIO.cpp.
References com::xuggle::ferry::JNIHelper::sGetJNIVersion().
{
    /* Because of static initialize in Mac OS, the only safe thing
     * to do here is return the version */
    return com::xuggle::ferry::JNIHelper::sGetJNIVersion();
}