Xuggle: csrc/com/xuggle/ferry/JNIMemoryManager.cpp File Reference
JNIMemoryManager.cpp File Reference
#include "JNIMemoryManager.h"
#include <stdexcept>
#include <new>
#include <cstdlib>
#include <cstring>
#include <climits>
#include <jni.h>
#include <com/xuggle/ferry/config.h>
#include "Ferry.h"
#include "RefCounted.h"
Namespaces
namespace com
namespace com::xuggle
namespace com::xuggle::ferry
Enumerations
enum VSJNIMemoryModel {
JAVA_STANDARD_HEAP = 0, JAVA_DIRECT_BUFFERS = 1, JAVA_DIRECT_BUFFERS_WITH_STANDARD_HEAP_NOTIFICATION = 2, NATIVE_BUFFERS = 3,
NATIVE_BUFFERS_WITH_STANDARD_HEAP_NOTIFICATION = 4
}
Must match numbers in JNIMemoryManager.java.
Functions
void VSJNI_MemoryManagerInit (JavaVM *aJVM)
JNIEXPORT void JNICALL Java_com_xuggle_ferry_JNIMemoryAllocator_setAllocator (JNIEnv *, jclass, jlong aNativeObj, jobject aMemMgr)
Don't enable this; it turns out that on Mac i86_64 at least during the loading of shared libraries, new linkages can override existing linkages So if a library calls new before we're loaded, then loads us, and then calls delete, the Mac may accidentally call our delete; not good.
JNIEXPORT jobject JNICALL Java_com_xuggle_ferry_JNIMemoryAllocator_getAllocator (JNIEnv *env, jclass, jlong aNativeObj)
JNIEXPORT jint JNICALL Java_com_xuggle_ferry_FerryJNI_getMemoryModel (JNIEnv *, jclass)
JNIEXPORT void JNICALL Java_com_xuggle_ferry_FerryJNI_setMemoryModel (JNIEnv *, jclass, jint value)
Enumeration Type Documentation
enum VSJNIMemoryModel
Must match numbers in JNIMemoryManager.java.
Enumerator:
JAVA_STANDARD_HEAP
JAVA_DIRECT_BUFFERS
JAVA_DIRECT_BUFFERS_WITH_STANDARD_HEAP_NOTIFICATION
NATIVE_BUFFERS
NATIVE_BUFFERS_WITH_STANDARD_HEAP_NOTIFICATION
Definition at line 62 of file JNIMemoryManager.cpp.
{
  JAVA_STANDARD_HEAP = 0,
  JAVA_DIRECT_BUFFERS = 1,
  JAVA_DIRECT_BUFFERS_WITH_STANDARD_HEAP_NOTIFICATION = 2,
  NATIVE_BUFFERS = 3,
  NATIVE_BUFFERS_WITH_STANDARD_HEAP_NOTIFICATION = 4,
};
Function Documentation
JNIEXPORT jint JNICALL Java_com_xuggle_ferry_FerryJNI_getMemoryModel (JNIEnv * , jclass)
Definition at line 756 of file JNIMemoryManager.cpp.
{
  return (jint) sVSJNI_IsMirroringNativeMemoryInJVM;
}
JNIEXPORT void JNICALL Java_com_xuggle_ferry_FerryJNI_setMemoryModel (JNIEnv * , jclass , jint value)
Definition at line 762 of file JNIMemoryManager.cpp.
{
#ifdef VSJNI_USE_JVM_FOR_MEMMANAGEMENT
  sVSJNI_IsMirroringNativeMemoryInJVM = (enum VSJNIMemoryModel) value;
#endif
}
JNIEXPORT jobject JNICALL Java_com_xuggle_ferry_JNIMemoryAllocator_getAllocator (JNIEnv * env, jclass , jlong aNativeObj)
Definition at line 743 of file JNIMemoryManager.cpp.
References com::xuggle::ferry::RefCounted::getJavaAllocator().
{
  // assume that the native object is a RefCounted
  com::xuggle::ferry::RefCounted *obj =
      *(com::xuggle::ferry::RefCounted**) &aNativeObj;
  jobject result = (jobject) obj->getJavaAllocator();
  if (result)
    result = env->NewLocalRef(result);
  return result;
}
JNIEXPORT void JNICALL Java_com_xuggle_ferry_JNIMemoryAllocator_setAllocator (JNIEnv * , jclass , jlong aNativeObj, jobject aMemMgr)
Don't enable this; it turns out that on Mac i86_64 at least during the loading of shared libraries, new linkages can override existing linkages So if a library calls new before we're loaded, then loads us, and then calls delete, the Mac may accidentally call our delete; not good.
Here are some JNI functions used by the JNIMemoryAllocator.java method
Definition at line 733 of file JNIMemoryManager.cpp.
References com::xuggle::ferry::RefCounted::setJavaAllocator().
{
  // assume that the native object is a RefCounted
  com::xuggle::ferry::RefCounted *obj =
      *(com::xuggle::ferry::RefCounted**) &aNativeObj;
  obj->setJavaAllocator(aMemMgr);
}
void VSJNI_MemoryManagerInit (JavaVM * aJVM)
Definition at line 126 of file JNIMemoryManager.cpp.
Referenced by com::xuggle::ferry::JNIHelper::setVM().
{
  sCachedJVM = aJVM;
#ifdef VSJNI_USE_JVM_FOR_MEMMANAGEMENT
  try
  {
    // Now, let's cache the commonly used classes.
    JNIEnv *env = VSJNI_getEnv();
    if (!env)
      throw std::runtime_error("could not find environment");
    jclass cls = env->FindClass("java/nio/ByteBuffer");
    if (!cls)
      throw std::runtime_error("could not find java.nio.ByteBuffer class");
    sByteBufferReferenceClass = (jclass) env->NewWeakGlobalRef(cls);
    if (!sByteBufferReferenceClass)
      throw std::runtime_error("could not get weak reference for class");
    sByteBufferAllocateDirectMethod = env->GetStaticMethodID(cls,
        "allocateDirect", "(I)Ljava/nio/ByteBuffer;");
    if (!sByteBufferAllocateDirectMethod)
      throw std::runtime_error(
          "could not find allocateDirect(int) method in java.nio.ByteBuffer");
    env->DeleteLocalRef(cls);
    if (env->ExceptionCheck())
      throw std::runtime_error("got exception in jni");
    cls = env->FindClass("com/xuggle/ferry/JNIMemoryAllocator");
    if (!cls)
      throw std::runtime_error(
          "could not find com.xuggle.ferry.JNIMemoryAllocatorclass");
    sJNIMemoryAllocatorClass = (jclass) env->NewWeakGlobalRef(cls);
    if (!sJNIMemoryAllocatorClass)
      throw std::runtime_error("could not get weak reference for class");
    sJNIMemoryAllocatorMallocMethod = env->GetMethodID(cls, "malloc", "(I)[B");
    if (!sJNIMemoryAllocatorMallocMethod)
      throw std::runtime_error(
          "could not find malloc(int) method in com.xuggle.ferry.JNIMemoryAllocator");
    sJNIMemoryAllocatorFreeMethod = env->GetMethodID(cls, "free", "([B)V");
    if (!sJNIMemoryAllocatorFreeMethod)
      throw std::runtime_error(
          "could not find free(byte[]) method in com.xuggle.ferry.JNIMemoryAllocator");
  }
  catch (std::exception e)
  {
    // DON'T HAVE JAVA do memory management.
    sCachedJVM = 0;
#ifdef VSJNI_MEMMANAGER_DEBUG
    fprintf(stderr,
        "got exception initializing jvm; using stdlib for memory allocation\n");
#endif
  }
#else
#endif // VSJNI_USE_JVM_FOR_MEMMANGEMENT
}